include:
  - //////.gitlab-refs.yaml

variables:
  DISCORDBOT_PATH: $CI_PROJECT_DIR/go/discordbot
  DISCORDBOT_REPO: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/discordbot
  DISCORDBOT_IMAGE_HASH: $CI_COMMIT_SHORT_SHA

build_discordbot:
  interruptible: true
  tags:
    - hetzner
  image:
    name: registry.gitlab.com/fynbos/fynbos/debian-runner-base:13295664
  before_script:
    - docker login -u AWS -p $(aws ecr get-login-password --profile shared --region eu-west-1) 823058932981.dkr.ecr.eu-west-1.amazonaws.com
    - cd $DISCORDBOT_PATH/../
  script:
    - docker build -t "823058932981.dkr.ecr.eu-west-1.amazonaws.com/discordbot:${DISCORDBOT_IMAGE_HASH}" -f discordbot/Dockerfile .
    - docker push "823058932981.dkr.ecr.eu-west-1.amazonaws.com/discordbot:${DISCORDBOT_IMAGE_HASH}"

test_discordbot:
  needs:
    - job: go-mod
      optional: true
  rules:
    - changes:
        - go/go.mod
        - go/discordbot/**/*
  tags:
    - hetzner
  image: registry.gitlab.com/fynbos/fynbos/debian-runner-base:13295664
  services:
    - name: cockroachdb/cockroach:v22.2.8
      alias: crdb
      command: ["start-single-node", "--insecure", "--store=type=mem,size=641MiB"]
  interruptible: true
  script:
    - curl -o /bin/atlas https://release.ariga.io/atlas/atlas-linux-amd64-v0.8.1 && chmod +x /bin/atlas
    - cd $DISCORDBOT_PATH
    - make -C ../backend generatetestmigrations CRDB_HOST=crdb
    - make testci
