services:
  botanist:
    build:
      context: ../typescript/botanist
      target: dev
    profiles:
      - application
      - frontend
    restart: always
    develop:
      watch:
        - path: ../typescript/botanist
          action: rebuild
    ports:
      - "13000:3000" # http port
      - "18002:8002" # websocket port
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.botanist.rule=Host(`admin.mgnt.interledger.test`)"
      - "traefik.http.services.botanist.loadbalancer.server.port=3000"

    environment:
      - FYNBOS_ENV=local

      - CHOKIDAR_USEPOLLING=true
      - BACKEND_GRPC_URL=backend:8448

    depends_on:
      - backend
