include:
  # tier 0 (infrastructure)
  - postgres.yaml
  - redis.yaml
  - traefik.yaml
  # - coredns.yaml

  # tier 1 (operational)
  # - registry.yaml

  # tier 2 (application services)
  - kratos.yaml
  - temporal.yaml
  - rafiki.yaml

  # enable ngrok if you are testing webhooks, see ngrok.yaml
  # - ngrok.yaml

  # tier 3 (application)
  - wallet.yaml
  # - protea.yaml
  - botanist.yaml
  - mockbos.yaml
