include:
  # profile: infrastructure
  - traefik.yaml
  - postgres.yaml
  - postgres-unit-tests.yaml
  - redis.yaml
  - mkdocs.yaml

  # profile: services
  - kratos.yaml
  - temporal.yaml
  - rafiki.yaml
  - ngrok.yaml

  # profile: application
  - wallet.yaml
  - protea.yaml
  - botanist.yaml
  - mockbos.yaml
  - mockgatehub.yaml
  - mockxago.yaml
  - mockpti.yaml
