services:
  elasticsearch:
    image: elasticsearch:9.1.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - action.auto_create_index=true
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: logstash:9.1.3
    ports:
      - "12202:12202"  # GELF input
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: kibana:9.1.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  esdata:
