services:
  # 1. Kratos migrations
  kratos-migrate:
    image: oryd/kratos:v1.3.1
    profiles:
      - services
    volumes:
      - ./config:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  # 2. Kratos Service
  kratos:
    image: oryd/kratos:v1.3.1
    profiles:
      - services
    ports:
      - "4433:4433"  # Public
      - "4434:4434"  # Admin
    environment:
      - DSN=postgres://postgres:postgres@postgres:5432/kratos?sslmode=disable
      - LOG_LEVEL=debug
      - LOG_LEAK_SENSITIVE_VALUES=true
    command: serve -c /etc/config/kratos/kratos.yml --dev
    volumes:
      - ./config:/etc/config/kratos
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kratos.rule=Host(`identity.interledger.test`)"
      - "traefik.http.routers.kratos.rule=(Host(`interledger.test`) && (PathPrefix(`/self-service`) || PathPrefix(`/sessions`)))"
      - "traefik.http.services.kratos.loadbalancer.server.port=4433"
    depends_on:
      - kratos-migrate
