services:
  mockbos:
    build:
      context: ../go
      dockerfile: mockbos/Dockerfile
      target: builder
    container_name: mockbos
    restart: always
    ports:
      - "18080:8080" # http port
    environment:
      - DB_URL=postgres://postgres:postgres@postgres:5432/mockbos?sslmode=disable
      - XAGO_WEBHOOK_URL=http://backend:8080/webhook/xago

    depends_on:
      - backend
    entrypoint: ["/go/bin/air", "--build.poll", "true", "--build.include_ext", "go,hcl", "--build.cmd", "go build -o /local/main /build/mockbos/main.go", "--build.bin", "/local/main"]    
    volumes:
      - ../go:/build