services:
  mockpti:
    build:
      context: ..
      dockerfile: go/mock/mockpti/Dockerfile
    profiles:
      - application
    restart: always
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mockpti.rule=Host(`mockpti.interledger.test`)"
      - "traefik.http.routers.mockpti.entrypoints=websecure"
      - "traefik.http.services.mockpti.loadbalancer.server.port=8080"
    environment:
      LOG_LEVEL: debug

      # Storage configuration
      MOCKPTI_REDIS_URL: redis://redis:6379
      MOCKPTI_REDIS_DB: '5'

      # Provider auth compatibility
      MOCKPTI_CLIENT_ID: ${BACKEND_PTI_CLIENT_ID:-04d3e1b5-96d4-47e4-9eaa-13e9b4b0f219}

      # Webhook configuration
      MOCKPTI_WEBHOOK_URL: http://backend:8080/webhooks/pti
      WEBHOOK_MIN_DELAY_SEC: '0.2'
      MOCKPTI_WEBHOOK_SIGNING_JWK: ${MOCKPTI_WEBHOOK_SIGNING_JWK:-{"d":"QHKIFGLV_cfpFn6F8AyNbbJXw3dsd6PSLDbw1qpKlA4l-TKgtEfyXXzFv8Kj8kH4xo7pcikQOU-_331ZXrR3UzYLQ6mF7sgO093n-0JG1zNkY85zFr5zBFgwQfQDh-CwS-UFJMONMsbQ2amnFyQlh_563Q_OIq46ers266cAKolNH4pAzIRwHMBNQYmTwa2yfXIUhjFtJbOSSXBZqc6KMGqA_-wxo6w4ZrXsP_YbOqfElRA_fZxlA9LKqEi7Jygt5i_cxCkEyDpTJCO74ix1d_dD92-boDSzEsm8czxx8607zYshbDLIn7KhpO4Pu52OFtW4g8Tr9nNXghAW9teMBQ","dp":"IKMQxbrBRW-LjOG1aXlfxEHrpXhoQTEh5WVNw8-j0YvMOjgzPU4sTVplwPdMvOiC0YZ-kwR67Tgjf4so5PVL88LyZd54v6aL4_XenkYcgrJkzCoJqFuargIFWFY8ecfeRwFQPnKTx2YGyZTi48tfqIt5VNg12TabwA8yAXU48r8","dq":"m5JiwGqvv4ZNc2ZXzMSvVkLzyUtcalnjooW9AC1xD9y20iaQb71WQANyuHfS4qBlTGF9s3KckctuLT53f-Mf4xfJGl_44L9oMIpqcwH_oXpE9-tA4AVJNtkYUD0BakbsmVIzh54FCJk7-8ALVkGm46FK0KyYc8JAdMP8Ohbt3AE","e":"AQAB","kty":"RSA","n":"yF6WeCgbEMCMqZr5oxzXyVjTC3kGdKCMSzAfi-_ECN_S0IQnv3KfH11mcHNeg2omP9033Ai_q0eWhyWOHyYOHsEdj-2PSmQaNPiYmP_ixiPuPClyqianLb6oYp3cLz6pYu1Hm4AkacddnAtzAxHB4fFHdXB6iz258zVHnt4JI6N0py88uWolRiVK8q1yR5kRzVCHs6bvgROJpI_PbDrqmaPJzfy8Jh6yW9IbM3QTceAregbrWY6W8CnciGiBWDkrvnqeLFti5CRNoaf5LKVeFxFYSLmF6BN1iPSBO4HK68sIbu6Rc2c0Ff35Yz3xCy7YbzIh2keNfKjJNS_BhM5fDw","p":"82t1OqIDj1VrmqaJx56cutski5yHWDqXR2JNeHOXvCo81Qo10zuvHEBNPqO5Yqeg91PDVDLdwkRegFM4JQF0PwOHpG2esjiQk9GTzPqEO8A9fSeWfQV6cE16OjKKvIG0vkqAtPIcFZyZswTDN5_Xj0jcQw2RRjJuB3xf7ZCahos","q":"0rmOqQtt8AgyFUTMzK4IRQG_DIZLdXOLfoaZxEm99DiV63_YKQviL-HK0HqkX2y9hyWkAUWAs1gKzBaLKngKh76KbJO9-NkbAUibwOmUgVJ9N8oe390AUXONFh-V4Tqz-uoOsoxB5b9Y1KKTwhm4aK2fFEWitfuJGGeKJgb73g0","qi":"Ozrt33UlbrSNp2mJGGBR_gLcI70mRRa5ttL9pJv4pY6Fstl0u9a7FxtugOLYQWatQEUacnUUzO09xxUKvtXvDvTFs0glJ8hX6CkD0c1f6AFVWcoc4AeI9VpUWXzl7Ju35rovh0ybOAA6mexFdUCATeLwfGPfL9eWWe8QFaW6yoU"}}
      MOCKPTI_WEBHOOK_ENCRYPTION_JWK: ${MOCKPTI_WEBHOOK_ENCRYPTION_JWK:-{"d":"B98CLTnsSLW6uODeoMxinN0wexXQFqjfoRQVAw9f1YYyrxvCbg0yuTHaOjONDNYI-c_QEPwGoDELzJYEBC8kFiVBDru3rwBoYT9Iey4JUkfe2chT2m6njw_nHxNDTEINm5Le_NcYBVPLUZ5xOWyThG4_4ssPcRFxEPZhiQPrFxBN_igvuurM0PtSD8O4LbD4Al77cizHKED-QCR_mwD2SNSID0CCT0kLeGNbfrZpzKVgXPcxaRg-To1bzvSFjV2jkbZONlXIDAA7FSNibBg9sF9XUgr-jtcjoeSAEuZrCt09VU1vCSLbhSdVBw5X_AA3qypLWGHigxdNyKm2kapmwQ","dp":"wEEgMkxQX06Eb46rKTsMSuvjKGoZttIRHgFnLB7701WrOPQcAlqWrLiXrpzUFuD3MprWDXo87cJpayCO8lH-jh5G2XfWPvPkoqUYeUyglwLYujSOekmS8Sno4auQ80bDB3qBaWO7IOtepAsRB0Mdp9Mim8s-tbuzZiOQvlZopyU","dq":"PUhZ6pNZ5QRy85ROW4MxzB_p7j8ZCfSOeuV125zo9PoKhU-Bl3z_fhziNrQxu0mdlX6wDNRYA01Q0wHDlg1D00Ejy2TRV6KZWLW_WgOlAYfT8B3TEdOBsKTHpWqOp-FscQURHVqHwwlZf8OldZZI6L03go_igKgQP7Yj0LUTnVE","e":"AQAB","kty":"RSA","n":"8QON17556njlKTc9UadXGqYYrAfgAG8cLohdCCO__3IXM11bt2TDKrBkUToUYSvfm5-9wMdMnV1AvlA1h0FMWAgyjXgEJxUtIWjxbGLvfgJyn0x3I-czRxoi4gZDo_vq0x_sMLrZqAbGenMVZM4oEcD2_qNVDmsvNqydAyn-rqRVohzjirnGLwQaB_WiXUOJv8RcIgzXNtMjf67JH0V6tPR2LGTqBq6cz8j6Y47YuGsvf5VyeXGaVFZ29zq2L7xJtft5Ytcj2j-XZABFRUF9obyqx8WCJQHUsaLPL2a1sp5xeB_NaHTj5F1ZUYLXfUl-Yd-jr1mMP0OUWHBP8CeDLQ","p":"-Nrf6mHe-y0DkzoIlbwvF9xvZkcmwBA4Tl0My3jWb0Yq5l3l-Rs7mAVSNvaf0yBnz8EF_kCE4G5NPG0p3VmBCiRRhlTPpDsYPK7b3Yrl5zYyLD-HiRQiiZp9_PAurENR1e4dnl7oRksu7wPISuSdgU5T4HVwCPOXwCpYUjBsT70","q":"9-8LychZAsVicKq1Mw3JFowE9v4TlNCMlCwSaYQUEY6-nGQtLpUCqB98UbXTVM6IfwAywMbSFdyB6M9Rp0r8Q0ZTe3NMOiffLl5pJwC6LuLdqIIk8WQTWIXD0tZDpUobgUe75M_9r5P54sgfX59itWzv5I4_cY6Dk2-9GgLBQDE","qi":"tLxcHy-F7RtZxNcWkEPJc7NPl5rVz1CbCb1sDvaifXXhnfzGcFdOOWhluWoWpzDD0KNsqs9ViZTBPO8EI9YP47FF1R0HRbYFcf73gTBh8wHrCD38FPpJGBcuPzfGUXclWL_6B-SjuBT1sEiRYC_v2M70aL5eVmKtiHAZ5yzJosc"}}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
