services:
  mockpti:
    build:
      context: ..
      dockerfile: go/mock/mockpti/Dockerfile
    profiles:
      - application
    restart: always
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mockpti.rule=Host(`mockpti.interledger.test`)"
      - "traefik.http.routers.mockpti.entrypoints=websecure"
      - "traefik.http.services.mockpti.loadbalancer.server.port=8080"
    environment:
      - CONFIG=/etc/mockpti/config.yaml
    volumes:
      - ./config/mockpti.yaml:/etc/mockpti/config.yaml:ro

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
