services:
  mockxago:
    build:
      context: ..
      dockerfile: go/mock/mockxago/Dockerfile
    profiles:
      - application
    restart: always
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mockxago.rule=Host(`mockxago.interledger.test`)"
      - "traefik.http.routers.mockxago.entrypoints=websecure"
      - "traefik.http.services.mockxago.loadbalancer.server.port=8080"
    environment:
      - CONFIG=/etc/mockxago/config.yaml,/etc/mockxago/config-override.yaml
    volumes:
      - ./config/mockxago.yaml:/etc/mockxago/config.yaml:ro
      - ./config-override/mockxago.yaml:/etc/mockxago/config-override.yaml:ro
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
