services:
  mockbos:
    build:
      context: ../go
      dockerfile: mock/mockbos/Dockerfile
      target: builder
    profiles:
      - application
    restart: always
    develop:
      watch:
        - path: ../go
          action: rebuild
    ports:
      - "18080:8080" # http port
    environment:
      - DB_URL=postgres://postgres:postgres@postgres:5432/mockbos?sslmode=disable
      - XAGO_WEBHOOK_URL=http://backend:8080/webhook/xago

    depends_on:
      - backend