services:
  mockgatehub:
    build:
      context: ..
      dockerfile: go/mock/mockgatehub/Dockerfile
    profiles:
      - application
    restart: always
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mockgatehub.rule=Host(`mockgatehub.interledger.test`)"
      - "traefik.http.routers.mockgatehub.entrypoints=websecure"
      - "traefik.http.services.mockgatehub.loadbalancer.server.port=8080"
    environment:
      - CONFIG=/etc/mockgatehub/config.yaml,/etc/mockgatehub/config-override.yaml
    volumes:
      - ./config/mockgatehub.yaml:/etc/mockgatehub/config.yaml:ro
      - ./config-override/mockgatehub.yaml:/etc/mockgatehub/config-override.yaml:ro
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
