services:
  protea:
    build:
      context: ../typescript/protea
      target: dev
    profiles:
      - application
      - frontend
    restart: always
    volumes:
      - ../typescript/protea:/app:rw
      # Exclude node_modules from sync - use container's version
      - /app/node_modules
    ports:
      - "3000:3000" # http port
      - "8002:8002" # websocket port
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.protea.rule=Host(`interledger.test`)"
      - "traefik.http.routers.protea.service=protea"
      - "traefik.http.services.protea.loadbalancer.server.port=3000"

      - "traefik.http.routers.protea-ws.rule=Host(`interledger.test`) && PathPrefix(`/socket`)"
      - "traefik.http.routers.protea-ws.service=protea-ws"
      - "traefik.http.services.protea-ws.loadbalancer.server.port=8002"

    environment:
      - FYNBOS_ENV=local
      - LOG_LEVEL=debug
      # Setting LOG_PRETTY to false will result in json logs
      - LOG_PRETTY=true

      - KRATOS_URL=http://kratos:4433
      - RAFIKI_AUTH_ENDPOINT=http://rafiki_auth:3009
      - RAFIKI_AUTH_SECRET=my-super-secret-identity-key

      - CHOKIDAR_USEPOLLING=true
      - COOKIE_SECRETS="[\"localsecret\"]"
      - PUSHER_APP_KEY=91988d6075551d29760a
      - PUSHER_APP_CLUSTER=eu
      - PAYMENT_POINTER_BASE=local.ilp.link # todo find a way to figure the name
      - DATO_API_TOKEN=b96709bce873f5280722da965b0e9d
      - BACKEND_GRPC_URL=http://backend:8443

      - REDIS_URL=redis://redis:6379/2

      - OP_INTPAY_ENABLED=${PROTEA_OP_INTPAY_ENABLED:-false}
      - OP_INTPAY_KEY_ID=${PROTEA_OP_INTPAY_KEY_ID:-02088dae-0666-4ab1-b97e-719480037c5c}
      - OP_INTPAY_PRIVATE_KEY=${PROTEA_OP_INTPAY_PRIVATE_KEY:-"LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1DNENBUUF3QlFZREsyVndCQ0lFSUNlemJMNS94b1h5MDBiemliYWVhYzhFVnllWTlCUzFMTDRiaThxSFZLSmoKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ=="}
      - OP_INTPAY_WALLET_ADDRESS=${PROTEA_OP_INTPAY_WALLET_ADDRESS:-https://ilp.interledger-test.dev/ilpusdtest}
      - OP_INTPAY_REDIRECT_URL=${PROTEA_OP_INTPAY_REDIRECT_URL:-https://interledger.test/quick-pay/finish}

    depends_on:
      - backend
