services:
  protea:
    build:
      context: ../typescript/protea
      target: dev
    restart: always
    develop:
      watch:
        - path: ../typescript/protea
          action: rebuild
    ports:
      - "3000:3000" # http port
      - "8002:8002" # websocket port
    labels:
      - "traefik.enable=true"
      # HTTP router for main app
      - "traefik.http.routers.protea-http.rule=Host(`interledger.test`) && !PathPrefix(`/socket`)"
      - "traefik.http.routers.protea-http.entrypoints=web"
      - "traefik.http.routers.protea-http.service=protea"
      # HTTPS router for main app
      - "traefik.http.routers.protea-https.rule=Host(`interledger.test`) && !PathPrefix(`/socket`)"
      - "traefik.http.routers.protea-https.entrypoints=websecure"
      - "traefik.http.routers.protea-https.tls=true"
      - "traefik.http.routers.protea-https.service=protea"
        # HTTP WebSocket router
      - "traefik.http.routers.protea-ws-http.rule=Host(`interledger.test`) && Path(`/socket`)"
      - "traefik.http.routers.protea-ws-http.entrypoints=web"
      - "traefik.http.routers.protea-ws-http.service=protea-ws"
      - "traefik.http.routers.protea-ws-http.middlewares=protea-ws-strip"
      # HTTPS WebSocket router
      - "traefik.http.routers.protea-ws-https.rule=Host(`interledger.test`) && Path(`/socket`)"
      - "traefik.http.routers.protea-ws-https.entrypoints=websecure"
      - "traefik.http.routers.protea-ws-https.tls=true"
      - "traefik.http.routers.protea-ws-https.service=protea-ws"
      - "traefik.http.routers.protea-ws-https.middlewares=protea-ws-strip"
      # WebSocket path stripping middleware
      - "traefik.http.middlewares.protea-ws-strip.stripprefix.prefixes=/socket"
      # Services
      - "traefik.http.services.protea.loadbalancer.server.port=3000"
      - "traefik.http.services.protea-ws.loadbalancer.server.port=8002"
    environment:
      - FYNBOS_ENV=local

      - KRATOS_URL=http://kratos:4433
      - RAFIKI_AUTH_ENDPOINT=http://rafiki_auth:3006

      - CHOKIDAR_USEPOLLING=true
      - COOKIE_SECRETS="[\"localsecret\"]"
      - PUSHER_APP_KEY=91988d6075551d29760a
      - PUSHER_APP_CLUSTER=eu
      - PAYMENT_POINTER_BASE=local.ilp.link # todo find a way to figure the name
      - DATO_API_TOKEN=b96709bce873f5280722da965b0e9d
      - BACKEND_GRPC_URL=http://backend:8443

      - REDIS_URL=redis://redis:6379/2
