services:
  # 1. Rafiki Auth
  rafiki_auth:
    image: ghcr.io/interledger/rafiki-auth:v2.3.0-beta
    profiles:
      - services
    restart: always
    extra_hosts:
    - "local.ilp.link:host-gateway"
    ports:
      - "3003:3003"  # Admin port         http://localhost:3003
      - "3006:3006"  # Auth port          http://localhost:3006
      - "3007:3007"  # Introspection port http://localhost:3007
      - "3009:3009"  # Interaction port   http://localhost:3009
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rafiki_auth.rule=Host(`auth.local.ilp.link`)"
      - "traefik.http.services.rafiki_auth.loadbalancer.server.port=3006"

    environment:
      - ENV_FILE=
      - LOG_LEVEL=info
      - NODE_ENV=production
      - NODE_TLS_REJECT_UNAUTHORIZED=0

      # Multi-tenancy
      - OPERATOR_TENANT_ID=my-tenant-id
      - ADMIN_API_SECRET=my-super-secret-admin-api-key

      # Database configuration
      - AUTH_DATABASE_URL=postgres://postgres:postgres@postgres:5432/rafiki_auth?sslmode=disable

      # Redis configuration
      - REDIS_URL=redis://redis:6379/0
      - REDIS_TLS_CA_FILE_PATH=
      - REDIS_TLS_CERT_FILE_PATH=
      - REDIS_TLS_KEY_FILE_PATH=

      - IDENTITY_SERVER_SECRET=my-super-secret-identity-key

      - COOKIE_KEY=my-super-secret-cookie-key

      - ACCESS_TOKEN_DELETION_DAYS=30
      - ACCESS_TOKEN_EXPIRY_SECONDS=600

      - ADMIN_PORT=3003
      - AUTH_PORT=3006
      - INTROSPECTION_PORT=3007
      - INTERACTION_PORT=3009

      - AUTH_SERVER_URL=https://auth.local.ilp.link
      - IDENTITY_SERVER_URL=https://interledger.test/consent

      # WTF is this?
      # Who designed this shit?
      - DATABASE_CLEANUP_WORKERS=1
      
      - INCOMING_PAYMENT_INTERACTION=false
      - QUOTE_INTERACTION=false
    
      - WAIT_SECONDS=1
      - TRUST_PROXY=true

    depends_on:
      - rafiki_backend

  # # 2. Rafiki Service
  rafiki_backend:
    image: ghcr.io/interledger/rafiki-backend:v2.3.0-beta
    profiles:
      - services
    restart: always
    ports:
      - "3880:80"    # HTTP port
      - "3001:3001"  # Admin port
      - "3002:3002"  # Connector port
    extra_hosts:
    - "local.ilp.link:host-gateway"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.rafiki_backend_connector.service=rafiki_backend_connector"
      - "traefik.http.routers.rafiki_backend_connector.rule=Host(`connector.local.ilp.link`)"
      - "traefik.http.services.rafiki_backend_connector.loadbalancer.server.port=3002"

      - "traefik.http.routers.rafiki_backend_openpayments.service=rafiki_backend_openpayments"
      - "traefik.http.routers.rafiki_backend_openpayments.rule=Host(`local.ilp.link`)"
      - "traefik.http.services.rafiki_backend_openpayments.loadbalancer.server.port=80"

    environment:
      - ENV_FILE=
      - LOG_LEVEL=debug
      - NODE_ENV=production
      - NODE_TLS_REJECT_UNAUTHORIZED=0

      # Multi-tenancy
      - OPERATOR_TENANT_ID=my-tenant-id
      - ADMIN_API_SECRET=my-super-secret-admin-api-key

      # Database configuration
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/rafiki_backend?sslmode=disable

      # Redis configuration
      - REDIS_URL=redis://redis:6379/1
      - REDIS_TLS_CA_FILE_PATH=
      - REDIS_TLS_CERT_FILE_PATH=
      - REDIS_TLS_KEY_FILE_PATH=

      - SIGNATURE_SECRET=your_signature_secret
      - STREAM_SECRET=BjPXtnd00G2mRQwP/8ZpwyZASOch5sUXT5o0iR5b5wU= # Example secret, replace with your own

      - ADMIN_PORT=3001
      - CONNECTOR_PORT=3002

      - AUTH_SERVER_GRANT_URL=https://auth.local.ilp.link
      - AUTH_SERVER_INTROSPECTION_URL=http://rafiki_auth:3007
      - AUTH_SERVICE_API_URL=http://rafiki_auth:3011

      - EXCHANGE_RATES_LIFETIME=15000

      - GRAPHQL_IDEMPOTENCY_KEY_TTL_MS=8.64e+07
      - GRAPHQL_IDEMPOTENCY_KEY_LOCK_MS=2000

      - IDENTITY_SERVER_URL=https://interledger.test/consent

      - ILP_ADDRESS=local.interledger-app
      - ILP_CONNECTOR_URL=https://connector.local.ilp.link

      - INCOMING_PAYMENT_WORKERS=1
      - INCOMING_PAYMENT_WORKER_IDLE=200

      - INSTANCE_NAME=Interledger App Local
      - KEY_ID=interledger-app-rafiki-key-id

      - OPEN_PAYMENTS_PORT=80
      - OPEN_PAYMENTS_URL=https://local.ilp.link
      - OUTGOING_PAYMENT_WORKERS=4
      - OUTGOING_PAYMENT_WORKER_IDLE=200
      - WALLET_ADDRESS_URL=https://local.ilp.link/.well-known/pay
      - WALLET_ADDRESS_REDIRECT_HTML_PAGE=https://interledger.test/me/%wp
      - PAYMENT_POINTER_WORKERS=1
      - PAYMENT_POINTER_WORKER_IDLE=200
      - PRIVATE_KEY_FILE=""
      - PUBLIC_HOST=https://local.ilp.link
      - QUOTE_LIFESPAN=300000

      - SIGNATURE_VERSION=1
      - SLIPPAGE=0.01
      - TIGERBEETLE_CLUSTER_ID=none
      - TIGERBEETLE_REPLICA_ADDRESSES=none
      - TRUST_PROXY=true
      - USE_TIGERBEETLE=false
      - WEBHOOK_TIMEOUT=200
      - WEBHOOK_URL=http://backend:8080/rafiki
      - WEBHOOK_WORKERS=1
      - WEBHOOK_WORKER_IDLE=200
      - WITHDRAWAL_THROTTLE_DELAY=

  # # 3. Rafiki Frontend
  rafiki_frontend:
    image: ghcr.io/interledger/rafiki-frontend:v2.3.0-beta
    profiles:
      - services
    restart: always
    ports:
      - "3010:3010"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rafiki_frontend.rule=Host(`rafiki.mgnt.interledger.test`)"
      - "traefik.http.services.rafiki_frontend.loadbalancer.server.port=3010"

    environment:
      - ENV_FILE=
      - LOG_LEVEL=debug
      - NODE_ENV=production

      - GRAPHQL_URL=http://rafiki_backend:3001/graphql

      - AUTH_ENABLED=false
      - OPEN_PAYMENTS_URL=https://local.ilp.link

      - PORT=3010

    depends_on:
      - rafiki_backend
