services: 
  # 1. Local Docker Registry
  registry:
    # Local Docker Registry for storing images, single platform ONLY
    # Use --platform linux/arm64/v8 for ARM64 images
    # Use --platform linux/amd64 for AMD64 images
    # Example: assuming you pulled ubuntu (docker pull ubuntu)
    # docker tag ubuntu localhost:5000/ubuntu
    # docker push --platform linux/arm64/v8 localhost:5000/ubuntu 
    # docker push --platform linux/amd64 localhost:5000/ubuntu
    image: registry:latest
    profiles:
      - infrastructure
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - registry-data:/var/lib/registry
    environment:
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://localhost:27015]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'

  # 2. Docker Registry UI
  registry-ui:
    image: joxit/docker-registry-ui:latest
    profiles:
      - infrastructure
    ports:
      - "27015:80"
    environment:
      - REGISTRY_URL=http://localhost:5000
      - SINGLE_REGISTRY=true
      - ENABLE_CORS=true
      - CORS_ORIGINS=http://localhost:27015
    depends_on:
      - registry

volumes:
  registry-data: