services:
  traefik:
    image: traefik:v3.5.2
    profiles:
      - infrastructure
    restart: always
    command: --providers.docker
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
      - "28080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/static.yaml:/etc/traefik/traefik.yaml              # static configuration
      - ./config/traefik/dynamic.yaml:/etc/traefik/dynamic.traefik.yaml:ro  # dynamic configuration

      - ./config/certs:/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.test`)"
      - "traefik.http.routers.traefik.service=api@internal"
