services:
  # 1. Migrations
  migration:
    build:
      context: ../go
      dockerfile: backend/Dockerfile
      target: builder
    profiles:
      - application
      - backend
    command: "migrate"
    develop:
      watch:
        - path: ../go
          action: rebuild
    restart: on-failure
    environment:
      - FYNBOS_ENV=local
      - RAFIKI_DB_URL=postgres://postgres:postgres@postgres:5432/rafiki_backend?sslmode=disable
      - RAFIKI_AUTH_DB_URL=postgres://postgres:postgres@postgres:5432/rafiki_auth?sslmode=disable
      - DB_URL_WITH_CERTS=postgres://postgres:postgres@postgres:5432/backend?sslmode=disable
      - PACIOLI_DB_URL_WITH_CERTS=postgres://postgres:postgres@postgres:5432/pacioli?sslmode=disable
      - KRATOS_URL=http://kratos:4434 # check it if is public or admin
      - LOG_LEVEL=info
    
  # 2. Backend 
  backend:
    build:
      context: ../go
      dockerfile: backend/Dockerfile
      target: builder
    profiles:
      - application
      - backend
    command: "dev"
    develop:
      watch:
        - path: ../go
          action: rebuild
    restart: always
    ports:
      - "8080:8080" # http port
      - "8081:8081" # open payments port
      - "8082:8082" # authorisation port
      - "8443:8443" # grpc port
      - "8448:8448" # wallet admin port
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`interledger.test`) && PathPrefix(`/webhooks`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"

    environment:
      - LOG_LEVEL=debug
      - ENV_FILE=
      - FYNBOS_ENV=local

      - RAFIKI_DB_URL=postgres://postgres:postgres@postgres:5432/rafiki_backend?sslmode=disable
      - RAFIKI_AUTH_DB_URL=postgres://postgres:postgres@postgres:5432/rafiki_auth?sslmode=disable

      - DB_URL_WITH_CERTS=postgres://postgres:postgres@postgres:5432/backend?sslmode=disable
      - DB_URL=postgres://postgres:postgres@postgres:5432/backend?sslmode=disable
      - PACIOLI_DB_URL_WITH_CERTS=postgres://postgres:postgres@postgres:5432/pacioli?sslmode=disable
      - PACIOLI_DB_URL=postgres://postgres:postgres@postgres:5432/pacioli?sslmode=disable

      - KRATOS_URL=http://kratos:4433
      - KRATOS_ADMIN_URL=http://kratos:4434

      - USD_LEDGER_ID=1

      - NOOP_EQUITY_ACCOUNT_ID=43d4b2bd-e29b-4a63-9aa8-7990776c714e

      - GOOGLE_OAUTH2_CLIENT_ID=google_oauth
      - RAFIKI_GRAPHQL_URL=http://rafiki_backend:3001/graphql

      - TEMPORAL_URL=temporal:7233
      
      - TWILIO_ACCOUNT_SID=SK021f793191208ba69c3bea87dd426085
      - TWILIO_SERVICE_SID=VA8af4e130da63b9fac4c042acbc33a267
      - TWILIO_ACCOUNT_TOKEN=test

      - ZENDESK_USER=matt@fynbos.dev
      - ZENDESK_TOKEN=test

      - OTEL_EXPORTER_OTLP_ENDPOINT=grpc://api.honeycomb.io:443
      - OTEL_EXPORTER_OTLP_HEADERS=x-honeycomb-team=7Qskhns7Dc7wgazrDe6yZD
      - OTEL_SERVICE_NAME=backend

      # todo later on!
      - PORT=8080
      - OPEN_PAYMENTS_PORT=8081
      - AUTHORISATION_PORT=8082
      
      - RAFIKI_BACKEND_GRAPHQL_URL=http://rafiki_backend:3001/graphql
      - RAFIKI_AUTH_GRAPHQL_URL=http://rafiki_auth:3003/graphql

      - ALLOWED_WALLET_IDS=
      - BLOCKED_REGIONS=

      - XAGO_API_PUBLIC_KEY=9c9895ac-569f-44f2-be52-9e060b5116bd 
      - XAGO_API_SECRET=6ce9d69b-d472-4734-b730-f3fa549fc811

      - PERSONA_WEBHOOK_TOKEN=wbhsec_9d0ea2bc-8b15-4ad0-8f1b-6dbfc986035b
      - PERSONA_TOKEN=persona_sandbox_a3bede7f-b77f-451f-8d7c-68e324e3eaf1
      - GATEHUB_APP_ID=d0cb50d1-07eb-4bcb-a6f8-f3143e43a34c
      - GATEHUB_SECRET=7cbdd10b9a3187dd32758e1237452af6d3ccfc38
      - GATEHUB_WEBHOOK_SECRET=93a193614286262a890f439fe853d15d2e6d725cf5bc00147b396d529956a395
      - GATEHUB_CARD_APP_ID=a50ff7db-56e3-49c6-9211-ad9f01edbb90
      - GATEHUB_GATEWAY_ID=b18965b5-8bb0-486e-88b2-7be47b974ac1
      - GATEHUB_PAYWISER_EURO_VAULT_ID=67df5a03-587a-491f-8edb-37a9ef13daba
      - GATEHUB_GATEHUB_EURO_VAULT_ID=a09a0a2c-1a3a-44c5-a1b9-603a6eea9341
      - CHIMONEY_TOKEN=d2c4a842795d0ab2a2785e9e58fda5578ac6059b9e07ccb2ebe532ac45f98d59
      - CHIMONEY_API_ID=eaeaca7b-4d35-4ec3-888b-a180418c80c6
      - CHIMONEY_TEAM_ID=qO4CopeTvTceTL0fGIoGMTqTQN82
      - CHIMONEY_WEBHOOK_SECRET=whsec_WYqGH4pT5mSi31Ccu8ICIN0Sa3lTpOa


      - PTI_BASE_URL=https://api.staging.fiant.io/v1
      - PTI_CLIENT_ID=81a556d8-106d-4c93-8c6f-f2f8e555b4f0
      - PTI_JWK={"d":"UMjijq3vSlU1DjJsvE1CZ8LEQMiHecbj6qv2iuhUNSQOzv5iPG2UDLP3FF2xonmV-ZV9GuQSEN78tSSmuU0Sguse7YWxAVM6w-EeeVS9rq-Uog4IPXaA50Yeu1MM9lwjmXOLDz7RASoh5u54mdg280RoWjDiP-40iB-Ngbv4FpO8CGTa-AqEVxMcXN36GxBLfyyNGAPNwoNyayvNiaAq3FdQ5qi8yhBaw6R43ie7Kk19YfKANMUxbBYM28ZGnlVZuXpY5MGraoYPeCILz6Fni5RWtxFKFCi8O77czwlkzCYMDzZ_j6r7UISWHfIgKXrqf3q_JyufDemFigK92LHMNbNx-OF7bVAze0yQNbdAXg1MQ1uWdaScNM4uKKYkef2j0SUOcMh_hwTlreYayYJPS1kKjxcIOdLzXZVgviWdidFsOT1qEr9ealVA7iYV7iqexhVS8CQm1R5R_Nin-BtczGW-6OInq44oeafw7OxwT33rEqciu5V4PsVw209em4egrmZrv8RrIXALwHL4P3_FlGl2Go_cxCZ-kE4hYuAjajVtr7MMVF2Ku3M8wNcHSeG81s0CMk0LEYNmBwXQZO5pP8tqKbfFv6CWW9wL3FBTxmR9HCGxouCDUuJ-t4Gjys9VzvqdYEs2QzimMAhRw5onzha3gNjwXDr6e8874zS4A-0","dp":"yNTThaMbd3mECn6Mp0S-yU2N6Q58OVsiZzwhNO0bqX-Zk9UtGpHNRT-rbzD7hY3ReAQAPwtRffuUWibqEY4KPaizC3w3B9a1E15lSVjk9WgDMIUjJ_rU7sVrjFjr9ULJmCuKQR42CYDXZNgKil76y_6FYvTPDYG_DDtTMAgWO7pyakBp1_pB3ib-YlddeozpJjKhjCgtNsxTeExEo6W5R_8rYTRbpnloIMJSLlHAefnHH7V9ntHlmCqGN_kK1MRAh2iUtU8Uldv9LdteAAIZGNT755dnuJNZ-1l8pj2WFN4pXSANfWwIfapIfb7aUOAt8C4jjyy7VDGSe8bDrGCS2Q","dq":"dhKzGVziOAuuFS2RIBi5UsoiIGzylFdJjKrfjdmZ0pcFiVmWHaTd8UU7O3BE8hiUXdi3E_G-Q2jiVHZfdLyIAkG2W5pGs_AslKv_skF7HnOXPIInbT5EHbHg_pcfR3y6NeWjjZR71p1KAsOtbUzeqdbLWv3QFYQzbDSHEDmV-fbEYLT3pn0FxojtkKwzVvO3rB35tLgEzjXz5r-Yifapj_ub61mlhpeOka7vFYj5ErkOmiwZema1qDH1PnHel4DN37OsDM38B0YZS0p6OKNXHUpY7HrzFRK8bOd1zg039VZuQoGRbYWpYgiGEFjcONgjsoN1_x4TS2L6zRAv_gJK7w","e":"AQAB","kid":"81c27002-f83b-45ea-9b3f-38096d7ac1ee","kty":"RSA","n":"0kDVpwyOIQFTWSTSbnKaUOAbsE2shES99v3JMQ_MvFMzhhjB7A04npiOAfCBpMJDmRxSBr36nxL588s2-B505KN0KFi3osGW5Af0JosBWKdU-ik85tiB3P9RpAMiWKRPEe9aRoNKlzTI263kNVIkc5CnXYNNsJB9UHfG1lfLkTmjtfT-VOeNvvMndJ9G0cw9CJyGSJOsvY32fZPbal407nHGS5f4yj3XJsG3Nwlq1sgsUdvPJznb4bLjJ_nDBzUpIali1rhRiVUfhyhEveut3ZNNzCGPjdbzu-qn_Q3GFmpSgMC-DWJuTOCVBkE6i1TMNMvsimnGAZJMjFb7cyvlxc6T5-m7ug_Tl_A_hfctbPemZDAGoT97DxQ-HakS54I0qaPDBqalz9tJ9iz-QKEzLencIUaKlRD6CiyC-Izffi5RiLgYEKeesUNbguMhHbLgLedWPje-A6cCHiohTajZNpYCDWc7oU2_w9a0z5cqG2Z-2e_b6Rbi8hp3Q1R94Ym55sg1NssyGDE4xxoC5pw7kwNhnQnSRk5Zozoa4_EyofBV3AQ7lIfHUyeAu8yfdcWuwPTetzjHJfsY94gGV2lqdnNAv4fVjPEoHgQRNllaAWQCqovd-UKnl5sRhtEFB9ENVJw-9gwnwoYB9xvWOkdBdVxuVjnrzmytndMku1nh6I0","p":"6G1ZW9-HLnpBqL5WSCg-addGEKf6ZMFSz_uywSd6Sd2MP6Vx5ziwcuvXMyPxayW8EhuPP6ZiKPZx1wCwKn7QjI3F-QRCx85d0tgz0xLjlYOXl3IslFfee0OM2xzqfb41ifETD_gl78rpnvbmyQRF2YaGb2aX8XcGOr57oUvi3hj7cj4dg1rWwTOu9VbHdp3hdDMsbJ0llvs34Qp0x3cicAs6B6E7Mr7XRNpPdZMr53QdjeGlD_cNAs2q_EDk64IFqI5UzKS-eMKoio3Jny84MmgSEUQdguFJ5ig3Z6SzZMubE3IPk3kgysIhRdCyAdHPk1cMzwPBJd6mK4yg4UKYjw","q":"55PFaErNEU5SXWNA6TjVj4tXgNEFeOqKQRPl3YxzaQTZvCkm67pu0CY30ymkSFVtH0YVmCp9oz8iWwk_GUY4i8EHhpb1jzPop7GFbBnvpoHHYl-I-HOKsOHngMNgLRQnhXr_MIi_naNxGmfnL2MRLJtwr_jaR1QHJLRe0ja7vh5-i06Jurt46e7yZfQvvQDDZAes2a8f2XhGRjA23clXVdZ1xplG-64AynuFLcLOh3OYWlym-QG5ZqpKHinC-y0saoDAsuuuXx9wOYTNvkNmz5WmAJDixcfqfAjQ21F2QV5cO6oSNiCVHafpc7byZihZIsCnN-t8g4ugmkoXmRyjIw","qi":"SzgQlV0cv2EWhlKV_kaoq6aty7TeRCHPH8FH7gd4V-Mf4HOoOuS7mtYk8FehKKwliqmy2YadIZERoHJBkUXiFoAlq_AkuQnFxrTT4Q5Fgm1uPkGCnQf92wXFEGFhzmlogOO4GcEQFfEJw8pN0i4UM42W91gfN2S6AjRP8QGOTjdlcVQbY70StbwG0HxewhvmSfwriqBs-3eoYR46jG6lK7vvascGjjZSqV0MZGGHcA_8hp9u7J1ZPksHAxvQ_nY76e7ZBC3ccGv9GkvkdfLxoviEsaovyWrajSQNCcxrk3MG64pkE9Fz-3ZzVH0ySnKmvLHzT4-OUPlQlwXeSsK3Bg"}
      - PTI_PUBLIC_KEY_JWK={"e":"AQAB","kid":"84d1a616-db99-47dd-b690-70742b87aa4e","kty":"RSA","n":"1EWed921xDloYd1SbAkUsHbPqeKtGIOAmZhT4aYrT3F1-rugltXSSugO7SlLuUlH1k1a2tJyK3TtCbuSHE11Y8SGQeRcUFvLISz6XqBgAA59NOj_6gIMuE1L4MM5nEfbFHxq6YqDMDO5hZ5_P-2BMS-dtxx9VoPgUJC_OuglDvckpG3xxqITIbhfGsDe2_KolEHRkW8ozGNfR2kAKpuJFTqJTUg7jFDmNq_zgUA6_13d9F_tWN6uyW5X0gN9UjpEE86uFh49ScjwVthcRamiqk-PmrGmgoFrrplszf6bD7QScytecrag92Ls1kmX00BHnV0MBsh-Bk8vE8u88MNT0dfj5OLMIhqS014najHSMnXdTZg2iav9-r-iAQ5vHnfMGupR3jBttGlFWp72cKZUqA_Tu0m4efxiTzWJk10rDOdLOBsQBkDmMC72X-FmfxYXscr4vrDRvbGAfEFoceanYg8fQbr0A4mQtLZlAAsmLBBuLHvw3MPpW2eD1H8wicm2i0J8_EHdhwp3u-83rtkVhowmjE9hav9lpjiFmSNGFYjR8ddxmRNM-vDc4o165frPnGpAhqTnnDelZcNT_CFkgwQ4H38J4ciuB50pM8meoCbapKunK9DqH0gs2iwpMUcq3B0pWJ27nvtnvujiVXTWCP9A8Dk4J-LQUU-TquQy8k0"}

    depends_on:
      - migration
