services:
  # 1. Migrations
  migration:
    build:
      context: ../go
      dockerfile: backend/Dockerfile
      target: builder
    profiles:
      - application
      - backend
    command: "migrate"
    develop:
      watch:
        - path: ../go
          action: rebuild
    restart: on-failure
    environment:
      - FYNBOS_ENV=local
      - RAFIKI_DB_URL=postgres://postgres:postgres@postgres:5432/rafiki_backend?sslmode=disable
      - RAFIKI_AUTH_DB_URL=postgres://postgres:postgres@postgres:5432/rafiki_auth?sslmode=disable
      - DB_URL_WITH_CERTS=postgres://postgres:postgres@postgres:5432/backend?sslmode=disable
      - PACIOLI_DB_URL_WITH_CERTS=postgres://postgres:postgres@postgres:5432/pacioli?sslmode=disable
      - KRATOS_URL=http://kratos:4434 # check it if is public or admin
      - LOG_LEVEL=info
    
  # 2. Backend 
  backend:
    build:
      context: ../go
      dockerfile: backend/Dockerfile
      target: builder
    profiles:
      - application
      - backend
    command: "dev"
    develop:
      watch:
        - path: ../go
          action: rebuild
    restart: always
    ports:
      - "8080:8080" # http port
      - "8081:8081" # open payments port
      - "8082:8082" # authorisation port
      - "8443:8443" # grpc port
      - "8448:8448" # wallet admin port
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`interledger.test`) && PathPrefix(`/webhooks`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"

    environment:
      - LOG_LEVEL=debug
      - ENV_FILE=
      - FYNBOS_ENV=local

      - RAFIKI_DB_URL=postgres://postgres:postgres@postgres:5432/rafiki_backend?sslmode=disable
      - RAFIKI_AUTH_DB_URL=postgres://postgres:postgres@postgres:5432/rafiki_auth?sslmode=disable

      - DB_URL_WITH_CERTS=postgres://postgres:postgres@postgres:5432/backend?sslmode=disable
      - DB_URL=postgres://postgres:postgres@postgres:5432/backend?sslmode=disable
      - PACIOLI_DB_URL_WITH_CERTS=postgres://postgres:postgres@postgres:5432/pacioli?sslmode=disable
      - PACIOLI_DB_URL=postgres://postgres:postgres@postgres:5432/pacioli?sslmode=disable

      - KRATOS_URL=http://kratos:4433
      - KRATOS_ADMIN_URL=http://kratos:4434

      - USD_LEDGER_ID=1

      - NOOP_EQUITY_ACCOUNT_ID=43d4b2bd-e29b-4a63-9aa8-7990776c714e

      - GOOGLE_OAUTH2_CLIENT_ID=google_oauth
      - RAFIKI_GRAPHQL_URL=http://rafiki_backend:3001/graphql

      - TEMPORAL_URL=temporal:7233
      
      - TWILIO_ACCOUNT_SID=SK021f793191208ba69c3bea87dd426085
      - TWILIO_SERVICE_SID=VA8af4e130da63b9fac4c042acbc33a267
      - TWILIO_ACCOUNT_TOKEN=test

      - ZENDESK_USER=matt@fynbos.dev
      - ZENDESK_TOKEN=test

      - OTEL_EXPORTER_OTLP_ENDPOINT=grpc://api.honeycomb.io:443
      - OTEL_EXPORTER_OTLP_HEADERS=x-honeycomb-team=7Qskhns7Dc7wgazrDe6yZD
      - OTEL_SERVICE_NAME=backend

      # todo later on!
      - PORT=8080
      - OPEN_PAYMENTS_PORT=8081
      - AUTHORISATION_PORT=8082
      
      - RAFIKI_BACKEND_GRAPHQL_URL=http://rafiki_backend:3001/graphql
      - RAFIKI_AUTH_GRAPHQL_URL=http://rafiki_auth:3003/graphql

      - ALLOWED_WALLET_IDS=
      - BLOCKED_REGIONS=

      - GATEHUB_APP_ID=<fetch-me-from-vault>
      - GATEHUB_SECRET=<fetch-me-from-vault>
      - GATEHUB_CARD_APP_ID=<fetch-me-from-vault> 
 
      - PTI_BASE_URL=<fetch-me-from-vault>
      - PTI_CLIENT_ID=<fetch-me-from-vault>
      - PTI_JWK=<fetch-me-from-vault>
      - PTI_PUBLIC_KEY_JWK={"e":"AQAB","kid":"84d1a616-db99-47dd-b690-70742b87aa4e","kty":"RSA","n":"1EWed921xDloYd1SbAkUsHbPqeKtGIOAmZhT4aYrT3F1-rugltXSSugO7SlLuUlH1k1a2tJyK3TtCbuSHE11Y8SGQeRcUFvLISz6XqBgAA59NOj_6gIMuE1L4MM5nEfbFHxq6YqDMDO5hZ5_P-2BMS-dtxx9VoPgUJC_OuglDvckpG3xxqITIbhfGsDe2_KolEHRkW8ozGNfR2kAKpuJFTqJTUg7jFDmNq_zgUA6_13d9F_tWN6uyW5X0gN9UjpEE86uFh49ScjwVthcRamiqk-PmrGmgoFrrplszf6bD7QScytecrag92Ls1kmX00BHnV0MBsh-Bk8vE8u88MNT0dfj5OLMIhqS014najHSMnXdTZg2iav9-r-iAQ5vHnfMGupR3jBttGlFWp72cKZUqA_Tu0m4efxiTzWJk10rDOdLOBsQBkDmMC72X-FmfxYXscr4vrDRvbGAfEFoceanYg8fQbr0A4mQtLZlAAsmLBBuLHvw3MPpW2eD1H8wicm2i0J8_EHdhwp3u-83rtkVhowmjE9hav9lpjiFmSNGFYjR8ddxmRNM-vDc4o165frPnGpAhqTnnDelZcNT_CFkgwQ4H38J4ciuB50pM8meoCbapKunK9DqH0gs2iwpMUcq3B0pWJ27nvtnvujiVXTWCP9A8Dk4J-LQUU-TquQy8k0"}

    depends_on:
      - migration
