type Query{
  identity: Identity
}

type Mutation {
  createIdentity(input: CreateIdentityInput!): CreateIdentityMutationResponse!
}

interface MutationResponse {
  code: String!
  success: Boolean!
  message: String!
}

type Identity {
  id: ID!
  firstName: String!
  lastName: String!
  mobileNumber: String!
  email: String!
  dateOfBirth: String!
  address: [String]!
  state: String!
  city: String!
  postalCode: String!
  country: String!
  taxIdNumber: String!
}

input CreateIdentityInput {
  firstName: String!
  lastName: String!
  mobileNumber: String!
  country: String!
}

type CreateIdentityMutationResponse implements MutationResponse {
  code: String!
  success: Boolean!
  message: String!
  identity: Identity
}