type Query {
  identity: Identity
  fundingSources: [FundingSource]!
  account: Account
  countries: [Country!]!
  transactions(input: Pagination!): TransactionsConnection!
  transaction(id: String!): Transaction!
}

type Mutation {
  initiateOnboarding: InitiateOnboardingMutationResponse!
  onboardAccount: OnboardingMutationResponse!
  createAccount(input: CreateAccountInput!): CreateAccountMutationResponse!
  verifyAccount(input: VerifyAccountInput!): VerifyAccountMutationResponse!
  linkUsdBankAccount(
    input: LinkUsdBankAccountInput!
  ): LinkFundingSourceMutationResponse!
  verifyUsdBankAccount(
    input: VerifyUsdBankAccountInput!
  ): VerifyUsdBankAccountMutationResponse!
}

interface MutationResponse {
  code: String!
  success: Boolean!
  message: String!
}

type Identity {
  id: ID!
  firstName: String!
  lastName: String!
  mobileNumber: String!
  email: String!
  country: String!
}

input CreateAccountInput {
  firstName: String!
  lastName: String!
  mobileNumber: String!
  country: String!
}

type InitiateOnboardingMutationResponse implements MutationResponse {
  code: String!
  success: Boolean!
  message: String!
  providerOnboarding: UnitProviderOnboarding!
}

type UnitProviderOnboarding {
  id: String!
  formUrl: String!
}

type OnboardingMutationResponse implements MutationResponse {
  code: String!
  success: Boolean!
  message: String!
  account: Account!
}

type CreateAccountMutationResponse implements MutationResponse {
  code: String!
  success: Boolean!
  message: String!
  account: Account
}

input VerifyAccountInput {
  DateOfBirth: String!
  Address: [String!]!
  State: String!
  City: String!
  PostalCode: String!
  TaxIdNumber: String!
}

type VerifyAccountMutationResponse implements MutationResponse {
  code: String!
  success: Boolean!
  message: String!
  account: Account
}

input LinkUsdBankAccountInput {
  name: String!
  accountNumber: String!
  routingNumber: String!
  institution: String!
  type: String!
}

type FundingSource {
  id: ID!
  name: String!
  verificationStatus: String!
  mask: String!
  type: String!
  subType: String!
}

type LinkFundingSourceMutationResponse implements MutationResponse {
  code: String!
  success: Boolean!
  message: String!
  fundingSource: FundingSource
}

type VerifyUsdBankAccountMutationResponse implements MutationResponse {
  code: String!
  success: Boolean!
  message: String!
  fundingSource: FundingSource
}

input VerifyUsdBankAccountInput {
  FundingSourceId: String!
}

enum TransactionType {
  DEPOSIT
  WITHDRAWAL
  OUTGOINGPAYMENT
  SENT
}

type Transaction {
  id: ID!
  type: TransactionType!
  description: String!
  amount: String!
  timestamp: String!
  status: String!
}


type Account {
  id: ID!
  balance: String!
  recentTransactions: [Transaction!]!
}

type Country {
  id: String!
  name: String!
}

type PageInfo {
  hasNextPage: Boolean!
  startCursor: String!
  endCursor: String!
}

input Pagination {
  after: String!
  first: Int!
}

type TransactionEdge {
  node: Transaction!
  cursor: String!
}

type TransactionsConnection {
  pageInfo: PageInfo!
  edges: [TransactionEdge!]!
}
