type Query{
  identity: Identity
}

type Mutation {
  createIdentity(input: IdentityInput!): CreateIdentityMutationResponse!
}

interface MutationResponse {
  code: String!
  success: Boolean!
  message: String!
}

type Identity {
  id: ID!
  legalName: String!
  country: String!
  email: String!
}

input IdentityInput {
  legalName: String!
  country: String!
}

type CreateIdentityMutationResponse implements MutationResponse {
  code: String!
  success: Boolean!
  message: String!
  identity: Identity
}