// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	notify "gitlab.com/fynbos/backend/notify"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// NotifyWallet mocks base method.
func (m *MockClient) NotifyWallet(ctx context.Context, walletId string, event notify.NotificationType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyWallet", ctx, walletId, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyWallet indicates an expected call of NotifyWallet.
func (mr *MockClientMockRecorder) NotifyWallet(ctx, walletId, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyWallet", reflect.TypeOf((*MockClient)(nil).NotifyWallet), ctx, walletId, event)
}
