// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreatePTIUserAddress implements pgx.CopyFromSource.
type iteratorForCreatePTIUserAddress struct {
	rows                 []CreatePTIUserAddressParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePTIUserAddress) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePTIUserAddress) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].Street,
		r.rows[0].PostalCode,
		r.rows[0].StateCode,
		r.rows[0].Country,
		r.rows[0].IsDefault,
	}, nil
}

func (r iteratorForCreatePTIUserAddress) Err() error {
	return nil
}

func (q *Queries) CreatePTIUserAddress(ctx context.Context, arg []CreatePTIUserAddressParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"pti_user_addresses"}, []string{"user_id", "street", "postal_code", "state_code", "country", "is_default"}, &iteratorForCreatePTIUserAddress{rows: arg})
}

// iteratorForCreatePTIUserEmail implements pgx.CopyFromSource.
type iteratorForCreatePTIUserEmail struct {
	rows                 []CreatePTIUserEmailParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePTIUserEmail) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePTIUserEmail) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].Address,
		r.rows[0].IsDefault,
	}, nil
}

func (r iteratorForCreatePTIUserEmail) Err() error {
	return nil
}

func (q *Queries) CreatePTIUserEmail(ctx context.Context, arg []CreatePTIUserEmailParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"pti_user_emails"}, []string{"user_id", "address", "is_default"}, &iteratorForCreatePTIUserEmail{rows: arg})
}

// iteratorForCreatePTIUserPhone implements pgx.CopyFromSource.
type iteratorForCreatePTIUserPhone struct {
	rows                 []CreatePTIUserPhoneParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePTIUserPhone) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePTIUserPhone) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].Number,
		r.rows[0].IsDefault,
	}, nil
}

func (r iteratorForCreatePTIUserPhone) Err() error {
	return nil
}

func (q *Queries) CreatePTIUserPhone(ctx context.Context, arg []CreatePTIUserPhoneParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"pti_user_phones"}, []string{"user_id", "number", "is_default"}, &iteratorForCreatePTIUserPhone{rows: arg})
}
