// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	rafiki "gitlab.com/fynbos/backend/rafiki"
	transactions "gitlab.com/fynbos/backend/transactions"
	wallets "gitlab.com/fynbos/backend/wallets"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CancelOutgoingPayment mocks base method.
func (m *MockClient) CancelOutgoingPayment(ctx context.Context, paymentPointerID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOutgoingPayment", ctx, paymentPointerID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelOutgoingPayment indicates an expected call of CancelOutgoingPayment.
func (mr *MockClientMockRecorder) CancelOutgoingPayment(ctx, paymentPointerID, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOutgoingPayment", reflect.TypeOf((*MockClient)(nil).CancelOutgoingPayment), ctx, paymentPointerID, reason)
}

// CreateIncomingPayment mocks base method.
func (m *MockClient) CreateIncomingPayment(ctx context.Context, args rafiki.CreateIncomingPaymentArgs) (*rafiki.IncomingPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIncomingPayment", ctx, args)
	ret0, _ := ret[0].(*rafiki.IncomingPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIncomingPayment indicates an expected call of CreateIncomingPayment.
func (mr *MockClientMockRecorder) CreateIncomingPayment(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIncomingPayment", reflect.TypeOf((*MockClient)(nil).CreateIncomingPayment), ctx, args)
}

// CreatePaymentPointer mocks base method.
func (m *MockClient) CreatePaymentPointer(ctx context.Context, address wallets.Wallet) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentPointer", ctx, address)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaymentPointer indicates an expected call of CreatePaymentPointer.
func (mr *MockClientMockRecorder) CreatePaymentPointer(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentPointer", reflect.TypeOf((*MockClient)(nil).CreatePaymentPointer), ctx, address)
}

// CreatePaymentPointerKey mocks base method.
func (m *MockClient) CreatePaymentPointerKey(ctx context.Context, keyID, walletID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentPointerKey", ctx, keyID, walletID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePaymentPointerKey indicates an expected call of CreatePaymentPointerKey.
func (mr *MockClientMockRecorder) CreatePaymentPointerKey(ctx, keyID, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentPointerKey", reflect.TypeOf((*MockClient)(nil).CreatePaymentPointerKey), ctx, keyID, walletID)
}

// FinalizeWebMonetization mocks base method.
func (m *MockClient) FinalizeWebMonetization(ctx context.Context, paymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeWebMonetization", ctx, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinalizeWebMonetization indicates an expected call of FinalizeWebMonetization.
func (mr *MockClientMockRecorder) FinalizeWebMonetization(ctx, paymentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeWebMonetization", reflect.TypeOf((*MockClient)(nil).FinalizeWebMonetization), ctx, paymentID)
}

// FundOutgoingPayment mocks base method.
func (m *MockClient) FundOutgoingPayment(ctx context.Context, paymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FundOutgoingPayment", ctx, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// FundOutgoingPayment indicates an expected call of FundOutgoingPayment.
func (mr *MockClientMockRecorder) FundOutgoingPayment(ctx, paymentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FundOutgoingPayment", reflect.TypeOf((*MockClient)(nil).FundOutgoingPayment), ctx, paymentID)
}

// GetGrant mocks base method.
func (m *MockClient) GetGrant(ctx context.Context, grantID string) (*rafiki.Grant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrant", ctx, grantID)
	ret0, _ := ret[0].(*rafiki.Grant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGrant indicates an expected call of GetGrant.
func (mr *MockClientMockRecorder) GetGrant(ctx, grantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrant", reflect.TypeOf((*MockClient)(nil).GetGrant), ctx, grantID)
}

// GetIncomingPayment mocks base method.
func (m *MockClient) GetIncomingPayment(ctx context.Context, id string) (*rafiki.IncomingPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomingPayment", ctx, id)
	ret0, _ := ret[0].(*rafiki.IncomingPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomingPayment indicates an expected call of GetIncomingPayment.
func (mr *MockClientMockRecorder) GetIncomingPayment(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomingPayment", reflect.TypeOf((*MockClient)(nil).GetIncomingPayment), ctx, id)
}

// GetWalletAddress mocks base method.
func (m *MockClient) GetWalletAddress(ctx context.Context, walletID string) (*rafiki.WalletAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletAddress", ctx, walletID)
	ret0, _ := ret[0].(*rafiki.WalletAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletAddress indicates an expected call of GetWalletAddress.
func (mr *MockClientMockRecorder) GetWalletAddress(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletAddress", reflect.TypeOf((*MockClient)(nil).GetWalletAddress), ctx, walletID)
}

// ListGrants mocks base method.
func (m *MockClient) ListGrants(ctx context.Context, walletID string) ([]rafiki.Grant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGrants", ctx, walletID)
	ret0, _ := ret[0].([]rafiki.Grant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGrants indicates an expected call of ListGrants.
func (mr *MockClientMockRecorder) ListGrants(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGrants", reflect.TypeOf((*MockClient)(nil).ListGrants), ctx, walletID)
}

// ListPendingTransactions mocks base method.
func (m *MockClient) ListPendingTransactions(ctx context.Context, walletID string) ([]transactions.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingTransactions", ctx, walletID)
	ret0, _ := ret[0].([]transactions.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingTransactions indicates an expected call of ListPendingTransactions.
func (mr *MockClientMockRecorder) ListPendingTransactions(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingTransactions", reflect.TypeOf((*MockClient)(nil).ListPendingTransactions), ctx, walletID)
}

// RevokeGrant mocks base method.
func (m *MockClient) RevokeGrant(ctx context.Context, grantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeGrant", ctx, grantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeGrant indicates an expected call of RevokeGrant.
func (mr *MockClientMockRecorder) RevokeGrant(ctx, grantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeGrant", reflect.TypeOf((*MockClient)(nil).RevokeGrant), ctx, grantID)
}

// RevokePaymentPointerKey mocks base method.
func (m *MockClient) RevokePaymentPointerKey(ctx context.Context, keyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokePaymentPointerKey", ctx, keyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokePaymentPointerKey indicates an expected call of RevokePaymentPointerKey.
func (mr *MockClientMockRecorder) RevokePaymentPointerKey(ctx, keyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokePaymentPointerKey", reflect.TypeOf((*MockClient)(nil).RevokePaymentPointerKey), ctx, keyID)
}

// RollbackWebMonetization mocks base method.
func (m *MockClient) RollbackWebMonetization(ctx context.Context, paymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackWebMonetization", ctx, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackWebMonetization indicates an expected call of RollbackWebMonetization.
func (mr *MockClientMockRecorder) RollbackWebMonetization(ctx, paymentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackWebMonetization", reflect.TypeOf((*MockClient)(nil).RollbackWebMonetization), ctx, paymentID)
}

// UpdateWalletAddressStatus mocks base method.
func (m *MockClient) UpdateWalletAddressStatus(ctx context.Context, walletId rafiki.UpdateAddressStatus, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWalletAddressStatus", ctx, walletId, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWalletAddressStatus indicates an expected call of UpdateWalletAddressStatus.
func (mr *MockClientMockRecorder) UpdateWalletAddressStatus(ctx, walletId, isActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWalletAddressStatus", reflect.TypeOf((*MockClient)(nil).UpdateWalletAddressStatus), ctx, walletId, isActive)
}

// WebhookHandler mocks base method.
func (m *MockClient) WebhookHandler() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebhookHandler")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// WebhookHandler indicates an expected call of WebhookHandler.
func (mr *MockClientMockRecorder) WebhookHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebhookHandler", reflect.TypeOf((*MockClient)(nil).WebhookHandler))
}

// WithdrawIncomingPaymentLiquidity mocks base method.
func (m *MockClient) WithdrawIncomingPaymentLiquidity(ctx context.Context, incomingPaymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawIncomingPaymentLiquidity", ctx, incomingPaymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawIncomingPaymentLiquidity indicates an expected call of WithdrawIncomingPaymentLiquidity.
func (mr *MockClientMockRecorder) WithdrawIncomingPaymentLiquidity(ctx, incomingPaymentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawIncomingPaymentLiquidity", reflect.TypeOf((*MockClient)(nil).WithdrawIncomingPaymentLiquidity), ctx, incomingPaymentID)
}

// WithdrawOutgoingPaymentLiquidity mocks base method.
func (m *MockClient) WithdrawOutgoingPaymentLiquidity(ctx context.Context, outgoingPaymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawOutgoingPaymentLiquidity", ctx, outgoingPaymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawOutgoingPaymentLiquidity indicates an expected call of WithdrawOutgoingPaymentLiquidity.
func (mr *MockClientMockRecorder) WithdrawOutgoingPaymentLiquidity(ctx, outgoingPaymentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawOutgoingPaymentLiquidity", reflect.TypeOf((*MockClient)(nil).WithdrawOutgoingPaymentLiquidity), ctx, outgoingPaymentID)
}
