package ledger

import (
	"context"
	"github.com/interledger/interledger-app/go/pacioli/ledger/tigerroach"

	"github.com/interledger/interledger-app/go/pacioli"
)

// ConfigureLedgers is declarative and will not fail if the ledger exists. It will fail if one exists with
// different fields.
func ConfigureLedgers(
	ctx context.Context,
	b Backends,
	args []pacioli.ConfigureLedgerArgs,
) ([]pacioli.LedgerResult, error) {
	return tigerroach.ConfigureLedgers(ctx, b, args)
}

func GetLedgers(ctx context.Context, b Backends, ids []uint32) ([]pacioli.Ledger, error) {
	// TODO: ACL
	return tigerroach.ListLedgers(ctx, b, ids)
}

// This is declaritive and will not fail if the account exists. It will fail if one exists with
// different fields.
func ConfigureAccounts(
	ctx context.Context,
	b Backends,
	args []pacioli.ConfigureAccountArgs,
) ([]pacioli.AccountResult, error) {

	res, err := tigerroach.ConfigureAccounts(ctx, b, args)
	if err != nil {
		// All err
		return nil, err
	}

	return res, nil
}

func GetAccounts(
	ctx context.Context,
	b Backends,
	accountIDs []string,
) ([]pacioli.Account, error) {

	trAccs, err := tigerroach.ListAccounts(ctx, b, accountIDs)
	if err != nil {
		return nil, err
	}

	return trAccs, nil
}

// TODO: Assuming that IDs are uuids and are being generated by another service for now. Might be better to be
// unopinionated and accept []byte.
func CreateTransfers(ctx context.Context, b Backends, args []pacioli.CreateTransferArgs) ([]pacioli.TransferResult, error) {
	// TODO: collect ledgers and perform ACL. TigerBeetle will introduce the ledger field onto
	// a transfer.

	trRes, err := tigerroach.CreateTransfers(ctx, b, args)
	if err != nil {
		return nil, err
	}

	return trRes, nil
}

func GetTransfers(ctx context.Context, b Backends, transferIDs []string) ([]pacioli.Transfer, error) {
	// TODO: ACL on ledgers involved

	trTransfers, err := tigerroach.ListTransfers(ctx, b, transferIDs)
	if err != nil {
		return nil, err
	}

	return trTransfers, nil
}

func PostTransfers(ctx context.Context, b Backends, transferIDs []string) ([]pacioli.TransferResult, error) {

	trNewIDs, trResults, err := tigerroach.PostTransfers(ctx, b, transferIDs)
	if err != nil {
		return nil, err
	}

	if len(trNewIDs) == 0 {
		return trResults, nil
	}

	return trResults, nil
}

func VoidTransfers(ctx context.Context, b Backends, transferIDs []string) ([]pacioli.TransferResult, error) {

	trResults, err := tigerroach.VoidTransfers(ctx, b, transferIDs)
	if err != nil {
		return nil, err
	}

	return trResults, nil
}
