package ledger

import (
	"context"
	"encoding/hex"
	"errors"
	"fmt"
	"reflect"
	"strings"

	"gitlab.com/fynbos/log"

	"go.uber.org/zap"

	"gitlab.com/fynbos/pacioli/ledger/tigerroach"

	tb_types "github.com/coilhq/tigerbeetle-go/pkg/types"
	"github.com/google/uuid"
	"gitlab.com/fynbos/pacioli"
)

// ConfigureLedgers is declaritive and will not fail if the ledger exists. It will fail if one exists with
// different fields.
func ConfigureLedgers(
	ctx context.Context,
	b Backends,
	args []pacioli.ConfigureLedgerArgs,
) ([]pacioli.LedgerResult, error) {
	return tigerroach.ConfigureLedgers(ctx, b, args)
}

func GetLedgers(ctx context.Context, b Backends, ids []uint32) ([]pacioli.Ledger, error) {
	// TODO: ACL
	return tigerroach.ListLedgers(ctx, b, ids)
}

// Helper function to convert uuids into u128 needed for TigerBeetle IDs.
// TODO: see if there is a better way to do this.
func UuidToU128(value string) (*tb_types.Uint128, error) {
	src := strings.Replace(value, "-", "", -1)
	var ret tb_types.Uint128
	bytesWritten, err := hex.Decode(ret[:], []byte(src))
	if err != nil {
		return nil, err
	}
	if bytesWritten > 16 {
		return nil, errors.New("String could not be converted into uint128.")
	}

	return &ret, nil
}

// Helper function to extract the uuid we put into the u128.
func U128ToUuid(value tb_types.Uint128) string {
	if U128IsEmpty(value) {
		return ""
	}
	s := hex.EncodeToString(value[:])
	ret := s[:8] + "-" + s[8:12] + "-" + s[12:16] + "-" + s[16:20] + "-" + s[20:]

	return ret
}

// U128IsEmpty is a helper function that return true if the uint128 type is empty
func U128IsEmpty(val tb_types.Uint128) bool {
	for _, v := range val {
		if v != 0 {
			return false
		}
	}
	return true
}

// This is declaritive and will not fail if the account exists. It will fail if one exists with
// different fields.
func ConfigureAccounts(
	ctx context.Context,
	b Backends,
	args []pacioli.ConfigureAccountArgs,
) ([]pacioli.AccountResult, error) {

	// Insert into tigerroach as main source of truth
	res, err := tigerroach.ConfigureAccounts(ctx, b, args)
	if err != nil {
		// All err
		return nil, err
	}

	// Insert successfully created accounts into tigerbeetle as a best effort,.
	var toCreate []tb_types.Account
	for i, arg := range args {
		var errFound bool
		for _, resCode := range res {
			if resCode.Index == uint32(i) {
				// The  account failed to create in TigerRoach, don;t try to replicate it in Tigerbeetle
				errFound = true
				break
			}
		}
		if errFound {
			continue
		}

		tbAccID, err := UuidToU128(arg.ID)
		if err != nil {
			log.Warn("failed to sync accounts to tigerbeetle", zap.Error(err))
			continue
		}
		toCreate = append(toCreate, tb_types.Account{
			ID:     *tbAccID,
			Code:   arg.Code,
			Flags:  arg.Flags.ToUint16(),
			Ledger: arg.LedgerID,
		})
	}

	tbEventErrors, err := b.TigerBeetle().CreateAccounts(toCreate)
	// this error will be due to connection / io buffer issues
	if err != nil {
		log.Warn("failed to sync accounts to tigerbeetle", zap.Error(err))
	} else if len(tbEventErrors) > 0 {
		log.Warn("failed to sync accounts to tigerbeetle with error codes", zap.Any("error_codes", tbEventErrors))
	}

	return res, nil
}

func GetAccounts(
	ctx context.Context,
	b Backends,
	accountIDs []string,
) ([]pacioli.Account, error) {
	tbAccIDs := []tb_types.Uint128{}
	for _, id := range accountIDs {
		_, err := uuid.Parse(id)
		if err != nil {
			return nil, fmt.Errorf("Account ID must be a uuid. %w", pacioli.ErrInvalidArg)
		}
		accID, err := UuidToU128(id)
		if err != nil {
			return nil, err
		}

		tbAccIDs = append(tbAccIDs, *accID)
	}

	trAccs, err := tigerroach.ListAccounts(ctx, b, accountIDs)
	if err != nil {
		return nil, err
	}

	// Do sanity check to ensure all accounts have counterparts in tigerbeetle
	tbAccsRaw, err := b.TigerBeetle().LookupAccounts(tbAccIDs)
	if err != nil {
		log.Warn("failed to load accounts from tigerbeetle", zap.Error(err))
		return trAccs, nil
	}

	tbAccs := make([]pacioli.Account, len(tbAccsRaw))
	for i, tbAcc := range tbAccsRaw {
		tbAccs[i] = pacioli.Account{
			ID:             U128ToUuid(tbAcc.ID),
			LedgerID:       tbAcc.Ledger,
			Code:           tbAcc.Code,
			DebitsPending:  tbAcc.DebitsPending,
			DebitsPosted:   tbAcc.DebitsPosted,
			CreditsPending: tbAcc.CreditsPending,
			CreditsPosted:  tbAcc.CreditsPosted,
			Flags:          pacioli.ToAccountFlags(tbAcc.Flags),
		}
	}

	for _, trAcc := range trAccs {
		var found pacioli.Account
		for _, tbAcc := range tbAccs {
			if tbAcc.ID == trAcc.ID {
				found = tbAcc
				break
			}
		}

		if found.ID == "" {
			log.Warn("account exists in tigerroach but not in tigerbeetle", zap.String("account_id", trAcc.ID))
		} else if !reflect.DeepEqual(found, trAcc) {
			log.Warn("account mismatch between tigerroach and tigerbeetle ", zap.Any("tigerroach_acc", trAcc), zap.Any("tigerbeetle_acc", found))
		}
	}

	// TODO: ACL on accounts

	return trAccs, nil
}

// TODO: Assuming that IDs are uuids and are being generated by another service for now. Might be better to be
// unopinionated and accept []byte.
func CreateTransfers(ctx context.Context, b Backends, args []pacioli.CreateTransferArgs) ([]pacioli.TransferResult, error) {
	// TODO: collect ledgers and perform ACL. TigerBeetle will introduce the ledger field onto
	// a transfer.
	tbTransfers := make([]tb_types.Transfer, len(args))
	for i, transfer := range args {
		err := b.Validator().Struct(transfer)
		if err != nil {
			return nil, fmt.Errorf("%s %w", err.Error(), pacioli.ErrInvalidArg)
		}
		transferID, err := UuidToU128(transfer.ID)
		if err != nil {
			return nil, err
		}

		debitAccountID, err := UuidToU128(transfer.DebitAccountID)
		if err != nil {
			return nil, err
		}

		creditAccountID, err := UuidToU128(transfer.CreditAccountID)
		if err != nil {
			return nil, err
		}

		tbTransfers[i] = tb_types.Transfer{
			ID:              *transferID,
			DebitAccountID:  *debitAccountID,
			CreditAccountID: *creditAccountID,
			Amount:          transfer.Amount,
			Code:            transfer.Code,
			Flags:           transfer.Flags.ToUint16(),
			Timeout:         transfer.Timeout,
			Ledger:          transfer.Ledger,
		}
	}

	eventErrors, err := b.TigerBeetle().CreateTransfers(tbTransfers)
	if err != nil {
		return nil, err
	}

	return eventErrors, nil
}

func GetTransfers(ctx context.Context, b Backends, transferIDs []string) ([]pacioli.Transfer, error) {
	tbTransferIDs := make([]tb_types.Uint128, len(transferIDs))
	for i, id := range transferIDs {
		_, err := uuid.Parse(id)
		if err != nil {
			return nil, fmt.Errorf("Transfer ID must be a uuid. %w", pacioli.ErrInvalidArg)
		}
		transferID, err := UuidToU128(id)
		if err != nil {
			return nil, err
		}

		tbTransferIDs[i] = *transferID
	}

	results, err := b.TigerBeetle().LookupTransfers(tbTransferIDs)
	if err != nil {
		return nil, err
	}

	ret := make([]pacioli.Transfer, len(results))
	for i, transfer := range results {
		ret[i] = pacioli.Transfer{
			ID:              U128ToUuid(transfer.ID),
			PendingID:       U128ToUuid(transfer.PendingID),
			DebitAccountID:  U128ToUuid(transfer.DebitAccountID),
			CreditAccountID: U128ToUuid(transfer.CreditAccountID),
			Amount:          transfer.Amount,
			Code:            transfer.Code,

			Flags: pacioli.TransferFlags{
				Linked:              transfer.Flags&(1<<0) == 1,
				Pending:             transfer.Flags&(1<<1) == 2,
				PostPendingTransfer: transfer.Flags&(1<<2) == 4,
				VoidPendingTransfer: transfer.Flags&(1<<3) == 8,
			},
		}
	}

	// TODO: ACL on ledgers involved

	return ret, nil
}

// TODO: Rename to PostTransfers to conform with Tigerbeetle
func CommitTransfers(ctx context.Context, b Backends, transferIDs []string) ([]pacioli.TransferResult, error) {
	tbTransfers := make([]tb_types.Transfer, len(transferIDs))
	tbTransferIDs := make([]tb_types.Uint128, len(transferIDs))

	for i, id := range transferIDs {
		_, err := uuid.Parse(id)
		if err != nil {
			return nil, fmt.Errorf("Transfer ID must be a uuid. %w", pacioli.ErrInvalidArg)
		}
		transferID, err := UuidToU128(id)
		if err != nil {
			return nil, err
		}

		tbTransferIDs[i] = *transferID
	}

	for i, tid := range tbTransferIDs {

		newID, err := UuidToU128(uuid.NewString())
		if err != nil {
			return nil, err
		}

		tbTransfers[i] = tb_types.Transfer{
			ID:        *newID,
			PendingID: tid,
			Flags: pacioli.TransferFlags{
				PostPendingTransfer: true,
			}.ToUint16(),
		}
	}

	eventErrors, err := b.TigerBeetle().CreateTransfers(tbTransfers)
	if err != nil {
		return nil, err
	}

	return eventErrors, nil
}

func VoidTransfers(ctx context.Context, b Backends, transferIDs []string) ([]pacioli.TransferResult, error) {
	tbTransfers := make([]tb_types.Transfer, len(transferIDs))
	tbTransferIDs := make([]tb_types.Uint128, len(transferIDs))

	for i, id := range transferIDs {
		_, err := uuid.Parse(id)
		if err != nil {
			return nil, fmt.Errorf("Transfer ID must be a uuid. %w", pacioli.ErrInvalidArg)
		}
		transferID, err := UuidToU128(id)
		if err != nil {
			return nil, err
		}

		tbTransferIDs[i] = *transferID
	}

	for i, tid := range tbTransferIDs {

		newID, err := UuidToU128(uuid.NewString())
		if err != nil {
			return nil, err
		}

		tbTransfers[i] = tb_types.Transfer{
			ID:        *newID,
			PendingID: tid,
			Flags: pacioli.TransferFlags{
				VoidPendingTransfer: true,
			}.ToUint16(),
		}
	}

	eventErrors, err := b.TigerBeetle().CreateTransfers(tbTransfers)
	if err != nil {
		return nil, err
	}

	return eventErrors, nil
}
