apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: cockroachdb
          command:
            - "/bin/bash"
            - "-ecx"
            # The use of qualified `hostname -f` is crucial:
            # Other nodes aren't able to look up the unqualified hostname.
            - exec
              /cockroach/cockroach
              start-single-node
              --logtostderr
              --advertise-host $(hostname -f)
              --certs-dir /cockroach/cockroach-certs
              --http-addr 0.0.0.0
              --cache $(expr $MEMORY_LIMIT_MIB / 4)MiB
              --max-sql-memory $(expr $MEMORY_LIMIT_MIB / 4)MiB

