// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	analytics "gitlab.com/fynbos/backend/analytics"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// Identify mocks base method.
func (m *MockClient) Identify(args analytics.IdentifyArgs) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Identify", args)
}

// Identify indicates an expected call of Identify.
func (mr *MockClientMockRecorder) Identify(args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Identify", reflect.TypeOf((*MockClient)(nil).Identify), args)
}

// TrackUserLogin mocks base method.
func (m *MockClient) TrackUserLogin(userID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackUserLogin", userID)
}

// TrackUserLogin indicates an expected call of TrackUserLogin.
func (mr *MockClientMockRecorder) TrackUserLogin(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackUserLogin", reflect.TypeOf((*MockClient)(nil).TrackUserLogin), userID)
}

// TrackUserLogout mocks base method.
func (m *MockClient) TrackUserLogout(userID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackUserLogout", userID)
}

// TrackUserLogout indicates an expected call of TrackUserLogout.
func (mr *MockClientMockRecorder) TrackUserLogout(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackUserLogout", reflect.TypeOf((*MockClient)(nil).TrackUserLogout), userID)
}

// TrackUserSignup mocks base method.
func (m *MockClient) TrackUserSignup(userID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackUserSignup", userID)
}

// TrackUserSignup indicates an expected call of TrackUserSignup.
func (mr *MockClientMockRecorder) TrackUserSignup(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackUserSignup", reflect.TypeOf((*MockClient)(nil).TrackUserSignup), userID)
}
