# Used for deploy steps. Will assume the specified role and set the required AWS env variables.
# This will effectively override the role that the ec2 instance has been given.
.assume_role:
  before_script:
    - echo "===== assuming permissions => $AWS_DEPLOY_ROLE_ARN ====="
    - KST=(`aws sts assume-role --role-arn $AWS_DEPLOY_ROLE_ARN --role-session-name "ClusterDeploy" --query '[Credentials.AccessKeyId,Credentials.SecretAccessKey,Credentials.SessionToken]' --output text`)
    - unset AWS_SECURITY_TOKEN
    - export AWS_DEFAULT_REGION=$AWS_REGION
    - export AWS_ACCESS_KEY_ID=${KST[0]}
    - export AWS_SECRET_ACCESS_KEY=${KST[1]}
    - export AWS_SESSION_TOKEN=${KST[2]}
    - export AWS_SECURITY_TOKEN=${KST[2]}

# Some tests will use TestContainers which needs access to a docker daemon.
# This will start docker-in-docker to which TestContainers can connect.
.docker_services:
  services:
      - name: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/docker:19.03.12-dind
        alias: docker
  variables:
    # Instruct docker to use dind service
    DOCKER_HOST: "tcp://docker:2375"
    # Instruct Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
    # Improve performance with overlayfs.
    DOCKER_DRIVER: overlay2

.dev_environment:
  environment:
    name: Dev
    url: https://dev.fynbos.dev
