# this will switch between branch and merge request pipelines
# https://docs.gitlab.com/ee/ci/yaml/index.html#workflowrules-templates
include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - local: /.gitlab-refs.yaml
  - local: go/**/.gitlab-ci.yml
  - local: go/.gitlab-ci.yml
  - local: typescript/**/.gitlab-ci.yml

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never

trigger_deploy_dev_eu1:
  environment: !reference [ .dev_eu1_environment, environment ]
  needs:
    - build_backend
    - build_protea
    - build_pacioli
  when: manual
  variables:
    GIT_STRATEGY: none
  image: alpine:3.8
  before_script:
    - apk add --no-cache git
    - wget -qO- https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.5/kustomize_v4.5.5_linux_amd64.tar.gz | tar xvz -C /usr/local/bin/
    - mkdir rooibos
    - git clone --single-branch --branch main https://$CI_USERNAME:$CI_PUSH_TOKEN@gitlab.com/fynbos/rooibos.git rooibos
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
  script:
    - echo "Deploying $CI_ENVIRONMENT_NAME found at $CI_ENVIRONMENT_URL"
    - cd rooibos
    - (cd backend/envs/dev-eu1 && kustomize edit set image 823058932981.dkr.ecr.eu-west-1.amazonaws.com/backend=823058932981.dkr.ecr.eu-west-1.amazonaws.com/backend:$CI_COMMIT_SHORT_SHA)
    - (cd protea/envs/dev-eu1 && kustomize edit set image 823058932981.dkr.ecr.eu-west-1.amazonaws.com/protea=823058932981.dkr.ecr.eu-west-1.amazonaws.com/protea:$CI_COMMIT_SHORT_SHA)
    - (cd pacioli/envs/dev-eu1 && kustomize edit set image 823058932981.dkr.ecr.eu-west-1.amazonaws.com/pacioli=823058932981.dkr.ecr.eu-west-1.amazonaws.com/pacioli:$CI_COMMIT_SHORT_SHA)
    - git commit -am 'Dev EU image update for ${CI_COMMIT_SHORT_SHA}'
    - git push origin main