secretsprovider: awskms://c5f081da-bd15-43db-8dff-b75223e682fc?region=eu-west-1
encryptedkey: AQICAHiP/+JL0FlxeJkz1M6tyqKdL/1AmJF/S8OxlViPKyExpAFhsA181znO4JAeOLyL2Iv1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFwQrFx4a8MAQGJFfAgEQgDsBV+neIEQ2B3ODPlxawJ6b+mvwmapmID2chLIBC8voQSwEUM1qJHjNwsvajVeN5aL3qGNKnc20EYRAQg==
