// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AtlasSchemaHistory struct {
	ID        pgtype.UUID
	Hash      string
	CreatedAt pgtype.Timestamp
}

type PtiTransaction struct {
	ID                                    pgtype.UUID
	RequestID                             string
	UserID                                pgtype.UUID
	ClientID                              string
	Date                                  pgtype.Text
	Status                                pgtype.Text
	TransactionType                       pgtype.Text
	PaymentMethod                         pgtype.Text
	PaymentStatusProviderResponseCode     pgtype.Text
	PaymentStatusProviderResponseCategory pgtype.Text
	Amount                                pgtype.Int8
	Currency                              pgtype.Text
	TotalAmount                           pgtype.Int8
	TotalCurrency                         pgtype.Text
	FeeAmount                             pgtype.Int8
	FeeCurrency                           pgtype.Text
	SubtotalAmount                        pgtype.Int8
	SubtotalCurrency                      pgtype.Text
	CreatedAt                             pgtype.Timestamp
	UpdatedAt                             pgtype.Timestamp
}

type PtiUser struct {
	ID            pgtype.UUID
	Type          pgtype.Text
	DateOfBirth   pgtype.Text
	SourceOfFunds pgtype.Text
	FirstName     pgtype.Text
	MiddleName    pgtype.Text
	LastName      pgtype.Text
	State         pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type PtiUserAddress struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Street     pgtype.Text
	PostalCode pgtype.Text
	StateCode  pgtype.Text
	Country    pgtype.Text
	IsDefault  pgtype.Bool
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type PtiUserEmail struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Address   string
	IsDefault pgtype.Bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type PtiUserPhone struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Number    pgtype.Text
	IsDefault pgtype.Bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type PtiWallet struct {
	ID        string
	UserID    pgtype.UUID
	Balance   pgtype.Int8
	Currency  pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type XagoBeneficiary struct {
	ID                         pgtype.UUID
	Name                       pgtype.Text
	Scope                      pgtype.Text
	CurrencyCode               pgtype.Text
	AccountNumber              pgtype.Text
	BranchCode                 pgtype.Text
	BankName                   pgtype.Text
	BankCountry                pgtype.Text
	AccountName                pgtype.Text
	BankBeneficiaryType        pgtype.Text
	Reference                  pgtype.Text
	Iban                       pgtype.Text
	Bic                        pgtype.Text
	BeneficiaryPhysicalAddress pgtype.Text
	BeneficiaryDistrict        pgtype.Text
	BeneficiaryCity            pgtype.Text
	BeneficiaryCountry         pgtype.Text
	BeneficiaryPostalCode      pgtype.Text
	BeneficiaryAddress         pgtype.Text
	AccountType                pgtype.Text
	CreatedAt                  pgtype.Timestamp
	UpdatedAt                  pgtype.Timestamp
}

type XagoSubAccount struct {
	ID                         pgtype.UUID
	DepositAddress             string
	DepositTag                 string
	DepositReference           string
	FirstName                  string
	LastName                   string
	Email                      string
	MobileNumber               string
	Country                    string
	Nationality                string
	IdentificationDocumentType string
	IdentificationNumber       string
	Address                    string
	City                       string
	District                   string
	PostalCode                 string
	AddressDocumentType        string
	DateOfBirth                pgtype.Date
	CreatedAt                  pgtype.Timestamp
	UpdatedAt                  pgtype.Timestamp
}

type XagoTransaction struct {
	ID             pgtype.UUID
	CurrencyCode   string
	Amount         float64
	OriginAmount   float64
	Status         string
	BeneficiaryID  string
	IdempotencyKey string
	Type           string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
