// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AtlasSchemaHistory struct {
	ID        pgtype.UUID
	Hash      string
	CreatedAt pgtype.Timestamp
}

type XagoBeneficiary struct {
	ID                         pgtype.UUID
	Name                       pgtype.Text
	Scope                      pgtype.Text
	CurrencyCode               pgtype.Text
	AccountNumber              pgtype.Text
	BranchCode                 pgtype.Text
	BankName                   pgtype.Text
	BankCountry                pgtype.Text
	AccountName                pgtype.Text
	BankBeneficiaryType        pgtype.Text
	Reference                  pgtype.Text
	Iban                       pgtype.Text
	Bic                        pgtype.Text
	BeneficiaryPhysicalAddress pgtype.Text
	BeneficiaryDistrict        pgtype.Text
	BeneficiaryCity            pgtype.Text
	BeneficiaryCountry         pgtype.Text
	BeneficiaryPostalCode      pgtype.Text
	BeneficiaryAddress         pgtype.Text
	AccountType                pgtype.Text
	CreatedAt                  pgtype.Timestamp
	UpdatedAt                  pgtype.Timestamp
}

type XagoSubAccount struct {
	ID                         pgtype.UUID
	DepositAddress             string
	DepositTag                 string
	FirstName                  string
	LastName                   string
	Email                      string
	MobileNumber               string
	Country                    string
	Nationality                string
	IdentificationDocumentType string
	IdentificationNumber       string
	Address                    string
	City                       string
	District                   string
	PostalCode                 string
	AddressDocumentType        string
	DateOfBirth                pgtype.Date
	CreatedAt                  pgtype.Timestamp
	UpdatedAt                  pgtype.Timestamp
}

type XagoTransaction struct {
	ID             pgtype.UUID
	CurrencyCode   string
	Amount         float64
	OriginAmount   float64
	Status         string
	BeneficiaryID  string
	IdempotencyKey string
	Type           string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
