// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustPTIWalletBalance = `-- name: AdjustPTIWalletBalance :exec
UPDATE pti_wallets SET balance=balance+$1 WHERE id=$2
`

type AdjustPTIWalletBalanceParams struct {
	Balance pgtype.Int8
	ID      string
}

func (q *Queries) AdjustPTIWalletBalance(ctx context.Context, arg AdjustPTIWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, adjustPTIWalletBalance, arg.Balance, arg.ID)
	return err
}

const createAstraAccessToken = `-- name: CreateAstraAccessToken :one
INSERT INTO astra_access_tokens (user_id, expires_in, token_type) VALUES ($1, $2, $3) RETURNING id, user_id, expires_in, token_type, refresh_token, created_at, updated_at
`

type CreateAstraAccessTokenParams struct {
	UserID    pgtype.UUID
	ExpiresIn pgtype.Int4
	TokenType pgtype.Text
}

func (q *Queries) CreateAstraAccessToken(ctx context.Context, arg CreateAstraAccessTokenParams) (AstraAccessToken, error) {
	row := q.db.QueryRow(ctx, createAstraAccessToken, arg.UserID, arg.ExpiresIn, arg.TokenType)
	var i AstraAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresIn,
		&i.TokenType,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAstraIntent = `-- name: CreateAstraIntent :one
INSERT INTO astra_user_intents (
    email,
    phone,
    first_name,
    last_name,
    address1,
    address2,
    city,
    state,
    postal_code,
    date_of_birth,
    ssn,
    ip_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, user_id, email, phone, first_name, last_name, address1, address2, city, state, postal_code, date_of_birth, ssn, ip_address, created_at, updated_at
`

type CreateAstraIntentParams struct {
	Email       string
	Phone       string
	FirstName   string
	LastName    string
	Address1    pgtype.Text
	Address2    pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	PostalCode  pgtype.Text
	DateOfBirth pgtype.Text
	Ssn         pgtype.Text
	IpAddress   pgtype.Text
}

func (q *Queries) CreateAstraIntent(ctx context.Context, arg CreateAstraIntentParams) (AstraUserIntent, error) {
	row := q.db.QueryRow(ctx, createAstraIntent,
		arg.Email,
		arg.Phone,
		arg.FirstName,
		arg.LastName,
		arg.Address1,
		arg.Address2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.DateOfBirth,
		arg.Ssn,
		arg.IpAddress,
	)
	var i AstraUserIntent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.Address1,
		&i.Address2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.DateOfBirth,
		&i.Ssn,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAstraTransaction = `-- name: CreateAstraTransaction :one
INSERT INTO astra_transactions (
    id,
    routine_type,
    routine_name,
    routine_id,
    client_correlation_id,
    source_id,
    destination_id,
    destination_user_id,
    amount,
    payment_type,
    initiated,
    updated,
    estimated_clearing_date,
    astra_settlement_reason,
    failure_reason,
    chargeback_action_status,
    chargeback_cb_id,
    chargeback_created,
    chargeback_exception_code,
    chargeback_exception_date,
    chargeback_exception_description,
    chargeback_exception_id,
    chargeback_exception_settled_amount,
    chargeback_exception_type,
    chargeback_merchant_reference_id,
    chargeback_network_id,
    chargeback_original_creation_date,
    chargeback_original_processed_date,
    chargeback_original_settled_amount,
    chargeback_status_date,
    chargeback_updated,
    chargeback_user_id,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
    $31, $32, $33
) RETURNING id, routine_type, routine_name, routine_id, client_correlation_id, source_id, destination_id, destination_user_id, amount, payment_type, initiated, updated, estimated_clearing_date, astra_settlement_reason, failure_reason, chargeback_action_status, chargeback_cb_id, chargeback_created, chargeback_exception_code, chargeback_exception_date, chargeback_exception_description, chargeback_exception_id, chargeback_exception_settled_amount, chargeback_exception_type, chargeback_merchant_reference_id, chargeback_network_id, chargeback_original_creation_date, chargeback_original_processed_date, chargeback_original_settled_amount, chargeback_status_date, chargeback_updated, chargeback_user_id, status, created_at, updated_at
`

type CreateAstraTransactionParams struct {
	ID                               pgtype.UUID
	RoutineType                      pgtype.Text
	RoutineName                      pgtype.Text
	RoutineID                        pgtype.Text
	ClientCorrelationID              pgtype.Text
	SourceID                         pgtype.UUID
	DestinationID                    pgtype.UUID
	DestinationUserID                pgtype.UUID
	Amount                           pgtype.Float8
	PaymentType                      pgtype.Text
	Initiated                        pgtype.Text
	Updated                          pgtype.Text
	EstimatedClearingDate            pgtype.Text
	AstraSettlementReason            pgtype.Text
	FailureReason                    pgtype.Text
	ChargebackActionStatus           pgtype.Text
	ChargebackCbID                   pgtype.Text
	ChargebackCreated                pgtype.Text
	ChargebackExceptionCode          pgtype.Text
	ChargebackExceptionDate          pgtype.Text
	ChargebackExceptionDescription   pgtype.Text
	ChargebackExceptionID            pgtype.Text
	ChargebackExceptionSettledAmount pgtype.Float8
	ChargebackExceptionType          pgtype.Text
	ChargebackMerchantReferenceID    pgtype.Text
	ChargebackNetworkID              pgtype.Text
	ChargebackOriginalCreationDate   pgtype.Text
	ChargebackOriginalProcessedDate  pgtype.Text
	ChargebackOriginalSettledAmount  pgtype.Float8
	ChargebackStatusDate             pgtype.Text
	ChargebackUpdated                pgtype.Text
	ChargebackUserID                 pgtype.Text
	Status                           pgtype.Text
}

func (q *Queries) CreateAstraTransaction(ctx context.Context, arg CreateAstraTransactionParams) (AstraTransaction, error) {
	row := q.db.QueryRow(ctx, createAstraTransaction,
		arg.ID,
		arg.RoutineType,
		arg.RoutineName,
		arg.RoutineID,
		arg.ClientCorrelationID,
		arg.SourceID,
		arg.DestinationID,
		arg.DestinationUserID,
		arg.Amount,
		arg.PaymentType,
		arg.Initiated,
		arg.Updated,
		arg.EstimatedClearingDate,
		arg.AstraSettlementReason,
		arg.FailureReason,
		arg.ChargebackActionStatus,
		arg.ChargebackCbID,
		arg.ChargebackCreated,
		arg.ChargebackExceptionCode,
		arg.ChargebackExceptionDate,
		arg.ChargebackExceptionDescription,
		arg.ChargebackExceptionID,
		arg.ChargebackExceptionSettledAmount,
		arg.ChargebackExceptionType,
		arg.ChargebackMerchantReferenceID,
		arg.ChargebackNetworkID,
		arg.ChargebackOriginalCreationDate,
		arg.ChargebackOriginalProcessedDate,
		arg.ChargebackOriginalSettledAmount,
		arg.ChargebackStatusDate,
		arg.ChargebackUpdated,
		arg.ChargebackUserID,
		arg.Status,
	)
	var i AstraTransaction
	err := row.Scan(
		&i.ID,
		&i.RoutineType,
		&i.RoutineName,
		&i.RoutineID,
		&i.ClientCorrelationID,
		&i.SourceID,
		&i.DestinationID,
		&i.DestinationUserID,
		&i.Amount,
		&i.PaymentType,
		&i.Initiated,
		&i.Updated,
		&i.EstimatedClearingDate,
		&i.AstraSettlementReason,
		&i.FailureReason,
		&i.ChargebackActionStatus,
		&i.ChargebackCbID,
		&i.ChargebackCreated,
		&i.ChargebackExceptionCode,
		&i.ChargebackExceptionDate,
		&i.ChargebackExceptionDescription,
		&i.ChargebackExceptionID,
		&i.ChargebackExceptionSettledAmount,
		&i.ChargebackExceptionType,
		&i.ChargebackMerchantReferenceID,
		&i.ChargebackNetworkID,
		&i.ChargebackOriginalCreationDate,
		&i.ChargebackOriginalProcessedDate,
		&i.ChargebackOriginalSettledAmount,
		&i.ChargebackStatusDate,
		&i.ChargebackUpdated,
		&i.ChargebackUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAstraUser = `-- name: CreateAstraUser :one
INSERT INTO astra_users (
    email,
    phone,
    first_name,
    last_name,
    address1,
    address2,
    city,
    state,
    postal_code,
    date_of_birth,
    ssn,
    ip_address,
    status,
    kyc_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, email, phone, first_name, last_name, address1, address2, city, state, postal_code, date_of_birth, ssn, ip_address, status, kyc_type, created_at, updated_at
`

type CreateAstraUserParams struct {
	Email       string
	Phone       string
	FirstName   string
	LastName    string
	Address1    pgtype.Text
	Address2    pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	PostalCode  pgtype.Text
	DateOfBirth pgtype.Text
	Ssn         pgtype.Text
	IpAddress   pgtype.Text
	Status      pgtype.Text
	KycType     pgtype.Text
}

func (q *Queries) CreateAstraUser(ctx context.Context, arg CreateAstraUserParams) (AstraUser, error) {
	row := q.db.QueryRow(ctx, createAstraUser,
		arg.Email,
		arg.Phone,
		arg.FirstName,
		arg.LastName,
		arg.Address1,
		arg.Address2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.DateOfBirth,
		arg.Ssn,
		arg.IpAddress,
		arg.Status,
		arg.KycType,
	)
	var i AstraUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.Address1,
		&i.Address2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.DateOfBirth,
		&i.Ssn,
		&i.IpAddress,
		&i.Status,
		&i.KycType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAstraUserAccount = `-- name: CreateAstraUserAccount :one
INSERT INTO astra_user_accounts (
    user_id,
    official_name,
    name,
    mask,
    institution_name,
    institution_logo,
    type,
    subtype,
    connection_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, official_name, name, mask, institution_name, institution_logo, type, subtype, connection_status, created_at, updated_at
`

type CreateAstraUserAccountParams struct {
	UserID           pgtype.UUID
	OfficialName     pgtype.Text
	Name             pgtype.Text
	Mask             pgtype.Text
	InstitutionName  pgtype.Text
	InstitutionLogo  pgtype.Text
	Type             pgtype.Text
	Subtype          pgtype.Text
	ConnectionStatus pgtype.Text
}

func (q *Queries) CreateAstraUserAccount(ctx context.Context, arg CreateAstraUserAccountParams) (AstraUserAccount, error) {
	row := q.db.QueryRow(ctx, createAstraUserAccount,
		arg.UserID,
		arg.OfficialName,
		arg.Name,
		arg.Mask,
		arg.InstitutionName,
		arg.InstitutionLogo,
		arg.Type,
		arg.Subtype,
		arg.ConnectionStatus,
	)
	var i AstraUserAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OfficialName,
		&i.Name,
		&i.Mask,
		&i.InstitutionName,
		&i.InstitutionLogo,
		&i.Type,
		&i.Subtype,
		&i.ConnectionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAstraUserCard = `-- name: CreateAstraUserCard :one
INSERT INTO astra_user_cards (
        user_id,
        address_verified,
        card_company,
        city,
        expiration_date,
        first_name,
        first_six_digits,
        last_four_digits,
        last_name,
        card_type,
        pull_enabled,
        push_enabled,
        removed,
        review_status,
        state,
        status,
        street_line_1,
        street_line_2,
        zip_code
    ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
    ) RETURNING id, user_id, address_verified, card_company, city, expiration_date, first_name, first_six_digits, last_four_digits, last_name, card_type, pull_enabled, push_enabled, removed, review_status, state, status, street_line_1, street_line_2, zip_code, created_at, updated_at
`

type CreateAstraUserCardParams struct {
	UserID          pgtype.UUID
	AddressVerified pgtype.Bool
	CardCompany     pgtype.Text
	City            pgtype.Text
	ExpirationDate  pgtype.Text
	FirstName       pgtype.Text
	FirstSixDigits  pgtype.Text
	LastFourDigits  pgtype.Text
	LastName        pgtype.Text
	CardType        pgtype.Text
	PullEnabled     pgtype.Bool
	PushEnabled     pgtype.Bool
	Removed         pgtype.Bool
	ReviewStatus    pgtype.Text
	State           pgtype.Text
	Status          pgtype.Text
	StreetLine1     pgtype.Text
	StreetLine2     pgtype.Text
	ZipCode         pgtype.Text
}

func (q *Queries) CreateAstraUserCard(ctx context.Context, arg CreateAstraUserCardParams) (AstraUserCard, error) {
	row := q.db.QueryRow(ctx, createAstraUserCard,
		arg.UserID,
		arg.AddressVerified,
		arg.CardCompany,
		arg.City,
		arg.ExpirationDate,
		arg.FirstName,
		arg.FirstSixDigits,
		arg.LastFourDigits,
		arg.LastName,
		arg.CardType,
		arg.PullEnabled,
		arg.PushEnabled,
		arg.Removed,
		arg.ReviewStatus,
		arg.State,
		arg.Status,
		arg.StreetLine1,
		arg.StreetLine2,
		arg.ZipCode,
	)
	var i AstraUserCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AddressVerified,
		&i.CardCompany,
		&i.City,
		&i.ExpirationDate,
		&i.FirstName,
		&i.FirstSixDigits,
		&i.LastFourDigits,
		&i.LastName,
		&i.CardType,
		&i.PullEnabled,
		&i.PushEnabled,
		&i.Removed,
		&i.ReviewStatus,
		&i.State,
		&i.Status,
		&i.StreetLine1,
		&i.StreetLine2,
		&i.ZipCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPTITransaction = `-- name: CreatePTITransaction :one
INSERT INTO pti_transactions (request_id, user_id, client_id, date, status, transaction_type, payment_method, payment_status_provider_response_code, payment_status_provider_response_category, amount, currency, total_amount, total_currency, fee_amount, fee_currency, subtotal_amount, subtotal_currency) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17) RETURNING id, request_id, user_id, client_id, date, status, transaction_type, payment_method, payment_status_provider_response_code, payment_status_provider_response_category, amount, currency, total_amount, total_currency, fee_amount, fee_currency, subtotal_amount, subtotal_currency, created_at, updated_at
`

type CreatePTITransactionParams struct {
	RequestID                             string
	UserID                                pgtype.UUID
	ClientID                              string
	Date                                  pgtype.Text
	Status                                pgtype.Text
	TransactionType                       pgtype.Text
	PaymentMethod                         pgtype.Text
	PaymentStatusProviderResponseCode     pgtype.Text
	PaymentStatusProviderResponseCategory pgtype.Text
	Amount                                pgtype.Int8
	Currency                              pgtype.Text
	TotalAmount                           pgtype.Int8
	TotalCurrency                         pgtype.Text
	FeeAmount                             pgtype.Int8
	FeeCurrency                           pgtype.Text
	SubtotalAmount                        pgtype.Int8
	SubtotalCurrency                      pgtype.Text
}

func (q *Queries) CreatePTITransaction(ctx context.Context, arg CreatePTITransactionParams) (PtiTransaction, error) {
	row := q.db.QueryRow(ctx, createPTITransaction,
		arg.RequestID,
		arg.UserID,
		arg.ClientID,
		arg.Date,
		arg.Status,
		arg.TransactionType,
		arg.PaymentMethod,
		arg.PaymentStatusProviderResponseCode,
		arg.PaymentStatusProviderResponseCategory,
		arg.Amount,
		arg.Currency,
		arg.TotalAmount,
		arg.TotalCurrency,
		arg.FeeAmount,
		arg.FeeCurrency,
		arg.SubtotalAmount,
		arg.SubtotalCurrency,
	)
	var i PtiTransaction
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ClientID,
		&i.Date,
		&i.Status,
		&i.TransactionType,
		&i.PaymentMethod,
		&i.PaymentStatusProviderResponseCode,
		&i.PaymentStatusProviderResponseCategory,
		&i.Amount,
		&i.Currency,
		&i.TotalAmount,
		&i.TotalCurrency,
		&i.FeeAmount,
		&i.FeeCurrency,
		&i.SubtotalAmount,
		&i.SubtotalCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPTIUser = `-- name: CreatePTIUser :one
INSERT INTO pti_users
(id, type, first_name, middle_name, last_name, date_of_birth, source_of_funds, state) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, type, date_of_birth, source_of_funds, first_name, middle_name, last_name, state, created_at, updated_at
`

type CreatePTIUserParams struct {
	ID            pgtype.UUID
	Type          pgtype.Text
	FirstName     pgtype.Text
	MiddleName    pgtype.Text
	LastName      pgtype.Text
	DateOfBirth   pgtype.Text
	SourceOfFunds pgtype.Text
	State         pgtype.Text
}

func (q *Queries) CreatePTIUser(ctx context.Context, arg CreatePTIUserParams) (PtiUser, error) {
	row := q.db.QueryRow(ctx, createPTIUser,
		arg.ID,
		arg.Type,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.DateOfBirth,
		arg.SourceOfFunds,
		arg.State,
	)
	var i PtiUser
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.DateOfBirth,
		&i.SourceOfFunds,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreatePTIUserAddressParams struct {
	UserID     pgtype.UUID
	Street     pgtype.Text
	PostalCode pgtype.Text
	StateCode  pgtype.Text
	Country    pgtype.Text
	IsDefault  pgtype.Bool
}

type CreatePTIUserEmailParams struct {
	UserID    pgtype.UUID
	Address   string
	IsDefault pgtype.Bool
}

type CreatePTIUserPhoneParams struct {
	UserID    pgtype.UUID
	Number    pgtype.Text
	IsDefault pgtype.Bool
}

const createPTIWallet = `-- name: CreatePTIWallet :one
INSERT INTO pti_wallets (id, user_id, currency) VALUES ($1, $2, $3) RETURNING id, user_id, balance, currency, created_at, updated_at
`

type CreatePTIWalletParams struct {
	ID       string
	UserID   pgtype.UUID
	Currency pgtype.Text
}

func (q *Queries) CreatePTIWallet(ctx context.Context, arg CreatePTIWalletParams) (PtiWallet, error) {
	row := q.db.QueryRow(ctx, createPTIWallet, arg.ID, arg.UserID, arg.Currency)
	var i PtiWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createXagoBeneficiary = `-- name: CreateXagoBeneficiary :one
INSERT INTO xago_beneficiaries
(id, name, scope, currency_code, account_number, branch_code,
 bank_name, bank_country, account_name, bank_beneficiary_type,
 reference, iban, bic, beneficiary_physical_address,
 beneficiary_district, beneficiary_city, beneficiary_country, beneficiary_postal_code,
 beneficiary_address, account_type)
VALUES (gen_random_uuid(),
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
returning id
`

type CreateXagoBeneficiaryParams struct {
	Name                       pgtype.Text
	Scope                      pgtype.Text
	CurrencyCode               pgtype.Text
	AccountNumber              pgtype.Text
	BranchCode                 pgtype.Text
	BankName                   pgtype.Text
	BankCountry                pgtype.Text
	AccountName                pgtype.Text
	BankBeneficiaryType        pgtype.Text
	Reference                  pgtype.Text
	Iban                       pgtype.Text
	Bic                        pgtype.Text
	BeneficiaryPhysicalAddress pgtype.Text
	BeneficiaryDistrict        pgtype.Text
	BeneficiaryCity            pgtype.Text
	BeneficiaryCountry         pgtype.Text
	BeneficiaryPostalCode      pgtype.Text
	BeneficiaryAddress         pgtype.Text
	AccountType                pgtype.Text
}

func (q *Queries) CreateXagoBeneficiary(ctx context.Context, arg CreateXagoBeneficiaryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createXagoBeneficiary,
		arg.Name,
		arg.Scope,
		arg.CurrencyCode,
		arg.AccountNumber,
		arg.BranchCode,
		arg.BankName,
		arg.BankCountry,
		arg.AccountName,
		arg.BankBeneficiaryType,
		arg.Reference,
		arg.Iban,
		arg.Bic,
		arg.BeneficiaryPhysicalAddress,
		arg.BeneficiaryDistrict,
		arg.BeneficiaryCity,
		arg.BeneficiaryCountry,
		arg.BeneficiaryPostalCode,
		arg.BeneficiaryAddress,
		arg.AccountType,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createXagoSubAccount = `-- name: CreateXagoSubAccount :one
INSERT INTO xago_sub_accounts
(id, deposit_tag, first_name, last_name, email, mobile_number,
 country, nationality, identification_document_type, identification_number,
 address, city, district, postal_code, address_document_type, date_of_birth)
VALUES (gen_random_uuid(), $1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $14, $15)
returning id
`

type CreateXagoSubAccountParams struct {
	DepositTag                 string
	FirstName                  string
	LastName                   string
	Email                      string
	MobileNumber               string
	Country                    string
	Nationality                string
	IdentificationDocumentType string
	IdentificationNumber       string
	Address                    string
	City                       string
	District                   string
	PostalCode                 string
	AddressDocumentType        string
	DateOfBirth                pgtype.Date
}

func (q *Queries) CreateXagoSubAccount(ctx context.Context, arg CreateXagoSubAccountParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createXagoSubAccount,
		arg.DepositTag,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MobileNumber,
		arg.Country,
		arg.Nationality,
		arg.IdentificationDocumentType,
		arg.IdentificationNumber,
		arg.Address,
		arg.City,
		arg.District,
		arg.PostalCode,
		arg.AddressDocumentType,
		arg.DateOfBirth,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createXagoTransaction = `-- name: CreateXagoTransaction :one
insert into xago_transactions
(id, currency_code, amount, origin_amount, status, beneficiary_id, idempotency_key, type)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, currency_code, amount, origin_amount, status, beneficiary_id, idempotency_key, type, created_at, updated_at
`

type CreateXagoTransactionParams struct {
	ID             pgtype.UUID
	CurrencyCode   string
	Amount         float64
	OriginAmount   float64
	Status         string
	BeneficiaryID  string
	IdempotencyKey string
	Type           string
}

func (q *Queries) CreateXagoTransaction(ctx context.Context, arg CreateXagoTransactionParams) (XagoTransaction, error) {
	row := q.db.QueryRow(ctx, createXagoTransaction,
		arg.ID,
		arg.CurrencyCode,
		arg.Amount,
		arg.OriginAmount,
		arg.Status,
		arg.BeneficiaryID,
		arg.IdempotencyKey,
		arg.Type,
	)
	var i XagoTransaction
	err := row.Scan(
		&i.ID,
		&i.CurrencyCode,
		&i.Amount,
		&i.OriginAmount,
		&i.Status,
		&i.BeneficiaryID,
		&i.IdempotencyKey,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAstraAccessToken = `-- name: GetAstraAccessToken :one
SELECT id, user_id, expires_in, token_type, refresh_token, created_at, updated_at FROM astra_access_tokens WHERE id=$1
`

func (q *Queries) GetAstraAccessToken(ctx context.Context, id pgtype.UUID) (AstraAccessToken, error) {
	row := q.db.QueryRow(ctx, getAstraAccessToken, id)
	var i AstraAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresIn,
		&i.TokenType,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAstraAccessTokenByRefreshToken = `-- name: GetAstraAccessTokenByRefreshToken :one
SELECT id, user_id, expires_in, token_type, refresh_token, created_at, updated_at FROM astra_access_tokens WHERE refresh_token=$1
`

func (q *Queries) GetAstraAccessTokenByRefreshToken(ctx context.Context, refreshToken pgtype.UUID) (AstraAccessToken, error) {
	row := q.db.QueryRow(ctx, getAstraAccessTokenByRefreshToken, refreshToken)
	var i AstraAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresIn,
		&i.TokenType,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAstraAccount = `-- name: GetAstraAccount :one
SELECT id, user_id, official_name, name, mask, institution_name, institution_logo, type, subtype, connection_status, created_at, updated_at FROM astra_user_accounts WHERE id=$1
`

func (q *Queries) GetAstraAccount(ctx context.Context, id pgtype.UUID) (AstraUserAccount, error) {
	row := q.db.QueryRow(ctx, getAstraAccount, id)
	var i AstraUserAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OfficialName,
		&i.Name,
		&i.Mask,
		&i.InstitutionName,
		&i.InstitutionLogo,
		&i.Type,
		&i.Subtype,
		&i.ConnectionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAstraCard = `-- name: GetAstraCard :one
SELECT id, user_id, address_verified, card_company, city, expiration_date, first_name, first_six_digits, last_four_digits, last_name, card_type, pull_enabled, push_enabled, removed, review_status, state, status, street_line_1, street_line_2, zip_code, created_at, updated_at FROM astra_user_cards WHERE id=$1
`

func (q *Queries) GetAstraCard(ctx context.Context, id pgtype.UUID) (AstraUserCard, error) {
	row := q.db.QueryRow(ctx, getAstraCard, id)
	var i AstraUserCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AddressVerified,
		&i.CardCompany,
		&i.City,
		&i.ExpirationDate,
		&i.FirstName,
		&i.FirstSixDigits,
		&i.LastFourDigits,
		&i.LastName,
		&i.CardType,
		&i.PullEnabled,
		&i.PushEnabled,
		&i.Removed,
		&i.ReviewStatus,
		&i.State,
		&i.Status,
		&i.StreetLine1,
		&i.StreetLine2,
		&i.ZipCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAstraIntent = `-- name: GetAstraIntent :one
SELECT id, user_id, email, phone, first_name, last_name, address1, address2, city, state, postal_code, date_of_birth, ssn, ip_address, created_at, updated_at FROM astra_user_intents WHERE id=$1
`

func (q *Queries) GetAstraIntent(ctx context.Context, id pgtype.UUID) (AstraUserIntent, error) {
	row := q.db.QueryRow(ctx, getAstraIntent, id)
	var i AstraUserIntent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.Address1,
		&i.Address2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.DateOfBirth,
		&i.Ssn,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAstraTransaction = `-- name: GetAstraTransaction :one
SELECT id, routine_type, routine_name, routine_id, client_correlation_id, source_id, destination_id, destination_user_id, amount, payment_type, initiated, updated, estimated_clearing_date, astra_settlement_reason, failure_reason, chargeback_action_status, chargeback_cb_id, chargeback_created, chargeback_exception_code, chargeback_exception_date, chargeback_exception_description, chargeback_exception_id, chargeback_exception_settled_amount, chargeback_exception_type, chargeback_merchant_reference_id, chargeback_network_id, chargeback_original_creation_date, chargeback_original_processed_date, chargeback_original_settled_amount, chargeback_status_date, chargeback_updated, chargeback_user_id, status, created_at, updated_at FROM astra_transactions WHERE id=$1
`

func (q *Queries) GetAstraTransaction(ctx context.Context, id pgtype.UUID) (AstraTransaction, error) {
	row := q.db.QueryRow(ctx, getAstraTransaction, id)
	var i AstraTransaction
	err := row.Scan(
		&i.ID,
		&i.RoutineType,
		&i.RoutineName,
		&i.RoutineID,
		&i.ClientCorrelationID,
		&i.SourceID,
		&i.DestinationID,
		&i.DestinationUserID,
		&i.Amount,
		&i.PaymentType,
		&i.Initiated,
		&i.Updated,
		&i.EstimatedClearingDate,
		&i.AstraSettlementReason,
		&i.FailureReason,
		&i.ChargebackActionStatus,
		&i.ChargebackCbID,
		&i.ChargebackCreated,
		&i.ChargebackExceptionCode,
		&i.ChargebackExceptionDate,
		&i.ChargebackExceptionDescription,
		&i.ChargebackExceptionID,
		&i.ChargebackExceptionSettledAmount,
		&i.ChargebackExceptionType,
		&i.ChargebackMerchantReferenceID,
		&i.ChargebackNetworkID,
		&i.ChargebackOriginalCreationDate,
		&i.ChargebackOriginalProcessedDate,
		&i.ChargebackOriginalSettledAmount,
		&i.ChargebackStatusDate,
		&i.ChargebackUpdated,
		&i.ChargebackUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAstraUser = `-- name: GetAstraUser :one
SELECT id, email, phone, first_name, last_name, address1, address2, city, state, postal_code, date_of_birth, ssn, ip_address, status, kyc_type, created_at, updated_at FROM astra_users WHERE id=$1
`

func (q *Queries) GetAstraUser(ctx context.Context, id pgtype.UUID) (AstraUser, error) {
	row := q.db.QueryRow(ctx, getAstraUser, id)
	var i AstraUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.Address1,
		&i.Address2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.DateOfBirth,
		&i.Ssn,
		&i.IpAddress,
		&i.Status,
		&i.KycType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAstraUserAccount = `-- name: GetAstraUserAccount :one
SELECT id, user_id, official_name, name, mask, institution_name, institution_logo, type, subtype, connection_status, created_at, updated_at FROM astra_user_accounts WHERE id=$1 AND user_id=$2
`

type GetAstraUserAccountParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetAstraUserAccount(ctx context.Context, arg GetAstraUserAccountParams) (AstraUserAccount, error) {
	row := q.db.QueryRow(ctx, getAstraUserAccount, arg.ID, arg.UserID)
	var i AstraUserAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OfficialName,
		&i.Name,
		&i.Mask,
		&i.InstitutionName,
		&i.InstitutionLogo,
		&i.Type,
		&i.Subtype,
		&i.ConnectionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAstraUserCard = `-- name: GetAstraUserCard :one
SELECT id, user_id, address_verified, card_company, city, expiration_date, first_name, first_six_digits, last_four_digits, last_name, card_type, pull_enabled, push_enabled, removed, review_status, state, status, street_line_1, street_line_2, zip_code, created_at, updated_at FROM astra_user_cards WHERE id=$1 AND user_id=$2
`

type GetAstraUserCardParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetAstraUserCard(ctx context.Context, arg GetAstraUserCardParams) (AstraUserCard, error) {
	row := q.db.QueryRow(ctx, getAstraUserCard, arg.ID, arg.UserID)
	var i AstraUserCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AddressVerified,
		&i.CardCompany,
		&i.City,
		&i.ExpirationDate,
		&i.FirstName,
		&i.FirstSixDigits,
		&i.LastFourDigits,
		&i.LastName,
		&i.CardType,
		&i.PullEnabled,
		&i.PushEnabled,
		&i.Removed,
		&i.ReviewStatus,
		&i.State,
		&i.Status,
		&i.StreetLine1,
		&i.StreetLine2,
		&i.ZipCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPTITransactionByRequestID = `-- name: GetPTITransactionByRequestID :one
SELECT id, request_id, user_id, client_id, date, status, transaction_type, payment_method, payment_status_provider_response_code, payment_status_provider_response_category, amount, currency, total_amount, total_currency, fee_amount, fee_currency, subtotal_amount, subtotal_currency, created_at, updated_at FROM pti_transactions WHERE request_id=$1
`

func (q *Queries) GetPTITransactionByRequestID(ctx context.Context, requestID string) (PtiTransaction, error) {
	row := q.db.QueryRow(ctx, getPTITransactionByRequestID, requestID)
	var i PtiTransaction
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.ClientID,
		&i.Date,
		&i.Status,
		&i.TransactionType,
		&i.PaymentMethod,
		&i.PaymentStatusProviderResponseCode,
		&i.PaymentStatusProviderResponseCategory,
		&i.Amount,
		&i.Currency,
		&i.TotalAmount,
		&i.TotalCurrency,
		&i.FeeAmount,
		&i.FeeCurrency,
		&i.SubtotalAmount,
		&i.SubtotalCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPTIUser = `-- name: GetPTIUser :one
SELECT id, type, date_of_birth, source_of_funds, first_name, middle_name, last_name, state, created_at, updated_at FROM pti_users WHERE id=$1
`

func (q *Queries) GetPTIUser(ctx context.Context, id pgtype.UUID) (PtiUser, error) {
	row := q.db.QueryRow(ctx, getPTIUser, id)
	var i PtiUser
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.DateOfBirth,
		&i.SourceOfFunds,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPTIUserAddresses = `-- name: GetPTIUserAddresses :many
SELECT id, user_id, street, postal_code, state_code, country, is_default, created_at, updated_at FROM pti_user_addresses WHERE user_id=$1
`

func (q *Queries) GetPTIUserAddresses(ctx context.Context, userID pgtype.UUID) ([]PtiUserAddress, error) {
	rows, err := q.db.Query(ctx, getPTIUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PtiUserAddress
	for rows.Next() {
		var i PtiUserAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Street,
			&i.PostalCode,
			&i.StateCode,
			&i.Country,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPTIUserEmails = `-- name: GetPTIUserEmails :many
SELECT id, user_id, address, is_default, created_at, updated_at FROM pti_user_emails WHERE user_id=$1
`

func (q *Queries) GetPTIUserEmails(ctx context.Context, userID pgtype.UUID) ([]PtiUserEmail, error) {
	rows, err := q.db.Query(ctx, getPTIUserEmails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PtiUserEmail
	for rows.Next() {
		var i PtiUserEmail
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPTIUserPhones = `-- name: GetPTIUserPhones :many
SELECT id, user_id, number, is_default, created_at, updated_at FROM pti_user_phones WHERE user_id=$1
`

func (q *Queries) GetPTIUserPhones(ctx context.Context, userID pgtype.UUID) ([]PtiUserPhone, error) {
	rows, err := q.db.Query(ctx, getPTIUserPhones, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PtiUserPhone
	for rows.Next() {
		var i PtiUserPhone
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Number,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPTIUserWallet = `-- name: GetPTIUserWallet :one
SELECT id, user_id, balance, currency, created_at, updated_at FROM pti_wallets WHERE id=$1 AND user_id=$2
`

type GetPTIUserWalletParams struct {
	ID     string
	UserID pgtype.UUID
}

func (q *Queries) GetPTIUserWallet(ctx context.Context, arg GetPTIUserWalletParams) (PtiWallet, error) {
	row := q.db.QueryRow(ctx, getPTIUserWallet, arg.ID, arg.UserID)
	var i PtiWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPTIUserWallets = `-- name: GetPTIUserWallets :many
SELECT id, user_id, balance, currency, created_at, updated_at FROM pti_wallets WHERE user_id=$1
`

func (q *Queries) GetPTIUserWallets(ctx context.Context, userID pgtype.UUID) ([]PtiWallet, error) {
	rows, err := q.db.Query(ctx, getPTIUserWallets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PtiWallet
	for rows.Next() {
		var i PtiWallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPTIWallet = `-- name: GetPTIWallet :one
SELECT id, user_id, balance, currency, created_at, updated_at FROM pti_wallets WHERE id=$1
`

func (q *Queries) GetPTIWallet(ctx context.Context, id string) (PtiWallet, error) {
	row := q.db.QueryRow(ctx, getPTIWallet, id)
	var i PtiWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getXagoBeneficiary = `-- name: GetXagoBeneficiary :one
select id, name, scope, currency_code, account_number, branch_code, bank_name, bank_country, account_name, bank_beneficiary_type, reference, iban, bic, beneficiary_physical_address, beneficiary_district, beneficiary_city, beneficiary_country, beneficiary_postal_code, beneficiary_address, account_type, created_at, updated_at
from xago_beneficiaries
where id = $1
`

func (q *Queries) GetXagoBeneficiary(ctx context.Context, id pgtype.UUID) (XagoBeneficiary, error) {
	row := q.db.QueryRow(ctx, getXagoBeneficiary, id)
	var i XagoBeneficiary
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.CurrencyCode,
		&i.AccountNumber,
		&i.BranchCode,
		&i.BankName,
		&i.BankCountry,
		&i.AccountName,
		&i.BankBeneficiaryType,
		&i.Reference,
		&i.Iban,
		&i.Bic,
		&i.BeneficiaryPhysicalAddress,
		&i.BeneficiaryDistrict,
		&i.BeneficiaryCity,
		&i.BeneficiaryCountry,
		&i.BeneficiaryPostalCode,
		&i.BeneficiaryAddress,
		&i.AccountType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getXagoSubAccount = `-- name: GetXagoSubAccount :one
select id, deposit_address, deposit_tag, first_name, last_name, email, mobile_number, country, nationality, identification_document_type, identification_number, address, city, district, postal_code, address_document_type, date_of_birth, created_at, updated_at from xago_sub_accounts where id = $1 limit 1
`

func (q *Queries) GetXagoSubAccount(ctx context.Context, id pgtype.UUID) (XagoSubAccount, error) {
	row := q.db.QueryRow(ctx, getXagoSubAccount, id)
	var i XagoSubAccount
	err := row.Scan(
		&i.ID,
		&i.DepositAddress,
		&i.DepositTag,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MobileNumber,
		&i.Country,
		&i.Nationality,
		&i.IdentificationDocumentType,
		&i.IdentificationNumber,
		&i.Address,
		&i.City,
		&i.District,
		&i.PostalCode,
		&i.AddressDocumentType,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getXagoSubAccountByDepositReference = `-- name: GetXagoSubAccountByDepositReference :one
select id, deposit_address, deposit_tag, first_name, last_name, email, mobile_number, country, nationality, identification_document_type, identification_number, address, city, district, postal_code, address_document_type, date_of_birth, created_at, updated_at from xago_sub_accounts where deposit_tag = $1 limit 1
`

func (q *Queries) GetXagoSubAccountByDepositReference(ctx context.Context, depositTag string) (XagoSubAccount, error) {
	row := q.db.QueryRow(ctx, getXagoSubAccountByDepositReference, depositTag)
	var i XagoSubAccount
	err := row.Scan(
		&i.ID,
		&i.DepositAddress,
		&i.DepositTag,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MobileNumber,
		&i.Country,
		&i.Nationality,
		&i.IdentificationDocumentType,
		&i.IdentificationNumber,
		&i.Address,
		&i.City,
		&i.District,
		&i.PostalCode,
		&i.AddressDocumentType,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getXagoTransaction = `-- name: GetXagoTransaction :one
select id, currency_code, amount, origin_amount, status, beneficiary_id, idempotency_key, type, created_at, updated_at
from xago_transactions
where id = $1
`

func (q *Queries) GetXagoTransaction(ctx context.Context, id pgtype.UUID) (XagoTransaction, error) {
	row := q.db.QueryRow(ctx, getXagoTransaction, id)
	var i XagoTransaction
	err := row.Scan(
		&i.ID,
		&i.CurrencyCode,
		&i.Amount,
		&i.OriginAmount,
		&i.Status,
		&i.BeneficiaryID,
		&i.IdempotencyKey,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPTIUserAddresses = `-- name: ListPTIUserAddresses :many
SELECT id, user_id, street, postal_code, state_code, country, is_default, created_at, updated_at FROM pti_user_addresses WHERE id = $1
`

func (q *Queries) ListPTIUserAddresses(ctx context.Context, id pgtype.UUID) ([]PtiUserAddress, error) {
	rows, err := q.db.Query(ctx, listPTIUserAddresses, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PtiUserAddress
	for rows.Next() {
		var i PtiUserAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Street,
			&i.PostalCode,
			&i.StateCode,
			&i.Country,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPTIUserEmails = `-- name: ListPTIUserEmails :many
SELECT id, user_id, address, is_default, created_at, updated_at FROM pti_user_emails WHERE id = $1
`

func (q *Queries) ListPTIUserEmails(ctx context.Context, id pgtype.UUID) ([]PtiUserEmail, error) {
	rows, err := q.db.Query(ctx, listPTIUserEmails, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PtiUserEmail
	for rows.Next() {
		var i PtiUserEmail
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listXagoBeneficiaries = `-- name: ListXagoBeneficiaries :many
select id, name, scope, currency_code, account_number, branch_code, bank_name, bank_country, account_name, bank_beneficiary_type, reference, iban, bic, beneficiary_physical_address, beneficiary_district, beneficiary_city, beneficiary_country, beneficiary_postal_code, beneficiary_address, account_type, created_at, updated_at
from xago_beneficiaries
`

func (q *Queries) ListXagoBeneficiaries(ctx context.Context) ([]XagoBeneficiary, error) {
	rows, err := q.db.Query(ctx, listXagoBeneficiaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XagoBeneficiary
	for rows.Next() {
		var i XagoBeneficiary
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.CurrencyCode,
			&i.AccountNumber,
			&i.BranchCode,
			&i.BankName,
			&i.BankCountry,
			&i.AccountName,
			&i.BankBeneficiaryType,
			&i.Reference,
			&i.Iban,
			&i.Bic,
			&i.BeneficiaryPhysicalAddress,
			&i.BeneficiaryDistrict,
			&i.BeneficiaryCity,
			&i.BeneficiaryCountry,
			&i.BeneficiaryPostalCode,
			&i.BeneficiaryAddress,
			&i.AccountType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listXagoDeposits = `-- name: ListXagoDeposits :many
select id, currency_code, amount, origin_amount, status, beneficiary_id, idempotency_key, type, created_at, updated_at
from xago_transactions
where type = 'deposit'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListXagoDepositsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListXagoDeposits(ctx context.Context, arg ListXagoDepositsParams) ([]XagoTransaction, error) {
	rows, err := q.db.Query(ctx, listXagoDeposits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XagoTransaction
	for rows.Next() {
		var i XagoTransaction
		if err := rows.Scan(
			&i.ID,
			&i.CurrencyCode,
			&i.Amount,
			&i.OriginAmount,
			&i.Status,
			&i.BeneficiaryID,
			&i.IdempotencyKey,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAstraUserIntentUserID = `-- name: UpdateAstraUserIntentUserID :exec
UPDATE astra_user_intents SET user_id=$1 WHERE id=$2
`

type UpdateAstraUserIntentUserIDParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) UpdateAstraUserIntentUserID(ctx context.Context, arg UpdateAstraUserIntentUserIDParams) error {
	_, err := q.db.Exec(ctx, updateAstraUserIntentUserID, arg.UserID, arg.ID)
	return err
}
