// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	linkedaccounts "gitlab.com/fynbos/backend/linkedaccounts"
	mx "gitlab.com/fynbos/backend/providers/mx"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateBankAccounts mocks base method.
func (m *MockClient) CreateBankAccounts(ctx context.Context, args mx.CreateBankAccountsArgs) ([]linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBankAccounts", ctx, args)
	ret0, _ := ret[0].([]linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBankAccounts indicates an expected call of CreateBankAccounts.
func (mr *MockClientMockRecorder) CreateBankAccounts(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBankAccounts", reflect.TypeOf((*MockClient)(nil).CreateBankAccounts), ctx, args)
}

// DeleteExternalUser mocks base method.
func (m *MockClient) DeleteExternalUser(ctx context.Context, guid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExternalUser", ctx, guid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExternalUser indicates an expected call of DeleteExternalUser.
func (mr *MockClientMockRecorder) DeleteExternalUser(ctx, guid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExternalUser", reflect.TypeOf((*MockClient)(nil).DeleteExternalUser), ctx, guid)
}

// GetAccount mocks base method.
func (m *MockClient) GetAccount(ctx context.Context, walletID, accountGuid string) (*mx.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, walletID, accountGuid)
	ret0, _ := ret[0].(*mx.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockClientMockRecorder) GetAccount(ctx, walletID, accountGuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockClient)(nil).GetAccount), ctx, walletID, accountGuid)
}

// GetWidget mocks base method.
func (m *MockClient) GetWidget(ctx context.Context, walletID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWidget", ctx, walletID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWidget indicates an expected call of GetWidget.
func (mr *MockClientMockRecorder) GetWidget(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWidget", reflect.TypeOf((*MockClient)(nil).GetWidget), ctx, walletID)
}

// ListUsers mocks base method.
func (m *MockClient) ListUsers(ctx context.Context) ([]mx.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]mx.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockClientMockRecorder) ListUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockClient)(nil).ListUsers), ctx)
}
