// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mx "gitlab.com/fynbos/backend/providers/mx"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockClient) CreateAccount(ctx context.Context, args mx.CreateAccountArgs) (*mx.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, args)
	ret0, _ := ret[0].(*mx.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockClientMockRecorder) CreateAccount(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockClient)(nil).CreateAccount), ctx, args)
}

// GetAccount mocks base method.
func (m *MockClient) GetAccount(ctx context.Context, mxAccountGuid string) (*mx.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, mxAccountGuid)
	ret0, _ := ret[0].(*mx.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockClientMockRecorder) GetAccount(ctx, mxAccountGuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockClient)(nil).GetAccount), ctx, mxAccountGuid)
}

// GetAccountBalance mocks base method.
func (m *MockClient) GetAccountBalance(ctx context.Context, mxAccountGuid string) (*mx.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalance", ctx, mxAccountGuid)
	ret0, _ := ret[0].(*mx.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalance indicates an expected call of GetAccountBalance.
func (mr *MockClientMockRecorder) GetAccountBalance(ctx, mxAccountGuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalance", reflect.TypeOf((*MockClient)(nil).GetAccountBalance), ctx, mxAccountGuid)
}

// GetAccountByFundingsource mocks base method.
func (m *MockClient) GetAccountByFundingsource(ctx context.Context, fundingsourceID string) (*mx.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByFundingsource", ctx, fundingsourceID)
	ret0, _ := ret[0].(*mx.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByFundingsource indicates an expected call of GetAccountByFundingsource.
func (mr *MockClientMockRecorder) GetAccountByFundingsource(ctx, fundingsourceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByFundingsource", reflect.TypeOf((*MockClient)(nil).GetAccountByFundingsource), ctx, fundingsourceID)
}

// GetAccountOwner mocks base method.
func (m *MockClient) GetAccountOwner(ctx context.Context, args mx.GetAccountOwnerArgs) (*mx.AccountOwner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountOwner", ctx, args)
	ret0, _ := ret[0].(*mx.AccountOwner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountOwner indicates an expected call of GetAccountOwner.
func (mr *MockClientMockRecorder) GetAccountOwner(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountOwner", reflect.TypeOf((*MockClient)(nil).GetAccountOwner), ctx, args)
}

// GetConnectWidget mocks base method.
func (m *MockClient) GetConnectWidget(ctx context.Context, accountID, identityID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectWidget", ctx, accountID, identityID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectWidget indicates an expected call of GetConnectWidget.
func (mr *MockClientMockRecorder) GetConnectWidget(ctx, accountID, identityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectWidget", reflect.TypeOf((*MockClient)(nil).GetConnectWidget), ctx, accountID, identityID)
}

// GetMemberStatus mocks base method.
func (m *MockClient) GetMemberStatus(ctx context.Context, mxUserGuid, mxMemberGuid string) (*mx.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberStatus", ctx, mxUserGuid, mxMemberGuid)
	ret0, _ := ret[0].(*mx.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberStatus indicates an expected call of GetMemberStatus.
func (mr *MockClientMockRecorder) GetMemberStatus(ctx, mxUserGuid, mxMemberGuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberStatus", reflect.TypeOf((*MockClient)(nil).GetMemberStatus), ctx, mxUserGuid, mxMemberGuid)
}

// GetMxUserByAccountID mocks base method.
func (m *MockClient) GetMxUserByAccountID(ctx context.Context, accountID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMxUserByAccountID", ctx, accountID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMxUserByAccountID indicates an expected call of GetMxUserByAccountID.
func (mr *MockClientMockRecorder) GetMxUserByAccountID(ctx, accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMxUserByAccountID", reflect.TypeOf((*MockClient)(nil).GetMxUserByAccountID), ctx, accountID)
}

// GetSelectedAccountGuid mocks base method.
func (m *MockClient) GetSelectedAccountGuid(ctx context.Context, mxUserGuid, mxMemberGuid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSelectedAccountGuid", ctx, mxUserGuid, mxMemberGuid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSelectedAccountGuid indicates an expected call of GetSelectedAccountGuid.
func (mr *MockClientMockRecorder) GetSelectedAccountGuid(ctx, mxUserGuid, mxMemberGuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelectedAccountGuid", reflect.TypeOf((*MockClient)(nil).GetSelectedAccountGuid), ctx, mxUserGuid, mxMemberGuid)
}

// InitiateCreateAccount mocks base method.
func (m *MockClient) InitiateCreateAccount(ctx context.Context, args mx.InitiateCreateAccountArgs) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateCreateAccount", ctx, args)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateCreateAccount indicates an expected call of InitiateCreateAccount.
func (mr *MockClientMockRecorder) InitiateCreateAccount(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateCreateAccount", reflect.TypeOf((*MockClient)(nil).InitiateCreateAccount), ctx, args)
}

// InitiateCreateFundingsource mocks base method.
func (m *MockClient) InitiateCreateFundingsource(ctx context.Context, args mx.InitiateCreateFundingsourceArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateCreateFundingsource", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitiateCreateFundingsource indicates an expected call of InitiateCreateFundingsource.
func (mr *MockClientMockRecorder) InitiateCreateFundingsource(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateCreateFundingsource", reflect.TypeOf((*MockClient)(nil).InitiateCreateFundingsource), ctx, args)
}

// ReadAccount mocks base method.
func (m *MockClient) ReadAccount(ctx context.Context, mxAccountGuid string) (*mx.AccountDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAccount", ctx, mxAccountGuid)
	ret0, _ := ret[0].(*mx.AccountDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAccount indicates an expected call of ReadAccount.
func (mr *MockClientMockRecorder) ReadAccount(ctx, mxAccountGuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAccount", reflect.TypeOf((*MockClient)(nil).ReadAccount), ctx, mxAccountGuid)
}

// StartBalanceAggregation mocks base method.
func (m *MockClient) StartBalanceAggregation(ctx context.Context, mxAccountGuid string) (*mx.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartBalanceAggregation", ctx, mxAccountGuid)
	ret0, _ := ret[0].(*mx.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartBalanceAggregation indicates an expected call of StartBalanceAggregation.
func (mr *MockClientMockRecorder) StartBalanceAggregation(ctx, mxAccountGuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBalanceAggregation", reflect.TypeOf((*MockClient)(nil).StartBalanceAggregation), ctx, mxAccountGuid)
}

// StartIdentityAggregation mocks base method.
func (m *MockClient) StartIdentityAggregation(ctx context.Context, mxUserGuid, mxMemberGuid string) (*mx.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartIdentityAggregation", ctx, mxUserGuid, mxMemberGuid)
	ret0, _ := ret[0].(*mx.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartIdentityAggregation indicates an expected call of StartIdentityAggregation.
func (mr *MockClientMockRecorder) StartIdentityAggregation(ctx, mxUserGuid, mxMemberGuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartIdentityAggregation", reflect.TypeOf((*MockClient)(nil).StartIdentityAggregation), ctx, mxUserGuid, mxMemberGuid)
}

// VerifyOwnership mocks base method.
func (m *MockClient) VerifyOwnership(ctx context.Context, args mx.VerifyOwnershipArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOwnership", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyOwnership indicates an expected call of VerifyOwnership.
func (mr *MockClientMockRecorder) VerifyOwnership(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOwnership", reflect.TypeOf((*MockClient)(nil).VerifyOwnership), ctx, args)
}

// WaitForCreateAccount mocks base method.
func (m *MockClient) WaitForCreateAccount(ctx context.Context, fundingsourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForCreateAccount", ctx, fundingsourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForCreateAccount indicates an expected call of WaitForCreateAccount.
func (mr *MockClientMockRecorder) WaitForCreateAccount(ctx, fundingsourceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForCreateAccount", reflect.TypeOf((*MockClient)(nil).WaitForCreateAccount), ctx, fundingsourceID)
}
