// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	contacts "github.com/interledger/interledger-app/go/backend/contacts"
	db "github.com/interledger/interledger-app/go/backend/db"
	wallets "github.com/interledger/interledger-app/go/backend/wallets"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClient) Create(ctx context.Context, args contacts.CreateContactArgs) (*contacts.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, args)
	ret0, _ := ret[0].(*contacts.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClientMockRecorder) Create(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClient)(nil).Create), ctx, args)
}

// Get mocks base method.
func (m *MockClient) Get(ctx context.Context, walletID string, wa wallets.Address) (*contacts.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, walletID, wa)
	ret0, _ := ret[0].(*contacts.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(ctx, walletID, wa interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClient)(nil).Get), ctx, walletID, wa)
}

// List mocks base method.
func (m *MockClient) List(ctx context.Context, walletID string, page db.Pagination, orderBy string) ([]contacts.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, walletID, page, orderBy)
	ret0, _ := ret[0].([]contacts.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClientMockRecorder) List(ctx, walletID, page, orderBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClient)(nil).List), ctx, walletID, page, orderBy)
}

// SetLastPaidAtNow mocks base method.
func (m *MockClient) SetLastPaidAtNow(ctx context.Context, walletID string, wa wallets.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastPaidAtNow", ctx, walletID, wa)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastPaidAtNow indicates an expected call of SetLastPaidAtNow.
func (mr *MockClientMockRecorder) SetLastPaidAtNow(ctx, walletID, wa interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastPaidAtNow", reflect.TypeOf((*MockClient)(nil).SetLastPaidAtNow), ctx, walletID, wa)
}
