apiVersion: v2
name: ingress
description: Emissary Ingress

type: application
version: 0.1.0
appVersion: "2.0.4"
dependencies:
  - name: emissary-ingress
    version: "7.1.9"
    repository: "https://app.getambassador.io"