package rpcserver

import (
	"context"

	"gitlab.com/fynbos/pacioli"

	"gitlab.com/fynbos/pacioli/healthcheck"
	"gitlab.com/fynbos/pacioli/ledger"
	pacioliv1 "gitlab.com/fynbos/proto/pacioli/v1"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/health/grpc_health_v1"
	"google.golang.org/grpc/reflection"
	"google.golang.org/grpc/status"
)

func NewServer(b ledger.Backends, hs healthcheck.Service) *grpc.Server {
	server := grpc.NewServer()
	pacioliv1.RegisterPacioliServiceServer(server, &rpcServer{b: b})
	grpc_health_v1.RegisterHealthServer(server, hs)
	reflection.Register(server)
	return server
}

type rpcServer struct {
	pacioliv1.UnimplementedPacioliServiceServer
	b ledger.Backends
}

// TODO: wire up grpc auth

func (s *rpcServer) ConfigureLedgers(ctx context.Context, req *pacioliv1.ConfigureLedgersRequest) (*pacioliv1.ConfigureLedgersResponse, error) {
	ledgers := make([]pacioli.ConfigureLedgerArgs, len(req.Args))
	for i, ledger := range req.Args {
		ledgers[i] = pacioli.ConfigureLedgerArgs{
			ID:    ledger.GetId(),
			Name:  ledger.GetName(),
			Asset: ledger.GetAsset(),
			Scale: uint8(ledger.GetScale()),
		}
	}
	eventErrors, err := ledger.ConfigureLedgers(ctx, s.b, ledgers)
	// This error will be due to connection / io / validation  issues
	if err != nil {
		switch err.(type) {
		default:
			return nil, status.Error(codes.Internal, err.Error())
		}
	}

	ret := make([]*pacioliv1.EventError, len(eventErrors))
	for i, err := range eventErrors {
		ret[i] = &pacioliv1.EventError{
			Index: err.Index,
			Code:  err.Code,
		}
	}

	return &pacioliv1.ConfigureLedgersResponse{
		Errors: ret,
	}, nil
}

func (s *rpcServer) GetLedgers(ctx context.Context, req *pacioliv1.GetLedgersRequest) (*pacioliv1.GetLedgersResponse, error) {
	ledgers, err := ledger.GetLedgers(ctx, s.b, req.GetIds())
	if err != nil {
		switch err.(type) {
		default:
			return nil, status.Error(codes.Internal, err.Error())
		}
	}

	ret := make([]*pacioliv1.Ledger, len(ledgers))
	for i, ledger := range ledgers {
		ret[i] = &pacioliv1.Ledger{
			Id:    ledger.ID,
			Name:  ledger.Name,
			Asset: ledger.Asset,
			Scale: uint32(ledger.Scale),
		}
	}

	return &pacioliv1.GetLedgersResponse{
		Ledgers: ret,
	}, nil
}

func (s *rpcServer) ConfigureAccounts(ctx context.Context, req *pacioliv1.ConfigureAccountsRequest) (*pacioliv1.ConfigureAccountsResponse, error) {
	accounts := make([]pacioli.ConfigureAccountArgs, len(req.Args))
	for i, account := range req.Args {
		flags := pacioli.AccountFlags{}
		if account.GetFlags() != nil {
			flags.Linked = account.GetFlags().Linked
			flags.DebitsMustNotExceedCredits = account.GetFlags().DebitsMustNotExceedCredits
			flags.CreditsMustNotExceedDebits = account.GetFlags().CreditsMustNotExceedDebits
		}
		accounts[i] = pacioli.ConfigureAccountArgs{
			ID:       account.GetId(),
			LedgerID: account.GetLedgerId(),
			Code:     uint16(account.GetCode()),
			Flags:    flags,
		}
	}
	eventErrors, err := ledger.ConfigureAccounts(ctx, s.b, accounts)
	// This error will be due to connection / io / validation  issues
	if err != nil {
		switch err.(type) {
		default:
			return nil, status.Error(codes.Internal, err.Error())
		}
	}

	ret := make([]*pacioliv1.EventError, len(eventErrors))
	for i, err := range eventErrors {
		ret[i] = &pacioliv1.EventError{
			Index: err.Index,
			Code:  uint32(err.Code),
		}
	}

	return &pacioliv1.ConfigureAccountsResponse{
		Errors: ret,
	}, nil
}

func (s *rpcServer) GetAccounts(ctx context.Context, req *pacioliv1.GetAccountsRequest) (*pacioliv1.GetAccountsResponse, error) {
	accounts, err := ledger.GetAccounts(ctx, s.b, req.GetIds())
	// This error will be due to connection / io / validation  issues
	if err != nil {
		switch err.(type) {
		default:
			return nil, status.Error(codes.Internal, "Failed to get account.")
		}
	}

	ret := make([]*pacioliv1.Account, len(accounts))
	for i, account := range accounts {
		ret[i] = &pacioliv1.Account{
			Id:              account.ID,
			LedgerId:        account.LedgerID,
			Code:            uint32(account.Code),
			DebitsReserved:  account.DebitsPending,
			DebitsAccepted:  account.DebitsPosted,
			CreditsAccepted: account.CreditsPosted,
			CreditsReserved: account.CreditsPending,
			Flags: &pacioliv1.AccountFlags{
				Linked:                     account.Flags.Linked,
				DebitsMustNotExceedCredits: account.Flags.DebitsMustNotExceedCredits,
				CreditsMustNotExceedDebits: account.Flags.CreditsMustNotExceedDebits,
			},
		}
	}

	return &pacioliv1.GetAccountsResponse{
		Accounts: ret,
	}, nil
}

// TODO: Assuming that IDs are uuids and are being generated by another service for now. Might be better to be
// unopinionated and accept []byte.
func (s *rpcServer) CreateTransfers(ctx context.Context, req *pacioliv1.CreateTransfersRequest) (*pacioliv1.CreateTransfersResponse, error) {
	transfers := req.GetTransfers()
	transferArgs := make([]pacioli.CreateTransferArgs, len(transfers))
	for i, transfer := range transfers {
		var flags pacioli.TransferFlags
		if transfer.Flags != nil {
			flags = pacioli.TransferFlags{
				Linked:              transfer.Flags.Linked,
				Pending:             transfer.Flags.Pending,
				PostPendingTransfer: transfer.Flags.PostPending,
				VoidPendingTransfer: transfer.Flags.VoidPending,
			}
		}

		transferArgs[i] = pacioli.CreateTransferArgs{
			ID:              transfer.GetId(),
			Amount:          transfer.GetAmount(),
			DebitAccountID:  transfer.GetDebitAccountId(),
			CreditAccountID: transfer.GetCreditAccountId(),
			Flags:           flags,
			Code:            uint16(transfer.GetCode()),
			Timeout:         transfer.GetTimeout(),
			Ledger:          transfer.Ledger,
		}
	}

	errors, err := ledger.CreateTransfers(ctx, s.b, transferArgs)
	if err != nil {
		switch err.(type) {
		default:
			return nil, status.Error(codes.Internal, "Failed to create transfer."+err.Error())
		}
	}

	errorsToReturn := make([]*pacioliv1.EventError, len(errors))
	for i, err := range errors {
		errorsToReturn[i] = &pacioliv1.EventError{
			Index: err.Index,
			Code:  uint32(err.Code),
		}
	}

	return &pacioliv1.CreateTransfersResponse{
		Errors: errorsToReturn,
	}, nil
}

func (s *rpcServer) GetTransfers(ctx context.Context, req *pacioliv1.GetTransfersRequest) (*pacioliv1.GetTransfersResponse, error) {
	transfers, err := ledger.GetTransfers(ctx, s.b, req.GetIds())
	if err != nil {
		switch err.(type) {
		default:
			return nil, status.Error(codes.Internal, "Failed to get transfers.")
		}
	}

	transfersToReturn := make([]*pacioliv1.Transfer, len(transfers))
	for i, transfer := range transfers {
		transfersToReturn[i] = &pacioliv1.Transfer{
			Id:              transfer.ID,
			PendingId:       transfer.PendingID,
			DebitAccountId:  transfer.DebitAccountID,
			CreditAccountId: transfer.CreditAccountID,
			Amount:          transfer.Amount,
			Code:            uint32(transfer.Code),
			Flags: &pacioliv1.TransferFlags{
				Linked:      transfer.Flags.Linked,
				Pending:     transfer.Flags.Pending,
				PostPending: transfer.Flags.PostPendingTransfer,
				VoidPending: transfer.Flags.VoidPendingTransfer,
			},
		}
	}

	return &pacioliv1.GetTransfersResponse{
		Transfers: transfersToReturn,
	}, nil
}

func (s *rpcServer) PostTransfers(ctx context.Context, req *pacioliv1.PostTransfersRequest) (*pacioliv1.PostTransfersResponse, error) {

	errors, err := ledger.CommitTransfers(ctx, s.b, req.TransferIds)
	if err != nil {
		switch err.(type) {
		default:
			return nil, status.Error(codes.Internal, "Failed to commit transfer."+err.Error())
		}
	}

	errorsToReturn := make([]*pacioliv1.EventError, len(errors))
	for i, err := range errors {
		errorsToReturn[i] = &pacioliv1.EventError{
			Index: err.Index,
			Code:  uint32(err.Code),
		}
	}

	return &pacioliv1.PostTransfersResponse{
		Errors: errorsToReturn,
	}, nil
}

func (s *rpcServer) VoidTransfers(ctx context.Context, req *pacioliv1.VoidTransfersRequest) (*pacioliv1.VoidTransfersResponse, error) {

	errors, err := ledger.VoidTransfers(ctx, s.b, req.TransferIds)
	if err != nil {
		switch err.(type) {
		default:
			return nil, status.Error(codes.Internal, "Failed to commit transfer."+err.Error())
		}
	}

	errorsToReturn := make([]*pacioliv1.EventError, len(errors))
	for i, err := range errors {
		errorsToReturn[i] = &pacioliv1.EventError{
			Index: err.Index,
			Code:  uint32(err.Code),
		}
	}

	return &pacioliv1.VoidTransfersResponse{
		Errors: errorsToReturn,
	}, nil
}
