// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	linkedaccounts "gitlab.com/fynbos/backend/linkedaccounts"
	payments "gitlab.com/fynbos/backend/payments"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// SendApplicationApprovedEmail mocks base method.
func (m *MockClient) SendApplicationApprovedEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendApplicationApprovedEmail", ctx, walletID)
}

// SendApplicationApprovedEmail indicates an expected call of SendApplicationApprovedEmail.
func (mr *MockClientMockRecorder) SendApplicationApprovedEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendApplicationApprovedEmail", reflect.TypeOf((*MockClient)(nil).SendApplicationApprovedEmail), ctx, walletID)
}

// SendApplicationDeniedEmail mocks base method.
func (m *MockClient) SendApplicationDeniedEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendApplicationDeniedEmail", ctx, walletID)
}

// SendApplicationDeniedEmail indicates an expected call of SendApplicationDeniedEmail.
func (mr *MockClientMockRecorder) SendApplicationDeniedEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendApplicationDeniedEmail", reflect.TypeOf((*MockClient)(nil).SendApplicationDeniedEmail), ctx, walletID)
}

// SendApplicationPendingEmail mocks base method.
func (m *MockClient) SendApplicationPendingEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendApplicationPendingEmail", ctx, walletID)
}

// SendApplicationPendingEmail indicates an expected call of SendApplicationPendingEmail.
func (mr *MockClientMockRecorder) SendApplicationPendingEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendApplicationPendingEmail", reflect.TypeOf((*MockClient)(nil).SendApplicationPendingEmail), ctx, walletID)
}

// SendConnectedAccountDocumentsNeededEmail mocks base method.
func (m *MockClient) SendConnectedAccountDocumentsNeededEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendConnectedAccountDocumentsNeededEmail", ctx, walletID)
}

// SendConnectedAccountDocumentsNeededEmail indicates an expected call of SendConnectedAccountDocumentsNeededEmail.
func (mr *MockClientMockRecorder) SendConnectedAccountDocumentsNeededEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConnectedAccountDocumentsNeededEmail", reflect.TypeOf((*MockClient)(nil).SendConnectedAccountDocumentsNeededEmail), ctx, walletID)
}

// SendConnectedAccountEmail mocks base method.
func (m *MockClient) SendConnectedAccountEmail(ctx context.Context, la linkedaccounts.LinkedAccount) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendConnectedAccountEmail", ctx, la)
}

// SendConnectedAccountEmail indicates an expected call of SendConnectedAccountEmail.
func (mr *MockClientMockRecorder) SendConnectedAccountEmail(ctx, la interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConnectedAccountEmail", reflect.TypeOf((*MockClient)(nil).SendConnectedAccountEmail), ctx, la)
}

// SendPaymentFailedEmail mocks base method.
func (m *MockClient) SendPaymentFailedEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendPaymentFailedEmail", ctx, walletID)
}

// SendPaymentFailedEmail indicates an expected call of SendPaymentFailedEmail.
func (mr *MockClientMockRecorder) SendPaymentFailedEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPaymentFailedEmail", reflect.TypeOf((*MockClient)(nil).SendPaymentFailedEmail), ctx, walletID)
}

// SendPaymentReceivedEmailV2 mocks base method.
func (m *MockClient) SendPaymentReceivedEmailV2(ctx context.Context, walletID string, payment *payments.Payment) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendPaymentReceivedEmailV2", ctx, walletID, payment)
}

// SendPaymentReceivedEmailV2 indicates an expected call of SendPaymentReceivedEmailV2.
func (mr *MockClientMockRecorder) SendPaymentReceivedEmailV2(ctx, walletID, payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPaymentReceivedEmailV2", reflect.TypeOf((*MockClient)(nil).SendPaymentReceivedEmailV2), ctx, walletID, payment)
}

// SendPaymentSentEmailV2 mocks base method.
func (m *MockClient) SendPaymentSentEmailV2(ctx context.Context, walletID string, payment *payments.Payment) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendPaymentSentEmailV2", ctx, walletID, payment)
}

// SendPaymentSentEmailV2 indicates an expected call of SendPaymentSentEmailV2.
func (mr *MockClientMockRecorder) SendPaymentSentEmailV2(ctx, walletID, payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPaymentSentEmailV2", reflect.TypeOf((*MockClient)(nil).SendPaymentSentEmailV2), ctx, walletID, payment)
}
