// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	currency "gitlab.com/fynbos/backend/currency"
	email "gitlab.com/fynbos/backend/email"
	linkedaccounts "gitlab.com/fynbos/backend/linkedaccounts"
	payments "gitlab.com/fynbos/backend/payments"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// SendApplicationApprovedEmail mocks base method.
func (m *MockClient) SendApplicationApprovedEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendApplicationApprovedEmail", ctx, walletID)
}

// SendApplicationApprovedEmail indicates an expected call of SendApplicationApprovedEmail.
func (mr *MockClientMockRecorder) SendApplicationApprovedEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendApplicationApprovedEmail", reflect.TypeOf((*MockClient)(nil).SendApplicationApprovedEmail), ctx, walletID)
}

// SendApplicationDeniedEmail mocks base method.
func (m *MockClient) SendApplicationDeniedEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendApplicationDeniedEmail", ctx, walletID)
}

// SendApplicationDeniedEmail indicates an expected call of SendApplicationDeniedEmail.
func (mr *MockClientMockRecorder) SendApplicationDeniedEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendApplicationDeniedEmail", reflect.TypeOf((*MockClient)(nil).SendApplicationDeniedEmail), ctx, walletID)
}

// SendApplicationPendingEmail mocks base method.
func (m *MockClient) SendApplicationPendingEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendApplicationPendingEmail", ctx, walletID)
}

// SendApplicationPendingEmail indicates an expected call of SendApplicationPendingEmail.
func (mr *MockClientMockRecorder) SendApplicationPendingEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendApplicationPendingEmail", reflect.TypeOf((*MockClient)(nil).SendApplicationPendingEmail), ctx, walletID)
}

// SendAuthenticatorResetEmail mocks base method.
func (m *MockClient) SendAuthenticatorResetEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendAuthenticatorResetEmail", ctx, walletID)
}

// SendAuthenticatorResetEmail indicates an expected call of SendAuthenticatorResetEmail.
func (mr *MockClientMockRecorder) SendAuthenticatorResetEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAuthenticatorResetEmail", reflect.TypeOf((*MockClient)(nil).SendAuthenticatorResetEmail), ctx, walletID)
}

// SendCardCreatedEmail mocks base method.
func (m *MockClient) SendCardCreatedEmail(ctx context.Context, walletID, cardID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendCardCreatedEmail", ctx, walletID, cardID)
}

// SendCardCreatedEmail indicates an expected call of SendCardCreatedEmail.
func (mr *MockClientMockRecorder) SendCardCreatedEmail(ctx, walletID, cardID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCardCreatedEmail", reflect.TypeOf((*MockClient)(nil).SendCardCreatedEmail), ctx, walletID, cardID)
}

// SendCardTransactionFXEmail mocks base method.
func (m *MockClient) SendCardTransactionFXEmail(ctx context.Context, walletID, maskedPAN, merchantName, date, surcharge, transactionAmount, billingAmount string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendCardTransactionFXEmail", ctx, walletID, maskedPAN, merchantName, date, surcharge, transactionAmount, billingAmount)
}

// SendCardTransactionFXEmail indicates an expected call of SendCardTransactionFXEmail.
func (mr *MockClientMockRecorder) SendCardTransactionFXEmail(ctx, walletID, maskedPAN, merchantName, date, surcharge, transactionAmount, billingAmount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCardTransactionFXEmail", reflect.TypeOf((*MockClient)(nil).SendCardTransactionFXEmail), ctx, walletID, maskedPAN, merchantName, date, surcharge, transactionAmount, billingAmount)
}

// SendConnectedAccountDocumentsNeededEmail mocks base method.
func (m *MockClient) SendConnectedAccountDocumentsNeededEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendConnectedAccountDocumentsNeededEmail", ctx, walletID)
}

// SendConnectedAccountDocumentsNeededEmail indicates an expected call of SendConnectedAccountDocumentsNeededEmail.
func (mr *MockClientMockRecorder) SendConnectedAccountDocumentsNeededEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConnectedAccountDocumentsNeededEmail", reflect.TypeOf((*MockClient)(nil).SendConnectedAccountDocumentsNeededEmail), ctx, walletID)
}

// SendConnectedAccountEmail mocks base method.
func (m *MockClient) SendConnectedAccountEmail(ctx context.Context, la linkedaccounts.LinkedAccount) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendConnectedAccountEmail", ctx, la)
}

// SendConnectedAccountEmail indicates an expected call of SendConnectedAccountEmail.
func (mr *MockClientMockRecorder) SendConnectedAccountEmail(ctx, la interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConnectedAccountEmail", reflect.TypeOf((*MockClient)(nil).SendConnectedAccountEmail), ctx, la)
}

// SendDepositFailedEmail mocks base method.
func (m *MockClient) SendDepositFailedEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendDepositFailedEmail", ctx, walletID)
}

// SendDepositFailedEmail indicates an expected call of SendDepositFailedEmail.
func (mr *MockClientMockRecorder) SendDepositFailedEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDepositFailedEmail", reflect.TypeOf((*MockClient)(nil).SendDepositFailedEmail), ctx, walletID)
}

// SendDepositReceivedEmail mocks base method.
func (m *MockClient) SendDepositReceivedEmail(ctx context.Context, walletID string, amt currency.Amount, sourceAccountName, date string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendDepositReceivedEmail", ctx, walletID, amt, sourceAccountName, date)
}

// SendDepositReceivedEmail indicates an expected call of SendDepositReceivedEmail.
func (mr *MockClientMockRecorder) SendDepositReceivedEmail(ctx, walletID, amt, sourceAccountName, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDepositReceivedEmail", reflect.TypeOf((*MockClient)(nil).SendDepositReceivedEmail), ctx, walletID, amt, sourceAccountName, date)
}

// SendKYCDocumentsRequiredEmail mocks base method.
func (m *MockClient) SendKYCDocumentsRequiredEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendKYCDocumentsRequiredEmail", ctx, walletID)
}

// SendKYCDocumentsRequiredEmail indicates an expected call of SendKYCDocumentsRequiredEmail.
func (mr *MockClientMockRecorder) SendKYCDocumentsRequiredEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendKYCDocumentsRequiredEmail", reflect.TypeOf((*MockClient)(nil).SendKYCDocumentsRequiredEmail), ctx, walletID)
}

// SendLimitsExceededEmail mocks base method.
func (m *MockClient) SendLimitsExceededEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendLimitsExceededEmail", ctx, walletID)
}

// SendLimitsExceededEmail indicates an expected call of SendLimitsExceededEmail.
func (mr *MockClientMockRecorder) SendLimitsExceededEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLimitsExceededEmail", reflect.TypeOf((*MockClient)(nil).SendLimitsExceededEmail), ctx, walletID)
}

// SendPaymentFailedEmail mocks base method.
func (m *MockClient) SendPaymentFailedEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendPaymentFailedEmail", ctx, walletID)
}

// SendPaymentFailedEmail indicates an expected call of SendPaymentFailedEmail.
func (mr *MockClientMockRecorder) SendPaymentFailedEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPaymentFailedEmail", reflect.TypeOf((*MockClient)(nil).SendPaymentFailedEmail), ctx, walletID)
}

// SendPaymentReceivedEmailV2 mocks base method.
func (m *MockClient) SendPaymentReceivedEmailV2(ctx context.Context, walletID string, payment *payments.Payment) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendPaymentReceivedEmailV2", ctx, walletID, payment)
}

// SendPaymentReceivedEmailV2 indicates an expected call of SendPaymentReceivedEmailV2.
func (mr *MockClientMockRecorder) SendPaymentReceivedEmailV2(ctx, walletID, payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPaymentReceivedEmailV2", reflect.TypeOf((*MockClient)(nil).SendPaymentReceivedEmailV2), ctx, walletID, payment)
}

// SendPaymentSentEmailV2 mocks base method.
func (m *MockClient) SendPaymentSentEmailV2(ctx context.Context, walletID string, payment *payments.Payment) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendPaymentSentEmailV2", ctx, walletID, payment)
}

// SendPaymentSentEmailV2 indicates an expected call of SendPaymentSentEmailV2.
func (mr *MockClientMockRecorder) SendPaymentSentEmailV2(ctx, walletID, payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPaymentSentEmailV2", reflect.TypeOf((*MockClient)(nil).SendPaymentSentEmailV2), ctx, walletID, payment)
}

// SendPending3DSConfirmation mocks base method.
func (m *MockClient) SendPending3DSConfirmation(ctx context.Context, walletID, confirmationID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendPending3DSConfirmation", ctx, walletID, confirmationID)
}

// SendPending3DSConfirmation indicates an expected call of SendPending3DSConfirmation.
func (mr *MockClientMockRecorder) SendPending3DSConfirmation(ctx, walletID, confirmationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPending3DSConfirmation", reflect.TypeOf((*MockClient)(nil).SendPending3DSConfirmation), ctx, walletID, confirmationID)
}

// SendWithdrawalEmail mocks base method.
func (m *MockClient) SendWithdrawalEmail(ctx context.Context, walletID string, amt currency.Amount, destinationAccount, date string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendWithdrawalEmail", ctx, walletID, amt, destinationAccount, date)
}

// SendWithdrawalEmail indicates an expected call of SendWithdrawalEmail.
func (mr *MockClientMockRecorder) SendWithdrawalEmail(ctx, walletID, amt, destinationAccount, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWithdrawalEmail", reflect.TypeOf((*MockClient)(nil).SendWithdrawalEmail), ctx, walletID, amt, destinationAccount, date)
}

// SendWithdrawalFailedEmail mocks base method.
func (m *MockClient) SendWithdrawalFailedEmail(ctx context.Context, walletID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendWithdrawalFailedEmail", ctx, walletID)
}

// SendWithdrawalFailedEmail indicates an expected call of SendWithdrawalFailedEmail.
func (mr *MockClientMockRecorder) SendWithdrawalFailedEmail(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWithdrawalFailedEmail", reflect.TypeOf((*MockClient)(nil).SendWithdrawalFailedEmail), ctx, walletID)
}

// SendAgreementChangedEmail mocks base method.
func (m *MockClient) SendAgreementChangedEmail(ctx context.Context, userID string, agreements []email.AgreementLink, deadlineDate string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAgreementChangedEmail", ctx, userID, agreements, deadlineDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAgreementChangedEmail indicates an expected call of SendAgreementChangedEmail.
func (mr *MockClientMockRecorder) SendAgreementChangedEmail(ctx, userID, agreements, deadlineDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAgreementChangedEmail", reflect.TypeOf((*MockClient)(nil).SendAgreementChangedEmail), ctx, userID, agreements, deadlineDate)
}
