// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	machnet "gitlab.com/fynbos/backend/providers/machnet"
	external "gitlab.com/fynbos/backend/providers/machnet/external"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateReceiveAccount mocks base method.
func (m *MockClient) CreateReceiveAccount(ctx context.Context, args machnet.CreateReceiveAccountArgs) (*machnet.ReceiveAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReceiveAccount", ctx, args)
	ret0, _ := ret[0].(*machnet.ReceiveAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReceiveAccount indicates an expected call of CreateReceiveAccount.
func (mr *MockClientMockRecorder) CreateReceiveAccount(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReceiveAccount", reflect.TypeOf((*MockClient)(nil).CreateReceiveAccount), ctx, args)
}

// CreateReceiveUser mocks base method.
func (m *MockClient) CreateReceiveUser(ctx context.Context, args machnet.CreateReceiveUserArgs) (*machnet.ReceiveUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReceiveUser", ctx, args)
	ret0, _ := ret[0].(*machnet.ReceiveUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReceiveUser indicates an expected call of CreateReceiveUser.
func (mr *MockClientMockRecorder) CreateReceiveUser(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReceiveUser", reflect.TypeOf((*MockClient)(nil).CreateReceiveUser), ctx, args)
}

// CreateReceiveUserAccount mocks base method.
func (m *MockClient) CreateReceiveUserAccount(ctx context.Context, args machnet.CreateReceiveUserAccountArgs) (*machnet.ReceiveUserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReceiveUserAccount", ctx, args)
	ret0, _ := ret[0].(*machnet.ReceiveUserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReceiveUserAccount indicates an expected call of CreateReceiveUserAccount.
func (mr *MockClientMockRecorder) CreateReceiveUserAccount(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReceiveUserAccount", reflect.TypeOf((*MockClient)(nil).CreateReceiveUserAccount), ctx, args)
}

// CreateUser mocks base method.
func (m *MockClient) CreateUser(ctx context.Context, args machnet.CreateArgs) (*machnet.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, args)
	ret0, _ := ret[0].(*machnet.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockClientMockRecorder) CreateUser(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockClient)(nil).CreateUser), ctx, args)
}

// GetReceiveAccount mocks base method.
func (m *MockClient) GetReceiveAccount(ctx context.Context, id string) (*machnet.ReceiveAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceiveAccount", ctx, id)
	ret0, _ := ret[0].(*machnet.ReceiveAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceiveAccount indicates an expected call of GetReceiveAccount.
func (mr *MockClientMockRecorder) GetReceiveAccount(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceiveAccount", reflect.TypeOf((*MockClient)(nil).GetReceiveAccount), ctx, id)
}

// GetReceiveUserAccountByReceiveAccountID mocks base method.
func (m *MockClient) GetReceiveUserAccountByReceiveAccountID(ctx context.Context, receiveAccountID string) (*machnet.ReceiveUserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceiveUserAccountByReceiveAccountID", ctx, receiveAccountID)
	ret0, _ := ret[0].(*machnet.ReceiveUserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceiveUserAccountByReceiveAccountID indicates an expected call of GetReceiveUserAccountByReceiveAccountID.
func (mr *MockClientMockRecorder) GetReceiveUserAccountByReceiveAccountID(ctx, receiveAccountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceiveUserAccountByReceiveAccountID", reflect.TypeOf((*MockClient)(nil).GetReceiveUserAccountByReceiveAccountID), ctx, receiveAccountID)
}

// GetReceiveUserByReceiveWalletID mocks base method.
func (m *MockClient) GetReceiveUserByReceiveWalletID(ctx context.Context, receiveWalletID string) (*machnet.ReceiveUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceiveUserByReceiveWalletID", ctx, receiveWalletID)
	ret0, _ := ret[0].(*machnet.ReceiveUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceiveUserByReceiveWalletID indicates an expected call of GetReceiveUserByReceiveWalletID.
func (mr *MockClientMockRecorder) GetReceiveUserByReceiveWalletID(ctx, receiveWalletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceiveUserByReceiveWalletID", reflect.TypeOf((*MockClient)(nil).GetReceiveUserByReceiveWalletID), ctx, receiveWalletID)
}

// GetUserByID mocks base method.
func (m *MockClient) GetUserByID(ctx context.Context, id string) (*machnet.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*machnet.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockClientMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockClient)(nil).GetUserByID), ctx, id)
}

// GetUserByWalletID mocks base method.
func (m *MockClient) GetUserByWalletID(ctx context.Context, walletID string) (*machnet.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByWalletID", ctx, walletID)
	ret0, _ := ret[0].(*machnet.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByWalletID indicates an expected call of GetUserByWalletID.
func (mr *MockClientMockRecorder) GetUserByWalletID(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByWalletID", reflect.TypeOf((*MockClient)(nil).GetUserByWalletID), ctx, walletID)
}

// GetWidgetToken mocks base method.
func (m *MockClient) GetWidgetToken(ctx context.Context, walletID string) (*machnet.WidgetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWidgetToken", ctx, walletID)
	ret0, _ := ret[0].(*machnet.WidgetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWidgetToken indicates an expected call of GetWidgetToken.
func (mr *MockClientMockRecorder) GetWidgetToken(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWidgetToken", reflect.TypeOf((*MockClient)(nil).GetWidgetToken), ctx, walletID)
}

// HandleEvent mocks base method.
func (m *MockClient) HandleEvent(ctx context.Context, event external.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleEvent indicates an expected call of HandleEvent.
func (mr *MockClientMockRecorder) HandleEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleEvent", reflect.TypeOf((*MockClient)(nil).HandleEvent), ctx, event)
}
