workflow:
  rules:
    - changes:
      - infra/**/*
    # we need to configure this pipeline to run on merge requests
    - if: $CI_MERGE_REQUEST_ID

stages:
  - hello

variables:
  PROJECT_PATH: $CI_PROJECT_DIR/infra/

image: golang:1.16-bullseye


hello:
  stage: hello
  script:
    - echo "Not set up yet"
  interruptible: true
