apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacioli
  labels:
    app: pacioli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacioli
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: pacioli
    spec:
      securityContext:
        runAsUser: 65532
      volumes:
      - name: cockroach-certs
        secret:
          secretName: cockroachdb.client.pacioli
          # items:
          #   - key: client.pacioli.key
          #     path: client.pacioli.key
          #     mode: 0600
          #   - key: client.pacioli.crt
          #     path: client.pacioli.crt
          #   - key: ca.crt
          #     path: ca.crt
      serviceAccountName: pacioli
      initContainers:
        - name: init-db
          image: fynbos/pacioli-init
          imagePullPolicy: Always
          env:
            - name: DB_URL
              # don't specify the ssl certs here. The application will read them in from file and inline them.
              value: "cockroach://pacioli@cockroachdb-public:26257/pacioli?sslmode=verify-full&max_conns=20&max_idle_conns=4"
          volumeMounts:
          - name: cockroach-certs
            mountPath: "/cockroach-certs"
      containers:
        - name: pacioli
          image: fynbos/pacioli
          imagePullPolicy: Always
          # TODO: Change these to appropriate values for the hardware that you're running. You can see
          # the resources that can be allocated on each of your Kubernetes nodes by running:
          #   kubectl describe nodes
          # Note that requests and limits should have identical values.
#          resources:
#            requests:
#              cpu: "2"
#              memory: "8Gi"
#            limits:
#              cpu: "2"
#              memory: "8Gi"
          ports:
            - containerPort: 8080
              name: http
          # we use the same endpoint for liveness and readiness as we are only running a graphql server
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: http
              scheme: HTTP
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: http
              scheme: HTTP
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: DB_URL
              # don't specify the ssl certs here. The application will read them in from file and inline them.
              value: "cockroach://pacioli@cockroachdb-public:26257/pacioli?sslmode=verify-full&max_conns=20&max_idle_conns=4"
            - name: TB_URL
              value: "tigerbeetle-0.tigerbeetle.default.svc.cluster.local:80"
          volumeMounts:
          - name: cockroach-certs
            mountPath: "/cockroach-certs"
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 30