{{- define "mock-services.mockxago.deployment" -}}
{{- $top := first . }}
{{- if and (kindIs "bool" $top.Values.mockxago.enabled) $top.Values.mockxago.enabled }}
{{- $cfgObj := include "mock-services.mockxago.configMap" $top | fromYaml -}}
{{- $dataHash := $cfgObj.data | toJson | sha256sum -}}
spec:
  template:
    metadata:
      annotations:
        ilf-configmap-mockxago-sha256: {{ $dataHash | quote }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ include "common.fullname" $top }}-{{ $top.Values.mockxago.configMaps.config.name }}
{{- end }}
{{- end }}
{{- if and (kindIs "bool" .Values.mockxago.enabled) .Values.mockxago.enabled }}
{{- $sa := include "mock-services.saSpec" (list . .Values.mockxago "mockxago") | fromYaml }}
{{- include "common.deployment" (list . .Values.mockxago.server .Values.mockxago.server.autoscaling $sa "mock-services.mockxago.deployment") }}
{{- end }}
