{{- define "mock-services.mockgatehub.deployment" -}}
{{- $top := first . }}
{{- if and (kindIs "bool" $top.Values.mockgatehub.enabled) $top.Values.mockgatehub.enabled }}
{{- $cfgObj := include "mock-services.mockgatehub.configMap" $top | fromYaml -}}
{{- $dataHash := $cfgObj.data | toJson | sha256sum -}}
spec:
  template:
    metadata:
      annotations:
        ilf-configmap-mockgatehub-sha256: {{ $dataHash | quote }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ include "common.fullname" $top }}-{{ $top.Values.mockgatehub.configMaps.config.name }}
{{- end }}
{{- end }}
{{- if and (kindIs "bool" .Values.mockgatehub.enabled) .Values.mockgatehub.enabled }}
{{- $sa := include "mock-services.saSpec" (list . .Values.mockgatehub "mockgatehub") | fromYaml }}
{{- include "common.deployment" (list . .Values.mockgatehub.server .Values.mockgatehub.server.autoscaling $sa "mock-services.mockgatehub.deployment") }}
{{- end }}
