{{- define "mock-services.mockpti.service" -}}
{{- $top := first . -}}
{{- end }}
{{- if and (kindIs "bool" .Values.mockpti.enabled) .Values.mockpti.enabled }}
{{- include "common.svc" (list . .Values.mockpti.server.service .Values.mockpti.server "mock-services.mockpti.service") }}
{{- end }}
