// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: pacioli/v1/pacioli.proto

package pacioli

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PacioliServiceClient is the client API for PacioliService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PacioliServiceClient interface {
	ConfigureLedgers(ctx context.Context, in *ConfigureLedgersRequest, opts ...grpc.CallOption) (*ConfigureLedgersResponse, error)
	GetLedgers(ctx context.Context, in *GetLedgersRequest, opts ...grpc.CallOption) (*GetLedgersResponse, error)
	ConfigureAccounts(ctx context.Context, in *ConfigureAccountsRequest, opts ...grpc.CallOption) (*ConfigureAccountsResponse, error)
	GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsResponse, error)
	CreateTransfers(ctx context.Context, in *CreateTransfersRequest, opts ...grpc.CallOption) (*CreateTransfersResponse, error)
	GetTransfers(ctx context.Context, in *GetTransfersRequest, opts ...grpc.CallOption) (*GetTransfersResponse, error)
	PostTransfers(ctx context.Context, in *PostTransfersRequest, opts ...grpc.CallOption) (*PostTransfersResponse, error)
	VoidTransfers(ctx context.Context, in *VoidTransfersRequest, opts ...grpc.CallOption) (*VoidTransfersResponse, error)
}

type pacioliServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPacioliServiceClient(cc grpc.ClientConnInterface) PacioliServiceClient {
	return &pacioliServiceClient{cc}
}

func (c *pacioliServiceClient) ConfigureLedgers(ctx context.Context, in *ConfigureLedgersRequest, opts ...grpc.CallOption) (*ConfigureLedgersResponse, error) {
	out := new(ConfigureLedgersResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/ConfigureLedgers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) GetLedgers(ctx context.Context, in *GetLedgersRequest, opts ...grpc.CallOption) (*GetLedgersResponse, error) {
	out := new(GetLedgersResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/GetLedgers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) ConfigureAccounts(ctx context.Context, in *ConfigureAccountsRequest, opts ...grpc.CallOption) (*ConfigureAccountsResponse, error) {
	out := new(ConfigureAccountsResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/ConfigureAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsResponse, error) {
	out := new(GetAccountsResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/GetAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) CreateTransfers(ctx context.Context, in *CreateTransfersRequest, opts ...grpc.CallOption) (*CreateTransfersResponse, error) {
	out := new(CreateTransfersResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/CreateTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) GetTransfers(ctx context.Context, in *GetTransfersRequest, opts ...grpc.CallOption) (*GetTransfersResponse, error) {
	out := new(GetTransfersResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/GetTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) PostTransfers(ctx context.Context, in *PostTransfersRequest, opts ...grpc.CallOption) (*PostTransfersResponse, error) {
	out := new(PostTransfersResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/PostTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) VoidTransfers(ctx context.Context, in *VoidTransfersRequest, opts ...grpc.CallOption) (*VoidTransfersResponse, error) {
	out := new(VoidTransfersResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/VoidTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PacioliServiceServer is the server API for PacioliService service.
// All implementations should embed UnimplementedPacioliServiceServer
// for forward compatibility
type PacioliServiceServer interface {
	ConfigureLedgers(context.Context, *ConfigureLedgersRequest) (*ConfigureLedgersResponse, error)
	GetLedgers(context.Context, *GetLedgersRequest) (*GetLedgersResponse, error)
	ConfigureAccounts(context.Context, *ConfigureAccountsRequest) (*ConfigureAccountsResponse, error)
	GetAccounts(context.Context, *GetAccountsRequest) (*GetAccountsResponse, error)
	CreateTransfers(context.Context, *CreateTransfersRequest) (*CreateTransfersResponse, error)
	GetTransfers(context.Context, *GetTransfersRequest) (*GetTransfersResponse, error)
	PostTransfers(context.Context, *PostTransfersRequest) (*PostTransfersResponse, error)
	VoidTransfers(context.Context, *VoidTransfersRequest) (*VoidTransfersResponse, error)
}

// UnimplementedPacioliServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPacioliServiceServer struct {
}

func (UnimplementedPacioliServiceServer) ConfigureLedgers(context.Context, *ConfigureLedgersRequest) (*ConfigureLedgersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureLedgers not implemented")
}
func (UnimplementedPacioliServiceServer) GetLedgers(context.Context, *GetLedgersRequest) (*GetLedgersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLedgers not implemented")
}
func (UnimplementedPacioliServiceServer) ConfigureAccounts(context.Context, *ConfigureAccountsRequest) (*ConfigureAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureAccounts not implemented")
}
func (UnimplementedPacioliServiceServer) GetAccounts(context.Context, *GetAccountsRequest) (*GetAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccounts not implemented")
}
func (UnimplementedPacioliServiceServer) CreateTransfers(context.Context, *CreateTransfersRequest) (*CreateTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransfers not implemented")
}
func (UnimplementedPacioliServiceServer) GetTransfers(context.Context, *GetTransfersRequest) (*GetTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransfers not implemented")
}
func (UnimplementedPacioliServiceServer) PostTransfers(context.Context, *PostTransfersRequest) (*PostTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTransfers not implemented")
}
func (UnimplementedPacioliServiceServer) VoidTransfers(context.Context, *VoidTransfersRequest) (*VoidTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoidTransfers not implemented")
}

// UnsafePacioliServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PacioliServiceServer will
// result in compilation errors.
type UnsafePacioliServiceServer interface {
	mustEmbedUnimplementedPacioliServiceServer()
}

func RegisterPacioliServiceServer(s grpc.ServiceRegistrar, srv PacioliServiceServer) {
	s.RegisterService(&PacioliService_ServiceDesc, srv)
}

func _PacioliService_ConfigureLedgers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureLedgersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).ConfigureLedgers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/ConfigureLedgers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).ConfigureLedgers(ctx, req.(*ConfigureLedgersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_GetLedgers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).GetLedgers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/GetLedgers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).GetLedgers(ctx, req.(*GetLedgersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_ConfigureAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).ConfigureAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/ConfigureAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).ConfigureAccounts(ctx, req.(*ConfigureAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).GetAccounts(ctx, req.(*GetAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_CreateTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).CreateTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/CreateTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).CreateTransfers(ctx, req.(*CreateTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_GetTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).GetTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/GetTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).GetTransfers(ctx, req.(*GetTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_PostTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).PostTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/PostTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).PostTransfers(ctx, req.(*PostTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_VoidTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).VoidTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/VoidTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).VoidTransfers(ctx, req.(*VoidTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PacioliService_ServiceDesc is the grpc.ServiceDesc for PacioliService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PacioliService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pacioli.v1.PacioliService",
	HandlerType: (*PacioliServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureLedgers",
			Handler:    _PacioliService_ConfigureLedgers_Handler,
		},
		{
			MethodName: "GetLedgers",
			Handler:    _PacioliService_GetLedgers_Handler,
		},
		{
			MethodName: "ConfigureAccounts",
			Handler:    _PacioliService_ConfigureAccounts_Handler,
		},
		{
			MethodName: "GetAccounts",
			Handler:    _PacioliService_GetAccounts_Handler,
		},
		{
			MethodName: "CreateTransfers",
			Handler:    _PacioliService_CreateTransfers_Handler,
		},
		{
			MethodName: "GetTransfers",
			Handler:    _PacioliService_GetTransfers_Handler,
		},
		{
			MethodName: "PostTransfers",
			Handler:    _PacioliService_PostTransfers_Handler,
		},
		{
			MethodName: "VoidTransfers",
			Handler:    _PacioliService_VoidTransfers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pacioli/v1/pacioli.proto",
}
