// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: pacioli/v1/pacioli.proto

package pacioli

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PacioliServiceClient is the client API for PacioliService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PacioliServiceClient interface {
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*Empty, error)
	CreateLedgers(ctx context.Context, in *CreateLedgersRequest, opts ...grpc.CallOption) (*CreateLedgersResponse, error)
	GetLedgers(ctx context.Context, in *GetLedgersRequest, opts ...grpc.CallOption) (*GetLedgersResponse, error)
	CreateAccounts(ctx context.Context, in *CreateAccountsRequest, opts ...grpc.CallOption) (*CreateAccountsResponse, error)
	GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*Account, error)
	CreateTransfers(ctx context.Context, in *CreateTransfersRequest, opts ...grpc.CallOption) (*CreateTransfersResponse, error)
	GetTransfers(ctx context.Context, in *GetTransfersRequest, opts ...grpc.CallOption) (*GetTransfersResponse, error)
}

type pacioliServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPacioliServiceClient(cc grpc.ClientConnInterface) PacioliServiceClient {
	return &pacioliServiceClient{cc}
}

func (c *pacioliServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/CreateTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) CreateLedgers(ctx context.Context, in *CreateLedgersRequest, opts ...grpc.CallOption) (*CreateLedgersResponse, error) {
	out := new(CreateLedgersResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/CreateLedgers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) GetLedgers(ctx context.Context, in *GetLedgersRequest, opts ...grpc.CallOption) (*GetLedgersResponse, error) {
	out := new(GetLedgersResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/GetLedgers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) CreateAccounts(ctx context.Context, in *CreateAccountsRequest, opts ...grpc.CallOption) (*CreateAccountsResponse, error) {
	out := new(CreateAccountsResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/CreateAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/GetAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) CreateTransfers(ctx context.Context, in *CreateTransfersRequest, opts ...grpc.CallOption) (*CreateTransfersResponse, error) {
	out := new(CreateTransfersResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/CreateTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pacioliServiceClient) GetTransfers(ctx context.Context, in *GetTransfersRequest, opts ...grpc.CallOption) (*GetTransfersResponse, error) {
	out := new(GetTransfersResponse)
	err := c.cc.Invoke(ctx, "/pacioli.v1.PacioliService/GetTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PacioliServiceServer is the server API for PacioliService service.
// All implementations should embed UnimplementedPacioliServiceServer
// for forward compatibility
type PacioliServiceServer interface {
	CreateTenant(context.Context, *CreateTenantRequest) (*Empty, error)
	CreateLedgers(context.Context, *CreateLedgersRequest) (*CreateLedgersResponse, error)
	GetLedgers(context.Context, *GetLedgersRequest) (*GetLedgersResponse, error)
	CreateAccounts(context.Context, *CreateAccountsRequest) (*CreateAccountsResponse, error)
	GetAccounts(context.Context, *GetAccountsRequest) (*Account, error)
	CreateTransfers(context.Context, *CreateTransfersRequest) (*CreateTransfersResponse, error)
	GetTransfers(context.Context, *GetTransfersRequest) (*GetTransfersResponse, error)
}

// UnimplementedPacioliServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPacioliServiceServer struct {
}

func (UnimplementedPacioliServiceServer) CreateTenant(context.Context, *CreateTenantRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedPacioliServiceServer) CreateLedgers(context.Context, *CreateLedgersRequest) (*CreateLedgersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLedgers not implemented")
}
func (UnimplementedPacioliServiceServer) GetLedgers(context.Context, *GetLedgersRequest) (*GetLedgersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLedgers not implemented")
}
func (UnimplementedPacioliServiceServer) CreateAccounts(context.Context, *CreateAccountsRequest) (*CreateAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccounts not implemented")
}
func (UnimplementedPacioliServiceServer) GetAccounts(context.Context, *GetAccountsRequest) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccounts not implemented")
}
func (UnimplementedPacioliServiceServer) CreateTransfers(context.Context, *CreateTransfersRequest) (*CreateTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransfers not implemented")
}
func (UnimplementedPacioliServiceServer) GetTransfers(context.Context, *GetTransfersRequest) (*GetTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransfers not implemented")
}

// UnsafePacioliServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PacioliServiceServer will
// result in compilation errors.
type UnsafePacioliServiceServer interface {
	mustEmbedUnimplementedPacioliServiceServer()
}

func RegisterPacioliServiceServer(s grpc.ServiceRegistrar, srv PacioliServiceServer) {
	s.RegisterService(&PacioliService_ServiceDesc, srv)
}

func _PacioliService_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/CreateTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_CreateLedgers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLedgersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).CreateLedgers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/CreateLedgers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).CreateLedgers(ctx, req.(*CreateLedgersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_GetLedgers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).GetLedgers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/GetLedgers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).GetLedgers(ctx, req.(*GetLedgersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_CreateAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).CreateAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/CreateAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).CreateAccounts(ctx, req.(*CreateAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).GetAccounts(ctx, req.(*GetAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_CreateTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).CreateTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/CreateTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).CreateTransfers(ctx, req.(*CreateTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacioliService_GetTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacioliServiceServer).GetTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pacioli.v1.PacioliService/GetTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacioliServiceServer).GetTransfers(ctx, req.(*GetTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PacioliService_ServiceDesc is the grpc.ServiceDesc for PacioliService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PacioliService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pacioli.v1.PacioliService",
	HandlerType: (*PacioliServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTenant",
			Handler:    _PacioliService_CreateTenant_Handler,
		},
		{
			MethodName: "CreateLedgers",
			Handler:    _PacioliService_CreateLedgers_Handler,
		},
		{
			MethodName: "GetLedgers",
			Handler:    _PacioliService_GetLedgers_Handler,
		},
		{
			MethodName: "CreateAccounts",
			Handler:    _PacioliService_CreateAccounts_Handler,
		},
		{
			MethodName: "GetAccounts",
			Handler:    _PacioliService_GetAccounts_Handler,
		},
		{
			MethodName: "CreateTransfers",
			Handler:    _PacioliService_CreateTransfers_Handler,
		},
		{
			MethodName: "GetTransfers",
			Handler:    _PacioliService_GetTransfers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pacioli/v1/pacioli.proto",
}
