// Code generated by MockGen. DO NOT EDIT.
// Source: ../client.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	persona "github.com/interledger/interledger-app/go/backend/kyc/persona"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateInquiry mocks base method.
func (m *MockClient) CreateInquiry(ctx context.Context, args persona.IndividualAttributes, idempotencyKey string) (*persona.InquiryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInquiry", ctx, args, idempotencyKey)
	ret0, _ := ret[0].(*persona.InquiryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInquiry indicates an expected call of CreateInquiry.
func (mr *MockClientMockRecorder) CreateInquiry(ctx, args, idempotencyKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInquiry", reflect.TypeOf((*MockClient)(nil).CreateInquiry), ctx, args, idempotencyKey)
}

// GetAccount mocks base method.
func (m *MockClient) GetAccount(ctx context.Context, id string) (*persona.AccountData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, id)
	ret0, _ := ret[0].(*persona.AccountData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockClientMockRecorder) GetAccount(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockClient)(nil).GetAccount), ctx, id)
}

// LookupInquiry mocks base method.
func (m *MockClient) LookupInquiry(ctx context.Context, inquiryID string) (*persona.Inquiry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupInquiry", ctx, inquiryID)
	ret0, _ := ret[0].(*persona.Inquiry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupInquiry indicates an expected call of LookupInquiry.
func (mr *MockClientMockRecorder) LookupInquiry(ctx, inquiryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupInquiry", reflect.TypeOf((*MockClient)(nil).LookupInquiry), ctx, inquiryID)
}

// RemoveTag mocks base method.
func (m *MockClient) RemoveTag(ctx context.Context, accountID, tag string) (*persona.AccountData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTag", ctx, accountID, tag)
	ret0, _ := ret[0].(*persona.AccountData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveTag indicates an expected call of RemoveTag.
func (mr *MockClientMockRecorder) RemoveTag(ctx, accountID, tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTag", reflect.TypeOf((*MockClient)(nil).RemoveTag), ctx, accountID, tag)
}

// ResumeInquiry mocks base method.
func (m *MockClient) ResumeInquiry(ctx context.Context, inquiryID, idempotencyKey string) (*persona.InquiryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeInquiry", ctx, inquiryID, idempotencyKey)
	ret0, _ := ret[0].(*persona.InquiryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeInquiry indicates an expected call of ResumeInquiry.
func (mr *MockClientMockRecorder) ResumeInquiry(ctx, inquiryID, idempotencyKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeInquiry", reflect.TypeOf((*MockClient)(nil).ResumeInquiry), ctx, inquiryID, idempotencyKey)
}

// ValidateWebhook mocks base method.
func (m *MockClient) ValidateWebhook(req *http.Request, body []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWebhook", req, body)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidateWebhook indicates an expected call of ValidateWebhook.
func (mr *MockClientMockRecorder) ValidateWebhook(req, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWebhook", reflect.TypeOf((*MockClient)(nil).ValidateWebhook), req, body)
}
