// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: backend/admin/v1/backend.proto

package admin

import (
	_ "google.golang.org/genproto/googleapis/rpc/code"
	_ "google.golang.org/genproto/googleapis/rpc/errdetails"
	_ "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_admin_v1_backend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_backend_admin_v1_backend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_backend_admin_v1_backend_proto_rawDescGZIP(), []int{0}
}

type AllowWaitlistSignupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AllowWaitlistSignupRequest) Reset() {
	*x = AllowWaitlistSignupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_admin_v1_backend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowWaitlistSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowWaitlistSignupRequest) ProtoMessage() {}

func (x *AllowWaitlistSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_admin_v1_backend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowWaitlistSignupRequest.ProtoReflect.Descriptor instead.
func (*AllowWaitlistSignupRequest) Descriptor() ([]byte, []int) {
	return file_backend_admin_v1_backend_proto_rawDescGZIP(), []int{1}
}

func (x *AllowWaitlistSignupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListWaitlistSignupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signups []*WaitlistSignup `protobuf:"bytes,1,rep,name=signups,proto3" json:"signups,omitempty"`
}

func (x *ListWaitlistSignupsResponse) Reset() {
	*x = ListWaitlistSignupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_admin_v1_backend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWaitlistSignupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWaitlistSignupsResponse) ProtoMessage() {}

func (x *ListWaitlistSignupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_admin_v1_backend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWaitlistSignupsResponse.ProtoReflect.Descriptor instead.
func (*ListWaitlistSignupsResponse) Descriptor() ([]byte, []int) {
	return file_backend_admin_v1_backend_proto_rawDescGZIP(), []int{2}
}

func (x *ListWaitlistSignupsResponse) GetSignups() []*WaitlistSignup {
	if x != nil {
		return x.Signups
	}
	return nil
}

type WaitlistSignup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	BetaOptIn bool   `protobuf:"varint,4,opt,name=beta_opt_in,json=betaOptIn,proto3" json:"beta_opt_in,omitempty"`
	CanSignup bool   `protobuf:"varint,5,opt,name=can_signup,json=canSignup,proto3" json:"can_signup,omitempty"`
	MugId     string `protobuf:"bytes,6,opt,name=mug_id,json=mugId,proto3" json:"mug_id,omitempty"`
}

func (x *WaitlistSignup) Reset() {
	*x = WaitlistSignup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_admin_v1_backend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitlistSignup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitlistSignup) ProtoMessage() {}

func (x *WaitlistSignup) ProtoReflect() protoreflect.Message {
	mi := &file_backend_admin_v1_backend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitlistSignup.ProtoReflect.Descriptor instead.
func (*WaitlistSignup) Descriptor() ([]byte, []int) {
	return file_backend_admin_v1_backend_proto_rawDescGZIP(), []int{3}
}

func (x *WaitlistSignup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WaitlistSignup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WaitlistSignup) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *WaitlistSignup) GetBetaOptIn() bool {
	if x != nil {
		return x.BetaOptIn
	}
	return false
}

func (x *WaitlistSignup) GetCanSignup() bool {
	if x != nil {
		return x.CanSignup
	}
	return false
}

func (x *WaitlistSignup) GetMugId() string {
	if x != nil {
		return x.MugId
	}
	return ""
}

var File_backend_admin_v1_backend_proto protoreflect.FileDescriptor

var file_backend_admin_v1_backend_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f,
	0x76, 0x31, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x15, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x64,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2c, 0x0a, 0x1a, 0x41, 0x6c, 0x6c,
	0x6f, 0x77, 0x57, 0x61, 0x69, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x61, 0x69, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x6c,
	0x69, 0x73, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x75,
	0x70, 0x73, 0x22, 0xa0, 0x01, 0x0a, 0x0e, 0x57, 0x61, 0x69, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x53,
	0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1e, 0x0a, 0x0b, 0x62, 0x65, 0x74, 0x61, 0x5f, 0x6f, 0x70, 0x74, 0x5f, 0x69, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x65, 0x74, 0x61, 0x4f, 0x70, 0x74, 0x49, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6e, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x15,
	0x0a, 0x06, 0x6d, 0x75, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6d, 0x75, 0x67, 0x49, 0x64, 0x32, 0xc5, 0x01, 0x0a, 0x07, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x12, 0x5c, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x69, 0x74, 0x6c, 0x69, 0x73,
	0x74, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x2d, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x69, 0x74, 0x6c, 0x69, 0x73, 0x74,
	0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5c, 0x0a, 0x13, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x57, 0x61, 0x69, 0x74, 0x6c, 0x69, 0x73, 0x74,
	0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x2c, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x57,
	0x61, 0x69, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x1a, 0x5a,
	0x18, 0x2e, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2f, 0x76, 0x31, 0x3b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_backend_admin_v1_backend_proto_rawDescOnce sync.Once
	file_backend_admin_v1_backend_proto_rawDescData = file_backend_admin_v1_backend_proto_rawDesc
)

func file_backend_admin_v1_backend_proto_rawDescGZIP() []byte {
	file_backend_admin_v1_backend_proto_rawDescOnce.Do(func() {
		file_backend_admin_v1_backend_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_admin_v1_backend_proto_rawDescData)
	})
	return file_backend_admin_v1_backend_proto_rawDescData
}

var file_backend_admin_v1_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_backend_admin_v1_backend_proto_goTypes = []interface{}{
	(*Empty)(nil),                       // 0: backend.admin.v1.Empty
	(*AllowWaitlistSignupRequest)(nil),  // 1: backend.admin.v1.AllowWaitlistSignupRequest
	(*ListWaitlistSignupsResponse)(nil), // 2: backend.admin.v1.ListWaitlistSignupsResponse
	(*WaitlistSignup)(nil),              // 3: backend.admin.v1.WaitlistSignup
	(*emptypb.Empty)(nil),               // 4: google.protobuf.Empty
}
var file_backend_admin_v1_backend_proto_depIdxs = []int32{
	3, // 0: backend.admin.v1.ListWaitlistSignupsResponse.signups:type_name -> backend.admin.v1.WaitlistSignup
	4, // 1: backend.admin.v1.Backend.ListWaitlistSignups:input_type -> google.protobuf.Empty
	1, // 2: backend.admin.v1.Backend.AllowWaitlistSignup:input_type -> backend.admin.v1.AllowWaitlistSignupRequest
	2, // 3: backend.admin.v1.Backend.ListWaitlistSignups:output_type -> backend.admin.v1.ListWaitlistSignupsResponse
	0, // 4: backend.admin.v1.Backend.AllowWaitlistSignup:output_type -> backend.admin.v1.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_backend_admin_v1_backend_proto_init() }
func file_backend_admin_v1_backend_proto_init() {
	if File_backend_admin_v1_backend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backend_admin_v1_backend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_admin_v1_backend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowWaitlistSignupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_admin_v1_backend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWaitlistSignupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_admin_v1_backend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitlistSignup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_admin_v1_backend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_admin_v1_backend_proto_goTypes,
		DependencyIndexes: file_backend_admin_v1_backend_proto_depIdxs,
		MessageInfos:      file_backend_admin_v1_backend_proto_msgTypes,
	}.Build()
	File_backend_admin_v1_backend_proto = out.File
	file_backend_admin_v1_backend_proto_rawDesc = nil
	file_backend_admin_v1_backend_proto_goTypes = nil
	file_backend_admin_v1_backend_proto_depIdxs = nil
}
