// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: backend/admin/v1/backend.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Backend_ListWaitlistSignups_FullMethodName                = "/backend.admin.v1.Backend/ListWaitlistSignups"
	Backend_AllowWaitlistSignup_FullMethodName                = "/backend.admin.v1.Backend/AllowWaitlistSignup"
	Backend_ListWallets_FullMethodName                        = "/backend.admin.v1.Backend/ListWallets"
	Backend_GetWalletDetails_FullMethodName                   = "/backend.admin.v1.Backend/GetWalletDetails"
	Backend_ListTransactions_FullMethodName                   = "/backend.admin.v1.Backend/ListTransactions"
	Backend_GetTransactionDetails_FullMethodName              = "/backend.admin.v1.Backend/GetTransactionDetails"
	Backend_ListLinkedAccounts_FullMethodName                 = "/backend.admin.v1.Backend/ListLinkedAccounts"
	Backend_ListAudit_FullMethodName                          = "/backend.admin.v1.Backend/ListAudit"
	Backend_GetWalletFeatures_FullMethodName                  = "/backend.admin.v1.Backend/GetWalletFeatures"
	Backend_SetWalletFeatures_FullMethodName                  = "/backend.admin.v1.Backend/SetWalletFeatures"
	Backend_ListIncompleteLinkedAccountReviews_FullMethodName = "/backend.admin.v1.Backend/ListIncompleteLinkedAccountReviews"
	Backend_GetLinkedAccountReview_FullMethodName             = "/backend.admin.v1.Backend/GetLinkedAccountReview"
	Backend_CompleteLinkedAccountReview_FullMethodName        = "/backend.admin.v1.Backend/CompleteLinkedAccountReview"
	Backend_GetLinkedAccount_FullMethodName                   = "/backend.admin.v1.Backend/GetLinkedAccount"
	Backend_ListDynamicFormCounts_FullMethodName              = "/backend.admin.v1.Backend/ListDynamicFormCounts"
	Backend_ExportDynamicForm_FullMethodName                  = "/backend.admin.v1.Backend/ExportDynamicForm"
	Backend_ListExternalApiCalls_FullMethodName               = "/backend.admin.v1.Backend/ListExternalApiCalls"
)

// BackendClient is the client API for Backend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendClient interface {
	ListWaitlistSignups(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListWaitlistSignupsResponse, error)
	AllowWaitlistSignup(ctx context.Context, in *AllowWaitlistSignupRequest, opts ...grpc.CallOption) (*Empty, error)
	ListWallets(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*ListWalletsResponse, error)
	GetWalletDetails(ctx context.Context, in *GetWalletDetailsRequest, opts ...grpc.CallOption) (*WalletDetails, error)
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	GetTransactionDetails(ctx context.Context, in *GetTransactionDetailsRequest, opts ...grpc.CallOption) (*GetTransactionDetailsResponse, error)
	ListLinkedAccounts(ctx context.Context, in *ListLinkedAccountsRequest, opts ...grpc.CallOption) (*ListLinkedAccountsResponse, error)
	ListAudit(ctx context.Context, in *ListAuditRequest, opts ...grpc.CallOption) (*ListAuditResponse, error)
	GetWalletFeatures(ctx context.Context, in *GetWalletFeaturesRequest, opts ...grpc.CallOption) (*Features, error)
	SetWalletFeatures(ctx context.Context, in *Features, opts ...grpc.CallOption) (*Features, error)
	ListIncompleteLinkedAccountReviews(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*LinkedAccountReviews, error)
	GetLinkedAccountReview(ctx context.Context, in *GetLinkedAccountReviewRequest, opts ...grpc.CallOption) (*LinkedAccountReview, error)
	CompleteLinkedAccountReview(ctx context.Context, in *CompleteLinkedAccountReviewRequest, opts ...grpc.CallOption) (*LinkedAccountReview, error)
	GetLinkedAccount(ctx context.Context, in *GetLinkedAccountRequest, opts ...grpc.CallOption) (*LinkedAccount, error)
	ListDynamicFormCounts(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*ListDynamicFormCountsResponse, error)
	ExportDynamicForm(ctx context.Context, in *ExportDynamicFormRequest, opts ...grpc.CallOption) (Backend_ExportDynamicFormClient, error)
	ListExternalApiCalls(ctx context.Context, in *ListExternalApiCallsRequest, opts ...grpc.CallOption) (*ListExternalApiCallsResponse, error)
}

type backendClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendClient(cc grpc.ClientConnInterface) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) ListWaitlistSignups(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListWaitlistSignupsResponse, error) {
	out := new(ListWaitlistSignupsResponse)
	err := c.cc.Invoke(ctx, Backend_ListWaitlistSignups_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) AllowWaitlistSignup(ctx context.Context, in *AllowWaitlistSignupRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Backend_AllowWaitlistSignup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListWallets(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*ListWalletsResponse, error) {
	out := new(ListWalletsResponse)
	err := c.cc.Invoke(ctx, Backend_ListWallets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetWalletDetails(ctx context.Context, in *GetWalletDetailsRequest, opts ...grpc.CallOption) (*WalletDetails, error) {
	out := new(WalletDetails)
	err := c.cc.Invoke(ctx, Backend_GetWalletDetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, Backend_ListTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetTransactionDetails(ctx context.Context, in *GetTransactionDetailsRequest, opts ...grpc.CallOption) (*GetTransactionDetailsResponse, error) {
	out := new(GetTransactionDetailsResponse)
	err := c.cc.Invoke(ctx, Backend_GetTransactionDetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListLinkedAccounts(ctx context.Context, in *ListLinkedAccountsRequest, opts ...grpc.CallOption) (*ListLinkedAccountsResponse, error) {
	out := new(ListLinkedAccountsResponse)
	err := c.cc.Invoke(ctx, Backend_ListLinkedAccounts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListAudit(ctx context.Context, in *ListAuditRequest, opts ...grpc.CallOption) (*ListAuditResponse, error) {
	out := new(ListAuditResponse)
	err := c.cc.Invoke(ctx, Backend_ListAudit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetWalletFeatures(ctx context.Context, in *GetWalletFeaturesRequest, opts ...grpc.CallOption) (*Features, error) {
	out := new(Features)
	err := c.cc.Invoke(ctx, Backend_GetWalletFeatures_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) SetWalletFeatures(ctx context.Context, in *Features, opts ...grpc.CallOption) (*Features, error) {
	out := new(Features)
	err := c.cc.Invoke(ctx, Backend_SetWalletFeatures_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListIncompleteLinkedAccountReviews(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*LinkedAccountReviews, error) {
	out := new(LinkedAccountReviews)
	err := c.cc.Invoke(ctx, Backend_ListIncompleteLinkedAccountReviews_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetLinkedAccountReview(ctx context.Context, in *GetLinkedAccountReviewRequest, opts ...grpc.CallOption) (*LinkedAccountReview, error) {
	out := new(LinkedAccountReview)
	err := c.cc.Invoke(ctx, Backend_GetLinkedAccountReview_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) CompleteLinkedAccountReview(ctx context.Context, in *CompleteLinkedAccountReviewRequest, opts ...grpc.CallOption) (*LinkedAccountReview, error) {
	out := new(LinkedAccountReview)
	err := c.cc.Invoke(ctx, Backend_CompleteLinkedAccountReview_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetLinkedAccount(ctx context.Context, in *GetLinkedAccountRequest, opts ...grpc.CallOption) (*LinkedAccount, error) {
	out := new(LinkedAccount)
	err := c.cc.Invoke(ctx, Backend_GetLinkedAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListDynamicFormCounts(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*ListDynamicFormCountsResponse, error) {
	out := new(ListDynamicFormCountsResponse)
	err := c.cc.Invoke(ctx, Backend_ListDynamicFormCounts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ExportDynamicForm(ctx context.Context, in *ExportDynamicFormRequest, opts ...grpc.CallOption) (Backend_ExportDynamicFormClient, error) {
	stream, err := c.cc.NewStream(ctx, &Backend_ServiceDesc.Streams[0], Backend_ExportDynamicForm_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &backendExportDynamicFormClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Backend_ExportDynamicFormClient interface {
	Recv() (*ExportDynamicFormResponse, error)
	grpc.ClientStream
}

type backendExportDynamicFormClient struct {
	grpc.ClientStream
}

func (x *backendExportDynamicFormClient) Recv() (*ExportDynamicFormResponse, error) {
	m := new(ExportDynamicFormResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *backendClient) ListExternalApiCalls(ctx context.Context, in *ListExternalApiCallsRequest, opts ...grpc.CallOption) (*ListExternalApiCallsResponse, error) {
	out := new(ListExternalApiCallsResponse)
	err := c.cc.Invoke(ctx, Backend_ListExternalApiCalls_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServer is the server API for Backend service.
// All implementations should embed UnimplementedBackendServer
// for forward compatibility
type BackendServer interface {
	ListWaitlistSignups(context.Context, *emptypb.Empty) (*ListWaitlistSignupsResponse, error)
	AllowWaitlistSignup(context.Context, *AllowWaitlistSignupRequest) (*Empty, error)
	ListWallets(context.Context, *PaginationRequest) (*ListWalletsResponse, error)
	GetWalletDetails(context.Context, *GetWalletDetailsRequest) (*WalletDetails, error)
	ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error)
	GetTransactionDetails(context.Context, *GetTransactionDetailsRequest) (*GetTransactionDetailsResponse, error)
	ListLinkedAccounts(context.Context, *ListLinkedAccountsRequest) (*ListLinkedAccountsResponse, error)
	ListAudit(context.Context, *ListAuditRequest) (*ListAuditResponse, error)
	GetWalletFeatures(context.Context, *GetWalletFeaturesRequest) (*Features, error)
	SetWalletFeatures(context.Context, *Features) (*Features, error)
	ListIncompleteLinkedAccountReviews(context.Context, *PaginationRequest) (*LinkedAccountReviews, error)
	GetLinkedAccountReview(context.Context, *GetLinkedAccountReviewRequest) (*LinkedAccountReview, error)
	CompleteLinkedAccountReview(context.Context, *CompleteLinkedAccountReviewRequest) (*LinkedAccountReview, error)
	GetLinkedAccount(context.Context, *GetLinkedAccountRequest) (*LinkedAccount, error)
	ListDynamicFormCounts(context.Context, *PaginationRequest) (*ListDynamicFormCountsResponse, error)
	ExportDynamicForm(*ExportDynamicFormRequest, Backend_ExportDynamicFormServer) error
	ListExternalApiCalls(context.Context, *ListExternalApiCallsRequest) (*ListExternalApiCallsResponse, error)
}

// UnimplementedBackendServer should be embedded to have forward compatible implementations.
type UnimplementedBackendServer struct {
}

func (UnimplementedBackendServer) ListWaitlistSignups(context.Context, *emptypb.Empty) (*ListWaitlistSignupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWaitlistSignups not implemented")
}
func (UnimplementedBackendServer) AllowWaitlistSignup(context.Context, *AllowWaitlistSignupRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllowWaitlistSignup not implemented")
}
func (UnimplementedBackendServer) ListWallets(context.Context, *PaginationRequest) (*ListWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWallets not implemented")
}
func (UnimplementedBackendServer) GetWalletDetails(context.Context, *GetWalletDetailsRequest) (*WalletDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletDetails not implemented")
}
func (UnimplementedBackendServer) ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedBackendServer) GetTransactionDetails(context.Context, *GetTransactionDetailsRequest) (*GetTransactionDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionDetails not implemented")
}
func (UnimplementedBackendServer) ListLinkedAccounts(context.Context, *ListLinkedAccountsRequest) (*ListLinkedAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLinkedAccounts not implemented")
}
func (UnimplementedBackendServer) ListAudit(context.Context, *ListAuditRequest) (*ListAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAudit not implemented")
}
func (UnimplementedBackendServer) GetWalletFeatures(context.Context, *GetWalletFeaturesRequest) (*Features, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletFeatures not implemented")
}
func (UnimplementedBackendServer) SetWalletFeatures(context.Context, *Features) (*Features, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetWalletFeatures not implemented")
}
func (UnimplementedBackendServer) ListIncompleteLinkedAccountReviews(context.Context, *PaginationRequest) (*LinkedAccountReviews, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIncompleteLinkedAccountReviews not implemented")
}
func (UnimplementedBackendServer) GetLinkedAccountReview(context.Context, *GetLinkedAccountReviewRequest) (*LinkedAccountReview, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinkedAccountReview not implemented")
}
func (UnimplementedBackendServer) CompleteLinkedAccountReview(context.Context, *CompleteLinkedAccountReviewRequest) (*LinkedAccountReview, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteLinkedAccountReview not implemented")
}
func (UnimplementedBackendServer) GetLinkedAccount(context.Context, *GetLinkedAccountRequest) (*LinkedAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinkedAccount not implemented")
}
func (UnimplementedBackendServer) ListDynamicFormCounts(context.Context, *PaginationRequest) (*ListDynamicFormCountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDynamicFormCounts not implemented")
}
func (UnimplementedBackendServer) ExportDynamicForm(*ExportDynamicFormRequest, Backend_ExportDynamicFormServer) error {
	return status.Errorf(codes.Unimplemented, "method ExportDynamicForm not implemented")
}
func (UnimplementedBackendServer) ListExternalApiCalls(context.Context, *ListExternalApiCallsRequest) (*ListExternalApiCallsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExternalApiCalls not implemented")
}

// UnsafeBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendServer will
// result in compilation errors.
type UnsafeBackendServer interface {
	mustEmbedUnimplementedBackendServer()
}

func RegisterBackendServer(s grpc.ServiceRegistrar, srv BackendServer) {
	s.RegisterService(&Backend_ServiceDesc, srv)
}

func _Backend_ListWaitlistSignups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListWaitlistSignups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListWaitlistSignups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListWaitlistSignups(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_AllowWaitlistSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowWaitlistSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).AllowWaitlistSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_AllowWaitlistSignup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).AllowWaitlistSignup(ctx, req.(*AllowWaitlistSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListWallets(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetWalletDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetWalletDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetWalletDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetWalletDetails(ctx, req.(*GetWalletDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListTransactions(ctx, req.(*ListTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetTransactionDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetTransactionDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetTransactionDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetTransactionDetails(ctx, req.(*GetTransactionDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListLinkedAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinkedAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListLinkedAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListLinkedAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListLinkedAccounts(ctx, req.(*ListLinkedAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListAudit(ctx, req.(*ListAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetWalletFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetWalletFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetWalletFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetWalletFeatures(ctx, req.(*GetWalletFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_SetWalletFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Features)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).SetWalletFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_SetWalletFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).SetWalletFeatures(ctx, req.(*Features))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListIncompleteLinkedAccountReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListIncompleteLinkedAccountReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListIncompleteLinkedAccountReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListIncompleteLinkedAccountReviews(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetLinkedAccountReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkedAccountReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetLinkedAccountReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetLinkedAccountReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetLinkedAccountReview(ctx, req.(*GetLinkedAccountReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_CompleteLinkedAccountReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteLinkedAccountReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).CompleteLinkedAccountReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_CompleteLinkedAccountReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).CompleteLinkedAccountReview(ctx, req.(*CompleteLinkedAccountReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetLinkedAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkedAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetLinkedAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetLinkedAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetLinkedAccount(ctx, req.(*GetLinkedAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListDynamicFormCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListDynamicFormCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListDynamicFormCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListDynamicFormCounts(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ExportDynamicForm_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportDynamicFormRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BackendServer).ExportDynamicForm(m, &backendExportDynamicFormServer{stream})
}

type Backend_ExportDynamicFormServer interface {
	Send(*ExportDynamicFormResponse) error
	grpc.ServerStream
}

type backendExportDynamicFormServer struct {
	grpc.ServerStream
}

func (x *backendExportDynamicFormServer) Send(m *ExportDynamicFormResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Backend_ListExternalApiCalls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExternalApiCallsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListExternalApiCalls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListExternalApiCalls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListExternalApiCalls(ctx, req.(*ListExternalApiCallsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Backend_ServiceDesc is the grpc.ServiceDesc for Backend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.admin.v1.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWaitlistSignups",
			Handler:    _Backend_ListWaitlistSignups_Handler,
		},
		{
			MethodName: "AllowWaitlistSignup",
			Handler:    _Backend_AllowWaitlistSignup_Handler,
		},
		{
			MethodName: "ListWallets",
			Handler:    _Backend_ListWallets_Handler,
		},
		{
			MethodName: "GetWalletDetails",
			Handler:    _Backend_GetWalletDetails_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _Backend_ListTransactions_Handler,
		},
		{
			MethodName: "GetTransactionDetails",
			Handler:    _Backend_GetTransactionDetails_Handler,
		},
		{
			MethodName: "ListLinkedAccounts",
			Handler:    _Backend_ListLinkedAccounts_Handler,
		},
		{
			MethodName: "ListAudit",
			Handler:    _Backend_ListAudit_Handler,
		},
		{
			MethodName: "GetWalletFeatures",
			Handler:    _Backend_GetWalletFeatures_Handler,
		},
		{
			MethodName: "SetWalletFeatures",
			Handler:    _Backend_SetWalletFeatures_Handler,
		},
		{
			MethodName: "ListIncompleteLinkedAccountReviews",
			Handler:    _Backend_ListIncompleteLinkedAccountReviews_Handler,
		},
		{
			MethodName: "GetLinkedAccountReview",
			Handler:    _Backend_GetLinkedAccountReview_Handler,
		},
		{
			MethodName: "CompleteLinkedAccountReview",
			Handler:    _Backend_CompleteLinkedAccountReview_Handler,
		},
		{
			MethodName: "GetLinkedAccount",
			Handler:    _Backend_GetLinkedAccount_Handler,
		},
		{
			MethodName: "ListDynamicFormCounts",
			Handler:    _Backend_ListDynamicFormCounts_Handler,
		},
		{
			MethodName: "ListExternalApiCalls",
			Handler:    _Backend_ListExternalApiCalls_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportDynamicForm",
			Handler:       _Backend_ExportDynamicForm_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "backend/admin/v1/backend.proto",
}
