// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: backend/v1/backend.proto

package backend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BackendAdminServiceClient is the client API for BackendAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendAdminServiceClient interface {
	GetUserAccountByEmail(ctx context.Context, in *GetUserAccountByEmailRequest, opts ...grpc.CallOption) (*Account, error)
}

type backendAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendAdminServiceClient(cc grpc.ClientConnInterface) BackendAdminServiceClient {
	return &backendAdminServiceClient{cc}
}

func (c *backendAdminServiceClient) GetUserAccountByEmail(ctx context.Context, in *GetUserAccountByEmailRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendAdminService/GetUserAccountByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendAdminServiceServer is the server API for BackendAdminService service.
// All implementations should embed UnimplementedBackendAdminServiceServer
// for forward compatibility
type BackendAdminServiceServer interface {
	GetUserAccountByEmail(context.Context, *GetUserAccountByEmailRequest) (*Account, error)
}

// UnimplementedBackendAdminServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBackendAdminServiceServer struct {
}

func (UnimplementedBackendAdminServiceServer) GetUserAccountByEmail(context.Context, *GetUserAccountByEmailRequest) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAccountByEmail not implemented")
}

// UnsafeBackendAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendAdminServiceServer will
// result in compilation errors.
type UnsafeBackendAdminServiceServer interface {
	mustEmbedUnimplementedBackendAdminServiceServer()
}

func RegisterBackendAdminServiceServer(s grpc.ServiceRegistrar, srv BackendAdminServiceServer) {
	s.RegisterService(&BackendAdminService_ServiceDesc, srv)
}

func _BackendAdminService_GetUserAccountByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAccountByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendAdminServiceServer).GetUserAccountByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendAdminService/GetUserAccountByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendAdminServiceServer).GetUserAccountByEmail(ctx, req.(*GetUserAccountByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendAdminService_ServiceDesc is the grpc.ServiceDesc for BackendAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.v1.BackendAdminService",
	HandlerType: (*BackendAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserAccountByEmail",
			Handler:    _BackendAdminService_GetUserAccountByEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/v1/backend.proto",
}

// BackendServiceClient is the client API for BackendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendServiceClient interface {
	GetBankAccountWidget(ctx context.Context, in *GetBankAccountWidgetRequest, opts ...grpc.CallOption) (*GetBankAccountWidgetResponse, error)
	AddBankAccount(ctx context.Context, in *AddBankAccountRequest, opts ...grpc.CallOption) (*AddBankAccountResponse, error)
	GetBankAccountDetails(ctx context.Context, in *GetBankAccountDetailsRequest, opts ...grpc.CallOption) (*BankAccountDetails, error)
	ContinueAddingBankAccount(ctx context.Context, in *ContinueAddingBankAccountRequest, opts ...grpc.CallOption) (*ContinueAddingBankAccountResponse, error)
	// Returns the current onboarding flow.
	GetOnboarding(ctx context.Context, in *GetOnboardingRequest, opts ...grpc.CallOption) (*Onboarding, error)
	// Creates the onboarding flow if it does not already exist.
	UpdateOnboarding(ctx context.Context, in *Onboarding, opts ...grpc.CallOption) (*Onboarding, error)
	// Creates a user identity, with the data in onboarding.
	CreateIdentity(ctx context.Context, in *CreateIdentityRequest, opts ...grpc.CallOption) (*CreateIdentityResponse, error)
	GetIdentity(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserIdentity, error)
	// Allows sending and checking an sms verification.
	SendPhoneVerification(ctx context.Context, in *SendPhoneVerificationRequest, opts ...grpc.CallOption) (*PhoneVerificationResponse, error)
	CheckPhoneVerificationCode(ctx context.Context, in *CheckPhoneVerificationCodeRequest, opts ...grpc.CallOption) (*PhoneVerificationResponse, error)
	SendOTP(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Allows signing agreements and getting agreements by id.
	GetAgreement(ctx context.Context, in *GetAgreementRequest, opts ...grpc.CallOption) (*Agreement, error)
	SignAgreements(ctx context.Context, in *SignAgreementsRequest, opts ...grpc.CallOption) (*SignAgreementsResponse, error)
	JoinWaitlist(ctx context.Context, in *JoinWaitlistRequest, opts ...grpc.CallOption) (*JoinWaitlistResponse, error)
	GetFundingsources(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetFundingsourcesResponse, error)
	CreateSupportTicket(ctx context.Context, in *CreateSupportTicketRequest, opts ...grpc.CallOption) (*Empty, error)
	GetCountries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCountriesResponse, error)
}

type backendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendServiceClient(cc grpc.ClientConnInterface) BackendServiceClient {
	return &backendServiceClient{cc}
}

func (c *backendServiceClient) GetBankAccountWidget(ctx context.Context, in *GetBankAccountWidgetRequest, opts ...grpc.CallOption) (*GetBankAccountWidgetResponse, error) {
	out := new(GetBankAccountWidgetResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetBankAccountWidget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) AddBankAccount(ctx context.Context, in *AddBankAccountRequest, opts ...grpc.CallOption) (*AddBankAccountResponse, error) {
	out := new(AddBankAccountResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/AddBankAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetBankAccountDetails(ctx context.Context, in *GetBankAccountDetailsRequest, opts ...grpc.CallOption) (*BankAccountDetails, error) {
	out := new(BankAccountDetails)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetBankAccountDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) ContinueAddingBankAccount(ctx context.Context, in *ContinueAddingBankAccountRequest, opts ...grpc.CallOption) (*ContinueAddingBankAccountResponse, error) {
	out := new(ContinueAddingBankAccountResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/ContinueAddingBankAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetOnboarding(ctx context.Context, in *GetOnboardingRequest, opts ...grpc.CallOption) (*Onboarding, error) {
	out := new(Onboarding)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetOnboarding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) UpdateOnboarding(ctx context.Context, in *Onboarding, opts ...grpc.CallOption) (*Onboarding, error) {
	out := new(Onboarding)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/UpdateOnboarding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) CreateIdentity(ctx context.Context, in *CreateIdentityRequest, opts ...grpc.CallOption) (*CreateIdentityResponse, error) {
	out := new(CreateIdentityResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/CreateIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetIdentity(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserIdentity, error) {
	out := new(UserIdentity)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) SendPhoneVerification(ctx context.Context, in *SendPhoneVerificationRequest, opts ...grpc.CallOption) (*PhoneVerificationResponse, error) {
	out := new(PhoneVerificationResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/SendPhoneVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) CheckPhoneVerificationCode(ctx context.Context, in *CheckPhoneVerificationCodeRequest, opts ...grpc.CallOption) (*PhoneVerificationResponse, error) {
	out := new(PhoneVerificationResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/CheckPhoneVerificationCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) SendOTP(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/SendOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetAgreement(ctx context.Context, in *GetAgreementRequest, opts ...grpc.CallOption) (*Agreement, error) {
	out := new(Agreement)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetAgreement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) SignAgreements(ctx context.Context, in *SignAgreementsRequest, opts ...grpc.CallOption) (*SignAgreementsResponse, error) {
	out := new(SignAgreementsResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/SignAgreements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) JoinWaitlist(ctx context.Context, in *JoinWaitlistRequest, opts ...grpc.CallOption) (*JoinWaitlistResponse, error) {
	out := new(JoinWaitlistResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/JoinWaitlist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetFundingsources(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetFundingsourcesResponse, error) {
	out := new(GetFundingsourcesResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetFundingsources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) CreateSupportTicket(ctx context.Context, in *CreateSupportTicketRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/CreateSupportTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetCountries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCountriesResponse, error) {
	out := new(GetCountriesResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetCountries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServiceServer is the server API for BackendService service.
// All implementations should embed UnimplementedBackendServiceServer
// for forward compatibility
type BackendServiceServer interface {
	GetBankAccountWidget(context.Context, *GetBankAccountWidgetRequest) (*GetBankAccountWidgetResponse, error)
	AddBankAccount(context.Context, *AddBankAccountRequest) (*AddBankAccountResponse, error)
	GetBankAccountDetails(context.Context, *GetBankAccountDetailsRequest) (*BankAccountDetails, error)
	ContinueAddingBankAccount(context.Context, *ContinueAddingBankAccountRequest) (*ContinueAddingBankAccountResponse, error)
	// Returns the current onboarding flow.
	GetOnboarding(context.Context, *GetOnboardingRequest) (*Onboarding, error)
	// Creates the onboarding flow if it does not already exist.
	UpdateOnboarding(context.Context, *Onboarding) (*Onboarding, error)
	// Creates a user identity, with the data in onboarding.
	CreateIdentity(context.Context, *CreateIdentityRequest) (*CreateIdentityResponse, error)
	GetIdentity(context.Context, *Empty) (*UserIdentity, error)
	// Allows sending and checking an sms verification.
	SendPhoneVerification(context.Context, *SendPhoneVerificationRequest) (*PhoneVerificationResponse, error)
	CheckPhoneVerificationCode(context.Context, *CheckPhoneVerificationCodeRequest) (*PhoneVerificationResponse, error)
	SendOTP(context.Context, *Empty) (*Empty, error)
	// Allows signing agreements and getting agreements by id.
	GetAgreement(context.Context, *GetAgreementRequest) (*Agreement, error)
	SignAgreements(context.Context, *SignAgreementsRequest) (*SignAgreementsResponse, error)
	JoinWaitlist(context.Context, *JoinWaitlistRequest) (*JoinWaitlistResponse, error)
	GetFundingsources(context.Context, *Empty) (*GetFundingsourcesResponse, error)
	CreateSupportTicket(context.Context, *CreateSupportTicketRequest) (*Empty, error)
	GetCountries(context.Context, *Empty) (*GetCountriesResponse, error)
}

// UnimplementedBackendServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBackendServiceServer struct {
}

func (UnimplementedBackendServiceServer) GetBankAccountWidget(context.Context, *GetBankAccountWidgetRequest) (*GetBankAccountWidgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankAccountWidget not implemented")
}
func (UnimplementedBackendServiceServer) AddBankAccount(context.Context, *AddBankAccountRequest) (*AddBankAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBankAccount not implemented")
}
func (UnimplementedBackendServiceServer) GetBankAccountDetails(context.Context, *GetBankAccountDetailsRequest) (*BankAccountDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankAccountDetails not implemented")
}
func (UnimplementedBackendServiceServer) ContinueAddingBankAccount(context.Context, *ContinueAddingBankAccountRequest) (*ContinueAddingBankAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContinueAddingBankAccount not implemented")
}
func (UnimplementedBackendServiceServer) GetOnboarding(context.Context, *GetOnboardingRequest) (*Onboarding, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnboarding not implemented")
}
func (UnimplementedBackendServiceServer) UpdateOnboarding(context.Context, *Onboarding) (*Onboarding, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOnboarding not implemented")
}
func (UnimplementedBackendServiceServer) CreateIdentity(context.Context, *CreateIdentityRequest) (*CreateIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIdentity not implemented")
}
func (UnimplementedBackendServiceServer) GetIdentity(context.Context, *Empty) (*UserIdentity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentity not implemented")
}
func (UnimplementedBackendServiceServer) SendPhoneVerification(context.Context, *SendPhoneVerificationRequest) (*PhoneVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPhoneVerification not implemented")
}
func (UnimplementedBackendServiceServer) CheckPhoneVerificationCode(context.Context, *CheckPhoneVerificationCodeRequest) (*PhoneVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPhoneVerificationCode not implemented")
}
func (UnimplementedBackendServiceServer) SendOTP(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOTP not implemented")
}
func (UnimplementedBackendServiceServer) GetAgreement(context.Context, *GetAgreementRequest) (*Agreement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgreement not implemented")
}
func (UnimplementedBackendServiceServer) SignAgreements(context.Context, *SignAgreementsRequest) (*SignAgreementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignAgreements not implemented")
}
func (UnimplementedBackendServiceServer) JoinWaitlist(context.Context, *JoinWaitlistRequest) (*JoinWaitlistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinWaitlist not implemented")
}
func (UnimplementedBackendServiceServer) GetFundingsources(context.Context, *Empty) (*GetFundingsourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFundingsources not implemented")
}
func (UnimplementedBackendServiceServer) CreateSupportTicket(context.Context, *CreateSupportTicketRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSupportTicket not implemented")
}
func (UnimplementedBackendServiceServer) GetCountries(context.Context, *Empty) (*GetCountriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountries not implemented")
}

// UnsafeBackendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendServiceServer will
// result in compilation errors.
type UnsafeBackendServiceServer interface {
	mustEmbedUnimplementedBackendServiceServer()
}

func RegisterBackendServiceServer(s grpc.ServiceRegistrar, srv BackendServiceServer) {
	s.RegisterService(&BackendService_ServiceDesc, srv)
}

func _BackendService_GetBankAccountWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankAccountWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetBankAccountWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetBankAccountWidget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetBankAccountWidget(ctx, req.(*GetBankAccountWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_AddBankAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBankAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).AddBankAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/AddBankAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).AddBankAccount(ctx, req.(*AddBankAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetBankAccountDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankAccountDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetBankAccountDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetBankAccountDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetBankAccountDetails(ctx, req.(*GetBankAccountDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_ContinueAddingBankAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinueAddingBankAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).ContinueAddingBankAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/ContinueAddingBankAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).ContinueAddingBankAccount(ctx, req.(*ContinueAddingBankAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetOnboarding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetOnboarding(ctx, req.(*GetOnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_UpdateOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Onboarding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).UpdateOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/UpdateOnboarding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).UpdateOnboarding(ctx, req.(*Onboarding))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_CreateIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).CreateIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/CreateIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).CreateIdentity(ctx, req.(*CreateIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetIdentity(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_SendPhoneVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPhoneVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).SendPhoneVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/SendPhoneVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).SendPhoneVerification(ctx, req.(*SendPhoneVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_CheckPhoneVerificationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPhoneVerificationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).CheckPhoneVerificationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/CheckPhoneVerificationCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).CheckPhoneVerificationCode(ctx, req.(*CheckPhoneVerificationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_SendOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).SendOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/SendOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).SendOTP(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetAgreement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetAgreement(ctx, req.(*GetAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_SignAgreements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignAgreementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).SignAgreements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/SignAgreements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).SignAgreements(ctx, req.(*SignAgreementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_JoinWaitlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinWaitlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).JoinWaitlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/JoinWaitlist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).JoinWaitlist(ctx, req.(*JoinWaitlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetFundingsources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetFundingsources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetFundingsources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetFundingsources(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_CreateSupportTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupportTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).CreateSupportTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/CreateSupportTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).CreateSupportTicket(ctx, req.(*CreateSupportTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetCountries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetCountries(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendService_ServiceDesc is the grpc.ServiceDesc for BackendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.v1.BackendService",
	HandlerType: (*BackendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBankAccountWidget",
			Handler:    _BackendService_GetBankAccountWidget_Handler,
		},
		{
			MethodName: "AddBankAccount",
			Handler:    _BackendService_AddBankAccount_Handler,
		},
		{
			MethodName: "GetBankAccountDetails",
			Handler:    _BackendService_GetBankAccountDetails_Handler,
		},
		{
			MethodName: "ContinueAddingBankAccount",
			Handler:    _BackendService_ContinueAddingBankAccount_Handler,
		},
		{
			MethodName: "GetOnboarding",
			Handler:    _BackendService_GetOnboarding_Handler,
		},
		{
			MethodName: "UpdateOnboarding",
			Handler:    _BackendService_UpdateOnboarding_Handler,
		},
		{
			MethodName: "CreateIdentity",
			Handler:    _BackendService_CreateIdentity_Handler,
		},
		{
			MethodName: "GetIdentity",
			Handler:    _BackendService_GetIdentity_Handler,
		},
		{
			MethodName: "SendPhoneVerification",
			Handler:    _BackendService_SendPhoneVerification_Handler,
		},
		{
			MethodName: "CheckPhoneVerificationCode",
			Handler:    _BackendService_CheckPhoneVerificationCode_Handler,
		},
		{
			MethodName: "SendOTP",
			Handler:    _BackendService_SendOTP_Handler,
		},
		{
			MethodName: "GetAgreement",
			Handler:    _BackendService_GetAgreement_Handler,
		},
		{
			MethodName: "SignAgreements",
			Handler:    _BackendService_SignAgreements_Handler,
		},
		{
			MethodName: "JoinWaitlist",
			Handler:    _BackendService_JoinWaitlist_Handler,
		},
		{
			MethodName: "GetFundingsources",
			Handler:    _BackendService_GetFundingsources_Handler,
		},
		{
			MethodName: "CreateSupportTicket",
			Handler:    _BackendService_CreateSupportTicket_Handler,
		},
		{
			MethodName: "GetCountries",
			Handler:    _BackendService_GetCountries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/v1/backend.proto",
}
