// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: backend/v1/backend.proto

package backend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BackendAdminServiceClient is the client API for BackendAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendAdminServiceClient interface {
	GetUserAccountByEmail(ctx context.Context, in *GetUserAccountByEmailRequest, opts ...grpc.CallOption) (*Account, error)
}

type backendAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendAdminServiceClient(cc grpc.ClientConnInterface) BackendAdminServiceClient {
	return &backendAdminServiceClient{cc}
}

func (c *backendAdminServiceClient) GetUserAccountByEmail(ctx context.Context, in *GetUserAccountByEmailRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendAdminService/GetUserAccountByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendAdminServiceServer is the server API for BackendAdminService service.
// All implementations should embed UnimplementedBackendAdminServiceServer
// for forward compatibility
type BackendAdminServiceServer interface {
	GetUserAccountByEmail(context.Context, *GetUserAccountByEmailRequest) (*Account, error)
}

// UnimplementedBackendAdminServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBackendAdminServiceServer struct {
}

func (UnimplementedBackendAdminServiceServer) GetUserAccountByEmail(context.Context, *GetUserAccountByEmailRequest) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAccountByEmail not implemented")
}

// UnsafeBackendAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendAdminServiceServer will
// result in compilation errors.
type UnsafeBackendAdminServiceServer interface {
	mustEmbedUnimplementedBackendAdminServiceServer()
}

func RegisterBackendAdminServiceServer(s grpc.ServiceRegistrar, srv BackendAdminServiceServer) {
	s.RegisterService(&BackendAdminService_ServiceDesc, srv)
}

func _BackendAdminService_GetUserAccountByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAccountByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendAdminServiceServer).GetUserAccountByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendAdminService/GetUserAccountByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendAdminServiceServer).GetUserAccountByEmail(ctx, req.(*GetUserAccountByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendAdminService_ServiceDesc is the grpc.ServiceDesc for BackendAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.v1.BackendAdminService",
	HandlerType: (*BackendAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserAccountByEmail",
			Handler:    _BackendAdminService_GetUserAccountByEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/v1/backend.proto",
}

// OpenPaymentServiceClient is the client API for OpenPaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenPaymentServiceClient interface {
	CreatePaymentPointer(ctx context.Context, in *CreatePaymentPointerRequest, opts ...grpc.CallOption) (*Empty, error)
	GetPaymentPointer(ctx context.Context, in *GetPaymentPointerRequest, opts ...grpc.CallOption) (*PaymentPointer, error)
	PaymentPointerExists(ctx context.Context, in *PaymentPointerExistsRequest, opts ...grpc.CallOption) (*PaymentPointerExistsResponse, error)
	ListWalletPaymentPointers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListWalletPaymentPointersResponse, error)
}

type openPaymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenPaymentServiceClient(cc grpc.ClientConnInterface) OpenPaymentServiceClient {
	return &openPaymentServiceClient{cc}
}

func (c *openPaymentServiceClient) CreatePaymentPointer(ctx context.Context, in *CreatePaymentPointerRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/backend.v1.OpenPaymentService/CreatePaymentPointer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openPaymentServiceClient) GetPaymentPointer(ctx context.Context, in *GetPaymentPointerRequest, opts ...grpc.CallOption) (*PaymentPointer, error) {
	out := new(PaymentPointer)
	err := c.cc.Invoke(ctx, "/backend.v1.OpenPaymentService/GetPaymentPointer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openPaymentServiceClient) PaymentPointerExists(ctx context.Context, in *PaymentPointerExistsRequest, opts ...grpc.CallOption) (*PaymentPointerExistsResponse, error) {
	out := new(PaymentPointerExistsResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.OpenPaymentService/PaymentPointerExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openPaymentServiceClient) ListWalletPaymentPointers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListWalletPaymentPointersResponse, error) {
	out := new(ListWalletPaymentPointersResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.OpenPaymentService/ListWalletPaymentPointers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenPaymentServiceServer is the server API for OpenPaymentService service.
// All implementations should embed UnimplementedOpenPaymentServiceServer
// for forward compatibility
type OpenPaymentServiceServer interface {
	CreatePaymentPointer(context.Context, *CreatePaymentPointerRequest) (*Empty, error)
	GetPaymentPointer(context.Context, *GetPaymentPointerRequest) (*PaymentPointer, error)
	PaymentPointerExists(context.Context, *PaymentPointerExistsRequest) (*PaymentPointerExistsResponse, error)
	ListWalletPaymentPointers(context.Context, *Empty) (*ListWalletPaymentPointersResponse, error)
}

// UnimplementedOpenPaymentServiceServer should be embedded to have forward compatible implementations.
type UnimplementedOpenPaymentServiceServer struct {
}

func (UnimplementedOpenPaymentServiceServer) CreatePaymentPointer(context.Context, *CreatePaymentPointerRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePaymentPointer not implemented")
}
func (UnimplementedOpenPaymentServiceServer) GetPaymentPointer(context.Context, *GetPaymentPointerRequest) (*PaymentPointer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentPointer not implemented")
}
func (UnimplementedOpenPaymentServiceServer) PaymentPointerExists(context.Context, *PaymentPointerExistsRequest) (*PaymentPointerExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentPointerExists not implemented")
}
func (UnimplementedOpenPaymentServiceServer) ListWalletPaymentPointers(context.Context, *Empty) (*ListWalletPaymentPointersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWalletPaymentPointers not implemented")
}

// UnsafeOpenPaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenPaymentServiceServer will
// result in compilation errors.
type UnsafeOpenPaymentServiceServer interface {
	mustEmbedUnimplementedOpenPaymentServiceServer()
}

func RegisterOpenPaymentServiceServer(s grpc.ServiceRegistrar, srv OpenPaymentServiceServer) {
	s.RegisterService(&OpenPaymentService_ServiceDesc, srv)
}

func _OpenPaymentService_CreatePaymentPointer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentPointerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenPaymentServiceServer).CreatePaymentPointer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.OpenPaymentService/CreatePaymentPointer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenPaymentServiceServer).CreatePaymentPointer(ctx, req.(*CreatePaymentPointerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenPaymentService_GetPaymentPointer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentPointerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenPaymentServiceServer).GetPaymentPointer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.OpenPaymentService/GetPaymentPointer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenPaymentServiceServer).GetPaymentPointer(ctx, req.(*GetPaymentPointerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenPaymentService_PaymentPointerExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentPointerExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenPaymentServiceServer).PaymentPointerExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.OpenPaymentService/PaymentPointerExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenPaymentServiceServer).PaymentPointerExists(ctx, req.(*PaymentPointerExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenPaymentService_ListWalletPaymentPointers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenPaymentServiceServer).ListWalletPaymentPointers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.OpenPaymentService/ListWalletPaymentPointers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenPaymentServiceServer).ListWalletPaymentPointers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// OpenPaymentService_ServiceDesc is the grpc.ServiceDesc for OpenPaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenPaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.v1.OpenPaymentService",
	HandlerType: (*OpenPaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePaymentPointer",
			Handler:    _OpenPaymentService_CreatePaymentPointer_Handler,
		},
		{
			MethodName: "GetPaymentPointer",
			Handler:    _OpenPaymentService_GetPaymentPointer_Handler,
		},
		{
			MethodName: "PaymentPointerExists",
			Handler:    _OpenPaymentService_PaymentPointerExists_Handler,
		},
		{
			MethodName: "ListWalletPaymentPointers",
			Handler:    _OpenPaymentService_ListWalletPaymentPointers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/v1/backend.proto",
}

// BackendServiceClient is the client API for BackendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendServiceClient interface {
	GetBankAccountWidget(ctx context.Context, in *GetBankAccountWidgetRequest, opts ...grpc.CallOption) (*GetBankAccountWidgetResponse, error)
	AddBankAccount(ctx context.Context, in *AddBankAccountRequest, opts ...grpc.CallOption) (*AddBankAccountResponse, error)
	GetBankAccountDetails(ctx context.Context, in *GetBankAccountDetailsRequest, opts ...grpc.CallOption) (*BankAccountDetails, error)
	ContinueAddingBankAccount(ctx context.Context, in *ContinueAddingBankAccountRequest, opts ...grpc.CallOption) (*ContinueAddingBankAccountResponse, error)
	UpdateIndividualKYC(ctx context.Context, in *UpdateIndividualKYCRequest, opts ...grpc.CallOption) (*Empty, error)
	SetSignupUserData(ctx context.Context, in *SetSignupUserDataRequest, opts ...grpc.CallOption) (*SetSignupUserDataResponse, error)
	SetSignupMobileNumber(ctx context.Context, in *SetSignupMobileNumberRequest, opts ...grpc.CallOption) (*Empty, error)
	// Returns the current signup flow.
	GetSignup(ctx context.Context, in *GetSignupRequest, opts ...grpc.CallOption) (*Signup, error)
	// Called after the user is created on Kratos with the new userID.
	CompleteSignup(ctx context.Context, in *CompleteSignupRequest, opts ...grpc.CallOption) (*Empty, error)
	CreateUserDefaultWallet(ctx context.Context, in *CreateUserDefaultWalletRequest, opts ...grpc.CallOption) (*Empty, error)
	// Allows sending and checking an sms verification.
	SendPhoneVerification(ctx context.Context, in *SendPhoneVerificationRequest, opts ...grpc.CallOption) (*Empty, error)
	SendOTP(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Allows signing agreements and getting agreements by id.
	GetAgreement(ctx context.Context, in *GetAgreementRequest, opts ...grpc.CallOption) (*Agreement, error)
	SignAgreements(ctx context.Context, in *SignAgreementsRequest, opts ...grpc.CallOption) (*SignAgreementsResponse, error)
	JoinWaitlist(ctx context.Context, in *JoinWaitlistRequest, opts ...grpc.CallOption) (*JoinWaitlistResponse, error)
	GetLinkedAccounts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetLinkedAccountsResponse, error)
	CreateSupportTicket(ctx context.Context, in *CreateSupportTicketRequest, opts ...grpc.CallOption) (*Empty, error)
	GetCountries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCountriesResponse, error)
	LinkCashAccount(ctx context.Context, in *LinkCashAccountRequest, opts ...grpc.CallOption) (*LinkedAccount, error)
	GetMachnetWidgetToken(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MachnetWidgetToken, error)
}

type backendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendServiceClient(cc grpc.ClientConnInterface) BackendServiceClient {
	return &backendServiceClient{cc}
}

func (c *backendServiceClient) GetBankAccountWidget(ctx context.Context, in *GetBankAccountWidgetRequest, opts ...grpc.CallOption) (*GetBankAccountWidgetResponse, error) {
	out := new(GetBankAccountWidgetResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetBankAccountWidget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) AddBankAccount(ctx context.Context, in *AddBankAccountRequest, opts ...grpc.CallOption) (*AddBankAccountResponse, error) {
	out := new(AddBankAccountResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/AddBankAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetBankAccountDetails(ctx context.Context, in *GetBankAccountDetailsRequest, opts ...grpc.CallOption) (*BankAccountDetails, error) {
	out := new(BankAccountDetails)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetBankAccountDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) ContinueAddingBankAccount(ctx context.Context, in *ContinueAddingBankAccountRequest, opts ...grpc.CallOption) (*ContinueAddingBankAccountResponse, error) {
	out := new(ContinueAddingBankAccountResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/ContinueAddingBankAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) UpdateIndividualKYC(ctx context.Context, in *UpdateIndividualKYCRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/UpdateIndividualKYC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) SetSignupUserData(ctx context.Context, in *SetSignupUserDataRequest, opts ...grpc.CallOption) (*SetSignupUserDataResponse, error) {
	out := new(SetSignupUserDataResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/SetSignupUserData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) SetSignupMobileNumber(ctx context.Context, in *SetSignupMobileNumberRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/SetSignupMobileNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetSignup(ctx context.Context, in *GetSignupRequest, opts ...grpc.CallOption) (*Signup, error) {
	out := new(Signup)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetSignup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) CompleteSignup(ctx context.Context, in *CompleteSignupRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/CompleteSignup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) CreateUserDefaultWallet(ctx context.Context, in *CreateUserDefaultWalletRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/CreateUserDefaultWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) SendPhoneVerification(ctx context.Context, in *SendPhoneVerificationRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/SendPhoneVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) SendOTP(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/SendOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetAgreement(ctx context.Context, in *GetAgreementRequest, opts ...grpc.CallOption) (*Agreement, error) {
	out := new(Agreement)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetAgreement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) SignAgreements(ctx context.Context, in *SignAgreementsRequest, opts ...grpc.CallOption) (*SignAgreementsResponse, error) {
	out := new(SignAgreementsResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/SignAgreements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) JoinWaitlist(ctx context.Context, in *JoinWaitlistRequest, opts ...grpc.CallOption) (*JoinWaitlistResponse, error) {
	out := new(JoinWaitlistResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/JoinWaitlist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetLinkedAccounts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetLinkedAccountsResponse, error) {
	out := new(GetLinkedAccountsResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetLinkedAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) CreateSupportTicket(ctx context.Context, in *CreateSupportTicketRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/CreateSupportTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetCountries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCountriesResponse, error) {
	out := new(GetCountriesResponse)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetCountries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) LinkCashAccount(ctx context.Context, in *LinkCashAccountRequest, opts ...grpc.CallOption) (*LinkedAccount, error) {
	out := new(LinkedAccount)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/LinkCashAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetMachnetWidgetToken(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MachnetWidgetToken, error) {
	out := new(MachnetWidgetToken)
	err := c.cc.Invoke(ctx, "/backend.v1.BackendService/GetMachnetWidgetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServiceServer is the server API for BackendService service.
// All implementations should embed UnimplementedBackendServiceServer
// for forward compatibility
type BackendServiceServer interface {
	GetBankAccountWidget(context.Context, *GetBankAccountWidgetRequest) (*GetBankAccountWidgetResponse, error)
	AddBankAccount(context.Context, *AddBankAccountRequest) (*AddBankAccountResponse, error)
	GetBankAccountDetails(context.Context, *GetBankAccountDetailsRequest) (*BankAccountDetails, error)
	ContinueAddingBankAccount(context.Context, *ContinueAddingBankAccountRequest) (*ContinueAddingBankAccountResponse, error)
	UpdateIndividualKYC(context.Context, *UpdateIndividualKYCRequest) (*Empty, error)
	SetSignupUserData(context.Context, *SetSignupUserDataRequest) (*SetSignupUserDataResponse, error)
	SetSignupMobileNumber(context.Context, *SetSignupMobileNumberRequest) (*Empty, error)
	// Returns the current signup flow.
	GetSignup(context.Context, *GetSignupRequest) (*Signup, error)
	// Called after the user is created on Kratos with the new userID.
	CompleteSignup(context.Context, *CompleteSignupRequest) (*Empty, error)
	CreateUserDefaultWallet(context.Context, *CreateUserDefaultWalletRequest) (*Empty, error)
	// Allows sending and checking an sms verification.
	SendPhoneVerification(context.Context, *SendPhoneVerificationRequest) (*Empty, error)
	SendOTP(context.Context, *Empty) (*Empty, error)
	// Allows signing agreements and getting agreements by id.
	GetAgreement(context.Context, *GetAgreementRequest) (*Agreement, error)
	SignAgreements(context.Context, *SignAgreementsRequest) (*SignAgreementsResponse, error)
	JoinWaitlist(context.Context, *JoinWaitlistRequest) (*JoinWaitlistResponse, error)
	GetLinkedAccounts(context.Context, *Empty) (*GetLinkedAccountsResponse, error)
	CreateSupportTicket(context.Context, *CreateSupportTicketRequest) (*Empty, error)
	GetCountries(context.Context, *Empty) (*GetCountriesResponse, error)
	LinkCashAccount(context.Context, *LinkCashAccountRequest) (*LinkedAccount, error)
	GetMachnetWidgetToken(context.Context, *Empty) (*MachnetWidgetToken, error)
}

// UnimplementedBackendServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBackendServiceServer struct {
}

func (UnimplementedBackendServiceServer) GetBankAccountWidget(context.Context, *GetBankAccountWidgetRequest) (*GetBankAccountWidgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankAccountWidget not implemented")
}
func (UnimplementedBackendServiceServer) AddBankAccount(context.Context, *AddBankAccountRequest) (*AddBankAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBankAccount not implemented")
}
func (UnimplementedBackendServiceServer) GetBankAccountDetails(context.Context, *GetBankAccountDetailsRequest) (*BankAccountDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankAccountDetails not implemented")
}
func (UnimplementedBackendServiceServer) ContinueAddingBankAccount(context.Context, *ContinueAddingBankAccountRequest) (*ContinueAddingBankAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContinueAddingBankAccount not implemented")
}
func (UnimplementedBackendServiceServer) UpdateIndividualKYC(context.Context, *UpdateIndividualKYCRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIndividualKYC not implemented")
}
func (UnimplementedBackendServiceServer) SetSignupUserData(context.Context, *SetSignupUserDataRequest) (*SetSignupUserDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSignupUserData not implemented")
}
func (UnimplementedBackendServiceServer) SetSignupMobileNumber(context.Context, *SetSignupMobileNumberRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSignupMobileNumber not implemented")
}
func (UnimplementedBackendServiceServer) GetSignup(context.Context, *GetSignupRequest) (*Signup, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignup not implemented")
}
func (UnimplementedBackendServiceServer) CompleteSignup(context.Context, *CompleteSignupRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteSignup not implemented")
}
func (UnimplementedBackendServiceServer) CreateUserDefaultWallet(context.Context, *CreateUserDefaultWalletRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserDefaultWallet not implemented")
}
func (UnimplementedBackendServiceServer) SendPhoneVerification(context.Context, *SendPhoneVerificationRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPhoneVerification not implemented")
}
func (UnimplementedBackendServiceServer) SendOTP(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOTP not implemented")
}
func (UnimplementedBackendServiceServer) GetAgreement(context.Context, *GetAgreementRequest) (*Agreement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgreement not implemented")
}
func (UnimplementedBackendServiceServer) SignAgreements(context.Context, *SignAgreementsRequest) (*SignAgreementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignAgreements not implemented")
}
func (UnimplementedBackendServiceServer) JoinWaitlist(context.Context, *JoinWaitlistRequest) (*JoinWaitlistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinWaitlist not implemented")
}
func (UnimplementedBackendServiceServer) GetLinkedAccounts(context.Context, *Empty) (*GetLinkedAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinkedAccounts not implemented")
}
func (UnimplementedBackendServiceServer) CreateSupportTicket(context.Context, *CreateSupportTicketRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSupportTicket not implemented")
}
func (UnimplementedBackendServiceServer) GetCountries(context.Context, *Empty) (*GetCountriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountries not implemented")
}
func (UnimplementedBackendServiceServer) LinkCashAccount(context.Context, *LinkCashAccountRequest) (*LinkedAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkCashAccount not implemented")
}
func (UnimplementedBackendServiceServer) GetMachnetWidgetToken(context.Context, *Empty) (*MachnetWidgetToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMachnetWidgetToken not implemented")
}

// UnsafeBackendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendServiceServer will
// result in compilation errors.
type UnsafeBackendServiceServer interface {
	mustEmbedUnimplementedBackendServiceServer()
}

func RegisterBackendServiceServer(s grpc.ServiceRegistrar, srv BackendServiceServer) {
	s.RegisterService(&BackendService_ServiceDesc, srv)
}

func _BackendService_GetBankAccountWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankAccountWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetBankAccountWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetBankAccountWidget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetBankAccountWidget(ctx, req.(*GetBankAccountWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_AddBankAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBankAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).AddBankAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/AddBankAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).AddBankAccount(ctx, req.(*AddBankAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetBankAccountDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankAccountDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetBankAccountDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetBankAccountDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetBankAccountDetails(ctx, req.(*GetBankAccountDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_ContinueAddingBankAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinueAddingBankAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).ContinueAddingBankAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/ContinueAddingBankAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).ContinueAddingBankAccount(ctx, req.(*ContinueAddingBankAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_UpdateIndividualKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIndividualKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).UpdateIndividualKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/UpdateIndividualKYC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).UpdateIndividualKYC(ctx, req.(*UpdateIndividualKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_SetSignupUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSignupUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).SetSignupUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/SetSignupUserData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).SetSignupUserData(ctx, req.(*SetSignupUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_SetSignupMobileNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSignupMobileNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).SetSignupMobileNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/SetSignupMobileNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).SetSignupMobileNumber(ctx, req.(*SetSignupMobileNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetSignup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetSignup(ctx, req.(*GetSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_CompleteSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).CompleteSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/CompleteSignup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).CompleteSignup(ctx, req.(*CompleteSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_CreateUserDefaultWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserDefaultWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).CreateUserDefaultWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/CreateUserDefaultWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).CreateUserDefaultWallet(ctx, req.(*CreateUserDefaultWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_SendPhoneVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPhoneVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).SendPhoneVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/SendPhoneVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).SendPhoneVerification(ctx, req.(*SendPhoneVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_SendOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).SendOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/SendOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).SendOTP(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetAgreement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetAgreement(ctx, req.(*GetAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_SignAgreements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignAgreementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).SignAgreements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/SignAgreements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).SignAgreements(ctx, req.(*SignAgreementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_JoinWaitlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinWaitlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).JoinWaitlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/JoinWaitlist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).JoinWaitlist(ctx, req.(*JoinWaitlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetLinkedAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetLinkedAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetLinkedAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetLinkedAccounts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_CreateSupportTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupportTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).CreateSupportTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/CreateSupportTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).CreateSupportTicket(ctx, req.(*CreateSupportTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetCountries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetCountries(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_LinkCashAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkCashAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).LinkCashAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/LinkCashAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).LinkCashAccount(ctx, req.(*LinkCashAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetMachnetWidgetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetMachnetWidgetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.v1.BackendService/GetMachnetWidgetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetMachnetWidgetToken(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendService_ServiceDesc is the grpc.ServiceDesc for BackendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.v1.BackendService",
	HandlerType: (*BackendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBankAccountWidget",
			Handler:    _BackendService_GetBankAccountWidget_Handler,
		},
		{
			MethodName: "AddBankAccount",
			Handler:    _BackendService_AddBankAccount_Handler,
		},
		{
			MethodName: "GetBankAccountDetails",
			Handler:    _BackendService_GetBankAccountDetails_Handler,
		},
		{
			MethodName: "ContinueAddingBankAccount",
			Handler:    _BackendService_ContinueAddingBankAccount_Handler,
		},
		{
			MethodName: "UpdateIndividualKYC",
			Handler:    _BackendService_UpdateIndividualKYC_Handler,
		},
		{
			MethodName: "SetSignupUserData",
			Handler:    _BackendService_SetSignupUserData_Handler,
		},
		{
			MethodName: "SetSignupMobileNumber",
			Handler:    _BackendService_SetSignupMobileNumber_Handler,
		},
		{
			MethodName: "GetSignup",
			Handler:    _BackendService_GetSignup_Handler,
		},
		{
			MethodName: "CompleteSignup",
			Handler:    _BackendService_CompleteSignup_Handler,
		},
		{
			MethodName: "CreateUserDefaultWallet",
			Handler:    _BackendService_CreateUserDefaultWallet_Handler,
		},
		{
			MethodName: "SendPhoneVerification",
			Handler:    _BackendService_SendPhoneVerification_Handler,
		},
		{
			MethodName: "SendOTP",
			Handler:    _BackendService_SendOTP_Handler,
		},
		{
			MethodName: "GetAgreement",
			Handler:    _BackendService_GetAgreement_Handler,
		},
		{
			MethodName: "SignAgreements",
			Handler:    _BackendService_SignAgreements_Handler,
		},
		{
			MethodName: "JoinWaitlist",
			Handler:    _BackendService_JoinWaitlist_Handler,
		},
		{
			MethodName: "GetLinkedAccounts",
			Handler:    _BackendService_GetLinkedAccounts_Handler,
		},
		{
			MethodName: "CreateSupportTicket",
			Handler:    _BackendService_CreateSupportTicket_Handler,
		},
		{
			MethodName: "GetCountries",
			Handler:    _BackendService_GetCountries_Handler,
		},
		{
			MethodName: "LinkCashAccount",
			Handler:    _BackendService_LinkCashAccount_Handler,
		},
		{
			MethodName: "GetMachnetWidgetToken",
			Handler:    _BackendService_GetMachnetWidgetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/v1/backend.proto",
}
