include:
  - //////.gitlab-refs.yaml

.go-cache-backend:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    policy: pull
    key:
      files:
        - go/go.mod
    paths:
      - .go/pkg/mod/

.job_rules:
  rules:
    - changes:
      - go/go.mod
      - go/backend/*

variables:
  BACKEND_PATH: $CI_PROJECT_DIR/go/backend
  BACKEND_REPO: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/backend
  BACKEND_IMAGE_HASH: $CI_COMMIT_SHORT_SHA
  DB_URL: postgres://root@crdb:26257/%s?sslmode=disable

build_backend:
  image: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/docker:20.10
  extends:
    - .go-cache-backend
  needs:
    - go-mod
  services:
    - name: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/cockroach:latest-v21.2
      alias: crdb
      command: ["start-single-node", "--insecure", "--store=type=mem,size=641MiB"]
  interruptible: true
  script:
    - mkdir -p ~/.docker
    - echo $DOCKER_AUTH_CONFIG > ~/.docker/config.json
    - cd $BACKEND_PATH
    - make pull
    - make testci
    - make build IMAGE_HASH=${BACKEND_IMAGE_HASH}
    - make push IMAGE_HASH=${BACKEND_IMAGE_HASH}
