include:
  - //////.gitlab-refs.yaml

.go-cache-backend:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    policy: pull
    key:
      files:
        - go/go.mod
    paths:
      - .go/pkg/mod/

variables:
  BACKEND_PATH: $CI_PROJECT_DIR/go/backend
  BACKEND_REPO: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/backend
  BACKEND_IMAGE_HASH: $CI_COMMIT_SHORT_SHA
  DB_URL: postgres://root@crdb:26257/%s?sslmode=disable

test_backend:
  rules:
    - changes:
        - go/go.mod
        - go/backend/**/*
        - go/proto/**/*
  tags:
    - k8s
  image: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/docker:20.10
  extends:
    - .go-cache-backend
  needs:
    - job: go-mod
      optional: true
  services:
    - name: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/cockroach:latest-v21.2
      alias: crdb
      command: [ "start-single-node", "--insecure", "--store=type=mem,size=641MiB" ]
    - name: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/tigerbeetle@sha256:b1fe98356a0db183b56b555eac17c5a43f4b61305f5ac711ea741d5085a2f977
      alias: tb
      entrypoint:
        - "/bin/bash"
      command: [ "-c",
                 "mkdir -p /var/lib/tigerbeetle; ./tigerbeetle init --cluster=0 --replica=0 --directory=/var/lib/tigerbeetle; ./tigerbeetle start --cluster=0 --replica=0 --addresses=0.0.0.0:3000 --directory=/var/lib/tigerbeetle;" ]
  interruptible: true
  script:
    - cd $BACKEND_PATH
    - make testci

build_backend:
  interruptible: true
  tags:
    - k8s
  needs:
    - job: test_backend
      optional: true
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}},\"credHelpers\":{\"823058932981.dkr.ecr.eu-west-1.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${BACKEND_PATH}/../"
      --dockerfile "${BACKEND_PATH}/Dockerfile"
      --destination "823058932981.dkr.ecr.eu-west-1.amazonaws.com/backend:${BACKEND_IMAGE_HASH}"
      --cache=true
      --cache-repo="${CI_REGISTRY}/fynbos/fynbos/backend-cache"
