include:
  - //////.gitlab-refs.yaml

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    policy: pull
    key:
      files:
        - go/go.mod
    paths:
      - .go/pkg/mod/

.job_rules:
  rules:
    - changes:
      - go/go.mod
      - go/backend/*

variables:
  BACKEND_PATH: $CI_PROJECT_DIR/go/backend
#  DOCKER_CONTEXT: $CI_PROJECT_DIR/go
  BACKEND_REPO: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/backend
  BACKEND_IMAGE_HASH: $CI_COMMIT_SHORT_SHA

build_backend:
  image: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/docker:19.03.12
  extends:
    - .go-cache
  needs:
    - go-mod
  interruptible: true
  script:
    - mkdir -p ~/.docker
    - echo $DOCKER_AUTH_CONFIG > ~/.docker/config.json
    - cd $BACKEND_PATH
    - echo "Running tests"
    - go test ./...
    - echo "Test finished"
    - echo "Building Image"
    - >-
      DOCKER_BUILDKIT=1 docker build
      -t ${BACKEND_REPO}:${BACKEND_IMAGE_HASH}
      -f $BACKEND_PATH/Dockerfile
      ./../
    - docker push ${BACKEND_REPO}:${BACKEND_IMAGE_HASH}
    - echo "Build Finished"