version: '3.5'

services:
 crdb:
   image: cockroachdb/cockroach:latest-v21.2
   ports:
     - "26257:26257"
   command: start-single-node --insecure --store=type=mem,size=641MiB
   volumes:
     - "crdb:/cockroach/cockroach-data"

volumes:
  crdb:
