version: "3.5"

services:
  crdb:
    image: cockroachdb/cockroach:v22.2.8
    networks:
      fynbos-dev:
    ports:
      - "26257:26257"
    command: start-single-node --insecure --store=type=mem,size=641MiB --advertise-addr=localhost
    volumes:
      - "crdb:/cockroach/cockroach-data"
      - "./db/testdbinit.sql:/docker-entrypoint-initdb.d/init.sql"
volumes:
  crdb:

networks:
  fynbos-dev:
