
docker_build('fynbos/backend', '../', dockerfile="./Dockerfile")

k8s_custom_deploy(
  "backend",
  apply_cmd="kubectl set image deployment/backend backend=$TILT_IMAGE_0 && kubectl get deployment/backend -o yaml",
  delete_cmd="echo backend managed outside of Tilt",
  image_deps=["fynbos/backend"],
  deps=[],
)