
load('ext://ko', 'ko_build')

# This will make ko bundle the sql migrations as static files inside the image.
# It is relative to the <import path> we give to ko which is "./db" folder
ko_build('fynbos/backend-init', 'gitlab.com/fynbos/backend/db', ["./db"])

docker_build('fynbos/backend', '../', dockerfile="./Dockerfile")

yaml = kustomize('./deploy/dev')
k8s_yaml(yaml)
