// Code generated by "stringer -type=IdentityType -trimprefix=IdentityType"; DO NOT EDIT.

package payments

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IdentityTypeUnknown-0]
	_ = x[IdentityTypeTwitter-1]
	_ = x[IdentityTypeWalletID-2]
	_ = x[IdentityTypeWalletURL-3]
	_ = x[IdentityTypeSlack-4]
	_ = x[IdentityTypeDiscord-5]
	_ = x[IdentityTypeExternalWalletURL-6]
	_ = x[identityTypeSentinel-7]
}

const _IdentityType_name = "UnknownTwitterWalletIDWalletURLSlackDiscordExternalWalletURLidentityTypeSentinel"

var _IdentityType_index = [...]uint8{0, 7, 14, 22, 31, 36, 43, 60, 80}

func (i IdentityType) String() string {
	if i < 0 || i >= IdentityType(len(_IdentityType_index)-1) {
		return "IdentityType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IdentityType_name[_IdentityType_index[i]:_IdentityType_index[i+1]]
}
