// Code generated by "stringer -type=RequiredActionType -trimprefix=RequiredActionType"; DO NOT EDIT.

package payments

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RequiredActionTypeUnknown-0]
	_ = x[RequiredActionTypeThreeDS-1]
}

const _RequiredActionType_name = "UnknownThreeDS"

var _RequiredActionType_index = [...]uint8{0, 7, 14}

func (i RequiredActionType) String() string {
	if i < 0 || i >= RequiredActionType(len(_RequiredActionType_index)-1) {
		return "RequiredActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RequiredActionType_name[_RequiredActionType_index[i]:_RequiredActionType_index[i+1]]
}
