// Code generated by "stringer -type=RequiredAction -trimprefix=RequiredAction"; DO NOT EDIT.

package payments

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RequiredActionUnknown-0]
	_ = x[RequiredActionThreeDS-1]
	_ = x[RequiredActionInformation-2]
	_ = x[RequiredActionSenderAccount-3]
	_ = x[RequiredActionReceiverAccount-4]
	_ = x[requiredActionSentinel-5]
}

const _RequiredAction_name = "UnknownThreeDSInformationSenderAccountReceiverAccountrequiredActionSentinel"

var _RequiredAction_index = [...]uint8{0, 7, 14, 25, 38, 53, 75}

func (i RequiredAction) String() string {
	if i < 0 || i >= RequiredAction(len(_RequiredAction_index)-1) {
		return "RequiredAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RequiredAction_name[_RequiredAction_index[i]:_RequiredAction_index[i+1]]
}
