// Code generated by "stringer -type=State -trimprefix=State"; DO NOT EDIT.

package payments

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateUnknown-0]
	_ = x[StateCreated-1]
	_ = x[StateConfirmed-2]
	_ = x[StateProcessing-3]
	_ = x[StateCompleted-4]
	_ = x[StateFailed-5]
	_ = x[stateSentinel-6]
}

const _State_name = "UnknownCreatedConfirmedProcessingCompletedFailedstateSentinel"

var _State_index = [...]uint8{0, 7, 14, 23, 33, 42, 48, 61}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
