// Code generated by "stringer -type=AccountResultCode -trimprefix=Account"; DO NOT EDIT.

package pacioli

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccountOK-0]
	_ = x[AccountLinkedEventFailed-1]
	_ = x[AccountReservedFlag-2]
	_ = x[AccountReservedField-3]
	_ = x[AccountIdMustNotBeZero-4]
	_ = x[AccountIdMustNotBeMaxInt-5]
	_ = x[AccountLedgerMustNotBeZero-6]
	_ = x[AccountCodeMustNotBeZero-7]
	_ = x[AccountMutuallyExclusiveFlags-8]
	_ = x[AccountOverflowsDebits-9]
	_ = x[AccountOverflowsCredits-10]
	_ = x[AccountExceedsCredits-11]
	_ = x[AccountExceedsDebits-12]
	_ = x[AccountExistsWithDifferentFlags-13]
	_ = x[AccountExistsWithDifferentUserData-14]
	_ = x[AccountExistsWithDifferentLedger-15]
	_ = x[AccountExistsWithDifferentCode-16]
	_ = x[AccountExistsWithDifferentDebitsPending-17]
	_ = x[AccountExistsWithDifferentDebitsPosted-18]
	_ = x[AccountExistsWithDifferentCreditsPending-19]
	_ = x[AccountExistsWithDifferentCreditsPosted-20]
	_ = x[AccountExists-21]
	_ = x[AccountLedgerDoesNotExist-404]
}

const (
	_AccountResultCode_name_0 = "OKLinkedEventFailedReservedFlagReservedFieldIdMustNotBeZeroIdMustNotBeMaxIntLedgerMustNotBeZeroCodeMustNotBeZeroMutuallyExclusiveFlagsOverflowsDebitsOverflowsCreditsExceedsCreditsExceedsDebitsExistsWithDifferentFlagsExistsWithDifferentUserDataExistsWithDifferentLedgerExistsWithDifferentCodeExistsWithDifferentDebitsPendingExistsWithDifferentDebitsPostedExistsWithDifferentCreditsPendingExistsWithDifferentCreditsPostedExists"
	_AccountResultCode_name_1 = "LedgerDoesNotExist"
)

var (
	_AccountResultCode_index_0 = [...]uint16{0, 2, 19, 31, 44, 59, 76, 95, 112, 134, 149, 165, 179, 192, 216, 243, 268, 291, 323, 354, 387, 419, 425}
)

func (i AccountResultCode) String() string {
	switch {
	case i <= 21:
		return _AccountResultCode_name_0[_AccountResultCode_index_0[i]:_AccountResultCode_index_0[i+1]]
	case i == 404:
		return _AccountResultCode_name_1
	default:
		return "AccountResultCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
