
docker_build('fynbos/pacioli', '../', dockerfile="./Dockerfile")

# see https://docs.tilt.dev/snippets.html?k8s_custom_deploy#snip_docker_build_existing_k8s_resource
k8s_custom_deploy(
  "pacioli",
  apply_cmd="""
    kubectl -v=0 set image deployment/pacioli pacioli=$TILT_IMAGE_0 pacioli-init=$TILT_IMAGE_0 > /dev/null && \
    kubectl get deployment/pacioli -o yaml
  """,
  delete_cmd="echo backend managed outside of Tilt",
  image_deps=["fynbos/pacioli"],
  deps=[],
)