// Code generated by MockGen. DO NOT EDIT.
// Source: ../smarty.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	kyc "github.com/interledger/interledger-app/go/backend/kyc"
)

// MockAddressValidator is a mock of AddressValidator interface.
type MockAddressValidator struct {
	ctrl     *gomock.Controller
	recorder *MockAddressValidatorMockRecorder
}

// MockAddressValidatorMockRecorder is the mock recorder for MockAddressValidator.
type MockAddressValidatorMockRecorder struct {
	mock *MockAddressValidator
}

// NewMockAddressValidator creates a new mock instance.
func NewMockAddressValidator(ctrl *gomock.Controller) *MockAddressValidator {
	mock := &MockAddressValidator{ctrl: ctrl}
	mock.recorder = &MockAddressValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressValidator) EXPECT() *MockAddressValidatorMockRecorder {
	return m.recorder
}

// ValidateUSPSAddress mocks base method.
func (m *MockAddressValidator) ValidateUSPSAddress(ctx context.Context, address kyc.Address) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUSPSAddress", ctx, address)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUSPSAddress indicates an expected call of ValidateUSPSAddress.
func (mr *MockAddressValidatorMockRecorder) ValidateUSPSAddress(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUSPSAddress", reflect.TypeOf((*MockAddressValidator)(nil).ValidateUSPSAddress), ctx, address)
}
