syntax = "proto3";

package pacioli.v1;

option go_package = "./pacioli/v1;pacioli";

service PacioliService {
  rpc ConfigureLedgers(ConfigureLedgersRequest) returns (ConfigureLedgersResponse);
  rpc GetLedgers(GetLedgersRequest) returns (GetLedgersResponse);
  rpc ConfigureAccounts(ConfigureAccountsRequest) returns (ConfigureAccountsResponse);
  rpc GetAccounts(GetAccountsRequest) returns (GetAccountsResponse);
  rpc CreateTransfers(CreateTransfersRequest) returns (CreateTransfersResponse);
  rpc GetTransfers(GetTransfersRequest) returns (GetTransfersResponse);
  rpc CommitTransfers(CommitTransfersRequest) returns (CommitTransfersResponse);
}

message Empty {}

message Ledger {
  uint32 id = 1;
  string name = 2;
  string asset = 3;
  uint32 scale = 4;
}

message ConfigureLedgersRequest {
  repeated Ledger args = 1;
}

message ConfigureLedgersResponse {
  repeated EventError errors = 1;
}

message GetLedgersRequest {
  repeated uint32 ids = 1;
}

message GetLedgersResponse {
  repeated Ledger ledgers = 1;
}

message Account {
  string id = 1;
  uint32 ledgerId = 2;
  uint32 code = 3;
  uint64 debitsReserved = 4;
  uint64 debitsAccepted = 5;
  uint64 creditsReserved = 6;
  uint64 creditsAccepted = 7;
  AccountFlags flags = 8;
}

message AccountFlags {
  bool linked = 1;
  bool debitsMustNotExceedCredits = 2;
  bool creditsMustNotExceedDebits = 3;
}

message ConfigureAccountsArgs {
  string id = 1;
  uint32 ledgerId = 2;
  uint32 code = 3;
  AccountFlags flags = 4;
}

message ConfigureAccountsRequest {
  repeated ConfigureAccountsArgs args = 1;
}

message ConfigureAccountsResponse {
  repeated EventError errors = 1;
}

message GetAccountsRequest {
  repeated string ids = 1;
}

message GetAccountsResponse {
  repeated Account accounts = 1;
}

message Transfer {
  string id = 1;
  string debitAccountId = 2;
  string creditAccountId = 3;
  uint64 amount = 4;
  uint32 code = 5;
  TransferFlags flags = 6;
  uint64 timeout = 7;
}

message TransferFlags {
  bool linked = 1;
  bool twoPhaseCommit = 2;
  bool condition = 3;
}

message CreateTransfersRequest {
  repeated Transfer transfers = 1;
}

message EventError {
  uint32 index = 1;
  uint32 code = 2;
}

message CreateTransfersResponse {
  repeated EventError errors = 1;
}

message GetTransfersRequest {
  repeated string ids = 1;
}

message GetTransfersResponse {
  repeated Transfer transfers = 1;
}

message CommitFlags {
  bool linked = 1;
  bool reject = 2;
  bool preimage = 3;
}

message Commit {
  string id = 1;
  uint32 code = 2;
  CommitFlags flags = 3;
}

message CommitTransfersRequest {
  repeated Commit commits = 1;
}

message CommitTransfersResponse {
  repeated EventError errors = 1;
}
