syntax = "proto3";

package pacioli.v1;

option go_package = "./pacioli/v1;pacioli";

service PacioliService {
  rpc CreateTenant(CreateTenantRequest) returns (Empty);
  rpc CreateLedgers(CreateLedgersRequest) returns (CreateLedgersResponse);
  rpc GetLedgers(GetLedgersRequest) returns (GetLedgersResponse);
  rpc CreateAccounts(CreateAccountsRequest) returns (CreateAccountsResponse);
  rpc GetAccounts(GetAccountsRequest) returns (Account);
  rpc CreateTransfers(CreateTransfersRequest) returns (CreateTransfersResponse);
  rpc GetTransfers(GetTransfersRequest) returns (GetTransfersResponse);
}

message Empty {}

message CreateTenantRequest {
  string name = 1;
}

message Ledger {
  uint32 id = 1;
  string name = 2;
  string asset = 3;
  uint32 scale =4;
}

message CreateLedgersRequest {
  repeated Ledger args = 1;
}

message CreateLedgersResponse {
  repeated EventError errors = 1;
}

message GetLedgersRequest {
  repeated string ids = 1;
}

message GetLedgersResponse {
  repeated Ledger ledgers = 1;
}

message Account {
  string id = 1;
  uint32 ledgerId = 2;
  uint32 code = 3;
  uint64 debitsReserved = 4;
  uint64 debitsAccepted = 5;
  uint64 creditsReserved = 6;
  uint64 creditsAccepted = 7;
  AccountFlags flags = 8;
}

message AccountFlags {
  bool linked = 1;
  bool debitsMustNotExceedCredits = 2;
  bool creditsMustNotExceedDebits = 3;
}

message CreateAccountArgs {
  string id = 1;
  uint32 ledgerId = 2;
  uint32 code = 3;
}

message CreateAccountsRequest {
  repeated CreateAccountArgs args = 1;
}

message CreateAccountsResponse {
  repeated EventError errors = 1;
}

message GetAccountsRequest {
  repeated string ids = 1;
}

message GetAccountsResponse {
  repeated Account accounts = 1;
}

message Transfer {
  string id = 1;
  string debitAccountId = 2;
  string creditAccountId = 3;
  uint64 amount = 4;
  uint32 code = 5;
  TransferFlags flags = 6;
}

message TransferFlags {
  bool linked = 1;
  bool twoPhaseCommit = 2;
  bool condition = 3;
}

message CreateTransfersRequest {
  repeated Transfer transfers = 1;
}

message EventError {
  uint32 index = 1;
  uint32 code = 2;
}

message CreateTransfersResponse {
  repeated EventError errors = 1;
}

message GetTransfersRequest {
  repeated string TransferIds = 1;
}

message GetTransfersResponse {
  repeated Transfer transfers = 1;
}
