// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go

// Package unit is a generated GoMock package.
package unit

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateApplicationForm mocks base method.
func (m *MockService) CreateApplicationForm(ctx context.Context, args *CreateApplicationFormArgs) (*ApplicationForm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApplicationForm", ctx, args)
	ret0, _ := ret[0].(*ApplicationForm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApplicationForm indicates an expected call of CreateApplicationForm.
func (mr *MockServiceMockRecorder) CreateApplicationForm(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplicationForm", reflect.TypeOf((*MockService)(nil).CreateApplicationForm), ctx, args)
}

// CreateCustomer mocks base method.
func (m *MockService) CreateCustomer(ctx context.Context, args *CreateCustomerArgs) (*Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", ctx, args)
	ret0, _ := ret[0].(*Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockServiceMockRecorder) CreateCustomer(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockService)(nil).CreateCustomer), ctx, args)
}

// GetApplicationForm mocks base method.
func (m *MockService) GetApplicationForm(ctx context.Context, userID string) (*ApplicationForm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplicationForm", ctx, userID)
	ret0, _ := ret[0].(*ApplicationForm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApplicationForm indicates an expected call of GetApplicationForm.
func (mr *MockServiceMockRecorder) GetApplicationForm(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplicationForm", reflect.TypeOf((*MockService)(nil).GetApplicationForm), ctx, userID)
}

// GetCustomerByAccountID mocks base method.
func (m *MockService) GetCustomerByAccountID(ctx context.Context, accountID string) (*Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByAccountID", ctx, accountID)
	ret0, _ := ret[0].(*Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByAccountID indicates an expected call of GetCustomerByAccountID.
func (mr *MockServiceMockRecorder) GetCustomerByAccountID(ctx, accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByAccountID", reflect.TypeOf((*MockService)(nil).GetCustomerByAccountID), ctx, accountID)
}

// GetCustomerByID mocks base method.
func (m *MockService) GetCustomerByID(ctx context.Context, id string) (*Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByID", ctx, id)
	ret0, _ := ret[0].(*Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByID indicates an expected call of GetCustomerByID.
func (mr *MockServiceMockRecorder) GetCustomerByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByID", reflect.TypeOf((*MockService)(nil).GetCustomerByID), ctx, id)
}

// VerifyWebhook mocks base method.
func (m *MockService) VerifyWebhook(ctx context.Context, body []byte, signature string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWebhook", ctx, body, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyWebhook indicates an expected call of VerifyWebhook.
func (mr *MockServiceMockRecorder) VerifyWebhook(ctx, body, signature interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWebhook", reflect.TypeOf((*MockService)(nil).VerifyWebhook), ctx, body, signature)
}
