// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	payments "gitlab.com/fynbos/backend/payments"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockClient) Get(ctx context.Context, id string) (*payments.OutgoingPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*payments.OutgoingPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClient)(nil).Get), ctx, id)
}

// InitiateOutgoingPayment mocks base method.
func (m *MockClient) InitiateOutgoingPayment(ctx context.Context, args payments.InitiateOutgoingPaymentArgs) (*payments.OutgoingPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateOutgoingPayment", ctx, args)
	ret0, _ := ret[0].(*payments.OutgoingPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateOutgoingPayment indicates an expected call of InitiateOutgoingPayment.
func (mr *MockClientMockRecorder) InitiateOutgoingPayment(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateOutgoingPayment", reflect.TypeOf((*MockClient)(nil).InitiateOutgoingPayment), ctx, args)
}

// SetState mocks base method.
func (m *MockClient) SetState(ctx context.Context, id string, state payments.State) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetState", ctx, id, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetState indicates an expected call of SetState.
func (mr *MockClientMockRecorder) SetState(ctx, id, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockClient)(nil).SetState), ctx, id, state)
}
