// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	payments "gitlab.com/fynbos/backend/payments"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AdminListAwaitingSignal mocks base method.
func (m *MockClient) AdminListAwaitingSignal(ctx context.Context) ([]payments.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminListAwaitingSignal", ctx)
	ret0, _ := ret[0].([]payments.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminListAwaitingSignal indicates an expected call of AdminListAwaitingSignal.
func (mr *MockClientMockRecorder) AdminListAwaitingSignal(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListAwaitingSignal", reflect.TypeOf((*MockClient)(nil).AdminListAwaitingSignal), ctx)
}

// Confirm mocks base method.
func (m *MockClient) Confirm(ctx context.Context, id string) (*payments.Payment, []payments.RequiredActionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, id)
	ret0, _ := ret[0].(*payments.Payment)
	ret1, _ := ret[1].([]payments.RequiredActionType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Confirm indicates an expected call of Confirm.
func (mr *MockClientMockRecorder) Confirm(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockClient)(nil).Confirm), ctx, id)
}

// Create mocks base method.
func (m *MockClient) Create(ctx context.Context, args payments.CreateArgs) (*payments.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, args)
	ret0, _ := ret[0].(*payments.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClientMockRecorder) Create(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClient)(nil).Create), ctx, args)
}

// Lookup mocks base method.
func (m *MockClient) Lookup(ctx context.Context, id string) (*payments.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", ctx, id)
	ret0, _ := ret[0].(*payments.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockClientMockRecorder) Lookup(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockClient)(nil).Lookup), ctx, id)
}

// SignalAccountLinked mocks base method.
func (m *MockClient) SignalAccountLinked(ctx context.Context, walletID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignalAccountLinked", ctx, walletID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignalAccountLinked indicates an expected call of SignalAccountLinked.
func (mr *MockClientMockRecorder) SignalAccountLinked(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalAccountLinked", reflect.TypeOf((*MockClient)(nil).SignalAccountLinked), ctx, walletID)
}

// SignalAstraTransferUpdate mocks base method.
func (m *MockClient) SignalAstraTransferUpdate(ctx context.Context, correlation string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignalAstraTransferUpdate", ctx, correlation)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignalAstraTransferUpdate indicates an expected call of SignalAstraTransferUpdate.
func (mr *MockClientMockRecorder) SignalAstraTransferUpdate(ctx, correlation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalAstraTransferUpdate", reflect.TypeOf((*MockClient)(nil).SignalAstraTransferUpdate), ctx, correlation)
}

// SignalExternalPayoutComplete mocks base method.
func (m *MockClient) SignalExternalPayoutComplete(ctx context.Context, id string, success bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignalExternalPayoutComplete", ctx, id, success)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignalExternalPayoutComplete indicates an expected call of SignalExternalPayoutComplete.
func (mr *MockClientMockRecorder) SignalExternalPayoutComplete(ctx, id, success interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalExternalPayoutComplete", reflect.TypeOf((*MockClient)(nil).SignalExternalPayoutComplete), ctx, id, success)
}

// SignalGatehubTransferComplete mocks base method.
func (m *MockClient) SignalGatehubTransferComplete(ctx context.Context, externalTransactionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignalGatehubTransferComplete", ctx, externalTransactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignalGatehubTransferComplete indicates an expected call of SignalGatehubTransferComplete.
func (mr *MockClientMockRecorder) SignalGatehubTransferComplete(ctx, externalTransactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalGatehubTransferComplete", reflect.TypeOf((*MockClient)(nil).SignalGatehubTransferComplete), ctx, externalTransactionID)
}

// SignalIdentityCreated mocks base method.
func (m *MockClient) SignalIdentityCreated(ctx context.Context, identifier string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignalIdentityCreated", ctx, identifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignalIdentityCreated indicates an expected call of SignalIdentityCreated.
func (mr *MockClientMockRecorder) SignalIdentityCreated(ctx, identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalIdentityCreated", reflect.TypeOf((*MockClient)(nil).SignalIdentityCreated), ctx, identifier)
}

// Update mocks base method.
func (m *MockClient) Update(ctx context.Context, args payments.UpdateArgs) (*payments.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, args)
	ret0, _ := ret[0].(*payments.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClientMockRecorder) Update(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClient)(nil).Update), ctx, args)
}

// UpdateReceiver mocks base method.
func (m *MockClient) UpdateReceiver(ctx context.Context, id string, identity payments.Identity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReceiver", ctx, id, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReceiver indicates an expected call of UpdateReceiver.
func (mr *MockClientMockRecorder) UpdateReceiver(ctx, id, identity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReceiver", reflect.TypeOf((*MockClient)(nil).UpdateReceiver), ctx, id, identity)
}
