// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go

// Package onboarding is a generated GoMock package.
package onboarding

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	accounts "gitlab.com/fynbos/backend/accounts"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockService) CreateAccount(ctx context.Context, args *CreateAccountArgs) (*accounts.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, args)
	ret0, _ := ret[0].(*accounts.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockServiceMockRecorder) CreateAccount(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockService)(nil).CreateAccount), ctx, args)
}

// GetOnboarding mocks base method.
func (m *MockService) GetOnboarding(ctx context.Context, args *GetOnboardingArgs) (*Onboarding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnboarding", ctx, args)
	ret0, _ := ret[0].(*Onboarding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnboarding indicates an expected call of GetOnboarding.
func (mr *MockServiceMockRecorder) GetOnboarding(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnboarding", reflect.TypeOf((*MockService)(nil).GetOnboarding), ctx, args)
}

// InitiateUnitCustomerOnboarding mocks base method.
func (m *MockService) InitiateUnitCustomerOnboarding(ctx context.Context, args *InitiateUnitCustomerOnboardingArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateUnitCustomerOnboarding", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitiateUnitCustomerOnboarding indicates an expected call of InitiateUnitCustomerOnboarding.
func (mr *MockServiceMockRecorder) InitiateUnitCustomerOnboarding(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateUnitCustomerOnboarding", reflect.TypeOf((*MockService)(nil).InitiateUnitCustomerOnboarding), ctx, args)
}

// UpdateOnboarding mocks base method.
func (m *MockService) UpdateOnboarding(ctx context.Context, args *UpdateOnboardingArgs) (*Onboarding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOnboarding", ctx, args)
	ret0, _ := ret[0].(*Onboarding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOnboarding indicates an expected call of UpdateOnboarding.
func (mr *MockServiceMockRecorder) UpdateOnboarding(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnboarding", reflect.TypeOf((*MockService)(nil).UpdateOnboarding), ctx, args)
}
