// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: backend/admin/v1/backend.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Backend_ListWaitlistSignups_FullMethodName                = "/backend.admin.v1.Backend/ListWaitlistSignups"
	Backend_AllowWaitlistSignup_FullMethodName                = "/backend.admin.v1.Backend/AllowWaitlistSignup"
	Backend_ListWallets_FullMethodName                        = "/backend.admin.v1.Backend/ListWallets"
	Backend_GetWalletDetails_FullMethodName                   = "/backend.admin.v1.Backend/GetWalletDetails"
	Backend_ListTransactions_FullMethodName                   = "/backend.admin.v1.Backend/ListTransactions"
	Backend_GetTransactionDetails_FullMethodName              = "/backend.admin.v1.Backend/GetTransactionDetails"
	Backend_ListLinkedAccounts_FullMethodName                 = "/backend.admin.v1.Backend/ListLinkedAccounts"
	Backend_ListAudit_FullMethodName                          = "/backend.admin.v1.Backend/ListAudit"
	Backend_GetWalletFeatures_FullMethodName                  = "/backend.admin.v1.Backend/GetWalletFeatures"
	Backend_SetWalletFeatures_FullMethodName                  = "/backend.admin.v1.Backend/SetWalletFeatures"
	Backend_ListIncompleteLinkedAccountReviews_FullMethodName = "/backend.admin.v1.Backend/ListIncompleteLinkedAccountReviews"
	Backend_GetLinkedAccountReview_FullMethodName             = "/backend.admin.v1.Backend/GetLinkedAccountReview"
	Backend_CompleteLinkedAccountReview_FullMethodName        = "/backend.admin.v1.Backend/CompleteLinkedAccountReview"
	Backend_GetLinkedAccount_FullMethodName                   = "/backend.admin.v1.Backend/GetLinkedAccount"
	Backend_ListFormSubmissionCounts_FullMethodName           = "/backend.admin.v1.Backend/ListFormSubmissionCounts"
	Backend_ExportFormSubmissions_FullMethodName              = "/backend.admin.v1.Backend/ExportFormSubmissions"
	Backend_ListFormSubmissions_FullMethodName                = "/backend.admin.v1.Backend/ListFormSubmissions"
	Backend_GetFormSubmissionDetails_FullMethodName           = "/backend.admin.v1.Backend/GetFormSubmissionDetails"
	Backend_ListExternalApiCalls_FullMethodName               = "/backend.admin.v1.Backend/ListExternalApiCalls"
	Backend_ListPaymentsAwaitingSignal_FullMethodName         = "/backend.admin.v1.Backend/ListPaymentsAwaitingSignal"
	Backend_SetWalletXagoBalanceEnabled_FullMethodName        = "/backend.admin.v1.Backend/SetWalletXagoBalanceEnabled"
	Backend_GetWalletXagoBalance_FullMethodName               = "/backend.admin.v1.Backend/GetWalletXagoBalance"
	Backend_SetWalletCountry_FullMethodName                   = "/backend.admin.v1.Backend/SetWalletCountry"
	Backend_ListCountries_FullMethodName                      = "/backend.admin.v1.Backend/ListCountries"
	Backend_EnablePTIBalance_FullMethodName                   = "/backend.admin.v1.Backend/EnablePTIBalance"
	Backend_GetPTIBalance_FullMethodName                      = "/backend.admin.v1.Backend/GetPTIBalance"
	Backend_CreateGatehubUser_FullMethodName                  = "/backend.admin.v1.Backend/CreateGatehubUser"
	Backend_GetGatehubBalance_FullMethodName                  = "/backend.admin.v1.Backend/GetGatehubBalance"
	Backend_GetGatehubUser_FullMethodName                     = "/backend.admin.v1.Backend/GetGatehubUser"
	Backend_CheckUserTotpEnabled_FullMethodName               = "/backend.admin.v1.Backend/CheckUserTotpEnabled"
	Backend_Delete2FATotpEnrollment_FullMethodName            = "/backend.admin.v1.Backend/Delete2FATotpEnrollment"
)

// BackendClient is the client API for Backend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendClient interface {
	ListWaitlistSignups(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListWaitlistSignupsResponse, error)
	AllowWaitlistSignup(ctx context.Context, in *AllowWaitlistSignupRequest, opts ...grpc.CallOption) (*Empty, error)
	ListWallets(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*ListWalletsResponse, error)
	GetWalletDetails(ctx context.Context, in *GetWalletDetailsRequest, opts ...grpc.CallOption) (*WalletDetails, error)
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	GetTransactionDetails(ctx context.Context, in *GetTransactionDetailsRequest, opts ...grpc.CallOption) (*GetTransactionDetailsResponse, error)
	ListLinkedAccounts(ctx context.Context, in *ListLinkedAccountsRequest, opts ...grpc.CallOption) (*ListLinkedAccountsResponse, error)
	ListAudit(ctx context.Context, in *ListAuditRequest, opts ...grpc.CallOption) (*ListAuditResponse, error)
	GetWalletFeatures(ctx context.Context, in *GetWalletFeaturesRequest, opts ...grpc.CallOption) (*Features, error)
	SetWalletFeatures(ctx context.Context, in *Features, opts ...grpc.CallOption) (*Features, error)
	ListIncompleteLinkedAccountReviews(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*LinkedAccountReviews, error)
	GetLinkedAccountReview(ctx context.Context, in *GetLinkedAccountReviewRequest, opts ...grpc.CallOption) (*LinkedAccountReview, error)
	CompleteLinkedAccountReview(ctx context.Context, in *CompleteLinkedAccountReviewRequest, opts ...grpc.CallOption) (*LinkedAccountReview, error)
	GetLinkedAccount(ctx context.Context, in *GetLinkedAccountRequest, opts ...grpc.CallOption) (*LinkedAccount, error)
	ListFormSubmissionCounts(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*ListFormSubmissionCountsResponse, error)
	ExportFormSubmissions(ctx context.Context, in *ExportFormSubmissionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportFormSubmissionsResponse], error)
	ListFormSubmissions(ctx context.Context, in *ListFormSubmissionsRequest, opts ...grpc.CallOption) (*ListFormSubmissionsResponse, error)
	GetFormSubmissionDetails(ctx context.Context, in *GetFormSubmissionDetailsRequest, opts ...grpc.CallOption) (*FormSubmissionDetails, error)
	ListExternalApiCalls(ctx context.Context, in *ListExternalApiCallsRequest, opts ...grpc.CallOption) (*ListExternalApiCallsResponse, error)
	ListPaymentsAwaitingSignal(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListPaymentsAwaitingSignalResponse, error)
	SetWalletXagoBalanceEnabled(ctx context.Context, in *SetWalletXagoBalanceEnabledRequest, opts ...grpc.CallOption) (*Empty, error)
	GetWalletXagoBalance(ctx context.Context, in *GetWalletXagoBalanceRequest, opts ...grpc.CallOption) (*GetWalletXagoBalanceResponse, error)
	SetWalletCountry(ctx context.Context, in *SetWalletCountryRequest, opts ...grpc.CallOption) (*Empty, error)
	ListCountries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCountriesResponse, error)
	// PTI
	EnablePTIBalance(ctx context.Context, in *EnablePTIBalanceRequest, opts ...grpc.CallOption) (*Empty, error)
	GetPTIBalance(ctx context.Context, in *GetPTIBalanceRequest, opts ...grpc.CallOption) (*GetPTIBalanceResponse, error)
	// Gatehub
	CreateGatehubUser(ctx context.Context, in *CreateGatehubUserRequest, opts ...grpc.CallOption) (*Empty, error)
	GetGatehubBalance(ctx context.Context, in *GetGatehubBalanceRequest, opts ...grpc.CallOption) (*GetGatehubBalanceResponse, error)
	GetGatehubUser(ctx context.Context, in *GetGatehubUserRequest, opts ...grpc.CallOption) (*GatehubUser, error)
	// Kratos
	CheckUserTotpEnabled(ctx context.Context, in *CheckUserTotpEnabledRequest, opts ...grpc.CallOption) (*CheckUserTotpEnabledResponse, error)
	Delete2FATotpEnrollment(ctx context.Context, in *Delete2FATotpEnrollmentRequest, opts ...grpc.CallOption) (*Empty, error)
}

type backendClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendClient(cc grpc.ClientConnInterface) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) ListWaitlistSignups(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListWaitlistSignupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWaitlistSignupsResponse)
	err := c.cc.Invoke(ctx, Backend_ListWaitlistSignups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) AllowWaitlistSignup(ctx context.Context, in *AllowWaitlistSignupRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Backend_AllowWaitlistSignup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListWallets(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*ListWalletsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWalletsResponse)
	err := c.cc.Invoke(ctx, Backend_ListWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetWalletDetails(ctx context.Context, in *GetWalletDetailsRequest, opts ...grpc.CallOption) (*WalletDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletDetails)
	err := c.cc.Invoke(ctx, Backend_GetWalletDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, Backend_ListTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetTransactionDetails(ctx context.Context, in *GetTransactionDetailsRequest, opts ...grpc.CallOption) (*GetTransactionDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionDetailsResponse)
	err := c.cc.Invoke(ctx, Backend_GetTransactionDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListLinkedAccounts(ctx context.Context, in *ListLinkedAccountsRequest, opts ...grpc.CallOption) (*ListLinkedAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinkedAccountsResponse)
	err := c.cc.Invoke(ctx, Backend_ListLinkedAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListAudit(ctx context.Context, in *ListAuditRequest, opts ...grpc.CallOption) (*ListAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditResponse)
	err := c.cc.Invoke(ctx, Backend_ListAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetWalletFeatures(ctx context.Context, in *GetWalletFeaturesRequest, opts ...grpc.CallOption) (*Features, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Features)
	err := c.cc.Invoke(ctx, Backend_GetWalletFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) SetWalletFeatures(ctx context.Context, in *Features, opts ...grpc.CallOption) (*Features, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Features)
	err := c.cc.Invoke(ctx, Backend_SetWalletFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListIncompleteLinkedAccountReviews(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*LinkedAccountReviews, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkedAccountReviews)
	err := c.cc.Invoke(ctx, Backend_ListIncompleteLinkedAccountReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetLinkedAccountReview(ctx context.Context, in *GetLinkedAccountReviewRequest, opts ...grpc.CallOption) (*LinkedAccountReview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkedAccountReview)
	err := c.cc.Invoke(ctx, Backend_GetLinkedAccountReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) CompleteLinkedAccountReview(ctx context.Context, in *CompleteLinkedAccountReviewRequest, opts ...grpc.CallOption) (*LinkedAccountReview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkedAccountReview)
	err := c.cc.Invoke(ctx, Backend_CompleteLinkedAccountReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetLinkedAccount(ctx context.Context, in *GetLinkedAccountRequest, opts ...grpc.CallOption) (*LinkedAccount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkedAccount)
	err := c.cc.Invoke(ctx, Backend_GetLinkedAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListFormSubmissionCounts(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*ListFormSubmissionCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFormSubmissionCountsResponse)
	err := c.cc.Invoke(ctx, Backend_ListFormSubmissionCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ExportFormSubmissions(ctx context.Context, in *ExportFormSubmissionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportFormSubmissionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Backend_ServiceDesc.Streams[0], Backend_ExportFormSubmissions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportFormSubmissionsRequest, ExportFormSubmissionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Backend_ExportFormSubmissionsClient = grpc.ServerStreamingClient[ExportFormSubmissionsResponse]

func (c *backendClient) ListFormSubmissions(ctx context.Context, in *ListFormSubmissionsRequest, opts ...grpc.CallOption) (*ListFormSubmissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFormSubmissionsResponse)
	err := c.cc.Invoke(ctx, Backend_ListFormSubmissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetFormSubmissionDetails(ctx context.Context, in *GetFormSubmissionDetailsRequest, opts ...grpc.CallOption) (*FormSubmissionDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FormSubmissionDetails)
	err := c.cc.Invoke(ctx, Backend_GetFormSubmissionDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListExternalApiCalls(ctx context.Context, in *ListExternalApiCallsRequest, opts ...grpc.CallOption) (*ListExternalApiCallsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExternalApiCallsResponse)
	err := c.cc.Invoke(ctx, Backend_ListExternalApiCalls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListPaymentsAwaitingSignal(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListPaymentsAwaitingSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentsAwaitingSignalResponse)
	err := c.cc.Invoke(ctx, Backend_ListPaymentsAwaitingSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) SetWalletXagoBalanceEnabled(ctx context.Context, in *SetWalletXagoBalanceEnabledRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Backend_SetWalletXagoBalanceEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetWalletXagoBalance(ctx context.Context, in *GetWalletXagoBalanceRequest, opts ...grpc.CallOption) (*GetWalletXagoBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletXagoBalanceResponse)
	err := c.cc.Invoke(ctx, Backend_GetWalletXagoBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) SetWalletCountry(ctx context.Context, in *SetWalletCountryRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Backend_SetWalletCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListCountries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCountriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCountriesResponse)
	err := c.cc.Invoke(ctx, Backend_ListCountries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) EnablePTIBalance(ctx context.Context, in *EnablePTIBalanceRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Backend_EnablePTIBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetPTIBalance(ctx context.Context, in *GetPTIBalanceRequest, opts ...grpc.CallOption) (*GetPTIBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPTIBalanceResponse)
	err := c.cc.Invoke(ctx, Backend_GetPTIBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) CreateGatehubUser(ctx context.Context, in *CreateGatehubUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Backend_CreateGatehubUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetGatehubBalance(ctx context.Context, in *GetGatehubBalanceRequest, opts ...grpc.CallOption) (*GetGatehubBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatehubBalanceResponse)
	err := c.cc.Invoke(ctx, Backend_GetGatehubBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetGatehubUser(ctx context.Context, in *GetGatehubUserRequest, opts ...grpc.CallOption) (*GatehubUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatehubUser)
	err := c.cc.Invoke(ctx, Backend_GetGatehubUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) CheckUserTotpEnabled(ctx context.Context, in *CheckUserTotpEnabledRequest, opts ...grpc.CallOption) (*CheckUserTotpEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUserTotpEnabledResponse)
	err := c.cc.Invoke(ctx, Backend_CheckUserTotpEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) Delete2FATotpEnrollment(ctx context.Context, in *Delete2FATotpEnrollmentRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Backend_Delete2FATotpEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServer is the server API for Backend service.
// All implementations should embed UnimplementedBackendServer
// for forward compatibility.
type BackendServer interface {
	ListWaitlistSignups(context.Context, *emptypb.Empty) (*ListWaitlistSignupsResponse, error)
	AllowWaitlistSignup(context.Context, *AllowWaitlistSignupRequest) (*Empty, error)
	ListWallets(context.Context, *PaginationRequest) (*ListWalletsResponse, error)
	GetWalletDetails(context.Context, *GetWalletDetailsRequest) (*WalletDetails, error)
	ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error)
	GetTransactionDetails(context.Context, *GetTransactionDetailsRequest) (*GetTransactionDetailsResponse, error)
	ListLinkedAccounts(context.Context, *ListLinkedAccountsRequest) (*ListLinkedAccountsResponse, error)
	ListAudit(context.Context, *ListAuditRequest) (*ListAuditResponse, error)
	GetWalletFeatures(context.Context, *GetWalletFeaturesRequest) (*Features, error)
	SetWalletFeatures(context.Context, *Features) (*Features, error)
	ListIncompleteLinkedAccountReviews(context.Context, *PaginationRequest) (*LinkedAccountReviews, error)
	GetLinkedAccountReview(context.Context, *GetLinkedAccountReviewRequest) (*LinkedAccountReview, error)
	CompleteLinkedAccountReview(context.Context, *CompleteLinkedAccountReviewRequest) (*LinkedAccountReview, error)
	GetLinkedAccount(context.Context, *GetLinkedAccountRequest) (*LinkedAccount, error)
	ListFormSubmissionCounts(context.Context, *PaginationRequest) (*ListFormSubmissionCountsResponse, error)
	ExportFormSubmissions(*ExportFormSubmissionsRequest, grpc.ServerStreamingServer[ExportFormSubmissionsResponse]) error
	ListFormSubmissions(context.Context, *ListFormSubmissionsRequest) (*ListFormSubmissionsResponse, error)
	GetFormSubmissionDetails(context.Context, *GetFormSubmissionDetailsRequest) (*FormSubmissionDetails, error)
	ListExternalApiCalls(context.Context, *ListExternalApiCallsRequest) (*ListExternalApiCallsResponse, error)
	ListPaymentsAwaitingSignal(context.Context, *emptypb.Empty) (*ListPaymentsAwaitingSignalResponse, error)
	SetWalletXagoBalanceEnabled(context.Context, *SetWalletXagoBalanceEnabledRequest) (*Empty, error)
	GetWalletXagoBalance(context.Context, *GetWalletXagoBalanceRequest) (*GetWalletXagoBalanceResponse, error)
	SetWalletCountry(context.Context, *SetWalletCountryRequest) (*Empty, error)
	ListCountries(context.Context, *Empty) (*ListCountriesResponse, error)
	// PTI
	EnablePTIBalance(context.Context, *EnablePTIBalanceRequest) (*Empty, error)
	GetPTIBalance(context.Context, *GetPTIBalanceRequest) (*GetPTIBalanceResponse, error)
	// Gatehub
	CreateGatehubUser(context.Context, *CreateGatehubUserRequest) (*Empty, error)
	GetGatehubBalance(context.Context, *GetGatehubBalanceRequest) (*GetGatehubBalanceResponse, error)
	GetGatehubUser(context.Context, *GetGatehubUserRequest) (*GatehubUser, error)
	// Kratos
	CheckUserTotpEnabled(context.Context, *CheckUserTotpEnabledRequest) (*CheckUserTotpEnabledResponse, error)
	Delete2FATotpEnrollment(context.Context, *Delete2FATotpEnrollmentRequest) (*Empty, error)
}

// UnimplementedBackendServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackendServer struct{}

func (UnimplementedBackendServer) ListWaitlistSignups(context.Context, *emptypb.Empty) (*ListWaitlistSignupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWaitlistSignups not implemented")
}
func (UnimplementedBackendServer) AllowWaitlistSignup(context.Context, *AllowWaitlistSignupRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllowWaitlistSignup not implemented")
}
func (UnimplementedBackendServer) ListWallets(context.Context, *PaginationRequest) (*ListWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWallets not implemented")
}
func (UnimplementedBackendServer) GetWalletDetails(context.Context, *GetWalletDetailsRequest) (*WalletDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletDetails not implemented")
}
func (UnimplementedBackendServer) ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedBackendServer) GetTransactionDetails(context.Context, *GetTransactionDetailsRequest) (*GetTransactionDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionDetails not implemented")
}
func (UnimplementedBackendServer) ListLinkedAccounts(context.Context, *ListLinkedAccountsRequest) (*ListLinkedAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLinkedAccounts not implemented")
}
func (UnimplementedBackendServer) ListAudit(context.Context, *ListAuditRequest) (*ListAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAudit not implemented")
}
func (UnimplementedBackendServer) GetWalletFeatures(context.Context, *GetWalletFeaturesRequest) (*Features, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletFeatures not implemented")
}
func (UnimplementedBackendServer) SetWalletFeatures(context.Context, *Features) (*Features, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetWalletFeatures not implemented")
}
func (UnimplementedBackendServer) ListIncompleteLinkedAccountReviews(context.Context, *PaginationRequest) (*LinkedAccountReviews, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIncompleteLinkedAccountReviews not implemented")
}
func (UnimplementedBackendServer) GetLinkedAccountReview(context.Context, *GetLinkedAccountReviewRequest) (*LinkedAccountReview, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinkedAccountReview not implemented")
}
func (UnimplementedBackendServer) CompleteLinkedAccountReview(context.Context, *CompleteLinkedAccountReviewRequest) (*LinkedAccountReview, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteLinkedAccountReview not implemented")
}
func (UnimplementedBackendServer) GetLinkedAccount(context.Context, *GetLinkedAccountRequest) (*LinkedAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinkedAccount not implemented")
}
func (UnimplementedBackendServer) ListFormSubmissionCounts(context.Context, *PaginationRequest) (*ListFormSubmissionCountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFormSubmissionCounts not implemented")
}
func (UnimplementedBackendServer) ExportFormSubmissions(*ExportFormSubmissionsRequest, grpc.ServerStreamingServer[ExportFormSubmissionsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExportFormSubmissions not implemented")
}
func (UnimplementedBackendServer) ListFormSubmissions(context.Context, *ListFormSubmissionsRequest) (*ListFormSubmissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFormSubmissions not implemented")
}
func (UnimplementedBackendServer) GetFormSubmissionDetails(context.Context, *GetFormSubmissionDetailsRequest) (*FormSubmissionDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFormSubmissionDetails not implemented")
}
func (UnimplementedBackendServer) ListExternalApiCalls(context.Context, *ListExternalApiCallsRequest) (*ListExternalApiCallsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExternalApiCalls not implemented")
}
func (UnimplementedBackendServer) ListPaymentsAwaitingSignal(context.Context, *emptypb.Empty) (*ListPaymentsAwaitingSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPaymentsAwaitingSignal not implemented")
}
func (UnimplementedBackendServer) SetWalletXagoBalanceEnabled(context.Context, *SetWalletXagoBalanceEnabledRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetWalletXagoBalanceEnabled not implemented")
}
func (UnimplementedBackendServer) GetWalletXagoBalance(context.Context, *GetWalletXagoBalanceRequest) (*GetWalletXagoBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletXagoBalance not implemented")
}
func (UnimplementedBackendServer) SetWalletCountry(context.Context, *SetWalletCountryRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetWalletCountry not implemented")
}
func (UnimplementedBackendServer) ListCountries(context.Context, *Empty) (*ListCountriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCountries not implemented")
}
func (UnimplementedBackendServer) EnablePTIBalance(context.Context, *EnablePTIBalanceRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnablePTIBalance not implemented")
}
func (UnimplementedBackendServer) GetPTIBalance(context.Context, *GetPTIBalanceRequest) (*GetPTIBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPTIBalance not implemented")
}
func (UnimplementedBackendServer) CreateGatehubUser(context.Context, *CreateGatehubUserRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGatehubUser not implemented")
}
func (UnimplementedBackendServer) GetGatehubBalance(context.Context, *GetGatehubBalanceRequest) (*GetGatehubBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatehubBalance not implemented")
}
func (UnimplementedBackendServer) GetGatehubUser(context.Context, *GetGatehubUserRequest) (*GatehubUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatehubUser not implemented")
}
func (UnimplementedBackendServer) CheckUserTotpEnabled(context.Context, *CheckUserTotpEnabledRequest) (*CheckUserTotpEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserTotpEnabled not implemented")
}
func (UnimplementedBackendServer) Delete2FATotpEnrollment(context.Context, *Delete2FATotpEnrollmentRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete2FATotpEnrollment not implemented")
}
func (UnimplementedBackendServer) testEmbeddedByValue() {}

// UnsafeBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendServer will
// result in compilation errors.
type UnsafeBackendServer interface {
	mustEmbedUnimplementedBackendServer()
}

func RegisterBackendServer(s grpc.ServiceRegistrar, srv BackendServer) {
	// If the following call pancis, it indicates UnimplementedBackendServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Backend_ServiceDesc, srv)
}

func _Backend_ListWaitlistSignups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListWaitlistSignups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListWaitlistSignups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListWaitlistSignups(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_AllowWaitlistSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowWaitlistSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).AllowWaitlistSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_AllowWaitlistSignup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).AllowWaitlistSignup(ctx, req.(*AllowWaitlistSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListWallets(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetWalletDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetWalletDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetWalletDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetWalletDetails(ctx, req.(*GetWalletDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListTransactions(ctx, req.(*ListTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetTransactionDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetTransactionDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetTransactionDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetTransactionDetails(ctx, req.(*GetTransactionDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListLinkedAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinkedAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListLinkedAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListLinkedAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListLinkedAccounts(ctx, req.(*ListLinkedAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListAudit(ctx, req.(*ListAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetWalletFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetWalletFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetWalletFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetWalletFeatures(ctx, req.(*GetWalletFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_SetWalletFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Features)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).SetWalletFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_SetWalletFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).SetWalletFeatures(ctx, req.(*Features))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListIncompleteLinkedAccountReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListIncompleteLinkedAccountReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListIncompleteLinkedAccountReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListIncompleteLinkedAccountReviews(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetLinkedAccountReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkedAccountReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetLinkedAccountReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetLinkedAccountReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetLinkedAccountReview(ctx, req.(*GetLinkedAccountReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_CompleteLinkedAccountReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteLinkedAccountReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).CompleteLinkedAccountReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_CompleteLinkedAccountReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).CompleteLinkedAccountReview(ctx, req.(*CompleteLinkedAccountReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetLinkedAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkedAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetLinkedAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetLinkedAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetLinkedAccount(ctx, req.(*GetLinkedAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListFormSubmissionCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListFormSubmissionCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListFormSubmissionCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListFormSubmissionCounts(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ExportFormSubmissions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportFormSubmissionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BackendServer).ExportFormSubmissions(m, &grpc.GenericServerStream[ExportFormSubmissionsRequest, ExportFormSubmissionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Backend_ExportFormSubmissionsServer = grpc.ServerStreamingServer[ExportFormSubmissionsResponse]

func _Backend_ListFormSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFormSubmissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListFormSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListFormSubmissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListFormSubmissions(ctx, req.(*ListFormSubmissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetFormSubmissionDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFormSubmissionDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetFormSubmissionDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetFormSubmissionDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetFormSubmissionDetails(ctx, req.(*GetFormSubmissionDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListExternalApiCalls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExternalApiCallsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListExternalApiCalls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListExternalApiCalls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListExternalApiCalls(ctx, req.(*ListExternalApiCallsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListPaymentsAwaitingSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListPaymentsAwaitingSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListPaymentsAwaitingSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListPaymentsAwaitingSignal(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_SetWalletXagoBalanceEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWalletXagoBalanceEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).SetWalletXagoBalanceEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_SetWalletXagoBalanceEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).SetWalletXagoBalanceEnabled(ctx, req.(*SetWalletXagoBalanceEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetWalletXagoBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletXagoBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetWalletXagoBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetWalletXagoBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetWalletXagoBalance(ctx, req.(*GetWalletXagoBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_SetWalletCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWalletCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).SetWalletCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_SetWalletCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).SetWalletCountry(ctx, req.(*SetWalletCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_ListCountries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListCountries(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_EnablePTIBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnablePTIBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).EnablePTIBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_EnablePTIBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).EnablePTIBalance(ctx, req.(*EnablePTIBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetPTIBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPTIBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetPTIBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetPTIBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetPTIBalance(ctx, req.(*GetPTIBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_CreateGatehubUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGatehubUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).CreateGatehubUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_CreateGatehubUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).CreateGatehubUser(ctx, req.(*CreateGatehubUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetGatehubBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatehubBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetGatehubBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetGatehubBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetGatehubBalance(ctx, req.(*GetGatehubBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetGatehubUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatehubUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetGatehubUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_GetGatehubUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetGatehubUser(ctx, req.(*GetGatehubUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_CheckUserTotpEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserTotpEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).CheckUserTotpEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_CheckUserTotpEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).CheckUserTotpEnabled(ctx, req.(*CheckUserTotpEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_Delete2FATotpEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Delete2FATotpEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).Delete2FATotpEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backend_Delete2FATotpEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).Delete2FATotpEnrollment(ctx, req.(*Delete2FATotpEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Backend_ServiceDesc is the grpc.ServiceDesc for Backend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.admin.v1.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWaitlistSignups",
			Handler:    _Backend_ListWaitlistSignups_Handler,
		},
		{
			MethodName: "AllowWaitlistSignup",
			Handler:    _Backend_AllowWaitlistSignup_Handler,
		},
		{
			MethodName: "ListWallets",
			Handler:    _Backend_ListWallets_Handler,
		},
		{
			MethodName: "GetWalletDetails",
			Handler:    _Backend_GetWalletDetails_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _Backend_ListTransactions_Handler,
		},
		{
			MethodName: "GetTransactionDetails",
			Handler:    _Backend_GetTransactionDetails_Handler,
		},
		{
			MethodName: "ListLinkedAccounts",
			Handler:    _Backend_ListLinkedAccounts_Handler,
		},
		{
			MethodName: "ListAudit",
			Handler:    _Backend_ListAudit_Handler,
		},
		{
			MethodName: "GetWalletFeatures",
			Handler:    _Backend_GetWalletFeatures_Handler,
		},
		{
			MethodName: "SetWalletFeatures",
			Handler:    _Backend_SetWalletFeatures_Handler,
		},
		{
			MethodName: "ListIncompleteLinkedAccountReviews",
			Handler:    _Backend_ListIncompleteLinkedAccountReviews_Handler,
		},
		{
			MethodName: "GetLinkedAccountReview",
			Handler:    _Backend_GetLinkedAccountReview_Handler,
		},
		{
			MethodName: "CompleteLinkedAccountReview",
			Handler:    _Backend_CompleteLinkedAccountReview_Handler,
		},
		{
			MethodName: "GetLinkedAccount",
			Handler:    _Backend_GetLinkedAccount_Handler,
		},
		{
			MethodName: "ListFormSubmissionCounts",
			Handler:    _Backend_ListFormSubmissionCounts_Handler,
		},
		{
			MethodName: "ListFormSubmissions",
			Handler:    _Backend_ListFormSubmissions_Handler,
		},
		{
			MethodName: "GetFormSubmissionDetails",
			Handler:    _Backend_GetFormSubmissionDetails_Handler,
		},
		{
			MethodName: "ListExternalApiCalls",
			Handler:    _Backend_ListExternalApiCalls_Handler,
		},
		{
			MethodName: "ListPaymentsAwaitingSignal",
			Handler:    _Backend_ListPaymentsAwaitingSignal_Handler,
		},
		{
			MethodName: "SetWalletXagoBalanceEnabled",
			Handler:    _Backend_SetWalletXagoBalanceEnabled_Handler,
		},
		{
			MethodName: "GetWalletXagoBalance",
			Handler:    _Backend_GetWalletXagoBalance_Handler,
		},
		{
			MethodName: "SetWalletCountry",
			Handler:    _Backend_SetWalletCountry_Handler,
		},
		{
			MethodName: "ListCountries",
			Handler:    _Backend_ListCountries_Handler,
		},
		{
			MethodName: "EnablePTIBalance",
			Handler:    _Backend_EnablePTIBalance_Handler,
		},
		{
			MethodName: "GetPTIBalance",
			Handler:    _Backend_GetPTIBalance_Handler,
		},
		{
			MethodName: "CreateGatehubUser",
			Handler:    _Backend_CreateGatehubUser_Handler,
		},
		{
			MethodName: "GetGatehubBalance",
			Handler:    _Backend_GetGatehubBalance_Handler,
		},
		{
			MethodName: "GetGatehubUser",
			Handler:    _Backend_GetGatehubUser_Handler,
		},
		{
			MethodName: "CheckUserTotpEnabled",
			Handler:    _Backend_CheckUserTotpEnabled_Handler,
		},
		{
			MethodName: "Delete2FATotpEnrollment",
			Handler:    _Backend_Delete2FATotpEnrollment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportFormSubmissions",
			Handler:       _Backend_ExportFormSubmissions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "backend/admin/v1/backend.proto",
}
