// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	waitlist "github.com/interledger/interledger-app/go/backend/waitlist"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockClient) Add(ctx context.Context, email, countryCode, fullName, mugID string, betaOptIn bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, email, countryCode, fullName, mugID, betaOptIn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockClientMockRecorder) Add(ctx, email, countryCode, fullName, mugID, betaOptIn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockClient)(nil).Add), ctx, email, countryCode, fullName, mugID, betaOptIn)
}

// AllowSignupById mocks base method.
func (m *MockClient) AllowSignupById(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowSignupById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// AllowSignupById indicates an expected call of AllowSignupById.
func (mr *MockClientMockRecorder) AllowSignupById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowSignupById", reflect.TypeOf((*MockClient)(nil).AllowSignupById), ctx, id)
}

// CanSignup mocks base method.
func (m *MockClient) CanSignup(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanSignup", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanSignup indicates an expected call of CanSignup.
func (mr *MockClientMockRecorder) CanSignup(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanSignup", reflect.TypeOf((*MockClient)(nil).CanSignup), ctx, id)
}

// IsMugAvailable mocks base method.
func (m *MockClient) IsMugAvailable(ctx context.Context, mugID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMugAvailable", ctx, mugID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMugAvailable indicates an expected call of IsMugAvailable.
func (mr *MockClientMockRecorder) IsMugAvailable(ctx, mugID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMugAvailable", reflect.TypeOf((*MockClient)(nil).IsMugAvailable), ctx, mugID)
}

// ListSignups mocks base method.
func (m *MockClient) ListSignups(ctx context.Context) ([]waitlist.Signup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSignups", ctx)
	ret0, _ := ret[0].([]waitlist.Signup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSignups indicates an expected call of ListSignups.
func (mr *MockClientMockRecorder) ListSignups(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSignups", reflect.TypeOf((*MockClient)(nil).ListSignups), ctx)
}

// SetSignupComplete mocks base method.
func (m *MockClient) SetSignupComplete(ctx context.Context, id, userSignupId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSignupComplete", ctx, id, userSignupId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSignupComplete indicates an expected call of SetSignupComplete.
func (mr *MockClientMockRecorder) SetSignupComplete(ctx, id, userSignupId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSignupComplete", reflect.TypeOf((*MockClient)(nil).SetSignupComplete), ctx, id, userSignupId)
}
