// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "gitlab.com/fynbos/backend/db"
	wallets "gitlab.com/fynbos/backend/wallets"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClient) Create(ctx context.Context, args wallets.CreateArgs) (*wallets.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, args)
	ret0, _ := ret[0].(*wallets.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClientMockRecorder) Create(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClient)(nil).Create), ctx, args)
}

// ForContext mocks base method.
func (m *MockClient) ForContext(ctx context.Context) (*wallets.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForContext", ctx)
	ret0, _ := ret[0].(*wallets.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForContext indicates an expected call of ForContext.
func (mr *MockClientMockRecorder) ForContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForContext", reflect.TypeOf((*MockClient)(nil).ForContext), ctx)
}

// Get mocks base method.
func (m *MockClient) Get(ctx context.Context, id string) (*wallets.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*wallets.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClient)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockClient) List(ctx context.Context, userID string) ([]wallets.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]wallets.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClientMockRecorder) List(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClient)(nil).List), ctx, userID)
}

// ListAll mocks base method.
func (m *MockClient) ListAll(ctx context.Context, page db.Pagination) ([]wallets.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx, page)
	ret0, _ := ret[0].([]wallets.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockClientMockRecorder) ListAll(ctx, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockClient)(nil).ListAll), ctx, page)
}

// SetWalletName mocks base method.
func (m *MockClient) SetWalletName(ctx context.Context, id, name string) (*wallets.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWalletName", ctx, id, name)
	ret0, _ := ret[0].(*wallets.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetWalletName indicates an expected call of SetWalletName.
func (mr *MockClientMockRecorder) SetWalletName(ctx, id, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWalletName", reflect.TypeOf((*MockClient)(nil).SetWalletName), ctx, id, name)
}
