apiVersion: v2
name: interledger-app
description: Interledger App Wallet — combined admin (Botanist), backend, and frontend (Protea) services
home: https://github.com/interledger/interledger-app

type: application
# version and appVersion is linked because we are doing this in the same repo
version: 1.18.3
appVersion: v1.18.3

dependencies:
  - name: common
    version: 0.9.0
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
  - name: Radu Popa
    email: radu@interledger.foundation
