import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:watsonia/styles/colors.dart';

final theme = ThemeData(
  useMaterial3: true,
  appBarTheme: const AppBarTheme(
    backgroundColor: TWColors.transparent,
    systemOverlayStyle: SystemUiOverlayStyle(
      statusBarColor: TWColors.bgApp,
      // For Android (dark icons)
      statusBarBrightness: Brightness.light,
      // For iOS (dark icons)
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: TWColors.bgApp,
      systemNavigationBarDividerColor: TWColors.bgApp,
    ),
  ),
  colorScheme: const ColorScheme(
    background: TWColors.bgApp,
    brightness: Brightness.light,
    primary: TWColors.bgApp,
    onPrimary: TWColors.bgApp,
    secondary: TWColors.bgApp,
    onSecondary: TWColors.bgApp,
    error: TWColors.bgApp,
    onError: TWColors.bgApp,
    onBackground: TWColors.bgApp,
    surface: TWColors.bgApp,
    onSurface: TWColors.textStrong,
  ),
);

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF005AC2),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFD8E2FF),
  onPrimaryContainer: Color(0xFF001A42),
  // primaryFixed: Color(0xFFD8E2FF),
  // onPrimaryFixed: Color(0xFF001A42),
  // primaryFixedDim: Color(0xFFADC6FF),
  // onPrimaryFixedVariant: Color(0xFF004395),
  secondary: Color(0xFF575E71),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFDBE2F9),
  onSecondaryContainer: Color(0xFF141B2C),
  // secondaryFixed: Color(0xFFDBE2F9),
  // onSecondaryFixed: Color(0xFF141B2C),
  // secondaryFixedDim: Color(0xFFBFC6DC),
  // onSecondaryFixedVariant: Color(0xFF3F4759),
  tertiary: Color(0xFF715573),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFCD7FB),
  onTertiaryContainer: Color(0xFF29132D),
  // tertiaryFixed: Color(0xFFFCD7FB),
  // onTertiaryFixed: Color(0xFF29132D),
  // tertiaryFixedDim: Color(0xFFDEBCDF),
  // onTertiaryFixedVariant: Color(0xFF583E5B),
  error: Color(0xFFB91C1C),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFBFCFE),
  onBackground: Color(0xFF191C1E),
  outline: Color(0xFF75777F),
  onInverseSurface: Color(0xFFF0F1F3),
  inverseSurface: Color(0xFF2E3133),
  inversePrimary: Color(0xFFADC6FF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF005AC2),
  outlineVariant: Color(0xFFC4C6D0),
  scrim: Color(0xFF000000),
  surface: Color(0xFFF8F9FB),
  onSurface: Color(0xFF191C1E),
  surfaceVariant: Color(0xFFE1E2EC),
  onSurfaceVariant: Color(0xFF44474F),
  // surfaceContainerHighest: Color(0xFFE1E2E5),
  // surfaceContainerHigh: Color(0xFFE7E8EA),
  // surfaceContainer: Color(0xFFEDEEF0),
  // surfaceContainerLow: Color(0xFFF3F4F6),
  // surfaceContainerLowest: Color(0xFFFFFFFF),
  // surfaceDim: Color(0xFFD9DADC),
  // surfaceBright: Color(0xFFF8F9FB),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFADC6FF),
  onPrimary: Color(0xFF002E6A),
  primaryContainer: Color(0xFF004395),
  onPrimaryContainer: Color(0xFFD8E2FF),
  // primaryFixed: Color(0xFFD8E2FF),
  // onPrimaryFixed: Color(0xFF001A42),
  // primaryFixedDim: Color(0xFFADC6FF),
  // onPrimaryFixedVariant: Color(0xFF004395),
  secondary: Color(0xFFBFC6DC),
  onSecondary: Color(0xFF293041),
  secondaryContainer: Color(0xFF3F4759),
  onSecondaryContainer: Color(0xFFDBE2F9),
  // secondaryFixed: Color(0xFFDBE2F9),
  // onSecondaryFixed: Color(0xFF141B2C),
  // secondaryFixedDim: Color(0xFFBFC6DC),
  // onSecondaryFixedVariant: Color(0xFF3F4759),
  tertiary: Color(0xFFDEBCDF),
  onTertiary: Color(0xFF402843),
  tertiaryContainer: Color(0xFF583E5B),
  onTertiaryContainer: Color(0xFFFCD7FB),
  // tertiaryFixed: Color(0xFFFCD7FB),
  // onTertiaryFixed: Color(0xFF29132D),
  // tertiaryFixedDim: Color(0xFFDEBCDF),
  // onTertiaryFixedVariant: Color(0xFF583E5B),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000B),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF191C1E),
  onBackground: Color(0xFFE1E2E5),
  outline: Color(0xFF8E9099),
  onInverseSurface: Color(0xFF191C1E),
  inverseSurface: Color(0xFFE1E2E5),
  inversePrimary: Color(0xFF005AC2),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFADC6FF),
  outlineVariant: Color(0xFF44474F),
  scrim: Color(0xFF000000),
  surface: Color(0xFF111415),
  onSurface: Color(0xFFC5C6C9),
  surfaceVariant: Color(0xFF44474F),
  onSurfaceVariant: Color(0xFFC4C6D0),
  // surfaceContainerHighest: Color(0xFF323537),
  // surfaceContainerHigh: Color(0xFF282A2C),
  // surfaceContainer: Color(0xFF1D2022),
  // surfaceContainerLow: Color(0xFF191C1E),
  // surfaceContainerLowest: Color(0xFF0C0F10),
  // surfaceDim: Color(0xFF111415),
  // surfaceBright: Color(0xFF37393B),
);
