package provision

import (
	"fmt"
	"io"
)

// Split divides provisioned wallets into senders and receivers.
//
// This remains for older harness code and tests; the provisioner itself now emits
// a flat wallet list that the runner expands via config.Load.
func Split(wallets []Wallet, senderCount int) (senders, receivers []Wallet) {
	if senderCount <= 0 || senderCount > len(wallets) {
		senderCount = len(wallets) / 2
	}

	// Funded wallets first, so senders get them; an unfunded sender has nothing to
	// drain. Built into one fresh slice rather than by appending one partition to
	// the other, which would write into the first partition's backing array.
	ordered := make([]Wallet, 0, len(wallets))
	for _, w := range wallets {
		if w.Balance > 0 {
			ordered = append(ordered, w)
		}
	}
	for _, w := range wallets {
		if w.Balance <= 0 {
			ordered = append(ordered, w)
		}
	}

	senderCount = min(senderCount, len(ordered))

	return ordered[:senderCount], ordered[senderCount:]
}

// WriteScenarioOverlay writes a YAML overlay listing the provisioned wallets.
//
// It is an overlay, not a whole scenario: layer it over one of the committed
// files in scenarios/ so the run shape stays in version control while the
// credentials stay local. Session tokens are deliberately omitted — they expire,
// and email plus password re-authenticates on every run.
func WriteScenarioOverlay(w io.Writer, wallets []Wallet) error {
	write := func(format string, args ...any) error {
		_, err := fmt.Fprintf(w, format, args...)
		return err
	}

	if err := write("# Generated by `perf provision`. Layer this over a scenario file:\n"); err != nil {
		return err
	}
	if err := write("#   perf run -config scenarios/many-to-many.yaml -config wallets.local.yaml\n"); err != nil {
		return err
	}
	if err := write("# These are local development credentials. Do not commit this file.\n\nwallets:\n"); err != nil {
		return err
	}

	for _, wallet := range wallets {
		if err := write("  - label: %s\n    email: %s\n    password: %q\n    wallet_address: %s\n", wallet.Label, wallet.Email, wallet.Password, wallet.WalletAddress); err != nil {
			return err
		}
	}

	return nil
}
