config:
  aws:region: eu-west-1
  fynbos:accountId: 823058932981
  cluster:oidcProvider: oidc.eks.eu-west-1.amazonaws.com/id/63D788C045B4A68C6DF3F6C6F816CF53
  cluster:name: live-eu-west-1-eks-cluster
  ebs:kmsKeyId:
