input LinkUsdBankAccountInput {
  name: String!
  accountNumber: String!
  routingNumber: String!
  institution: String!
  type: String!
}

mutation LinkUsdBankAccount($input: LinkUsdBankAccountInput!) {
  linkUsdBankAccount(input: $input) {
    code
    success
    message
    fundingSource {
      id
      name
      verificationStatus
      mask
      type
      subType
    }
  }
}

input VerifyUsdBankAccountInput {
  FundingSourceId: String!
}

mutation VerifyUsdBankAccount($input: VerifyUsdBankAccountInput!) {
  verifyUsdBankAccount(input: $input) {
    code
    success
    message
    fundingSource {
      id
      name
      verificationStatus
      mask
      type
      subType
    }
  }
}
