build_runner_image:
  interruptible: true
  rules:
    - changes:
      - infra/gitlab/runner-image/*
  tags:
    - hetzner
  image:
    name: registry.gitlab.com/fynbos/fynbos/debian-runner-base
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - cd infra/gitlab/runner-image
  script:
    - docker build -t registry.gitlab.com/fynbos/fynbos/debian-runner-base:$CI_COMMIT_SHORT_SHA .
    - docker push registry.gitlab.com/fynbos/fynbos/debian-runner-base:$CI_COMMIT_SHORT_SHA