syntax = "proto3";

package backend.admin.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/rpc/code.proto";
import "google/rpc/error_details.proto";
import "google/rpc/status.proto";

option go_package = "./backend/admin/v1;admin";

service Backend {
  rpc ListWaitlistSignups(google.protobuf.Empty) returns (ListWaitlistSignupsResponse);
  rpc AllowWaitlistSignup(AllowWaitlistSignupRequest) returns (Empty);
}

message Empty {}

message AllowWaitlistSignupRequest {
  string id = 1;
}

message ListWaitlistSignupsResponse {
  repeated WaitlistSignup signups = 1;
}

message WaitlistSignup {
  string id = 1;
  string name = 2;
  string email = 3;
  bool beta_opt_in = 4;
  bool can_signup = 5;
  string mug_id = 6;
}
