syntax = "proto3";

package backend.admin.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/rpc/code.proto";
import "google/rpc/error_details.proto";
import "google/rpc/status.proto";

option go_package = "./backend/admin/v1;admin";

service Backend {
  rpc ListWaitlistSignups(google.protobuf.Empty) returns (ListWaitlistSignupsResponse);
  rpc AllowWaitlistSignup(AllowWaitlistSignupRequest) returns (Empty);
  rpc ListWallets(PaginationRequest) returns (ListWalletsResponse);
  rpc GetWalletDetails(GetWalletDetailsRequest) returns (WalletDetails);
  rpc ListTransactions(ListTransactionsRequest) returns (ListTransactionsResponse);
  rpc GetTransactionDetails(GetTransactionDetailsRequest) returns (GetTransactionDetailsResponse);
  rpc ListLinkedAccounts(ListLinkedAccountsRequest) returns (ListLinkedAccountsResponse);
  rpc ListAudit(ListAuditRequest) returns (ListAuditResponse);
  rpc GetWalletFeatures(GetWalletFeaturesRequest) returns (Features);
  rpc SetWalletFeatures(Features) returns (Features);
  rpc ListIncompleteLinkedAccountReviews(PaginationRequest) returns (LinkedAccountReviews);
  rpc GetLinkedAccountReview(GetLinkedAccountReviewRequest) returns (LinkedAccountReview);
  rpc CompleteLinkedAccountReview(CompleteLinkedAccountReviewRequest) returns (LinkedAccountReview);
  rpc GetLinkedAccount(GetLinkedAccountRequest) returns (LinkedAccount);
  rpc ListExternalApiCalls(ListExternalApiCallsRequest) returns (ListExternalApiCallsResponse);
  rpc ListPaymentsAwaitingSignal(google.protobuf.Empty) returns (ListPaymentsAwaitingSignalResponse);
  rpc SetWalletXagoBalanceEnabled(SetWalletXagoBalanceEnabledRequest) returns (Empty);
  rpc GetWalletXagoBalance(GetWalletXagoBalanceRequest) returns (GetWalletXagoBalanceResponse);

  rpc SetWalletCountry(SetWalletCountryRequest) returns (Empty);
  rpc ListCountries(Empty) returns (ListCountriesResponse);

  // PTI
  rpc EnablePTIBalance(EnablePTIBalanceRequest) returns (Empty);
  rpc GetPTIBalance(GetPTIBalanceRequest) returns (GetPTIBalanceResponse);

  // Gatehub
  rpc CreateGatehubUser(CreateGatehubUserRequest) returns (Empty);
  rpc GetGatehubBalance(GetGatehubBalanceRequest) returns (GetGatehubBalanceResponse);
  rpc GetGatehubUser(GetGatehubUserRequest) returns (GatehubUser);

  // Kratos
  rpc CheckUserTotpEnabled(CheckUserTotpEnabledRequest) returns (CheckUserTotpEnabledResponse);
  rpc Delete2FATotpEnrollment(Delete2FATotpEnrollmentRequest) returns (Empty);
}

message CheckUserTotpEnabledRequest {
  string identityId = 1;
  string walletID = 2;
}

message CheckUserTotpEnabledResponse {
  bool isEnabled = 1;
}

message Delete2FATotpEnrollmentRequest {
  string identityId = 1;
  string walletID = 2;
}

message GatehubUser {
  string walletID = 1;
  string externalID = 2;
  string email = 3;
  int32 verificationLevel = 4;
  repeated GatehubVerification verifications = 5;
  GatehubProfile profile = 6;
  repeated GatehubDocument documents = 7;
}

message GatehubVerification {
  string uuid = 1;
  int32 state = 2;
  int32 status = 3;
  string provider_type = 4;
}

message GatehubDocument {
  int32 id = 1;
  string createdAt = 2;
  string uuid = 3;
  string updatedAt = 4;
  string type = 5;
  string subtype = 6;
  string value = 7;
  int32 profileId = 8;
  int32 userId = 9;
  string expiryDate = 10;
}

message GatehubProfile {
  string uuid = 1;
  google.protobuf.Timestamp createdAt = 2;
  int32 birthDay = 3;
  int32 birthMonth = 4;
  int32 birthYear = 5;
  string gender = 6;
  string firstName = 7;
  string middleName = 8;
  string lastName = 9;
  string citizenship = 10;
  string addressPostalCode = 11;
  string addressSubdivision = 12;
  string addressCountryCode = 13;
  string addressCity = 14;
  string addressStreet1 = 15;
  string addressStreet2 = 16;
  string birthCity = 19;
  string birthCountryCode = 20;
  string taxResidency = 21;
  string expectedVolume = 22;
}

message GetGatehubUserRequest {
  string walletID = 1;
}

message CreateGatehubUserRequest {
  string walletID = 1;
}

message GetGatehubBalanceRequest {
  string walletID = 1;
}

message GetGatehubBalanceResponse {
  Amount balance = 1;
  Amount available = 2;
}

message GetPTIBalanceRequest {
  string walletId = 1;
}

message GetPTIBalanceResponse {
  Amount balance = 1;
  Amount available = 2;
}

message EnablePTIBalanceRequest {
  string walletId = 1;
}

message SetWalletCountryRequest {
  string id = 1;
  string countryCode = 2;
}

message Country {
  string code = 1;
  string name = 2;
  string numeric = 3;
  bool supported = 4;
}

message ListCountriesResponse {
  repeated Country countries = 1;
}

message ListPaymentsAwaitingSignalResponse {
  repeated Payment payments = 1;
}

message Payment {
  string id = 1;
  string publicID = 2;
  string state = 3;
  string receiverWalletUrl = 4;
  string receiverIdentity = 5;
  string receiverIdentityType = 6;
  string senderAmount = 7;
  string senderAccount = 8; // Linked Account ID
  string note = 9;
  repeated string requiredActions = 10;
  string senderWalletUrl = 11;
  google.protobuf.Timestamp updatedAt = 12;
}

message ListExternalApiCallsRequest {
  string paymentId = 1;
}

message ExternalApiCall {
  string id = 1;
  string provider = 2;
  string context = 3;
  string method = 4;
  string requestBody = 5;
  string requestPath = 6;
  string responseBody = 7;
  string responseStatus = 8;
}

message ListExternalApiCallsResponse {
  repeated ExternalApiCall list = 1;
}

message Empty {}

message LinkedAccountReview {
  string id = 1;
  string state = 2;
  string newState = 3;
  string linkedAccountID = 4;
  string reviewedBy = 5;
  string reason = 6;
  string walletID = 9;
  string walletName = 10;
  string mask = 11;
  google.protobuf.Timestamp createdAt = 7;
  google.protobuf.Timestamp completedAt = 8;
}

message LinkedAccountReviews {
  repeated LinkedAccountReview reviews = 1;
}

message GetLinkedAccountReviewRequest {
  string id = 1;
}

message CompleteLinkedAccountReviewRequest {
  string id = 1;
  string reason = 2;
  string newState = 3;
}

message GetWalletFeaturesRequest {
  string walletID = 1;
}

message Features {
  bool sendEnabled = 1;
  bool receiveEnabled = 2;
  bool linkedAccountsEnabled = 3;
  bool cardsEnabled = 4;
  bool banksEnabled = 5;
  bool identitiesEnabled = 6;
  bool twitterEnabled = 7;
  string walletID = 8;
  bool addCardsEnabled = 9;
  bool zarBalanceEnabled = 10;
  bool manageWalletCardsEnabled = 11;
  bool accountEnabled = 12;
}

message ListAuditRequest {
  string walletID = 1;
}

message ListAuditResponse {
  repeated AuditOperation operations = 1;
}

message AuditOperation {
  string adminUser = 1;
  string walletID = 2;
  string operation = 3;
  string parameters = 4;
  google.protobuf.Timestamp timestamp = 5;
}

message ListLinkedAccountsRequest {
  string walletID = 1;
}

message GetLinkedAccountRequest {
  string id = 1;
}

message ListLinkedAccountsResponse {
  repeated LinkedAccount accounts = 1;
}

message LinkedAccount {
  string id = 1;
  string walletID = 2;
  string name = 3;
  string nickname = 4;
  string mask = 5;
  string provider = 6;
  string providerID = 7;
  string type = 8;
  string state = 9;
  string canSend = 10;
  string canReceive = 11;
  string sendCurrencyCode = 12; // e.g. USD
  string sendCurrencyCountryCode = 13; // e.g. US
  string receiveCurrencyCode = 14;
  string receiveCurrencyCountryCode = 15;
  google.protobuf.Timestamp deletedAt = 16;
  bool defaultSend = 17;
  bool defaultReceive = 18;
}

message GetTransactionDetailsRequest {
  string walletID = 1;
  string transactionID = 2;
}

message GetTransactionDetailsResponse {
  Transaction transaction = 1;
  repeated Transfer transfers = 2;
}

message Transfer {
  string ID = 1;
  string linkedAccountID = 2;
  string linkedAccountProvider = 3;
  string linkedAccountType = 4;
  string foreignID = 9;
  double amount = 5;
  string currency = 6;
  string state = 7;
  google.protobuf.Timestamp timestamp = 8;
}

message ListTransactionsRequest {
  string walletID = 1;
  PaginationRequest page = 2;
}

message ListTransactionsResponse {
  repeated Transaction transactions = 1;
  string nextPageToken = 2;
}

message Transaction {
  string walletID = 8;
  string id = 1;
  string type = 2;
  string asset = 7;
  double amount = 3;
  string source = 4;
  string destination = 5;
  google.protobuf.Timestamp timestamp = 6;
  string paymentId = 9;
}

message GetUserTransactionsRequest {
  string userID = 1;
}
message GetWalletDetailsRequest {
  string walletID = 1;
}

message WalletDetails {
  repeated User users = 8;
  string walletID = 1;
  string firstName = 2;
  string lastName = 3;
  string countryCode = 4;
  int32 gender = 5; // 0 Unknown, 1 Male, 2 Female, 3 Other
  google.protobuf.Timestamp dateOfBirth = 6;
  string address = 7;
  string kycStatus = 9;
  string placeOfBirth = 10;
  string nationality = 11;
  string walletName = 12;
}

message PaginationRequest {
  int32 pageSize = 1;
  optional string pageToken = 2;
}

message Wallet {
  string walletID = 1;
  string walletName = 2;
  repeated User users = 3;
}

message ListWalletsResponse {
  repeated Wallet wallets = 1;
  string nextPageToken = 2;
}

message User {
  string id = 1;
  string email = 2;
  string phoneNumber = 3;
}

message AllowWaitlistSignupRequest {
  string id = 1;
}

message ListWaitlistSignupsResponse {
  repeated WaitlistSignup signups = 1;
}

message WaitlistSignup {
  string id = 1;
  string name = 2;
  string email = 3;
  bool beta_opt_in = 4;
  bool can_signup = 5;
  string mug_id = 6;
  string country_code = 7;
}

message SetWalletXagoBalanceEnabledRequest {
  string wallet_id = 1;
}

message GetWalletXagoBalanceRequest {
  string wallet_id = 1;
}

message GetWalletXagoBalanceResponse {
  Amount balance = 1;
  Amount available = 2;
}

message Amount {
  uint64 amount = 1;
  string asset = 2;
  int32 assetScale = 3;
  string country = 4;
}
