syntax = "proto3";

package backend.admin.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/rpc/code.proto";
import "google/rpc/error_details.proto";
import "google/rpc/status.proto";

option go_package = "./backend/admin/v1;admin";

service Backend {
  rpc ListWaitlistSignups(google.protobuf.Empty) returns (ListWaitlistSignupsResponse);
  rpc AllowWaitlistSignup(AllowWaitlistSignupRequest) returns (Empty);
  rpc ListWallets(PaginationRequest) returns (ListWalletsResponse);
  rpc GetWalletDetails(GetWalletDetailsRequest) returns (WalletDetails);
  rpc ListTransactions(ListTransactionsRequest) returns (ListTransactionsResponse);
  rpc GetTransactionDetails(GetTransactionDetailsRequest) returns (GetTransactionDetailsResponse);
  rpc ListLinkedAccounts(ListLinkedAccountsRequest) returns (ListLinkedAccountsResponse);
  rpc ListAudit(ListAuditRequest) returns (ListAuditResponse);
  rpc GetWalletFeatures(GetWalletFeaturesRequest) returns (Features);
  rpc SetWalletFeatures(Features) returns (Features);
  rpc ListIncompleteLinkedAccountReviews(PaginationRequest) returns (LinkedAccountReviews);
  rpc GetLinkedAccountReview(GetLinkedAccountReviewRequest) returns (LinkedAccountReview);
  rpc CompleteLinkedAccountReview(CompleteLinkedAccountReviewRequest) returns(LinkedAccountReview);
}

message Empty {}

message LinkedAccountReview {
  string id = 1;
  string state = 2;
  string newState = 3;
  string linkedAccountID = 4;
  string reviewedBy = 5;
  string reason = 6;
  google.protobuf.Timestamp createdAt = 7; 
  google.protobuf.Timestamp completedAt = 8; 
}

message LinkedAccountReviews {
  repeated LinkedAccountReview reviews = 1;
}

message GetLinkedAccountReviewRequest {
  string id = 1;
}

message CompleteLinkedAccountReviewRequest {
  string id = 1;
  string reason = 2;
  string newState = 3;
}

message GetWalletFeaturesRequest {
  string walletID = 1;
}

message Features {
  bool sendEnabled = 1;
  bool receiveEnabled = 2;
  bool linkedAccountsEnabled = 3;
  bool cardsEnabled = 4;
  bool banksEnabled = 5;
  bool identitiesEnabled = 6;
  bool twitterEnabled = 7;
  string walletID = 8;
}

message ListAuditRequest {
  string walletID = 1;
}

message ListAuditResponse {
  repeated AuditOperation operations = 1;
}

message AuditOperation {
  string adminUser = 1;
  string walletID = 2;
  string operation = 3;
  string parameters = 4;
  google.protobuf.Timestamp timestamp = 5;
}

message ListLinkedAccountsRequest {
  string walletID = 1;
}

message ListLinkedAccountsResponse {
  repeated LinkedAccount accounts = 1;
}

message LinkedAccount {
  string id = 1;
  string walletID = 2;
  string name = 3;
  string nickname = 4;
  string mask = 5;
  string provider = 6;
  string providerID = 7;
  string type = 8;
}

message GetTransactionDetailsRequest {
  string walletID = 1;
  string transactionID = 2;
}

message GetTransactionDetailsResponse {
  Transaction transaction = 1;
  repeated Transfer transfers = 2;
}

message Transfer {
  string ID = 1;
  string linkedAccountID = 2;
  string linkedAccountProvider = 3;
  string linkedAccountType = 4;
  string foreignID = 9;
  double amount = 5;
  string currency = 6;
  string state = 7;
  google.protobuf.Timestamp timestamp = 8;
}

message ListTransactionsRequest {
  string walletID = 1;
  PaginationRequest page = 2;
}

message ListTransactionsResponse {
  repeated Transaction transactions = 1;
  string nextPageToken = 2;
}

message Transaction {
  string walletID = 8;
  string id = 1;
  string type = 2;
  string asset = 7;
  double amount = 3;
  string source = 4;
  string destination = 5;
  google.protobuf.Timestamp timestamp = 6;
}

message GetUserTransactionsRequest {
  string userID = 1;
}
message GetWalletDetailsRequest {
  string walletID = 1;
}

message WalletDetails {
  repeated User users = 8;
  string walletID = 1;
  string firstName = 2;
  string lastName = 3;
  string countryCode = 4;
  int32 gender = 5; // 0 Unknown, 1 Male, 2 Female, 3 Other
  google.protobuf.Timestamp dateOfBirth = 6;
  string address = 7;
  string kycStatus = 9;
  string placeOfBirth = 10;
  string nationality = 11;
}

message PaginationRequest {
  int32 pageSize = 1;
  optional string pageToken = 2;
}

message Wallet {
  string walletID = 1;
  string walletName = 2;
  repeated User users = 3;
}

message ListWalletsResponse {
  repeated Wallet wallets = 1;
  string nextPageToken = 2;
}

message User {
  string id = 1;
  string email = 2;
  string phoneNumber = 3;
}

message AllowWaitlistSignupRequest {
  string id = 1;
}

message ListWaitlistSignupsResponse {
  repeated WaitlistSignup signups = 1;
}

message WaitlistSignup {
  string id = 1;
  string name = 2;
  string email = 3;
  bool beta_opt_in = 4;
  bool can_signup = 5;
  string mug_id = 6;
  string country_code = 7;
}
