services:
  botanist:
    build:
      context: ../typescript/botanist
    container_name: botanist
    restart: always
    ports:
      - "13000:3000" # http port
      - "18002:8002" # websocket port
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/healthz || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
      - FYNBOS_ENV=local

      - CHOKIDAR_USEPOLLING=true
      - BACKEND_GRPC_URL=http://backend:8443
