apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tigerbeetle
spec:
  selector:
    matchLabels:
      app: tigerbeetle # has to match .spec.template.metadata.labels
  serviceName: tigerbeetle
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: tigerbeetle # has to match .spec.selector.matchLabels
    spec:
      serviceAccountName: tigerbeetle
      affinity:
        # don't co-locate replicas on the same node.
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - tigerbeetle
            topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-tigerbeetle
        image: donchangfoot/tigerbeetle
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/tigerbeetle
        env:
        - name: CLUSTER
          value: "0"
        command:
          - "/bin/bash"
          - "-c"
          - |
            set -ex
            REPLICA=${HOSTNAME##*-}
            FMT_CLUSTER=$(echo $CLUSTER | awk '{ printf("%010d\n", $1) }')
            FMT_REPLICA=$(echo $REPLICA | awk '{ printf("%03d\n", $1) }')
            ls /var/lib/tigerbeetle
            DATA_FILE=/var/lib/tigerbeetle/cluster_${FMT_CLUSTER}_replica_${FMT_REPLICA}.tigerbeetle
            if [[ ! -f "$DATA_FILE" ]]; then
              /opt/beta-beetle/tigerbeetle \
              init \
              --cluster=$CLUSTER \
              --replica=$REPLICA \
              --directory=/var/lib/tigerbeetle
            fi
      containers:
      - name: tigerbeetle
        image: donchangfoot/tigerbeetle
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/tigerbeetle
        env:
        - name: CLUSTER
          value: "0"
        command:
          - "/bin/bash"
          - "-c"
          - |
            set -ex
            REPLICA=${HOSTNAME##*-}
            /opt/beta-beetle/tigerbeetle \
            start \
            --cluster=$CLUSTER \
            --replica=$REPLICA \
            --directory=/var/lib/tigerbeetle \
            --addresses=0.0.0.0:8080
      # specify volume so that storage is independent of pod lifecycle.
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 256Mi
