// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sqlx "github.com/jmoiron/sqlx"
	account_transactions "gitlab.com/fynbos/backend/accounttransactions"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClient) Create(ctx context.Context, args *account_transactions.CreateTransactionArgs) (*account_transactions.AccountTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, args)
	ret0, _ := ret[0].(*account_transactions.AccountTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClientMockRecorder) Create(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClient)(nil).Create), ctx, args)
}

// CreatePending mocks base method.
func (m *MockClient) CreatePending(ctx context.Context, args *account_transactions.CreatePendingTransactionArgs) (*account_transactions.AccountTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePending", ctx, args)
	ret0, _ := ret[0].(*account_transactions.AccountTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePending indicates an expected call of CreatePending.
func (mr *MockClientMockRecorder) CreatePending(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePending", reflect.TypeOf((*MockClient)(nil).CreatePending), ctx, args)
}

// Get mocks base method.
func (m *MockClient) Get(ctx context.Context, id string) (*account_transactions.AccountTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*account_transactions.AccountTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClient)(nil).Get), ctx, id)
}

// GetByAccount mocks base method.
func (m *MockClient) GetByAccount(ctx context.Context, t *sqlx.Tx, args *account_transactions.GetByAccountArgs) ([]*account_transactions.AccountTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccount", ctx, t, args)
	ret0, _ := ret[0].([]*account_transactions.AccountTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccount indicates an expected call of GetByAccount.
func (mr *MockClientMockRecorder) GetByAccount(ctx, t, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccount", reflect.TypeOf((*MockClient)(nil).GetByAccount), ctx, t, args)
}

// GetPage mocks base method.
func (m *MockClient) GetPage(ctx context.Context, args *account_transactions.PaginationArgs) ([]account_transactions.AccountTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPage", ctx, args)
	ret0, _ := ret[0].([]account_transactions.AccountTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPage indicates an expected call of GetPage.
func (mr *MockClientMockRecorder) GetPage(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPage", reflect.TypeOf((*MockClient)(nil).GetPage), ctx, args)
}

// GetPageInfo mocks base method.
func (m *MockClient) GetPageInfo(ctx context.Context, accountID string, edges []account_transactions.AccountTransaction) (bool, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageInfo", ctx, accountID, edges)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetPageInfo indicates an expected call of GetPageInfo.
func (mr *MockClientMockRecorder) GetPageInfo(ctx, accountID, edges interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageInfo", reflect.TypeOf((*MockClient)(nil).GetPageInfo), ctx, accountID, edges)
}

// PostPending mocks base method.
func (m *MockClient) PostPending(ctx context.Context, id string) (*account_transactions.AccountTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostPending", ctx, id)
	ret0, _ := ret[0].(*account_transactions.AccountTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostPending indicates an expected call of PostPending.
func (mr *MockClientMockRecorder) PostPending(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostPending", reflect.TypeOf((*MockClient)(nil).PostPending), ctx, id)
}

// VoidPending mocks base method.
func (m *MockClient) VoidPending(ctx context.Context, id string) (*account_transactions.AccountTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VoidPending", ctx, id)
	ret0, _ := ret[0].(*account_transactions.AccountTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VoidPending indicates an expected call of VoidPending.
func (mr *MockClientMockRecorder) VoidPending(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VoidPending", reflect.TypeOf((*MockClient)(nil).VoidPending), ctx, id)
}
