// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	currency "github.com/interledger/interledger-app/go/backend/currency"
	db "github.com/interledger/interledger-app/go/backend/db"
	linkedaccounts "github.com/interledger/interledger-app/go/backend/linkedaccounts"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CanSendToWallet mocks base method.
func (m *MockClient) CanSendToWallet(ctx context.Context, sendWalletID, receiveWalletID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanSendToWallet", ctx, sendWalletID, receiveWalletID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanSendToWallet indicates an expected call of CanSendToWallet.
func (mr *MockClientMockRecorder) CanSendToWallet(ctx, sendWalletID, receiveWalletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanSendToWallet", reflect.TypeOf((*MockClient)(nil).CanSendToWallet), ctx, sendWalletID, receiveWalletID)
}

// CompleteReview mocks base method.
func (m *MockClient) CompleteReview(ctx context.Context, args linkedaccounts.CompleteReviewArgs) (*linkedaccounts.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteReview", ctx, args)
	ret0, _ := ret[0].(*linkedaccounts.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteReview indicates an expected call of CompleteReview.
func (mr *MockClientMockRecorder) CompleteReview(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteReview", reflect.TypeOf((*MockClient)(nil).CompleteReview), ctx, args)
}

// Create mocks base method.
func (m *MockClient) Create(ctx context.Context, args *linkedaccounts.CreateArgs) (*linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, args)
	ret0, _ := ret[0].(*linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClientMockRecorder) Create(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClient)(nil).Create), ctx, args)
}

// CreateBatch mocks base method.
func (m *MockClient) CreateBatch(ctx context.Context, args []linkedaccounts.CreateArgs) ([]linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, args)
	ret0, _ := ret[0].([]linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockClientMockRecorder) CreateBatch(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockClient)(nil).CreateBatch), ctx, args)
}

// CreateReviews mocks base method.
func (m *MockClient) CreateReviews(ctx context.Context, args []linkedaccounts.CreateReviewArgs) ([]linkedaccounts.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReviews", ctx, args)
	ret0, _ := ret[0].([]linkedaccounts.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReviews indicates an expected call of CreateReviews.
func (mr *MockClientMockRecorder) CreateReviews(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReviews", reflect.TypeOf((*MockClient)(nil).CreateReviews), ctx, args)
}

// Delete mocks base method.
func (m *MockClient) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClientMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClient)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockClient) Get(ctx context.Context, id string) (*linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClient)(nil).Get), ctx, id)
}

// GetByProviderID mocks base method.
func (m *MockClient) GetByProviderID(ctx context.Context, args linkedaccounts.GetByProviderIDArgs) (*linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProviderID", ctx, args)
	ret0, _ := ret[0].(*linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProviderID indicates an expected call of GetByProviderID.
func (mr *MockClientMockRecorder) GetByProviderID(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProviderID", reflect.TypeOf((*MockClient)(nil).GetByProviderID), ctx, args)
}

// GetDefaultReceive mocks base method.
func (m *MockClient) GetDefaultReceive(ctx context.Context, walletID string, cc currency.Currency) (*linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultReceive", ctx, walletID, cc)
	ret0, _ := ret[0].(*linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultReceive indicates an expected call of GetDefaultReceive.
func (mr *MockClientMockRecorder) GetDefaultReceive(ctx, walletID, cc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultReceive", reflect.TypeOf((*MockClient)(nil).GetDefaultReceive), ctx, walletID, cc)
}

// GetDefaultSend mocks base method.
func (m *MockClient) GetDefaultSend(ctx context.Context, walletID string, cc currency.Currency) (*linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultSend", ctx, walletID, cc)
	ret0, _ := ret[0].(*linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultSend indicates an expected call of GetDefaultSend.
func (mr *MockClientMockRecorder) GetDefaultSend(ctx, walletID, cc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultSend", reflect.TypeOf((*MockClient)(nil).GetDefaultSend), ctx, walletID, cc)
}

// GetReview mocks base method.
func (m *MockClient) GetReview(ctx context.Context, id string) (*linkedaccounts.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReview", ctx, id)
	ret0, _ := ret[0].(*linkedaccounts.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReview indicates an expected call of GetReview.
func (mr *MockClientMockRecorder) GetReview(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReview", reflect.TypeOf((*MockClient)(nil).GetReview), ctx, id)
}

// ListBalances mocks base method.
func (m *MockClient) ListBalances(ctx context.Context, walletID string) ([]linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalances", ctx, walletID)
	ret0, _ := ret[0].([]linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBalances indicates an expected call of ListBalances.
func (mr *MockClientMockRecorder) ListBalances(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalances", reflect.TypeOf((*MockClient)(nil).ListBalances), ctx, walletID)
}

// ListByProviderID mocks base method.
func (m *MockClient) ListByProviderID(ctx context.Context, provider, providerID string) ([]linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProviderID", ctx, provider, providerID)
	ret0, _ := ret[0].([]linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProviderID indicates an expected call of ListByProviderID.
func (mr *MockClientMockRecorder) ListByProviderID(ctx, provider, providerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProviderID", reflect.TypeOf((*MockClient)(nil).ListByProviderID), ctx, provider, providerID)
}

// ListByWalletId mocks base method.
func (m *MockClient) ListByWalletId(ctx context.Context, walletID string) ([]linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByWalletId", ctx, walletID)
	ret0, _ := ret[0].([]linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByWalletId indicates an expected call of ListByWalletId.
func (mr *MockClientMockRecorder) ListByWalletId(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByWalletId", reflect.TypeOf((*MockClient)(nil).ListByWalletId), ctx, walletID)
}

// ListIncompleteReviews mocks base method.
func (m *MockClient) ListIncompleteReviews(ctx context.Context, pagination db.Pagination) ([]linkedaccounts.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncompleteReviews", ctx, pagination)
	ret0, _ := ret[0].([]linkedaccounts.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncompleteReviews indicates an expected call of ListIncompleteReviews.
func (mr *MockClientMockRecorder) ListIncompleteReviews(ctx, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncompleteReviews", reflect.TypeOf((*MockClient)(nil).ListIncompleteReviews), ctx, pagination)
}

// ListReviews mocks base method.
func (m *MockClient) ListReviews(ctx context.Context, pagination db.Pagination) ([]linkedaccounts.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReviews", ctx, pagination)
	ret0, _ := ret[0].([]linkedaccounts.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReviews indicates an expected call of ListReviews.
func (mr *MockClientMockRecorder) ListReviews(ctx, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReviews", reflect.TypeOf((*MockClient)(nil).ListReviews), ctx, pagination)
}

// MarkNotDeleted mocks base method.
func (m *MockClient) MarkNotDeleted(ctx context.Context, id string) (*linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotDeleted", ctx, id)
	ret0, _ := ret[0].(*linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotDeleted indicates an expected call of MarkNotDeleted.
func (mr *MockClientMockRecorder) MarkNotDeleted(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotDeleted", reflect.TypeOf((*MockClient)(nil).MarkNotDeleted), ctx, id)
}

// SetDefaultReceive mocks base method.
func (m *MockClient) SetDefaultReceive(ctx context.Context, id string) (*linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultReceive", ctx, id)
	ret0, _ := ret[0].(*linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDefaultReceive indicates an expected call of SetDefaultReceive.
func (mr *MockClientMockRecorder) SetDefaultReceive(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultReceive", reflect.TypeOf((*MockClient)(nil).SetDefaultReceive), ctx, id)
}

// SetDefaultSend mocks base method.
func (m *MockClient) SetDefaultSend(ctx context.Context, id string) (*linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultSend", ctx, id)
	ret0, _ := ret[0].(*linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDefaultSend indicates an expected call of SetDefaultSend.
func (mr *MockClientMockRecorder) SetDefaultSend(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultSend", reflect.TypeOf((*MockClient)(nil).SetDefaultSend), ctx, id)
}

// SetNickname mocks base method.
func (m *MockClient) SetNickname(ctx context.Context, id, nickname string) (*linkedaccounts.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNickname", ctx, id, nickname)
	ret0, _ := ret[0].(*linkedaccounts.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNickname indicates an expected call of SetNickname.
func (mr *MockClientMockRecorder) SetNickname(ctx, id, nickname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNickname", reflect.TypeOf((*MockClient)(nil).SetNickname), ctx, id, nickname)
}
