// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GenerateDomainIdentity mocks base method.
func (m *MockClient) GenerateDomainIdentity(ctx context.Context, walletUrl, identifier string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDomainIdentity", ctx, walletUrl, identifier)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDomainIdentity indicates an expected call of GenerateDomainIdentity.
func (mr *MockClientMockRecorder) GenerateDomainIdentity(ctx, walletUrl, identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDomainIdentity", reflect.TypeOf((*MockClient)(nil).GenerateDomainIdentity), ctx, walletUrl, identifier)
}

// GenerateDomainIdentityOG mocks base method.
func (m *MockClient) GenerateDomainIdentityOG(ctx context.Context, walletUrl, identifier string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDomainIdentityOG", ctx, walletUrl, identifier)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDomainIdentityOG indicates an expected call of GenerateDomainIdentityOG.
func (mr *MockClientMockRecorder) GenerateDomainIdentityOG(ctx, walletUrl, identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDomainIdentityOG", reflect.TypeOf((*MockClient)(nil).GenerateDomainIdentityOG), ctx, walletUrl, identifier)
}

// GenerateSlackIdentity mocks base method.
func (m *MockClient) GenerateSlackIdentity(ctx context.Context, walletUrl, identifier string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSlackIdentity", ctx, walletUrl, identifier)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSlackIdentity indicates an expected call of GenerateSlackIdentity.
func (mr *MockClientMockRecorder) GenerateSlackIdentity(ctx, walletUrl, identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSlackIdentity", reflect.TypeOf((*MockClient)(nil).GenerateSlackIdentity), ctx, walletUrl, identifier)
}

// GenerateSlackIdentityOG mocks base method.
func (m *MockClient) GenerateSlackIdentityOG(ctx context.Context, walletUrl, identifier string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSlackIdentityOG", ctx, walletUrl, identifier)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSlackIdentityOG indicates an expected call of GenerateSlackIdentityOG.
func (mr *MockClientMockRecorder) GenerateSlackIdentityOG(ctx, walletUrl, identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSlackIdentityOG", reflect.TypeOf((*MockClient)(nil).GenerateSlackIdentityOG), ctx, walletUrl, identifier)
}

// GenerateTwitterIdentity mocks base method.
func (m *MockClient) GenerateTwitterIdentity(ctx context.Context, walletUrl, identifier string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTwitterIdentity", ctx, walletUrl, identifier)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTwitterIdentity indicates an expected call of GenerateTwitterIdentity.
func (mr *MockClientMockRecorder) GenerateTwitterIdentity(ctx, walletUrl, identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTwitterIdentity", reflect.TypeOf((*MockClient)(nil).GenerateTwitterIdentity), ctx, walletUrl, identifier)
}

// GenerateTwitterIdentityOG mocks base method.
func (m *MockClient) GenerateTwitterIdentityOG(ctx context.Context, walletUrl, identifier string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTwitterIdentityOG", ctx, walletUrl, identifier)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTwitterIdentityOG indicates an expected call of GenerateTwitterIdentityOG.
func (mr *MockClientMockRecorder) GenerateTwitterIdentityOG(ctx, walletUrl, identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTwitterIdentityOG", reflect.TypeOf((*MockClient)(nil).GenerateTwitterIdentityOG), ctx, walletUrl, identifier)
}
