dsn: "postgres://postgres:postgres@postgres:5432/kratos?sslmode=disable"
cookies:
  same_site: Strict
courier:
  templates:
    verification:
      valid:
        email:
          body:
            html: https://cdn.fynbos.app/emails/verification/v2/valid/email.body.gotmpl
            plaintext: https://cdn.fynbos.app/emails/verification/v2/valid/email.body.plaintext.gotmpl
          subject: https://cdn.fynbos.app/emails/verification/v2/valid/email.subject.gotmpl
      invalid:
        email:
          body:
            html: https://cdn.fynbos.app/emails/verification/v2/invalid/email.body.gotmpl
            plaintext: https://cdn.fynbos.app/emails/verification/v2/invalid/email.body.plaintext.gotmpl
          subject: https://cdn.fynbos.app/emails/verification/v2/invalid/email.subject.gotmpl
    recovery:
      valid:
        email:
          body:
            html: https://cdn.fynbos.app/emails/recovery/v2/valid/email.body.gotmpl
            plaintext: https://cdn.fynbos.app/emails/recovery/v2/valid/email.body.plaintext.gotmpl
          subject: https://cdn.fynbos.app/emails/recovery/v2/valid/email.subject.gotmpl
      invalid:
        email:
          body:
            html: https://cdn.fynbos.app/emails/recovery/v2/invalid/email.body.gotmpl
            plaintext: https://cdn.fynbos.app/emails/recovery/v2/invalid/email.body.plaintext.gotmpl
          subject: https://cdn.fynbos.app/emails/recovery/v2/invalid/email.subject.gotmpl
  smtp:
    from_address: no-reply@interledger.test
    connection_uri: "smtp://mailhog:1025/?disable_starttls=true"
hashers:
  algorithm: argon2
  argon2:
    dedicated_memory: 1GB
    expected_deviation: 500ms
    expected_duration: 500ms
    iterations: 1
    key_length: 16
    memory: 128MB
    parallelism: 1
    salt_length: 16
identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.json
log:
  format: text
  leak_sensitive_values: false
  level: debug
selfservice:
  allowed_return_urls:
    - http://interledger.test
    - https://interledger.test/*
  default_browser_return_url: http://interledger.test
  flows:
    error:
      ui_url: http://interledger.test/error
    login:
      after:
        default_browser_return_url: http://interledger.test
      lifespan: 10m
      ui_url: http://interledger.test/login
    logout:
      after:
        default_browser_return_url: http://interledger.test
    recovery:
      enabled: true
      lifespan: 15m
      ui_url: http://interledger.test/error
    registration:
      after:
        default_browser_return_url: http://interledger.test
        password:
          default_browser_return_url: http://interledger.test
          hooks:
            - hook: session
      enabled: true
      lifespan: 10m
      ui_url: http://interledger.test/signup
    settings:
      privileged_session_max_age: 15m
      ui_url: http://interledger.test/settings
    verification:
      after:
        default_browser_return_url: http://interledger.test
      enabled: true
      ui_url: http://interledger.test/verify
  methods:
    link:
      config:
        base_url: http://interledger.test
        lifespan: 1h
      enabled: true
    password:
      enabled: true
    totp:
      enabled: true
      config:
        issuer: interledger.app
    webauthn:
      enabled: true
      config:
        passwordless: false
        rp:
          display_name: "Interledger"
          id: interledger.test
          origins:
            - https://identity.interledger.test
            - https://interledger.test
    lookup_secret:
      enabled: true
serve:
  admin:
    port: 4434
  public:
    base_url: http://interledger.test
    cors:
      enabled: true
    port: 4433
session:
  cookie:
    domain: ""
    name: ory_kratos_session
    path: ""
    persistent: true
    same_site: Strict
  earliest_possible_extend: 24h
  lifespan: 420h
  whoami:
    required_aal: highest_available
