input {
  gelf {
    # port => 12201
    use_udp => false

    use_tcp => true
    port_tcp => 12202
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cocojambo"
  }
}
