workflow:
  rules:
    - changes:
      - go/**/*
    # we need to configure this pipeline to run on merge requests
    - if: $CI_MERGE_REQUEST_ID

stages:
  - install
  - lint
  - test
  - build

image: docker:19.03.12

# DinD service is required for Testcontainers
services:
  - name: docker:19.03.12-dind
    alias: docker

variables:
  # Instruct docker to use dind service
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

include:
  - '$CI_PROJECT_DIR/go/backend/.gitlab-ci.yml'
