.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    policy: pull-push
    key:
      files:
        - go/go.mod
    paths:
      - .go/pkg/mod/

go-mod:
  interruptible: true
  tags:
    - k8s
  image: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/docker:20.10
  extends: .go-cache
  rules:
    - changes:
        - go/go.mod
        - go/**/*.go
        - go/.golangci.yml
  script:
    - cd go
    - go mod download
    - make lintci
    - make lint
  artifacts:
    when: always
    reports:
      codequality: ./go/gl-code-quality-report.json
    paths:
      - ./go/gl-code-quality-report.json