.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    key:
      files:
        - go/go.mod
    paths:
      - .go/pkg/mod/

go-mod:
  image: public.ecr.aws/docker/library/golang:1.17
  extends: .go-cache
  script:
    - cd go
    - go mod download