syntax = "proto3";

package backend.v1;

import "google/rpc/code.proto";
import "google/rpc/error_details.proto";
import "google/rpc/status.proto";

option go_package = "./backend/v1;backend";

service BackendAdminService {
  rpc GetUserAccountByEmail(GetUserAccountByEmailRequest) returns (Account);
}

message GetUserAccountByEmailRequest {
  string email = 1;
}

message Account {
  string id = 1;
  int64 balance = 2;
  uint64 debitsReserved = 3;
  uint64 debitsAccepted = 4;
  uint64 creditsReserved = 5;
  uint64 creditsAccepted = 6;
}

message Empty {}

service BackendService {
  rpc GetBankAccountWidget(GetBankAccountWidgetRequest) returns (GetBankAccountWidgetResponse);
  rpc AddBankAccount(AddBankAccountRequest) returns (AddBankAccountResponse);
  rpc GetBankAccountDetails(GetBankAccountDetailsRequest) returns (BankAccountDetails);
  rpc ContinueAddingBankAccount(ContinueAddingBankAccountRequest) returns (ContinueAddingBankAccountResponse);
  // Returns the current onboarding flow.
  rpc GetOnboarding(GetOnboardingRequest) returns (Onboarding);
  // Creates the onboarding flow if it does not already exist.
  rpc UpdateOnboarding(Onboarding) returns (Onboarding);
  // Allows sending and checking an sms verification.
  rpc SendPhoneVerification(SendPhoneVerificationRequest) returns (PhoneVerificationResponse);
  rpc CheckPhoneVerificationCode(CheckPhoneVerificationCodeRequest) returns (PhoneVerificationResponse);
  rpc SendOTP(Empty) returns (Empty);
  // Allows signing agreements and getting agreements by id.
  rpc GetAgreement(GetAgreementRequest) returns (Agreement);
  rpc SignAgreements(SignAgreementsRequest) returns (SignAgreementsResponse);
  rpc JoinWaitlist(JoinWaitlistRequest) returns (JoinWaitlistResponse);
  rpc GetLinkedAccounts(Empty) returns (GetLinkedAccountsResponse);
  rpc CreateSupportTicket(CreateSupportTicketRequest) returns (Empty);
  rpc GetCountries(Empty) returns (GetCountriesResponse);
}

message GetStatementsResponse {
  message Statement {
    string id = 1;
    string period = 2;
    string accountId = 3;
  }

  repeated Statement statements = 1;
}

message GetStatementPDFRequest {
  string statementId = 1;
}

message GetStatementPDFResponse {
  string id = 1;
  bytes statementPdf = 2;
}

message CreateSupportTicketRequest {
  string description = 1;
  string firstName = 2;
  string lastName = 3;
  string email = 4;
}

message GetBankAccountWidgetRequest {}

message GetBankAccountWidgetResponse {
  string url = 1;
}

message AddBankAccountRequest {
  string userGuid = 1;
  string memberGuid = 2;
}

message AddBankAccountResponse {
  string fundingsourceId = 1;
}

message LinkedAccount {
  string id = 1;
  string type = 2;
  string name = 3;
  string mask = 4;
}

message GetOnboardingRequest {
  string id = 1;
}

message Onboarding {
  optional string id = 1;
  optional string first_name = 2;
  optional string last_name = 3;
  optional string country_of_residence = 4;
  optional string email = 5;
  optional string phone = 6;
  optional bool phone_verified = 7;
  optional bool service_agreement = 8;
}

message SendPhoneVerificationRequest {
  string to = 1;
  string onboardingId = 2;
}

message CheckPhoneVerificationCodeRequest {
  string to = 1;
  string code = 2;
  string onboardingId = 3;
}

message PhoneVerificationResponse {
  // The status from twilio. Can be "approved" or "pending"
  string status = 1;
}

message GetAgreementRequest {
  string id = 1;
}

message Agreement {
  string content = 1;
}

message SignAgreementsRequest {
  repeated string agreementIds = 1;
  string userId = 2;
  string ipAddress = 3;
}

message SignAgreementsResponse {
  bool signed = 1;
}

message JoinWaitlistRequest {
  string email = 1;
  string country_code = 2;
  string full_name = 3;
}

message JoinWaitlistResponse {}

message GetLinkedAccountsResponse {
  repeated LinkedAccount linkedAccounts = 1;
}

message GetBankAccountDetailsRequest {
  string fundingsourceId = 1;
}

message BankAccountDetails {
  string fundingsourceId = 1;
  string Type = 2;
  string institution = 3;
  string mask = 4;
}

message ContinueAddingBankAccountRequest {
  string fundingsourceId = 1;
  string otp = 2;
  string nickName = 3;
}

message ContinueAddingBankAccountResponse {
  bool success = 1;
  string error = 2;
}

message Country {
  string id =1;
  string name = 2;
}

message GetCountriesResponse {
  repeated Country countries = 1;
}
