syntax = "proto3";

package backend.v1;

import "google/protobuf/timestamp.proto";
import "google/rpc/code.proto";
import "google/rpc/error_details.proto";
import "google/rpc/status.proto";

option go_package = "./backend/v1;backend";

message PaginationRequest {
  int32 pageSize = 1;
  optional string pageToken = 2;
}

service OpenPaymentService {
  rpc CreatePaymentPointer(CreatePaymentPointerRequest) returns (Empty);
  rpc GetPaymentPointer(GetPaymentPointerRequest) returns (PaymentPointer);
  rpc PaymentPointerExists(PaymentPointerExistsRequest) returns (PaymentPointerExistsResponse);
  rpc ListWalletPaymentPointers(Empty) returns (ListWalletPaymentPointersResponse);
  rpc CreateQuote(CreateQuoteRequest) returns (Quote);
  rpc LookupQuote(LookupQuoteRequest) returns (Quote);
  rpc CreateIncomingPayment(CreateIncomingPaymentRequest) returns (IncomingPayment);
  rpc LookupIncomingPayment(LookupIncomingPaymentRequest) returns (IncomingPayment);
  rpc PreCheckOutgoingPayment(PreCheckOutgoingPaymentRequest) returns (PreCheckOutgoingPaymentResponse);
  rpc CreateOutgoingPayment(CreateOutgoingPaymentRequest) returns (OutgoingPayment);
  rpc LookupOutgoingPayment(LookupOutgoingPaymentRequest) returns (OutgoingPayment);
  rpc CanSendToPaymentPointer(CanSendToPaymentPointerRequest) returns (CanSendToPaymentPointerResponse);
}

message CanSendToPaymentPointerRequest {
  string paymentPointer = 1;
}

message CanSendToPaymentPointerResponse {
  bool canSend = 1;
}

message Transaction {
  string id = 1;
  string type = 2;
  Amount amount = 3;
  string source = 4;
  string destination = 5;
  google.protobuf.Timestamp timestamp = 6;
  string state = 7;
  repeated Transfer transfers = 8;
  string foreignId = 9;

  // Display
  string title = 10;
  string formattedAmount = 11;
  string formattedTime = 12;
  string formattedDate = 13;
  string subtotal = 14;
  string fees = 15;
  string accountTitle = 16;
  string reference = 17;
  string destinationIdentity = 18;
  string destinationIdentityType = 19;
}

message ListTransactionsResponse {
  repeated Transaction transactions = 1;
  string nextPageToken = 2;
}

message Amount {
  uint64 amount = 1;
  string asset = 2;
  int32 assetScale = 3;
}

message LookupOutgoingPaymentRequest {
  string id = 1;
}

message ThreeDS {
  string id = 1;
  string jwt = 2;
  string deviceCollectionURL = 3;
  string songbirdURL = 4;
}

message OutgoingPayment {
  string id = 1;
  string paymentPointer = 2;
  string toPaymentPointer = 11;
  bool failed = 3;
  string receiver = 4;
  Amount sendAmount = 5;
  Amount receiveAmount = 6;
  Amount sentAmount = 7;
  string description = 8;
  google.protobuf.Timestamp createdAt = 9;
  google.protobuf.Timestamp updatedAt = 10;
}

message PreCheckOutgoingPaymentRequest {
  string quoteID = 1;
}

message PreCheckOutgoingPaymentResponse {
  bool exceedsLimits = 1;
  string limitType = 2; // ANNUAL, MONTHLY, DAILY, HOLD (MAX BALANCE)
  bool insufficientBalance = 3;
}

message CreateOutgoingPaymentRequest {
  string quoteID = 1;
  string description = 2;
  string externalRef = 3;
  string ipAddress = 4;
  string idempotencyKey = 5;
  string threeDSID = 6;
  string identity = 7;
  string identityType = 8;
}

message LookupIncomingPaymentRequest {
  string id = 1;
}

message CreateIncomingPaymentRequest {
  string paymentPointer = 1;
  optional Amount amount = 2;
  string reference = 3;
  google.protobuf.Timestamp expiresAt = 4;
}

message IncomingPayment {
  string id = 1;
  string paymentPointer = 2;
  string fromPaymentPointer = 10;
  optional Amount incomingAmount = 3;
  optional Amount receivedAmount = 4;
  bool completed = 5;
  string externalRef = 6;
  google.protobuf.Timestamp expiresAt = 7;
  google.protobuf.Timestamp createdAt = 8;
  google.protobuf.Timestamp updatedAt = 9;
}

message LookupQuoteRequest {
  string id = 1;
}

message CreateQuoteRequest {
  string sendPaymentPointer = 1;
  string receivePaymentPointer = 2;
  Amount amount = 3;
  google.protobuf.Timestamp expiresAt = 4;
  string description = 5;
  optional string sendLinkedAccount = 6;
}

message Quote {
  string id = 1;
  string paymentPointer = 2;
  string receiver = 3;
  Amount sendAmount = 4;
  Amount receiveAmount = 5;
  google.protobuf.Timestamp expiresAt = 6;
  google.protobuf.Timestamp createdAt = 7;
}

message PaymentPointerExistsRequest {
  string url = 1;
}

message PaymentPointerExistsResponse {
  bool exists = 1;
}

message GetPaymentPointerRequest {
  string url = 1;
}

message ListWalletPaymentPointersResponse {
  repeated PaymentPointer pointers = 1;
}

message CreatePaymentPointerRequest {
  string url = 1;
  string asset = 2;
  int32 assetScale = 3;
  string alias = 4;
}

message PaymentPointer {
  string url = 1;
  string asset = 2;
  int32 assetScale = 3;
  string alias = 4;
  string walletID = 5;
  string formatted = 6;
  string legalName = 7;
}

message Empty {}

service BackendService {
  rpc UpdateIndividualKYC(UpdateIndividualKYCRequest) returns (Empty);
  rpc GetIndividualKYC(Empty) returns (IndividualKYCResponse);
  rpc IsUSPSAddress(Address) returns (IsUSPSAddressResponse);
  rpc SetSignupUserData(SetSignupUserDataRequest) returns (SetSignupUserDataResponse);
  rpc SetSignupMobileNumber(SetSignupMobileNumberRequest) returns (Empty);
  // Returns the current signup flow.
  rpc GetSignup(GetSignupRequest) returns (Signup);
  // Called after the user is created on Kratos with the new userID.
  rpc CompleteSignup(CompleteSignupRequest) returns (Empty);
  rpc CreateUserDefaultWallet(CreateUserDefaultWalletRequest) returns (Empty);
  // Wallet
  rpc SetWalletName(SetWalletNameRequest) returns (Empty);
  rpc GetWalletInfo(Empty) returns (WalletInfo);
  // Allows sending and checking an sms verification.
  rpc SendPhoneVerification(SendPhoneVerificationRequest) returns (Empty);
  rpc SendOTP(Empty) returns (Empty);
  // Allows signing agreements and getting agreements by id.
  rpc GetAgreement(GetAgreementRequest) returns (Agreement);
  rpc SignAgreements(SignAgreementsRequest) returns (SignAgreementsResponse);
  rpc GetLinkedAccounts(Empty) returns (GetLinkedAccountsResponse);
  rpc GetLinkedAccount(GetLinkedAccountRequest) returns (LinkedAccount);
  rpc SetNicknameLinkedAccount(SetNicknameLinkedAccountRequest) returns (LinkedAccount);
  rpc DeleteLinkedAccount(DeleteLinkedAccountRequest) returns (Empty);
  rpc CreateSupportTicket(CreateSupportTicketRequest) returns (Empty);
  rpc GetCountries(Empty) returns (GetCountriesResponse);
  rpc GetCurrentWallet(Empty) returns (GetCurrentWalletResponse);

  //Waitlist
  rpc JoinWaitlist(JoinWaitlistRequest) returns (JoinWaitlistResponse);
  rpc CanSignup(CanSignupRequest) returns (CanSignupResponse);
  rpc SetSignupComplete(SetSignupCompleteRequest) returns (Empty);
  rpc IsMugAvailable(IsMugAvailableRequest) returns (IsMugAvailableResponse);

  //Transactions
  rpc ListTransactions(PaginationRequest) returns (ListTransactionsResponse);
  rpc ListTransactionsCompleted(PaginationRequest) returns (ListTransactionsResponse);
  rpc ListTransactionsWithPending(PaginationRequest) returns (ListTransactionsResponse);
  rpc LookupTransaction(LookupTransactionRequest) returns (Transaction);

  // Limits GNAP
  rpc ListLimits(Empty) returns (ListLimitsResponse);
  rpc UpdateClientLimits(UpdateClientLimitsRequest) returns (Empty);

  //Connections
  rpc CreateConnection(CreateConnectionRequest) returns (Empty);
  rpc ListConnections(Empty) returns (ListConnectionsResponse);
  rpc GetConnection(GetConnectionRequest) returns (Connection);
  rpc GetConnectionLimits(GetConnectionLimitsRequest) returns (ConnectionLimits);
  rpc UpdateConnectionLimits(UpdateConnectionLimitsRequest) returns (Empty);
  rpc DeleteConnection(DeleteConnectionRequest) returns (Empty);

  // Public Wallet Data
  rpc GetPublicWalletDetails(GetPublicWalletDetailsRequest) returns (GetPublicWalletDetailsResponse);

  // Contacts
  rpc CreateContact(CreateContactRequest) returns (Contact);
  rpc ListContacts(ListContactsRequest) returns (ListContactsResponse);

  // Identities
  rpc ListIdentities(Empty) returns (ListIdentitiesResponse);
  rpc ListPublicIdentities(ListPublicIdentitiesRequest) returns (ListIdentitiesResponse);
  rpc DeleteIdentity(DeleteIdentityRequest) returns (Empty);
  rpc SetIdentityPublic(SetIdentityPublicRequest) returns (Identity);
  rpc GetIdentity(GetIdentityRequest) returns (GetIdentityResponse);
  rpc GetIdentityBySignatureHash(GetIdentityBySignatureHashRequest) returns (GetIdentityResponse);

  // KYC
  rpc KYCStatus(Empty) returns (KYCStatusResponse);
  rpc StartKYC(Empty) returns (Empty);
  rpc GetPersonaInquiry(KYCPersonaInquiryRequest) returns (KYCPersonaInquiryResponse);

  // MX
  rpc GetMXWidget(Empty) returns (MXWidgetResponse);
  rpc CreateMXBankAccounts(CreateMXBankAccountsRequest) returns (CreateMXBankAccountsResponse);

  // GMT
  rpc OnboardGMTUser(Empty) returns (Empty);

  // Tabapay 3DS
  rpc Init3DS(Init3DSRequest) returns (Init3DSResponse);
  rpc Lookup3DS(Lookup3DSRequest) returns (Lookup3DSResponse);
  rpc Authenticate3DS(Authenticate3DSRequest) returns (Authenticate3DSResponse);

  // Basistheory
  rpc CreateCard(CreateCardRequest) returns (Empty);

  // Features
  rpc ListFeatures(Empty) returns (Features);

  // Twitter
  rpc CreateTwitterAuthURL(Empty) returns (CreateTwitterAuthURLResponse);
  rpc TwitterCallback(TwitterCallbackRequest) returns (TwitterCallbackResponse);
  rpc VerifyTwitter(VerifyTwitterRequest) returns (Empty);

  // Payments
  rpc GetPaymentAddress(GetPaymentAddressRequest) returns (GetPaymentAddressResponse);

  // Search
  rpc SearchWallets(SearchWalletsRequest) returns (SearchWalletsResponse);
}

message SearchWalletsRequest {
  string term = 1;
}

message SearchWalletsResponse {
  repeated SearchResult results = 1;
}

message SearchResult {
  string walletID = 1;
  string identifier = 2;
  string identifierType = 3;
}

message WalletInfo {
  string walletID = 1;
  string url = 2;
  string formattedURL = 3;
  bool hasCard = 4;
  bool hasBank = 5;
  bool hasIdentities = 6;
  bool hasTransacted = 7;
  bool hasWalletAddress = 8;
}

message Features {
  bool sendEnabled = 1;
  bool receiveEnabled = 2;
  bool linkedAccountsEnabled = 3;
  bool cardsEnabled = 4;
  bool banksEnabled = 5;
  bool identitiesEnabled = 6;
  bool twitterEnabled = 7;
}

message CreateCardRequest {
  string tokenID = 1;
}

message Init3DSRequest {
  string idempotencyKey = 1;
  string quoteID = 2;
}

message Init3DSResponse {
  string id = 1;
  string jwt = 2;
  string deviceCollectionURL = 3;
  string songbirdURL = 4;
}

message Lookup3DSResponse {
  string processorTransactionID = 1;
  string challengeURL = 2;
  string payload = 3;
}

message Lookup3DSRequest {
  string idempotencyKey = 1;
  string threeDSID = 2;
  bool  javascriptEnabled = 3;
  string userAgent = 4;
  string header = 5;
  bool javaEnabled = 6;
  string language = 7;
  string colorDepth = 8;
  string screenHeight =9;
  string screenWidth = 10;
  string timezone = 11;
  string ipAddress = 12;
}

message Authenticate3DSRequest {
  string idempotencyKey = 1;
  string threeDSID = 2;
  string jwt = 3;
}

message Authenticate3DSResponse {
  string status = 1;
}

message CreateMXBankAccountsRequest {
  string sessionGuid = 1;
  string userGuid = 2;
  string memberGuid = 3;
}

message CreateMXBankAccountsResponse {
  repeated LinkedAccount linkedAccounts = 1;
}

message MXWidgetResponse {
  string url = 1;
}

message ConnectionLimits {
  Amount daily = 1;
  Amount monthly = 2;
  Amount overall = 3;
}

message Connection {
  string id = 1;
  string applicationName = 2;
  string publicKeyFingerprint = 3;
  string createdAt = 4;
  string lastUsedAt = 5;
}

message CreateConnectionRequest {
  string applicationName = 1;
  string publicKey = 2; // pem encoded ed25519 public key
  Amount dailyLimit = 3;
  Amount monthlyLimit = 4;
  Amount overallLimit = 5;
}

message GetConnectionRequest {
  string id = 1;
}

message GetConnectionLimitsRequest {
  string id = 1;
}

message DeleteConnectionRequest {
  string id = 1;
}

message ListConnectionsResponse {
  repeated Connection keys = 1;
}

message UpdateConnectionLimitsRequest {
  string id = 1;
  Amount daily = 2;
  Amount monthly = 3;
  Amount overall = 4;
}

message Transfer {
  string type = 1;
  string state = 2;
  google.protobuf.Timestamp timestamp = 3;
  Amount amount = 4;
  string foreignId = 5;
  string linkedAccountId = 6;
}

message ListStatementsResponse {
  repeated string periods = 1;
  string nextPageToken = 2;
}

message CreateSupportTicketRequest {
  string description = 1;
  string firstName = 2;
  string lastName = 3;
  string email = 4;
}

message IndividualKYCResponse {
  string firstName = 1;
  string lastName = 2;
  string countryCode = 3;
  int32 gender = 4; // 0 Unknown, 1 Male, 2 Female, 3 Other
  google.protobuf.Timestamp dateOfBirth = 5;
  Address address = 6;
  string placeOfBirth = 7;
  string nationality = 8;
}

message UpdateIndividualKYCRequest {
  optional string firstName = 1;
  optional string lastName = 2;
  optional string countryCode = 3;
  optional int32 gender = 4; // 0 Unknown, 1 Male, 2 Female, 3 Other
  optional google.protobuf.Timestamp dateOfBirth = 5;
  optional Address address = 6;
  string ipAddress = 7;
  optional string placeOfBirth = 8;
  optional string nationality = 9;
}

message Address {
  optional string line1 = 1;
  optional string line2 = 2;
  optional string building = 3;
  optional string apartment = 4;
  optional string city = 5;
  optional string state = 6;
  optional string zipCode = 7;
  optional string countryCode = 8;
  optional string placeID = 9;
  optional string formattedAddress = 10;
}

message IsUSPSAddressResponse {
  bool valid = 1;
}

message GetBankAccountWidgetRequest {}

message GetBankAccountWidgetResponse {
  string url = 1;
}

message AddBankAccountRequest {
  string userGuid = 1;
  string memberGuid = 2;
}

message AddBankAccountResponse {
  string fundingsourceId = 1;
}

message LinkedAccount {
  string id = 1;
  string type = 2;
  string name = 3;
  string mask = 4;
  string nickname = 5;

  // Display
  bool canSend = 6;
  bool canReceive = 7;
  string title = 8;
}

message GetSignupRequest {
  string id = 1;
}

message SetSignupUserDataRequest {
  optional string id = 1;
  string firstName = 2;
  string lastName = 3;
  string email = 4;
  string countryCode = 5;
}

message SetSignupUserDataResponse {
  string id = 1;
}

message SetSignupMobileNumberRequest {
  string id = 1;
  string mobile = 2;
  string otp = 3;
}

message Signup {
  string id = 1;
  string firstName = 2;
  string lastName = 3;
  string email = 4;
  string countryCode = 5;
  string mobileNumber = 6;
  string userId = 7;
  bool completed = 8;
}

message CompleteSignupRequest {
  string id = 1;
  string userId = 2;
}

message CreateUserDefaultWalletRequest {
  string userID = 1;
}

message SendPhoneVerificationRequest {
  string to = 1;
}

message GetAgreementRequest {
  string id = 1;
}

message Agreement {
  string content = 1;
}

message SignAgreementsRequest {
  repeated string agreementIds = 1;
  string userId = 2;
  string ipAddress = 3;
}

message SignAgreementsResponse {
  bool signed = 1;
}

message JoinWaitlistRequest {
  string email = 1;
  string country_code = 2;
  string full_name = 3;
  bool beta_opt_in = 4;
  optional string mug_id = 5;
}

message JoinWaitlistResponse {}

message IsMugAvailableRequest {
  string mug_id = 1;
}

message IsMugAvailableResponse {
  bool available = 1;
}

message GetLinkedAccountsResponse {
  repeated LinkedAccount linkedAccounts = 1;
}

message GetLinkedAccountRequest {
  string id = 1;
}

message SetNicknameLinkedAccountRequest {
  string id = 1;
  string nickname = 2;
}

message DeleteLinkedAccountRequest {
  string id = 1;
}

message Country {
  string id = 1;
  string name = 2;
}

message GetCountriesResponse {
  repeated Country countries = 1;
}

message CanSignupRequest {
  string id = 1;
}

message CanSignupResponse {
  bool canSignup = 1;
}

message SetSignupCompleteRequest {
  string id = 1;
  string userId = 2;
}

message StartMachnetWalletTopupRequest {
  string fromLinkedAccountId = 1;
  uint64 amount = 2;
  string ipAddress = 3;
  string currency = 4;
  string idempotencyKey = 5;
}

message LookupTransactionRequest {
  string id = 1;
}

message GetCurrentWalletResponse {
  string id = 1;
}

message Limit {
  LimitAmount Annual = 1;
  LimitAmount Daily = 2;
  LimitAmount Monthly = 3;
  LimitAmount WalletHold = 4;
}

message LimitAmount {
  string remaining = 1;
  string total = 2;
  int32 percentage = 3;
}

message SetWalletNameRequest {
  string name = 1;
}

message GetPublicWalletDetailsRequest {
  string id = 1;
}

message GetPublicWalletDetailsResponse {
  string id = 1;
  string publicName = 2;
}

message ListLimitsResponse {
  repeated ConfiguredLimit limits = 1;
}

message ConfiguredLimit {
  string foreignId = 1;
  string foreignDisplay = 2;
  string foreignType = 3;
  Amount daily = 4;
  Amount monthly = 5;
  Amount overall = 6;
}

message UpdateClientLimitsRequest {
  string clientUrl = 1;
  Amount daily = 2;
  Amount monthly = 3;
  Amount overall = 4;
}

message Contact {
  string id = 1;
  string payment_pointer = 2;
  string name = 3;
  string wallet_id = 4;
}

message ListContactsRequest {
  int32 page_size = 1;
  optional string page_token = 2;
  optional string order_by = 3;
}

message ListContactsResponse {
  repeated Contact contacts = 1;
  string next_page_token = 2;
}

message CreateContactRequest {
  string payment_pointer = 1;
}

message ListIdentitiesResponse {
  repeated Identity identities = 1;
}

message Identity {
  string id = 1;
  string wallet = 2;
  string platform = 3;
  string identifier = 4;
  string state = 5;
  string key_id = 6;
  string signature = 7;
  string signature_hash = 8;
  string proof = 9;
  string ctime = 10;
  bool public = 11;
  google.protobuf.Timestamp verified_at = 12;
  string wallet_id = 13;
}

message IdentityVerificationInstructions {
  string identity_id = 1;
  string code = 2;
  string instructions = 3;
}

message DeleteIdentityRequest {
  string id = 1;
}

message SetIdentityPublicRequest {
  string id = 1;
  bool public = 2;
}

message ListPublicIdentitiesRequest {
  string wallet_id = 1;
}

message KYCStatusResponse {
  int32 kyc_status = 1;
}

message KYCPersonaInquiryRequest {
  optional string idempotency_key = 1;
}

message KYCPersonaInquiryResponse {
  string id = 1;
  optional string session_token = 2;
}

message CreateTwitterAuthURLResponse {
  string url = 1;
}

message TwitterCallbackRequest {
  string state = 1;
  string code = 2;
}

message TwitterCallbackResponse {
  string id = 1;
}

message GetIdentityRequest{
  string id = 1;
}

message GetIdentityResponse{
   Identity identity = 1;
}

message VerifyTwitterRequest {
  string identity_id = 1;
}

message GetIdentityBySignatureHashRequest{
  string signature_hash = 1;
}

message GetPaymentAddressRequest {
  string address = 1;
}

message GetPaymentAddressResponse {
  string wallet_url = 1;
  string type = 2; // wallet, twitter
  string handle = 3; // url or twitter handle
  bool canSendToAddress = 4;
}
