syntax = "proto3";

package backend.v1;

import "google/rpc/code.proto";
import "google/rpc/error_details.proto";
import "google/rpc/status.proto";

option go_package = "./backend/v1;backend";

service BackendAdminService {
  rpc GetUserAccountByEmail(GetUserAccountByEmailRequest) returns (Account);
}

message GetUserAccountByEmailRequest {
  string email = 1;
}

message Account {
  string id = 1;
  int64 balance = 2;
  uint64 debitsReserved = 3;
  uint64 debitsAccepted = 4;
  uint64 creditsReserved = 5;
  uint64 creditsAccepted = 6;
}


service OpenPaymentService {
  rpc CreatePaymentPointer(CreatePaymentPointerRequest) returns (Empty);
  rpc GetPaymentPointer(GetPaymentPointerRequest) returns (PaymentPointer);
  rpc PaymentPointerExists(PaymentPointerExistsRequest) returns (PaymentPointerExistsResponse);
  rpc ListWalletPaymentPointers(Empty) returns (ListWalletPaymentPointersResponse);
}

message PaymentPointerExistsRequest {
  string url = 1;
}

message PaymentPointerExistsResponse {
  bool exists = 1;
}

message GetPaymentPointerRequest {
  string url = 1;
}

message ListWalletPaymentPointersResponse {
  repeated PaymentPointer pointers = 1;
}

message CreatePaymentPointerRequest {
  string url = 1;
  string asset = 2;
  int32 assetScale = 3;
  string alias = 4;
}

message PaymentPointer {
  string url = 1;
  string asset = 2;
  int32 assetScale = 3;
  string alias = 4;
  string walletID = 5;
}

message Empty {}

service BackendService {
  rpc GetBankAccountWidget(GetBankAccountWidgetRequest) returns (GetBankAccountWidgetResponse);
  rpc AddBankAccount(AddBankAccountRequest) returns (AddBankAccountResponse);
  rpc GetBankAccountDetails(GetBankAccountDetailsRequest) returns (BankAccountDetails);
  rpc ContinueAddingBankAccount(ContinueAddingBankAccountRequest) returns (ContinueAddingBankAccountResponse);

  rpc SetSignupUserData(SetSignupUserDataRequest) returns (SetSignupUserDataResponse);
  rpc SetSignupMobileNumber(SetSignupMobileNumberRequest) returns (Empty);
  // Returns the current signup flow.
  rpc GetSignup(GetSignupRequest) returns (Signup);
  // Called after the user is created on Kratos with the new userID.
  rpc CompleteSignup(CompleteSignupRequest) returns (Empty);
  rpc CreateUserDefaultWallet(CreateUserDefaultWalletRequest) returns (Empty);
  // Allows sending and checking an sms verification.
  rpc SendPhoneVerification(SendPhoneVerificationRequest) returns (Empty);
  rpc SendOTP(Empty) returns (Empty);
  // Allows signing agreements and getting agreements by id.
  rpc GetAgreement(GetAgreementRequest) returns (Agreement);
  rpc SignAgreements(SignAgreementsRequest) returns (SignAgreementsResponse);
  rpc JoinWaitlist(JoinWaitlistRequest) returns (JoinWaitlistResponse);
  rpc GetLinkedAccounts(Empty) returns (GetLinkedAccountsResponse);
  rpc CreateSupportTicket(CreateSupportTicketRequest) returns (Empty);
  rpc GetCountries(Empty) returns (GetCountriesResponse);
  rpc LinkCashAccount(LinkCashAccountRequest) returns (LinkedAccount);
}

message GetStatementsResponse {
  message Statement {
    string id = 1;
    string period = 2;
    string accountId = 3;
  }

  repeated Statement statements = 1;
}

message GetStatementPDFRequest {
  string statementId = 1;
}

message GetStatementPDFResponse {
  string id = 1;
  bytes statementPdf = 2;
}

message CreateSupportTicketRequest {
  string description = 1;
  string firstName = 2;
  string lastName = 3;
  string email = 4;
}

message GetBankAccountWidgetRequest {}

message GetBankAccountWidgetResponse {
  string url = 1;
}

message AddBankAccountRequest {
  string userGuid = 1;
  string memberGuid = 2;
}

message AddBankAccountResponse {
  string fundingsourceId = 1;
}

message LinkedAccount {
  string id = 1;
  string type = 2;
  string name = 3;
  string mask = 4;
}

message GetSignupRequest {
  string id = 1;
}

message SetSignupUserDataRequest {
  optional string id = 1;
  string firstName = 2;
  string lastName = 3;
  string email = 4;
  string countryCode = 5;
}

message SetSignupUserDataResponse {
  string id = 1;
}

message SetSignupMobileNumberRequest {
  string id = 1;
  string mobile = 2;
  string otp = 3;
}

message Signup {
  string id = 1;
  string firstName = 2;
  string lastName = 3;
  string email = 4;
  string countryCode = 5;
  string mobileNumber = 6;
  string userId = 7;
  bool completed = 8;
}

message CompleteSignupRequest {
  string id = 1;
  string userId = 2;
}

message CreateUserDefaultWalletRequest {
  string userID = 1;
}

message SendPhoneVerificationRequest {
  string to = 1;
}

message GetAgreementRequest {
  string id = 1;
}

message Agreement {
  string content = 1;
}

message SignAgreementsRequest {
  repeated string agreementIds = 1;
  string userId = 2;
  string ipAddress = 3;
}

message SignAgreementsResponse {
  bool signed = 1;
}

message JoinWaitlistRequest {
  string email = 1;
  string country_code = 2;
  string full_name = 3;
}

message JoinWaitlistResponse {}

message GetLinkedAccountsResponse {
  repeated LinkedAccount linkedAccounts = 1;
}

message GetBankAccountDetailsRequest {
  string fundingsourceId = 1;
}

message BankAccountDetails {
  string fundingsourceId = 1;
  string Type = 2;
  string institution = 3;
  string mask = 4;
}

message ContinueAddingBankAccountRequest {
  string fundingsourceId = 1;
  string otp = 2;
  string nickName = 3;
}

message ContinueAddingBankAccountResponse {
  bool success = 1;
  string error = 2;
}

message Country {
  string id =1;
  string name = 2;
}

message GetCountriesResponse {
  repeated Country countries = 1;
}

message LinkCashAccountRequest {
  string name = 1;
}
