sequenceDiagram
    title Incoming Payment Completed/Expired

    participant RA as Rafiki Admin
    participant R as Rafiki
    participant WB as Wallet Backend
    participant T as Temporal (Workflows)
    participant P as Provider (GateHub)

    R ->> WB: Send webhook
    WB ->> WB: Validate signature
    alt not valid
        WB ->>R: Return 400
    end
    WB ->> WB: Determine webhook type
    alt unknown webhook type
        WB ->> WB: Log unknown webhook type
        WB ->>R: Return 200
    end 
    WB ->> WB: Webhook type is incoming_payment.completed/expired
    WB ->> T: Start workflow RafikiIncomingPaymentFinalized
    alt cannot start workflow
        T ->> WB: Returns error
        WB ->> R: Return 400
    else
        T ->> WB: Workflow started
        WB ->> R: Return 200 (ACKNOWLEDGED)
    end

    Note over T: Async Workflow
    T ->> T: Ensure the incoming payment has received amount value > 0
    alt no amount
    T ->> T: Nothing to do
    else has amount
        T ->> P: Transfer from intermediary  account<br/>to user account
        alt Bad response
            P ->> T: Non 200 status code
            T ->> T: Retry mechanism
        else 200 status code
            P ->> T: OK
        end
        T ->> T: Workflow waits for signal
        P ->> WB: Sends webhook that the transfer is complete<br/>(core.deposit.completed)
        WB ->> WB: Validate signature
        alt validation not passing
            WB ->> P: Return 400
        else validation passing
            WB ->> WB: Check transaction type (hosted)
            WB ->> T: Signal running workflow
            WB ->> P: Return 200 ACK
        end
        T ->> T: Create TX
        T ->> T: Create ledger transfer and POST it immediately

        T ->> RA: CreateIncomingPaymentWithdrawal
    end