include:
  - //.gitlab-refs.yaml

# 👇 Adds Chromatic as a job
chromatic_publish:
  rules:
    - changes:
        - typescript/protea/app/components/**/*
    # we need to configure this pipeline to run on merge requests
    # https://gitlab.com/gitlab-org/gitlab/-/merge_requests/25611/diffs
  #    - if: $CI_MERGE_REQUEST_ID
  tags:
    - hetzner
  variables:
    PROJECT_PATH: $CI_PROJECT_DIR/typescript/protea
    PROTEA_IMAGE_HASH: $CI_COMMIT_SHORT_SHA
  # Sets the docker image for the job
  image: public.ecr.aws/docker/library/node:16

  # Cache the dependencies
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

  before_script:
    - echo "changing directory to $PROJECT_PATH"
    - cd $PROJECT_PATH
    - echo "Installing dependencies"
    - corepack enable && corepack prepare pnpm@7.26.1 --activate
    - pnpm install --frozen-lockfile

  script:
    - pnpm chromatic --project-token=$CHROMATIC_PROJECT_TOKEN
      --auto-accept-changes=main
