include:
  - //.gitlab-refs.yaml

.job_rules:
  rules:  
    - changes:
        - typescript/protea/**/*
    # we need to configure this pipeline to run on merge requests
    # https://gitlab.com/gitlab-org/gitlab/-/merge_requests/25611/diffs
#    - if: $CI_MERGE_REQUEST_ID

variables:
  PROJECT_PATH: $CI_PROJECT_DIR/typescript/protea
  PROTEA_IMAGE_HASH: $CI_COMMIT_SHORT_SHA

image: node:16-alpine3.11

default:
  before_script:
    - echo "changing directory to $PROJECT_PATH"
    - cd $PROJECT_PATH

build_protea:
  image: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/docker:19.03.12
  interruptible: true
  script:
    - mkdir -p ~/.docker
    - echo $DOCKER_AUTH_CONFIG > ~/.docker/config.json
    - make build IMAGE_HASH=${PROTEA_IMAGE_HASH}
    - make push IMAGE_HASH=${PROTEA_IMAGE_HASH}
