workflow:
  rules:
    - changes:
        - typescript/protea/**/*
    # we need to configure this pipeline to run on merge requests
    # https://gitlab.com/gitlab-org/gitlab/-/merge_requests/25611/diffs
    - if: $CI_MERGE_REQUEST_ID

stages:
  - lint
  - deploy

variables:
  PROJECT_PATH: $CI_PROJECT_DIR/typescript/protea

image: node:16-alpine3.11

default:
  before_script:
    - echo "changing directory to $PROJECT_PATH"
    - cd $PROJECT_PATH

deploy:
  stage: deploy
  only:
    - main
  script:
    - yarn dlx vercel --prod -t $VERCEL_CLI_TOKEN

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - yarn dlx vercel -t $VERCEL_CLI_TOKEN
