sync_components = sync('./components', '/app/components')
sync_contexts = sync('./contexts', '/app/contexts')
sync_hooks = sync('./hooks', '/app/hooks')
sync_lib = sync('./lib', '/app/lib')
sync_pages = sync('./pages', '/app/pages')
sync_public = sync('./public', '/app/public')
sync_styles = sync('./styles', '/app/styles')
sync_generated = sync('./generated', '/app/generated')

local_resource('generate watch', serve_cmd='yarn generate:watch')

docker_build('protea', '.', target="dev", live_update=[
sync_components,sync_contexts,sync_hooks,sync_lib,sync_pages,sync_public,sync_styles,sync_generated
], ignore=["deploy/"])

k8s_custom_deploy(
  "protea",
  apply_cmd="kubectl set image deployment/protea protea=$TILT_IMAGE_0 && kubectl get deployment/protea -o yaml",
  delete_cmd="echo protea managed outside of Tilt",
  image_deps=["protea"],
  deps=[],
)