sync_app = sync('./app', '/app/app')
sync_public = sync('./public', '/app/public')
sync_generated = sync('./generated', '/app/generated')

local_resource('protea port forward debugging', serve_cmd = 'kubectl port-forward --namespace protea deployment/protea 9229:9229', resource_deps = ['protea'])

docker_build('protea', '.', target = "dev", live_update = [
  sync_app, sync_public, sync_generated
], ignore = ["deploy/", "integration/", "test-results/", "playwright-report/"])

k8s_custom_deploy(
  "protea",
  apply_cmd="""
      kubectl -v=0 --namespace protea set image deployment/protea protea=$TILT_IMAGE_0 > /dev/null && \
      kubectl get --namespace protea deployment/protea -o yaml
  """,
  delete_cmd = "echo protea managed outside of Tilt",
  image_deps = ["protea"],
  deps = [],
)
