kind: Namespace
apiVersion: v1
metadata:
  name: backend
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-tabapaytest
  namespace: backend
  labels:
    app: backend-tabapaytest
spec:
  containers:
    - name: backend
      image: 823058932981.dkr.ecr.eu-west-1.amazonaws.com/backend:tabapaytest
      imagePullPolicy: Always
      command: ["sleep", "infinity"]
