// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go

// Package deposits is a generated GoMock package.
package deposits

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockService) Get(ctx context.Context, id string) (*Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockService)(nil).Get), ctx, id)
}

// InitiateDeposit mocks base method.
func (m *MockService) InitiateDeposit(ctx context.Context, args *InitiateDepositArgs) (*Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateDeposit", ctx, args)
	ret0, _ := ret[0].(*Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateDeposit indicates an expected call of InitiateDeposit.
func (mr *MockServiceMockRecorder) InitiateDeposit(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateDeposit", reflect.TypeOf((*MockService)(nil).InitiateDeposit), ctx, args)
}

// SetState mocks base method.
func (m *MockService) SetState(ctx context.Context, id string, state State) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetState", ctx, id, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetState indicates an expected call of SetState.
func (mr *MockServiceMockRecorder) SetState(ctx, id, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockService)(nil).SetState), ctx, id, state)
}
