sync_app = sync('./app', '/app/app')
sync_public = sync('./public', '/app/public')
sync_generated = sync('./generated', '/app/generated')

local_resource('botanist tailwind watch', cmd = 'pnpm build:css', deps=['./app'], ignore=['./app/styles'])
local_resource('botanist port forward', serve_cmd = 'kubectl port-forward --namespace botanist deployment/botanist 8002:8002', resource_deps = ['botanist'])

docker_build('botanist', '.', target = "dev", live_update = [
  sync_app, sync_public, sync_generated
], ignore = ["deploy/"])

k8s_custom_deploy(
  "botanist",
  apply_cmd="""
      kubectl -v=0 --namespace botanist set image deployment/botanist botanist=$TILT_IMAGE_0 > /dev/null && \
      kubectl get --namespace botanist deployment/botanist -o yaml
  """,
  delete_cmd = "echo botanist managed outside of Tilt",
  image_deps = ["botanist"],
  deps = [],
)
