apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - mock-secrets.yaml
  - app-secrets.yaml
  - soketi.yaml
  - tls-store.yaml
  - ingressroutes/frontend.yaml
  - ingressroutes/admin.yaml
  - ingressroutes/kratos.yaml
  - ingressroutes/mock-services.yaml
