// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go

// Package twilio is a generated GoMock package.
package twilio

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CheckVerificationCode mocks base method.
func (m *MockService) CheckVerificationCode(ctx context.Context, args *CheckVerificationCodeArgs) (*Verification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckVerificationCode", ctx, args)
	ret0, _ := ret[0].(*Verification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckVerificationCode indicates an expected call of CheckVerificationCode.
func (mr *MockServiceMockRecorder) CheckVerificationCode(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckVerificationCode", reflect.TypeOf((*MockService)(nil).CheckVerificationCode), ctx, args)
}

// ListSuccessfulVerificationAttempts mocks base method.
func (m *MockService) ListSuccessfulVerificationAttempts(ctx context.Context, args ListSuccessfulVerificationAttemptsArgs) ([]Verification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSuccessfulVerificationAttempts", ctx, args)
	ret0, _ := ret[0].([]Verification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSuccessfulVerificationAttempts indicates an expected call of ListSuccessfulVerificationAttempts.
func (mr *MockServiceMockRecorder) ListSuccessfulVerificationAttempts(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSuccessfulVerificationAttempts", reflect.TypeOf((*MockService)(nil).ListSuccessfulVerificationAttempts), ctx, args)
}

// SendVerificationCode mocks base method.
func (m *MockService) SendVerificationCode(ctx context.Context, phoneNumber string) (*Verification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationCode", ctx, phoneNumber)
	ret0, _ := ret[0].(*Verification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendVerificationCode indicates an expected call of SendVerificationCode.
func (mr *MockServiceMockRecorder) SendVerificationCode(ctx, phoneNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationCode", reflect.TypeOf((*MockService)(nil).SendVerificationCode), ctx, phoneNumber)
}
