// Code generated by "stringer -type=Status -trimprefix=Status"; DO NOT EDIT.

package kyc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnknown-0]
	_ = x[StatusPending-1]
	_ = x[StatusDocumentsRequired-2]
	_ = x[StatusApproved-3]
	_ = x[StatusDenied-4]
	_ = x[StatusInReview-5]
	_ = x[StatusLevel1-6]
	_ = x[StatusLevel2-7]
}

const _Status_name = "UnknownPendingDocumentsRequiredApprovedDeniedInReviewLevel1Level2"

var _Status_index = [...]uint8{0, 7, 14, 31, 39, 45, 53, 59, 65}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
