// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	currency "github.com/interledger/interledger-app/go/backend/currency"
	limits "github.com/interledger/interledger-app/go/backend/limits"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// ExceedsKYCLimits mocks base method.
func (m *MockClient) ExceedsKYCLimits(ctx context.Context, walletID string, amount currency.Amount) (bool, limits.LimitType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExceedsKYCLimits", ctx, walletID, amount)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(limits.LimitType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ExceedsKYCLimits indicates an expected call of ExceedsKYCLimits.
func (mr *MockClientMockRecorder) ExceedsKYCLimits(ctx, walletID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExceedsKYCLimits", reflect.TypeOf((*MockClient)(nil).ExceedsKYCLimits), ctx, walletID, amount)
}
