{{- define "interledger-app.mockpti.deployment" -}}
{{- $top := first . }}
{{- if and (kindIs "bool" $top.Values.mockpti.enabled) $top.Values.mockpti.enabled }}
{{- $cfgObj := include "interledger-app.mockpti.configMap" $top | fromYaml -}}
{{- $dataHash := $cfgObj.data | toJson | sha256sum -}}
spec:
  template:
    metadata:
      annotations:
        ilf-configmap-mockpti-sha256: {{ $dataHash | quote }}
{{- end }}
{{- end }}
{{- if and (kindIs "bool" .Values.mockpti.enabled) .Values.mockpti.enabled }}
{{- include "common.deployment" (list . .Values.mockpti.server .Values.mockpti.server.autoscaling .Values.mockpti.server.serviceAccount "interledger-app.mockpti.deployment") }}
{{- end }}
