{{- define "interledger-app.backend.worker.deployment" -}}
{{- $top := first . }}
{{- $cfgObj := include "interledger-app.backend.configMap" $top | fromYaml -}}
{{- $dataHash := $cfgObj.data | toJson | sha256sum -}}
spec:
  template:
    metadata:
      annotations:
        ilf-configmap-backend-sha256: {{ $dataHash | quote }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ include "common.fullname" $top }}-backend-config
{{- end }}
{{- if .Values.backend.worker.enabled }}
{{- include "common.deployment" (list . .Values.backend.worker .Values.backend.worker.autoscaling .Values.backend.worker.serviceAccount "interledger-app.backend.worker.deployment") }}
{{- end }}
