apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsUser: 65532
      volumes:
        - name: cockroach-certs
          secret:
            secretName: cockroachdb-backend
            items:
              - key: tls.key
                path: client.backend.key
              - key: tls.crt
                path: client.backend.crt
              - key: ca.crt
                path: ca.crt
      serviceAccountName: backend
      initContainers:
        - name: init-db
          image: fynbos/backend-init
          imagePullPolicy: Always
          env:
            - name: DB_URL
              # don't specify the ssl certs here. The application will read them in from file and inline them.
              value: "cockroach://backend@cockroachdb-public:26257/backend?sslmode=verify-full&max_conns=20&max_idle_conns=4"
          volumeMounts:
            - name: cockroach-certs
              mountPath: "/cockroach-certs"
      containers:
        - name: backend
          image: fynbos/backend
          imagePullPolicy: Always
          # TODO: Change these to appropriate values for the hardware that you're running. You can see
          # the resources that can be allocated on each of your Kubernetes nodes by running:
          #   kubectl describe nodes
          # Note that requests and limits should have identical values.
          #          resources:
          #            requests:
          #              cpu: "2"
          #              memory: "8Gi"
          #            limits:
          #              cpu: "2"
          #              memory: "8Gi"
          ports:
            - containerPort: 8080
              name: http
          # we use the same endpoint for liveness and readiness as we are only running a graphql server
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: http
              scheme: HTTP
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: http
              scheme: HTTP
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: DB_URL
              # don't specify the ssl certs here. The application will read them in from file and inline them.
              value: "cockroach://backend@cockroachdb-public:26257/backend?sslmode=verify-full&max_conns=20&max_idle_conns=4"
            - name: KRATOS_URL
              value: "http://kratos-public"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_OUTPUT_PATH
              value: "./logs.txt"
          volumeMounts:
            - name: cockroach-certs
              mountPath: "/cockroach-certs"
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 30
