include:
  - //////.gitlab-refs.yaml

variables:
  ENV_PATH: $CI_PROJECT_DIR/go/env

build_env:
  rules:
    - changes:
        - go/go.mod
        - go/env/**/*
  tags:
    - hetzner
  image: registry.gitlab.com/fynbos/fynbos/debian-runner-base:b59a3751
  interruptible: true
  script:
    - cd $ENV_PATH
    - make testci
