apiVersion: v1
kind: ServiceAccount
metadata:
  name: protea
  labels:
    app: protea
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: protea
  labels:
    app: protea
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: protea
  labels:
    app: protea
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: protea
subjects:
  - kind: ServiceAccount
    name: protea
    namespace: default