#cloud-config

#groups:
#  - docker [ec2-user]

package_upgrade: true
package_update: true

write_files:
  - owner: root:root
    path: /root/config.toml
    content: |
      concurrent = 4
      check_interval = 0

      [[runners]]
        name = "gitlab-aws-autoscaler"
        url = "https://gitlab.com"
        token = "{{.GitlabToken}}"
        executor = "docker+machine"
        limit = 3
        environment = ["DOCKER_AUTH_CONFIG={ \"credsStore\": \"ecr-login\" }"]
        [runners.docker]
          tls_verify = false
          image = "docker:19.03.12"
          privileged = true
          disable_cache = false
          volumes = ["/cache", "/usr/bin/docker-credential-ecr-login:/usr/bin/docker-credential-ecr-login"]
        [runners.cache]
          Insecure = false
        [runners.machine]
            IdleCount = 0
            IdleTime = 60
            MaxBuilds = 10
            MachineDriver = "amazonec2"
            MachineName = "gitlab-docker-machine-%s"
            MachineOptions = [
              "amazonec2-region={{.AwsRegion}}",
              "amazonec2-vpc-id={{.AwsVpcId}}",
              "amazonec2-subnet-id={{.AwsSubnetId}}",
              "amazonec2-zone=a",
              "amazonec2-security-group={{.SgName}}",
              "amazonec2-use-private-address=true",
              "amazonec2-private-address-only=true",
              "amazonec2-tags=runner-manager-name,gitlab-aws-autoscaler,gitlab,true,gitlab-runner-autoscale,true",
              "amazonec2-instance-type=m5d.large",
              "amazonec2-iam-instance-profile={{.RunnerProfileName}}",
              "engine-install-url=https://releases.rancher.com/install-docker/19.03.15.sh",
            ]
  - owner: root:root
    path: /root/.docker/config.json
    content: |
      { "credsStore": "ecr-login" }
  - owner: root:root
    path: /root/.aws/config
    content: |
      [default]
      region={{.AwsRegion}}
    append: true

runcmd:
  - 'amazon-linux-extras install docker'
  - 'yum -y install amazon-ecr-credential-helper'
  - 'usermod -a -G docker ec2-user'
  - 'systemctl enable docker'
  - 'systemctl start docker'
  - 'curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | sudo bash'
  - 'yum install -y gitlab-runner'
  - 'wget "https://gitlab-docker-machine-downloads.s3.amazonaws.com/main/docker-machine-Linux-x86_64" -O /tmp/docker-machine'
  - 'sudo mv /tmp/docker-machine /usr/bin/docker-machine'
  - 'sudo chmod +x /usr/bin/docker-machine'
  - 'export USER=root'
  - 'export HOME=/root'
  - 'docker-machine create --driver none --url localhost dummy-machine'
  - 'docker-machine rm -y dummy-machine'
  - 'unset HOME'
  - 'unset USER'
  - 'sudo cp /root/config.toml /etc/gitlab-runner/config.toml'
