name: Build and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - main
      - 'release/v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - "**"

permissions:
  id-token: write
  contents: read
  packages: write

env:
  # We use Artifact Repository, GCR references are legacy as GCR has been deprecated.
  GCR_PROJECT: ${{ secrets.GCR_PROJECT }}
  GSA_EMAIL: ${{ secrets.GSA_EMAIL }}
  GCR_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCR_WORKLOAD_IDENTITY_PROVIDER }}

jobs:
  select_packages:
    # Selects and outputs the list of packages to be used in subsequent matrix builds
    runs-on: ubuntu-latest
    outputs:
      builds: ${{ steps.select_packages.outputs.builds }}
    steps:
      - name: Select packages
        id: select_packages
        run: |
          # Define packages
          platform='[{"os": "linux", "arch": "amd64"}]'
          go_pkgs='[{"name": "backend", "context": "./go", "file": "./go/backend/Dockerfile"}, {"name": "mockbos", "context": "./go", "file": "./go/mockbos/Dockerfile"}, {"name": "temporal", "context": "./go", "file": "./go/temporal/Dockerfile"}]'
          ts_pkgs='[{"name": "protea", "context": "./typescript/protea", "file": "./typescript/protea/Dockerfile", "sentry_project":"frontend"}, {"name": "botanist", "context": "./typescript/botanist", "file": "./typescript/botanist/Dockerfile", "sentry_project""}]'

          # Add type=go to go_pkgs
          go_pkgs=$(echo "$go_pkgs" | jq 'map(. + {type: "go"})')
          # Add type=ts to ts_pkgs
          ts_pkgs=$(echo "$ts_pkgs" | jq 'map(. + {type: "ts"})')

          # Create outputs by combining platform, go_pkgs, and ts_pkgs into a single JSON object
          echo builds=$(jq -n --argjson go "$go_pkgs" --argjson ts "$ts_pkgs" --argjson platform "$platform" '{package: ($go + $ts), platform: $platform}') >> "$GITHUB_OUTPUT"

  version_generator:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_generator.outputs.NEW_VERSION }}
      tagPushed: ${{ steps.version_generator.outputs.SHOULD_PUSH_TAG }}
      dockerPush: ${{ steps.version_generator.outputs.PUSH_DOCKER_IMAGE }}
      generateRelease: ${{ steps.version_generator.outputs.GENERATE_RELEASE }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - id: version_generator
        name: Generate version properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHOULD_PUSH_TAG=false
          PUSH_DOCKER_IMAGE=false
          GENERATE_RELEASE=false
          if [ "${{ github.event_name == 'schedule' }}" = true ]; then
            PUSH_DOCKER_IMAGE=true
            NEW_VERSION="nightly"
          elif [ "${{ github.event_name == 'workflow_dispatch' }}" = true ]; then
            NEW_VERSION="manual_${{ github.ref_name }}"
            PUSH_DOCKER_IMAGE=true
          elif [ "${{ startsWith(github.ref_name, 'release/v')}}" = true ]; then
            PUSH_DOCKER_IMAGE=true
            SHOULD_PUSH_TAG=true
            GENERATE_RELEASE=true
            VERSION_PREFIX=$(echo "${{ github.ref_name }}" | sed 's|release/||')
            read major minor patch pre_release <<< $(echo "$VERSION_PREFIX" | awk -F'[.v-]' '{print $2, $3, $4, $5}')
            version_search="v$major.$minor.*"
            if [ -n "$pre_release" ]; then
                version_search="$version_search-$pre_release"
            fi
            echo "VERSION_SEARCH: $version_search"
            VERSION_PREFIX=$(git tag -l $version_search --sort=-taggerdate | head -n 1)
            if [ -n "$VERSION_PREFIX" ]; then
              read major minor patch pre_release <<< $(echo "$VERSION_PREFIX" | awk -F'[.v-]' '{print $2, $3, $4, $5}')
              patch=$((patch + 1))
            fi
            NEW_VERSION="v${major}.${minor}.${patch}"
            if [ -n "$pre_release" ]; then
              NEW_VERSION="$NEW_VERSION-${pre_release}"
            fi
          else
            NEW_VERSION=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9_.-]/_/g')

            if [[ ! "$NEW_VERSION" =~ ^[a-zA-Z0-9] ]]; then
                NEW_VERSION="tag_$NEW_VERSION"
            fi
          fi

          # Remove any characters that are not alphanumeric, period, underscore, or hyphen
          NEW_VERSION=$(echo $NEW_VERSION | tr -c '[:alnum:]._-' '-')

          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version will be: $NEW_VERSION"

          echo "SHOULD_PUSH_TAG=$SHOULD_PUSH_TAG" >> $GITHUB_OUTPUT
          echo "Will tag be pushed? $SHOULD_PUSH_TAG"

          echo "PUSH_DOCKER_IMAGE=$PUSH_DOCKER_IMAGE" >> $GITHUB_OUTPUT
          echo "Will docker image be pushed? $PUSH_DOCKER_IMAGE"

          echo "GENERATE_RELEASE=$GENERATE_RELEASE" >> $GITHUB_OUTPUT
          echo "Will generate release noted? $GENERATE_RELEASE"

          if [ "$SHOULD_PUSH_TAG" = true ]; then
            git tag -fa $NEW_VERSION -m "$NEW_VERSION"
            git push -f origin $NEW_VERSION
          fi

  builds:
    needs: [select_packages, version_generator]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.select_packages.outputs.builds)}}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Go Docker image
        if: matrix.package.type == 'go'
        uses: docker/build-push-action@v5
        with:
          push: false
          platforms: ${{ matrix.platform.os }}/${{ matrix.platform.arch }}
          context: ${{ matrix.package.context }}
          file: ${{ matrix.package.file }}
          tags: interledger-app-${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}:${{ needs.version_generator.outputs.version }}
          build-args: |
            GOLANG_VERSION=1.23
            BUILDARCH=${{ matrix.platform.arch }}
            BUILDOS=${{ matrix.platform.os }}
          outputs: type=docker,dest=/tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
      - name: Build TypeScript Docker image
        if: matrix.package.type == 'ts'
        uses: docker/build-push-action@v5
        with:
          push: false
          platforms: ${{ matrix.platform.os }}/${{ matrix.platform.arch }}
          context: ${{ matrix.package.context }}
          file: ${{ matrix.package.file }}
          tags: interledger-app-${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}:${{ needs.version_generator.outputs.version }}
          build-args: |
            IMAGE_HASH=$GITHUB_SHA
            BUILDARCH=${{ matrix.platform.arch }}
            BUILDOS=${{ matrix.platform.os }}
            SENTRY_ORG=${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT=${{ matrix.package.sentry_project }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_DSN }}
          outputs: type=docker,dest=/tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
      - name: List Docker images
        run: docker images
      - name: Save docker image to cache
        uses: actions/cache@v4
        with:
          path: /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
          key: ${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}

  push-image-gcp-artifact-registry:
    name: Push to Google Artifact Registry
    needs: [builds, version_generator, select_packages]
    runs-on: ubuntu-latest
    if: needs.version_generator.outputs.dockerPush == 'true'
    strategy:
      matrix: ${{fromJson(needs.select_packages.outputs.builds)}}
    steps:
      - name: Load cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
          key: ${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Load Docker image
        run: |
          docker load -i /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
    
      - name: List Docker images
        run: docker images

      - name: Retag for Artifact Registry
        run: |
          IMAGE_ID=$(docker images interledger-app-${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }} --format "{{.ID}}" | head -n 1)
          # Tag appropriately for our GCP project
          PUSH_IMAGE=europe-west4-docker.pkg.dev/${{ env.GCR_PROJECT }}/interledger-app/${{ matrix.package.name }}:${{ needs.version_generator.outputs.version }}
          docker tag $IMAGE_ID $PUSH_IMAGE
          echo "PUSH_IMAGE=$PUSH_IMAGE" >> $GITHUB_ENV 

      - uses: 'google-github-actions/auth@v2'
        with:
            service_account: ${{ env.GSA_EMAIL }}
            workload_identity_provider: ${{ env.GCR_WORKLOAD_IDENTITY_PROVIDER}}
            export_environment_variables: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Configure Docker to use the gcloud command-line tool as a credential helper for authentication
        run: |-
          gcloud --quiet auth configure-docker \
              europe-west4-docker.pkg.dev

      - name: Push to Artifact Registry
        run: |
          echo "Pushing $PUSH_IMAGE"
          docker push $PUSH_IMAGE
