name: Build and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - main
      - 'release/v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - "**"

permissions:
  id-token: write
  contents: write
  packages: write


jobs:
  select_packages:
    # Selects and outputs the list of packages to be used in subsequent matrix builds
    runs-on: ubuntu-latest
    outputs:
      builds: ${{ steps.select_packages.outputs.builds }}
    steps:
      - uses: actions/checkout@v4
      - name: Select packages
        id: select_packages
        uses: actions/github-script@v7
        with:
          script: |
            const { default: selectPackages } = await import('${{ github.workspace }}/tooling/github-scripts/select-packages.js')
            await selectPackages({ github, core, context })

  version_generator:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_generator.outputs.NEW_VERSION }}
      tagPushed: ${{ steps.version_generator.outputs.SHOULD_PUSH_TAG }}
      dockerPush: ${{ steps.version_generator.outputs.PUSH_DOCKER_IMAGE }}
      generateRelease: ${{ steps.version_generator.outputs.GENERATE_RELEASE }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Generate version properties
        id: version_generator
        uses: actions/github-script@v7
        with:
          script: |
            const { default: versionGenerator } = await import('${{ github.workspace }}/tooling/github-scripts/version-generator.js')
            await versionGenerator({ github, core, context })

  builds:
    needs: [select_packages, version_generator]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.select_packages.outputs.builds)}}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Go Docker image
        if: matrix.package.type == 'go'
        uses: docker/build-push-action@v5
        with:
          push: false
          platforms: ${{ matrix.platform.os }}/${{ matrix.platform.arch }}
          context: ${{ matrix.package.context }}
          file: ${{ matrix.package.file }}
          tags: interledger-app-${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}:${{ needs.version_generator.outputs.version }}
          build-args: |
            GOLANG_VERSION=1.25.1
            BUILDARCH=${{ matrix.platform.arch }}
            BUILDOS=${{ matrix.platform.os }}
          outputs: type=docker,dest=/tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
      - name: store-cdn-key
        if: matrix.package.type == 'ts'
        run: |
          cd ${{ matrix.package.context }}
          echo "${{ secrets.GCP_CDN_UPLOADER_KEY_JSON_B64 }}" > ./gsa-key.json.b64
          base64 --decode ./gsa-key.json.b64 > ./gsa-key.json
          sha256sum ./gsa-key.json
      - name: Build TypeScript Docker image
        if: matrix.package.type == 'ts'
        uses: docker/build-push-action@v5
        with:
          push: false
          platforms: ${{ matrix.platform.os }}/${{ matrix.platform.arch }}
          context: ${{ matrix.package.context }}
          file: ${{ matrix.package.file }}
          tags: interledger-app-${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}:${{ needs.version_generator.outputs.version }}
          build-args: |
            IMAGE_HASH=${{ needs.version_generator.outputs.version }}
            BUILDARCH=${{ matrix.platform.arch }}
            BUILDOS=${{ matrix.platform.os }}
            UPLOAD_SOURCEMAPS=${{ needs.version_generator.outputs.dockerPush }}
            SENTRY_ORG=${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT=${{ matrix.package.sentry_project }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_RELEASE=${{ needs.version_generator.outputs.version }}
            REMIX_PUBLIC_PATH=${{ matrix.package.cdn_public_path }}
            CDN_BUCKET_NAME=${{ matrix.package.cdn_bucket }}
          outputs: type=docker,dest=/tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
      - name: List Docker images
        run: docker images
      - name: Save docker image to cache
        uses: actions/cache@v4
        with:
          path: /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
          key: ${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}

  push-image-gcp-artifact-registry:
    name: Prod images push
    needs: [builds, version_generator, select_packages]
    runs-on: ubuntu-latest
    env:
      # We use Artifact Repository, GCR references are legacy as GCR has been deprecated.
      GCR_PROJECT: ${{ secrets.GCR_PROJECT }}
      GSA_EMAIL: ${{ secrets.GSA_EMAIL }}
      GCR_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCR_WORKLOAD_IDENTITY_PROVIDER }}
    if: needs.version_generator.outputs.dockerPush == 'true'
    strategy:
      matrix: ${{fromJson(needs.select_packages.outputs.builds)}}
    steps:
      - name: Load cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
          key: ${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Load Docker image
        run: |
          docker load -i /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
    
      - name: List Docker images
        run: docker images

      - name: Retag for Artifact Registry
        run: |
          IMAGE_ID=$(docker images interledger-app-${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }} --format "{{.ID}}" | head -n 1)
          # Tag appropriately for our GCP project
          PUSH_IMAGE=europe-west4-docker.pkg.dev/${{ env.GCR_PROJECT }}/interledger-app/${{ matrix.package.name }}:${{ needs.version_generator.outputs.version }}
          docker tag $IMAGE_ID $PUSH_IMAGE
          echo "PUSH_IMAGE=$PUSH_IMAGE" >> $GITHUB_ENV 

      - uses: 'google-github-actions/auth@v2'
        with:
            service_account: ${{ env.GSA_EMAIL }}
            workload_identity_provider: ${{ env.GCR_WORKLOAD_IDENTITY_PROVIDER}}
            export_environment_variables: true

      - name: Sanity checks
        run: |
          gcloud auth list
          gcloud config list

      - name: Configure Docker to use the gcloud command-line tool as a credential helper for authentication
        run: |-
          gcloud --quiet auth configure-docker \
              europe-west4-docker.pkg.dev

      - name: Push to Artifact Registry
        run: |
          echo "Pushing $PUSH_IMAGE"
          docker push $PUSH_IMAGE


  push-dev-image-gcp-artifact-registry:
    name: DEV Images push
    needs: [builds, version_generator, select_packages]
    runs-on: ubuntu-latest
    env:
      GCR_PROJECT: ${{ secrets.GCR_DEV_PROJECT }}
      GSA_EMAIL: ${{ secrets.GSA_DEV_EMAIL }}
      GCR_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCR_DEV_WORKLOAD_IDENTITY_PROVIDER }}
    if: needs.version_generator.outputs.dockerPush == 'true'
    strategy:
      matrix: ${{fromJson(needs.select_packages.outputs.builds)}}
    steps:
      - name: Load cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
          key: ${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Load Docker image
        run: |
          docker load -i /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
    
      - name: List Docker images
        run: docker images

      - name: Retag for Artifact Registry
        run: |
          IMAGE_ID=$(docker images interledger-app-${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }} --format "{{.ID}}" | head -n 1)
          # Tag appropriately for our GCP project
          PUSH_IMAGE=europe-west4-docker.pkg.dev/${{ env.GCR_PROJECT }}/interledger-app/${{ matrix.package.name }}:${{ needs.version_generator.outputs.version }}
          docker tag $IMAGE_ID $PUSH_IMAGE
          echo "PUSH_IMAGE=$PUSH_IMAGE" >> $GITHUB_ENV 

      - uses: 'google-github-actions/auth@v2'
        with:
            service_account: ${{ env.GSA_EMAIL }}
            workload_identity_provider: ${{ env.GCR_WORKLOAD_IDENTITY_PROVIDER}}
            export_environment_variables: true

      - name: Sanity checks
        run: |
          gcloud auth list
          gcloud config list

      - name: Configure Docker to use the gcloud command-line tool as a credential helper for authentication
        run: |-
          gcloud --quiet auth configure-docker \
              europe-west4-docker.pkg.dev

      - name: Push to Artifact Registry
        run: |
          echo "Pushing $PUSH_IMAGE"
          docker push $PUSH_IMAGE