name: Go build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 21 * * *'
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.20'
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: go
          version: 'v1.51.1'


  version-generator:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-generator.outputs.NEW_VERSION }}
      tagPushed: ${{ steps.version-generator.outputs.SHOULD_PUSH_TAG }}
      dockerPush: ${{ steps.version-generator.outputs.PUSH_DOCKER_IMAGE }}
      generateRelease: ${{ steps.version-generator.outputs.GENERATE_RELEASE }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
          fetch-tags: true

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - id: version-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}  # GitHub Workflow Run ID
          COMMIT_SHA: ${{ github.sha }} # Commit SHA to ensure uniqueness
        run: |
          SHOULD_PUSH_TAG=false
          PUSH_DOCKER_IMAGE=false
          GENERATE_RELEASE=false

          # Get latest tag following SemVer
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+(\-[a-z]+[0-9]*)?(\+build\.[0-9]+)?$' | head -n 1)
          [ -z "$LATEST_TAG" ] && LATEST_TAG="v0.0.0"

          # Extract version components
          VERSION_BASE=$(echo "$LATEST_TAG" | sed -E 's/\+build\.[0-9]+//')

          # Parse commits since last tag
          COMMITS=$(git log "$LATEST_TAG"..HEAD --pretty=format:"%s")

          MAJOR=0; MINOR=0; PATCH=0; BREAKING=false

          while IFS= read -r COMMIT; do
            if [[ "$COMMIT" =~ ^(feat|BREAKING CHANGE) ]]; then
              MAJOR=$((MAJOR + 1))
              BREAKING=true
            elif [[ "$COMMIT" =~ ^fix ]]; then
              PATCH=$((PATCH + 1))
            else
              MINOR=$((MINOR + 1))
            fi
          done <<< "$COMMITS"

          # Extract old version
          IFS='.' read -r OLD_MAJOR OLD_MINOR OLD_PATCH <<< "$(echo "$VERSION_BASE" | sed 's/v//')"

          # Apply SemVer rules
          if [ "$BREAKING" = true ]; then
            NEW_VERSION="v$((OLD_MAJOR + 1)).0.0"
          elif [ "$MINOR" -gt 0 ]; then
            NEW_VERSION="v$OLD_MAJOR.$((OLD_MINOR + 1)).0"
          elif [ "$PATCH" -gt 0 ]; then
            NEW_VERSION="v$OLD_MAJOR.$OLD_MINOR.$((OLD_PATCH + 1))"
          else
            NEW_VERSION="$LATEST_TAG"
          fi

          BRANCH=$(git rev-parse --abbrev-ref HEAD)

          if [ "$BRANCH" == "main" ]; then
            SHOULD_PUSH_TAG=true
            PUSH_DOCKER_IMAGE=true
            GENERATE_RELEASE=false
            NEW_VERSION="$NEW_VERSION+build.$RUN_ID"
          elif [ "$BRANCH" == "release" ]; then
            SHOULD_PUSH_TAG=true
            PUSH_DOCKER_IMAGE=true
            GENERATE_RELEASE=true
            NEW_VERSION="$NEW_VERSION-rc.$RUN_ID"
          fi

          # Check if tag already exists before pushing
          if git rev-parse "$NEW_VERSION" >/dev/null 2>&1; then
            echo "Tag $NEW_VERSION already exists. Skipping tagging."
            SHOULD_PUSH_TAG=false
          fi

          # Output for debugging
          echo "LATEST_TAG=$LATEST_TAG"
          echo "VERSION_BASE=$VERSION_BASE"
          echo "COMMITS=$COMMITS"
          echo "NEW_VERSION=$NEW_VERSION"

          # Output variables
          echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_ENV"
          echo "SHOULD_PUSH_TAG=$SHOULD_PUSH_TAG" >> "$GITHUB_ENV"
          echo "PUSH_DOCKER_IMAGE=$PUSH_DOCKER_IMAGE" >> "$GITHUB_ENV"
          echo "GENERATE_RELEASE=$GENERATE_RELEASE" >> "$GITHUB_ENV"  

  builds:
    needs: [golangci, version-generator]
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        package: 
          - name: backend
          - name: mockbos
        platform:
          - os: linux
            arch: amd64
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout code
        uses: actions/checkout@v4        
      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          platforms: ${{ matrix.platform.os }}/${{ matrix.platform.arch }}
          context: ./go
          file: ./go/${{ matrix.package.name }}/Dockerfile
          build-args: |
            GOLANG_VERSION=1.23
            ATLAS_VERSION=v0.31.0
            AIR_VERSE_VERSION=v1.52
            GRPC_HEALTH_PROBE_VERSION=v0.4.7
            BUILDARCH=${{ matrix.platform.arch }}
            BUILDOS=${{ matrix.platform.os }}
          outputs: type=docker,dest=/tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
      - name: Save docker image to cache
        uses: actions/cache@v4
        with:
          path: /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
          key: ${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}


  push-version-tag:
    name: Push semantic version 2 tag
    needs: [builds, version-generator]
    if: needs.version-generator.outputs.dockerPush == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Push tag
        if: ${{ needs.version-generator.outputs.tagPushed == 'true' }}
        run: |
          git tag ${{ needs.version-generator.outputs.version }}
          git push origin ${{ needs.version-generator.outputs.version }}

  push-image:
    name: Push to registry
    needs: [builds, version-generator,push-version-tag]
    runs-on: ubuntu-latest
    if: needs.version-generator.outputs.dockerPush == 'true'
    strategy:
      matrix: 
        package: 
          - name: backend
          - name: mockbos
        platform:
          - os: linux
            arch: amd64      
    steps:
      - name: Load cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
          key: ${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}
          fail-on-cache-miss: true
      # Loads the docker image from cache
      - name: Load Docker image
        run: docker load -i /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
      - name: List images
        run: docker images
      # Push it to the registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to registry
        # Push latest image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/interledger-app-${{ matrix.package }}-${{ matrix.platform.os }}${{ matrix.platform.arch }}:${{ needs.version-generator.outputs.version }}
