name: Go build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 21 * * *'
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.20'
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: go
          version: 'v1.51.1'
          
  builds:
    needs: golangci
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        package: 
          - name: backend
          - name: pacioli
          - name: mockbos
        platform:
          - os: linux
            arch: amd64
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout code
        uses: actions/checkout@v4        
      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          platforms: ${{ matrix.platform.os }}/${{ matrix.platform.arch }}
          context: ./go
          file: ./go/${{ matrix.package.name }}/Dockerfile
          build-args: |
            GOLANG_VERSION=1.23
            ATLAS_VERSION=v0.31.0
            AIR_VERSE_VERSION=v1.52
            GRPC_HEALTH_PROBE_VERSION=v0.4.7
            BUILDARCH=${{ matrix.platform.arch }}
            BUILDOS=${{ matrix.platform.os }}
          outputs: type=docker,dest=/tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
      - name: Save docker image to cache
        uses: actions/cache@v4
        with:
          path: /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
          key: ${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}

  push:
    needs: builds
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        package: 
          - name: backend
          - name: pacioli
          - name: mockbos
        platform:
          - os: linux
            arch: amd64      
    steps:
      - name: Load cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
          key: ${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Load Docker image
        run: docker load -i /tmp/${{ matrix.package.name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ github.sha }}.tar
      - name: List images
        run: docker images
      
      # TODO Push to registry. Will do this with next iteration. Need to understand how tags will work first.
