name: Go Tests

on:
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    uses: ./.github/workflows/go-test-template.yml
    with:
      test_path: './go/backend'
      coverage_key: 'backend'
      db_name: 'backend'
  pacioli-tests:
    uses: ./.github/workflows/go-test-template.yml
    with:
      test_path: './go/pacioli'
      coverage_key: 'pacioli'
      db_name: 'pacioli'
  cli-tests:
    uses: ./.github/workflows/go-test-template.yml
    with:
      test_path: './go/cli'
      coverage_key: 'cli'
      db_name: 'cli'
  httpmessagesignatures-tests:
    uses: ./.github/workflows/go-test-template.yml
    with:
      test_path: './go/httpmessagesignatures'
      coverage_key: 'httpmessagesignatures'
      db_name: 'httpmessagesignatures'
