name: Go Tests

on:
  pull_request:
    paths:
      - 'go/**'
      - '.github/workflows/go-test-template.yml'
      - '.github/workflows/mock-tester.yml'

jobs:
  configa-tests:
    uses: ./.github/workflows/go-test-template.yml
    with:
      test_path: './go/configa'
      coverage_key: 'configa'

  backend-tests:
    uses: ./.github/workflows/go-test-template.yml
    with:
      test_path: './go/backend'
      coverage_key: 'backend'
      db_name: 'backend'
  pacioli-tests:
    uses: ./.github/workflows/go-test-template.yml
    with:
      test_path: './go/pacioli'
      coverage_key: 'pacioli'
      db_name: 'pacioli'

  mockxago-tests:
    uses: ./.github/workflows/mock-tester.yml
    with:
      test_path: './go/mock/mockxago'
      coverage_key: 'mockxago'

  mockgatehub-tests:
    uses: ./.github/workflows/mock-tester.yml
    with:
      test_path: './go/mock/mockgatehub'
      coverage_key: 'mockgatehub'

  mockchimoney-tests:
    uses: ./.github/workflows/mock-tester.yml
    with:
      test_path: './go/mock/mockchimoney'
      coverage_key: 'mockchimoney'

  mockpti-tests:
    uses: ./.github/workflows/mock-tester.yml
    with:
      test_path: './go/mock/mockpti'
      coverage_key: 'mockpti'
