name: Go Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'documentation/**'

jobs:
  backend-tests:
    uses: ./.github/workflows/go-test-template.yml
    with:
      test_path: './go/backend'
      coverage_key: 'backend'
      db_name: 'backend'
  pacioli-tests:
    uses: ./.github/workflows/go-test-template.yml
    with:
      test_path: './go/pacioli'
      coverage_key: 'pacioli'
      db_name: 'pacioli'

  mockxago-tests:
    uses: ./.github/workflows/mock-tester.yml
    with:
      test_path: './go/mock/mockxago'
      coverage_key: 'mockxago'

  mockgatehub-tests:
    uses: ./.github/workflows/mock-tester.yml
    with:
      test_path: './go/mock/mockgatehub'
      coverage_key: 'mockgatehub'

