name: Code quality checks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - 'documentation/**'
      - 'local/**'

jobs:

  golangci:
    name: GoLang Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: go
          version: latest
