name: Code quality checks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/linting.yml"
      - "go/**/*.go"

jobs:

  golangci:
    name: GoLang Linting
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/interledger/builders/gotester:v1.1.0
    env:
      GOFLAGS: -buildvcs=false
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: golangci-lint
        run: |
          cd go
          golangci-lint run ./...
