name: Test GitHub Actions Tooling

on:
  pull_request:
    branches:
      - main
    paths:
      - 'tooling/github-actions/**'

  push:
    branches:
      - main
    paths:
      - 'tooling/github-actions/**'

jobs:
  test-tooling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.5.0
      - uses: actions/setup-node@v4
        with:
          version: 8.5.0
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        working-directory: tooling/github-actions
        shell: bash
        run: pnpm install --frozen-lockfile
      - name: Run tests
        working-directory: tooling/github-actions
        shell: bash
        run: pnpm test
