// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go

// Package fundingsources is a generated GoMock package.
package fundingsources

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, args *CreateArgs) (*FundingSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, args)
	ret0, _ := ret[0].(*FundingSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, args)
}

// CreateBankAccount mocks base method.
func (m *MockService) CreateBankAccount(ctx context.Context, args *CreateBankAccountArgs) (*FundingSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBankAccount", ctx, args)
	ret0, _ := ret[0].(*FundingSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBankAccount indicates an expected call of CreateBankAccount.
func (mr *MockServiceMockRecorder) CreateBankAccount(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBankAccount", reflect.TypeOf((*MockService)(nil).CreateBankAccount), ctx, args)
}

// CreateMxBankAccount mocks base method.
func (m *MockService) CreateMxBankAccount(ctx context.Context, args *CreateMxBankAccountArgs) (*FundingSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMxBankAccount", ctx, args)
	ret0, _ := ret[0].(*FundingSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMxBankAccount indicates an expected call of CreateMxBankAccount.
func (mr *MockServiceMockRecorder) CreateMxBankAccount(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMxBankAccount", reflect.TypeOf((*MockService)(nil).CreateMxBankAccount), ctx, args)
}

// Get mocks base method.
func (m *MockService) Get(ctx context.Context, id string) (*FundingSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*FundingSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockService)(nil).Get), ctx, id)
}

// GetByAccountId mocks base method.
func (m *MockService) GetByAccountId(ctx context.Context, identityId string) ([]FundingSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountId", ctx, identityId)
	ret0, _ := ret[0].([]FundingSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountId indicates an expected call of GetByAccountId.
func (mr *MockServiceMockRecorder) GetByAccountId(ctx, identityId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountId", reflect.TypeOf((*MockService)(nil).GetByAccountId), ctx, identityId)
}

// GetMxConnectWidget mocks base method.
func (m *MockService) GetMxConnectWidget(ctx context.Context, accountID, identityID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMxConnectWidget", ctx, accountID, identityID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMxConnectWidget indicates an expected call of GetMxConnectWidget.
func (mr *MockServiceMockRecorder) GetMxConnectWidget(ctx, accountID, identityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMxConnectWidget", reflect.TypeOf((*MockService)(nil).GetMxConnectWidget), ctx, accountID, identityID)
}

// Verify mocks base method.
func (m *MockService) Verify(ctx context.Context, args *VerifyArgs) (*FundingSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, args)
	ret0, _ := ret[0].(*FundingSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockServiceMockRecorder) Verify(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockService)(nil).Verify), ctx, args)
}

// VerifyMxBankAccount mocks base method.
func (m *MockService) VerifyMxBankAccount(ctx context.Context, identityID, fundingsourceID string) (*FundingSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyMxBankAccount", ctx, identityID, fundingsourceID)
	ret0, _ := ret[0].(*FundingSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyMxBankAccount indicates an expected call of VerifyMxBankAccount.
func (mr *MockServiceMockRecorder) VerifyMxBankAccount(ctx, identityID, fundingsourceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyMxBankAccount", reflect.TypeOf((*MockService)(nil).VerifyMxBankAccount), ctx, identityID, fundingsourceID)
}
