#cloud-config

package_upgrade: true
package_update: true

mounts:
 - [ xvdb, /opt/vault/data, "ext4", "defaults,nofail", "0", "2" ]

write_files:
  - path: /opt/vault/tls/encrypted-vault.key.pem
    encoding: b64
    content: {{ .EncryptedTlsPrivateKey }}
  - path: /opt/vault/tls/vault.crt.pem
    encoding: b64
    content: {{ .TlsCert }}
    owner: vault:vault
    permissions: "0644"
  - path: /etc/systemd/system/vault.service
    encoding: b64
    content: {{ .SystemdConfig }}
  - path: /opt/vault/config/default.hcl
    encoding: b64
    content: {{ .VaultConfig }}
    owner: vault:vault

runcmd:
  - test -z "$(lsblk -f | grep nvme1n1 | awk '{print $2}')" && mkfs -t ext4 /dev/xvdb
  - chown vault:vault /opt/vault/data
  - echo "Decrypting tls private key"
  - AWS_DEFAULT_REGION=eu-west-1 aws kms decrypt --ciphertext-blob fileb:///opt/vault/tls/encrypted-vault.key.pem --key-id {{ .KmsKeyId }} --output text --query Plaintext | base64 --decode > /opt/vault/tls/vault.key.pem
  - chown vault:vault /opt/vault/tls/vault.key.pem
  - chmod 640 /opt/vault/tls/vault.key.pem
  - echo "Starting Vault..."
  - systemctl daemon-reload
  - systemctl enable vault.service
  - systemctl restart vault.service
